const Map<String, String> es_CL = {
    ///
    /// Common
    ///
    "title_inmotion": "INMOTION",
    "prompt_welcome_to_inmotion": "Bienvenido a INMOTION",
    "btn_more": "Más",
    "btn_view_more": "Ver Más",
    "btn_cancel": "Cancelar",
    "btn_exit": "Salir",
    "btn_confirm": "Confirmar",
    "btn_complete": "Terminar",
    "btn_submit": "Enviar",
    "btn_i_see": "Yo veo",
    "btn_skip": "Saltar",
    "btn_next_step": "Siguiente",
    "btn_save": "Guardar",
    "btn_save_image": "Guardar Imagen",
    "btn_edit": "Editar",
    "btn_preview": "Vista Previa",
    "btn_rename": "Renombrar",
    "btn_copy": "Copiar",
    "btn_delete": "Suprimir",
    "btn_publish": "Publicar",
    "tab_vehicle": "Vehículo",
    "tab_moment": "Momentos",
    "tab_discover": "Descubrir",
    "tab_mine": "Yo",
    "prompt_page_error": "Ha ocurrido un error.",
    "btn_share": "Compartir",
    "btn_report": "Informar",
    "btn_enable": "Activar",
    "btn_enabled": "Activado",
    "btn_go_to_enable": "Ir a activar",
    "btn_retry": "Reintentar",
    "prompt_title_warning": "Atención",
    "prompt_title_tips": "Recomendaciones",
    "prompt_title_warm_tips": "Consejos",
    "prompt_confirm_to_cancel": "Confirma cancelar?",
    "prompt_failed": "Fallo",
    "btn_agree": "Aprobar",
    'btn_reject': 'Rechazar',
    'btn_arrow': 'Permitir',
    "btn_need_help": "Ayuda?",
    "btn_common_problem": "Problemas comunes",
    "page_message_center": "Centro de Mensajes",
    "title_sys_message": "Mensaje de Sistema",
    "title_social_message": "Mensaje Social",
    "btn_save_and_share": "Guardar y Compartir",
    "prompt_saved": "Guardado",
    "prompt_save_failed": "Falló el guardado",
    "prompt_updated": "Actualizado",
    "prompt_update_failed": "Falló la actualización",
    "prompt_data_empty": "Sin datos.",
    "prompt_loading": "Cargando...",
    "prompt_load_failed": "Falló la carga",
    "prompt_copied": "Copiado",
    "prompt_action_failed": "Falló",
    "prompt_press_again_to_exit": "Presione nuevamente para salir.",
    "prompt_description": "Descripción",

    "datetime_just_now": "Ahora",
    "datetime_x_minutes_ago": "%smin atrás",
    "datetime_yesterday_x": "Ayer %s",

    "unknown": "Desconocido",

    "prompt_location_settings_tips": 'Favor permitir INMOTION acceder a la ubicación en Configuración-Aplicaciones-INMOTION-Permisos para buscar vehículos.',
    "prompt_bluetooth_settings_tips": 'Favor permitir INMOTION acceder a dispositivos cercanos en Configuración-Aplicaciones-INMOTION-Permisos para usar las funciones para buscar y conectar con vehículos normalmente.',
    "prompt_camera_settings_tips": 'Favor permitir INMOTION acceder a la cámara en Configuración-Aplicaciones-INMOTION-Permisos para funciones como tomar fotografías y escanear códigos QR.',
    "prompt_microphone_settings_tips": 'Favor permitir INMOTION acceder al micrófono en Configuración-Aplicaciones-INMOTION-Permisos para funciones como crear sonidos personalizados.',
    "prompt_storage_settings_tips": 'Favor permitir INMOTION acceder a archivos y medios en Configuración-Aplicaciones-INMOTION-Permisos, para que funciones como subir avatares y guardar imágenes puedan ser utilizadas normalmente.',

    "prompt_location_settings_desc": 'INMOTION requiere permisos de Ubicación para buscar el vehículo.',
    "prompt_bluetooth_settings_desc": 'INMOTION requiere permisos de Acceso a Dispositivos Cercanos para buscar y conectar con vehículos.',
    "prompt_camera_settings_desc": 'INMOTION requiere permisos de Cámara para tomar fotos y escanear códigos QR.',
    "prompt_microphone_settings_desc": 'INMOTION requiere permisos de Micrófono para crear sonidos personalizados.',
    "prompt_storage_settings_desc": 'INMOTION requiere permisos de Archivos y Medios para subir y guardar imágenes al teléfono.',

    ///
    /// Account
    ///

    "prompt_auto_register_if_account_not_exists": "Luego de la verificación, la cuenta será creada automáticamente utilizando el número de teléfono no registrado",
    "btn_login": "Iniciar",
    "btn_register": "Registrar",
    "title_register": "Registrar",
    "title_cn_phone_quick_login": "Inicio Rápido",
    "prompt_input_phone": "Número de teléfono",
    "prompt_input_email": "Email",
    "prompt_input_email_or_username": "Email/Usuario",
    "prompt_input_verification_code": "Código de verificación",
    "prompt_input_password": "Clave de usuario",
    "prompt_input_a_valid_phone": "Favor ingresar un número de teléfono válido!",
    "prompt_input_a_valid_email": "Favor ingresar un e-mail válido!",
    "prompt_input_a_valid_email_or_username": "Favor ingresar un e-mail o nombre de usuario válido!",
    "prompt_input_a_valid_password": "Favor ingresar una clave de usuario válida",
    "btn_forgot_password": "Clave olvidada?",
    "btn_reset_password": "Reiniciar clave",
    "btn_login_via_password": "Iniciar con usuario y clave",
    "btn_login_via_verification_code": "Iniciar con código de verificación",
    "btn_request_verification_code": "Obtener código",
    "btn_request_sms_verification_code": "Obtener código",
    "prompt_verification_code_has_sent_to": "El código de verificación se envió a %s",
    "btn_resend": "Reenviar",
    "title_user_agreement": "Acuerdo de Utilización",
    "title_privacy_policy": "Política de Privacidad",
    "title_user_agreement_and_privacy_policy": "INMOTION\nAcuerdo de Utilización y Política de Privacidad",
    "title_user_agreement_and_privacy_policy_tips": "La protección de su información personal y privacidad es importante para nosotros. Para proteger mejor sus derechos, favor leer cuidadosamente y aceptar el %s y la %s para comenzar a utilizar la INMOTION APP.",
    "prompt_register_agreement_tips": "Registrarse o Iniciar Sesión significa su aceptación del %s y la %s",
    "title_select_country_or_region": "Seleccionar País/Región",
    "btn_modify_phone": "Modificar Número de Teléfono",
    "btn_modify_email": "Modificar Email",
    "btn_bind_phone": "Asociar Número de Teléfono",
    "btn_modify_password": "Modificar Clave",
    "phone_number": "Número de Teléfono",
    "email": "Email",
    "btn_register_via": "Registrar con %s",
    "btn_bind_via": "Asociar con %s",
    "btn_reset_password_via": "Reiniciar con %s",
    "btn_bind_account": "Asociar cuenta",
    "prompt_password_limit_tips": "Favor ingresar 6-20 números y caracteres, no sólo números",
    "prompt_empty_password": "Faltó ingresar clave",
    "title_bind_social_account": "Asociar Cuenta Social",
    "prompt_social_account_auth_failed": "Falló la autentificación",
    "prompt_bind_social_account_tips": "*Puede iniciar en INMOTION mediante una cuenta social asociada.",
    'state_bound': 'Asociada',
    'state_not_bound': 'No Asociada',
    'prompt_unbind_social_account_tips': 'Luego de disociar, no podrá usar %s para iniciar en INMOTION. Confirma desear disociar?',
    'btn_logout': 'Salir',
    'prompt_logout_tips': 'Confirma salir?',
    "title_operation_verification": "Verificación de Seguridad",
    "prompt_operation_verification_tips": "La operación actual, requiere de verificación. Favor verificar mediante alguno de estos métodos",
    "title_verify_operation_via": "Verificar via %s",
    "prompt_operation_verification_expired": "Favor desarrollar primero la verificación de seguridad!",
    "text_none": "Ninguno",
    "title_account_cancellation": "Cerrado de Cuenta",
    "prompt_account_cancellation_details": "Una vez cerrada la cuenta INMOTION, ésta es irrecuperable. Recomendamos respaldar la información y datos relativos a su cuenta. Favor recordar: si cierra su cuenta INMOTION, no podrá volver a usarla ni recuperar sus productos verificados ni otra información (incluso si registra una nueva cuenta utilizando el mismo número de teléfono o email), incluyendo pero no limitado a:\n(1) Los productos autentificados por su cuenta INMOTION serán automáticamente desafiliados, y otros usuarios podrán autentificar directamente al conectarse con esos productos;\n(2) Ud no podrá recuperar las actualizaciones, likes y comentarios que haya compartido en su cuenta INMOTION;\n(3) La moneda LE en su cuenta INMOTION y artículos virtuales canjeados con LE (ej. paquetes de luces LED atmosféricas) no podrán ser recuperados;\n(4) Favor notar que la cancelación de su cuenta INMOTION no significa que las actividades y responsabilidades asociadas antes de la cancelación serán eximidas o mitigadas.",
    "prompt_account_cancellation_apply_success": "La solicitud de cancelación ha sido enviada exitosamente y será procesada tan pronto como sea posible.",

    /// Chinese phone quick verify error
    "prompt_cn_phone_auth_no_sim_card": "No se detectó una tarjeta SIM!",
    "prompt_cn_phone_auth_unknown_operator": "Operador desconocido!",
    "prompt_cn_phone_auth_network_not_enable": "Datos móviles no han sido habilitados!",
    "prompt_cn_phone_auth_unknown": "Error desconocido!",

    ///
    /// Vehicle
    ///
    "btn_search_vehicle": "Buscar vehículo",
    "prompt_canceled": "Cancelado",
    "prompt_had_connected_before": "Conectado antes",
    "title_vehicle_activation": "Activación",
    "prompt_wait_for_activation_tips_finished": "Favor leer/observar los consejos de seguridad.",
    "prompt_had_read_activation_tips": "He leído cuidadosamente los consejos de seguridad y conozco los riesgos potenciales",
    "btn_activate": "Activar Ahora",
    "prompt_activated": "Activación exitosa!",
    "prompt_activate_failed": "Activación fallida",
    "prompt_activate_canceled": "Activación cancelada",
    "prompt_authorize_as_owner_after_activation": "La autentificación del vehículo es requerida para operaciones como el bloqueo con la APP. Desea verificarse como su propietario ahora?",
    "prompt_authorize_as_owner_later_after_activation": "Ud también puede hacerlo más tarde en 'Yo - Autentificación del Propietario'",
    "prompt_set_vehicle_password_failed": "No se estableció la clave",
    "prompt_set_vehicle_password_later_after_activation": "Ud también puede hacerlo más tarde en 'Vehículo - Ajustes del Vehículo - Clave'",
    "prompt_bluetooth_disabled": "La función Bluetooth no está habilitada",
    "prompt_location_disabled": "El servicio de posicionamiento no está habilitado",
    "prompt_no_bluetooth_permission": "Sin permiso para usar Bluetooth",
    "prompt_no_location_permission": "Sin permiso para usar posicionamiento",
    "prompt_no_scan_bluetooth_permission": "Sin permiso para buscar dispositivos Bluetooth",
    "prompt_no_connect_bluetooth_permission": "Sin permiso para conectar Bluetooth",
    "prompt_no_device_found": "No se encontraron vehículos.",
    "prompt_tap_to_connect": "Seleccionar el vehículo a conectar",
    "prompt_scanning": "Buscando...",
    "prompt_connecting": "Conectando...",
    "prompt_connection_canceled": "Conexión cancelada",
    "prompt_connected": "Conexión exitosa",
    "prompt_connection_timeout": "Conexión expiró",
    "prompt_connection_failed": "Conexión fallida",
    "prompt_unsupported_models": "Vehículo incompatible",
    "prompt_Initialization_data_exception": "Excepción de datos de inicialización, código de error: %s",
    "btn_enable_bluetooth": "Habilitar Bluetooth",
    "btn_enable_location": "Habilitar servicio de posicionamiento",
    "btn_request_bluetooth_permission": "Solicitud de permiso de Bluetooth",
    "btn_request_location_permission": "Solicitud de permiso de posicionamiento",
    "btn_scan_again": "Buscar nuevamente",
    "btn_cancel_connection": "Cancelar",
    "prompt_why_need_to_enable_location": "Porqué debo habilitar el servicio de posicionamiento?",
    "prompt_why_need_location_permission": "Porqué INMOTION necesita permiso de posicionamiento?",
    "prompt_why_do_i_couldnt_find_vehicles": "Porqué no pude buscar mi vehículo?",
    "btn_view_solutions": "Ver Soluciones",
    "prompt_connect_failed_server_ip_service_error": "Error temporal de servidores. Pronto lo solucionaremos. Favor reintentar más tarde.",
    "prompt_connect_failed_unknown_model": "Ud no puede utilizar la App INMOTION porque el modelo de su vehículo no es compatible.\nFavor contactarse con nosotros para más información.",
    "prompt_connect_failed_unknown_sn": "Ud no puede utilizar la App INMOTION porque el N/S de su vehículo no es válido.\nFavor contactarnos para más información.",
    "prompt_connect_failed_vehicle_locked": "El vehículo está en modo BLOQUEADO. Favor contactarnos para más información.",
    "prompt_connect_failed_vehicle_lost_mode": "El vehículo está en modo EXTRAVIADO. Ud puede deshabilitarlo en 'Yo - Buscar Mi Vehículo' si es el propietario.",
    "prompt_connect_failed_area_not_available": "Ud no puede utilizar este vehículo en la zona actual.",
    "text_vehicle_ride_time": "Tiempo de Viaje",
    "text_vehicle_power_on_time": "Tiempo Encendido",
    "text_vehicle_ride_mileage": "Distancia de Viaje",
    "text_vehicle_max_speed": "Vel. Máx.",
    "text_vehicle_ave_speed": "Vel. Promedio",
    "text_vehicle_last_ave_speed": "Vel. Promedio Previa",
    "text_vehicle_total_mileage": "Kilometraje Total",
    "text_vehicle_subtotal_mileage": "Kilometraje Subtotal",
    "text_vehicle_dynamic_speed_limit": "Límite de Vel. Dinámica",
    "text_vehicle_realtime_power": "Potencia",
    "text_vehicle_max_power": "Potencia Máx.",
    "text_vehicle_ave_power": "Potencia Promedio",
    "text_vehicle_mos_temp": "Temp. de los MOS",
    "text_vehicle_current": "Corriente",
    "text_vehicle_voltage": "Voltaje",
    "text_vehicle_consumption": "Consumo",
    "text_vehicle_recovery": "Regeneración",
    "text_vehicle_last_ride_mileage": "Kilometraje Previo",
    "text_vehicle_last_ride_time": "Tiempo de Viaje Previo",
    "text_vehicle_last_max_speed": "Vel. Máx. Previa",
    "text_vehicle_realtime_speed": "Velocidad",
    "text_vehicle_battery_discharge_current": "Corriente de descarga de la batería",
    "text_vehicle_battery_voltage": "Tensión de la batería",
    "text_vehicle_battery_output_power": "Potencia de salida de la batería",
    "text_vehicle_motor_output_power": "Potencia de salida del motor",
    "text_vehicle_motor_torque": "Torque del motor",
    "text_vehicle_remaining_battery": "Energía remanente",
    "text_vehicle_output_rate": "Tensión vectorial de salida(%)",
    "text_vehicle_dynamic_current_limit": "Límite de corriente dinámica",

    "prompt_long_press_to_edit": "Presionar largo para editar",
    "prompt_double_click_to_reset": "Hacer doble clic para reiniciar el kilometraje subtotal",
    "prompt_confirm_to_reset_subtotal_mileage": "Confirma reiniciar el kilometraje subtotal?",

    "text_vehicle_speed": "Velocidad",
    "text_vehicle_mileage": "Kilometraje",
    "text_vehicle_power": "Potencia",
    "text_vehicle_time": "Duración",
    "text_vehicle_tempture": "Temperatura",
    "text_vehicle_other": "Otro",

    "text_vehicle_motor_temp": "Temp. del Motor",
    "text_vehicle_front_motor_temp": "Temp. del Motor Delantero",
    "text_vehicle_rear_motor_temp": "Temp. del Motor Trasero",
    "text_vehicle_battery_temp": "Temp. en la Batería",
    "text_vehicle_motherboard_high_temp": "Temp. en la Controladora",
    "text_vehicle_driver_board_cpu_temp": "Temp. en la CPU",
    "text_vehicle_imu_temp": "Temp. en la IMU",

    "text_gps_speed": "Velocidad por GPS",

    "prompt_status_connecting": "Conectando",
    "prompt_status_connected": "Conectado",
    "prompt_status_disconnected": "Sin Conectar",
    "prompt_vehicle_disconnected": "El vehículo está desconectado",
    "prompt_no_connected_vehicles_yet": "Aún sin vehículos conectados.",
    "prompt_current_connected_vehicle": "Vehículo Conectado",
    "prompt_last_connected_at": "Última Conexión: %s",
    "title_switch_vehicle": "Cambiar Vehículos",
    "btn_disconnect_and_scan": "Desconectar y Buscar",
    "btn_scan": "Search",
    "btn_detailed_data": "Datos Detallados",
    "title_about_vehicle": "Sobre el Vehículo",
    "title_battery_info": "Información de las Baterías",
    "title_customer_service": "Servicio En Línea",
    "title_faq": "Consultas Frecuentes",

    "title_gps_riding_tracks": "Mis Viajes",
    "title_vehicle_riding_record": "Registro de Viajes",

    "text_vehicle_riding_record_mileage": "Distancia Recorrida: %s",
    "text_vehicle_riding_record_max_speed": "Velocidad Máx.: %s",

    "title_vehicle_riding_report": "Informe de Viajes",
    "prompt_invalid_riding_track": "Informe de viaje inválido.",

    "title_basic_battery_info": "Información Básica de Energía",
    "text_battery_voltage": "Tensión de Batería",
    "text_battery_charge_voltage": "Tensión de Carga",
    "title_detailed_battery_info": "Información de Baterías",
    "text_battery_detected_status": "Estado de Detección de Baterías",
    "text_battery_detected": "Detectada",
    "text_battery_not_detected": "No detectada",
    "text_battery_enable_status": "Estado de Activación de Baterías",
    "text_battery_enabled": "Activada",
    "text_battery_disabled": "Desactivada",
    "text_battery_error_status": "Estado de Baterías",
    "text_battery_ok": "Operativa",
    "text_battery_error": "Error",
    "text_battery_signal_logic_error": "Error de señal lógica",

    "title_battery_cells_voltage": "Tensión de Celdas de Baterías",

    "title_bms_basic_info": "Info. Básica",
    "text_bms_battery_sn": "N/S de Batería",
    "text_bms_manufacture_date": "Fecha de Fabricación",
    "text_bms_full_charge_cycles": "Ciclos de Carga Completa",
    "text_bms_software_version": "Versión del Software de BMS",
    "text_bms_hardware_Version": "Versión del Hardware de BMS",
    "title_bms_data_and_status": "Datos & Estado",
    "text_bms_voltage": "Voltaje",
    "text_bms_charge_state": "Estado de Carga",
    "text_bms_charge_current": "Corriente de Carga",
    "text_bms_discharge_current": "Corriente de Descarga",
    "text_bms_charge_mos_state": "Carga de MOS",
    "text_bms_discharge_mos_state": "Descarga de MOS",
    "text_bms_error_status": "Estado de Error",
    "text_bms_warning_status": "Estado de Advertencia",
    "text_bms_protection_status": "Estado de Protección",
    "text_bms_cell_balancing_status": "Balance de Celdas",
    "text_bms_max_cell_voltage": "Máx. Tensión de Celdas",
    "text_bms_min_cell_voltage": "Mín. Tensión de Celdas",
    "text_bms_charge_mos_temp": "Temp. de Carga de MOS",
    "text_bms_discharge_mos_temp": "Temp. de Descarga de MOS",
    "text_bms_cells_temp": "Temperatura de Celdas",
    "text_bms_cells_voltage": "Tensión de Celdas",

    /// vehicle settings
    "title_vehicle_settings": "Ajustes del Vehículo",
    "prompt_operation_succeed": "Operación Exitosa",
    "prompt_operation_failed": "Operación Fallida",
    "title_vehicle_password": "Clave del Vehículo",
    "text_vehicle_password_disabled": "Clave Desactivada",
    "text_vehicle_password_gesture": "Gesto",
    "text_vehicle_password_slide": "Deslizar",
    "text_vehicle_password_number": "Número",
    "title_modify_vehicle_password": "Modificar Clave",
    "title_set_vehicle_password": "Establecer Clave",
    "prompt_vehicle_number_password_tips": "Favor ingresar una clave de 4 o 6 dígitos",
    "title_vehicle_userinfo": "Información de Usuarios",
    "title_vehicle_userinfo_avatar": "Avatar",
    "title_vehicle_userinfo_name": "Nombre del Vehículo",
    "prompt_vehicle_userinfo_name_tips": "Favor ingresar 1–16 caracteres alfanuméricos y símbolos",
    "title_choose_setting_item": "Selección de Ajustes",
    "vehicle_setting_item_limit_speed_25": "Norma de Límite de 25km/h",
    "vehicle_setting_item_limit_speed": "Límite de Velocidad",
    "vehicle_setting_item_drive_mode": "Modo de Conducción",
    "vehicle_setting_item_drive_mode_normal": "Traslado Diario",
    "vehicle_setting_item_drive_mode_normal_tips": "Aceleración y desaceleración flexible y cómoda",
    "vehicle_setting_item_drive_mode_off_road": "Todoterreno",
    "vehicle_setting_item_drive_mode_off_road_tips": "Dureza alta de pedales para cargar más fuerte, escalar colinas y conducción todoterreno",
    "vehicle_setting_item_pedestrian_mode_limit_speed": "Velocidad Máx. (modo Peatón)",
    "vehicle_setting_item_pedal_sensitivity": "Dureza de Pedal",
    "vehicle_setting_item_split_mode": "Modo Separado",
    "vehicle_setting_item_split_mode_speeding": "Aceleración",
    "vehicle_setting_item_split_mode_breaking": "Frenado",
    "vehicle_setting_item_electronic_brake_force": "Fuerza de Frenado",
    "vehicle_setting_item_power_assist": "Potencia Asistida",
    "vehicle_setting_item_acc_assist": "Asistencia de Aceleración",
    "vehicle_setting_item_brake_assist": "Asistencia de Frenado",
    "vehicle_setting_item_cruise": "Control de Velocidad Crucero",
    "vehicle_setting_item_ride_assist": "Conducción Asistida",
    "vehicle_setting_item_zero_start": "Impulso Desde Cero",
    "vehicle_setting_item_assist_balance": "Balance Asistido",
    "vehicle_setting_item_load_detect": "Detección de Peso",
    "vehicle_setting_item_noload_detect": "Detección Sin Peso",
    "vehicle_setting_item_up_hill_assist": "Escalada Asistida",
    "vehicle_setting_item_down_hill_assist": "Bajada Asistida",
    "vehicle_setting_item_overspeed_alarm": "Alarma de Velocidad",
    "vehicle_setting_item_lock": "Bloqueo",
    "vehicle_setting_item_password": "Clave",
    "vehicle_setting_item_diagnosis": "Revisión diagnóstica",
    "vehicle_setting_item_headlight": "Luz Frontal",
    "vehicle_setting_item_headlight_brightness": "Intensidad de Luz Frontal",
    "vehicle_setting_item_drl": "Luz de Posición",
    "vehicle_setting_item_low_beam_headlight": "Luz Frontal Baja",
    "vehicle_setting_item_low_beam_headlight_brightness": "Intensidad de Luz Frontal Baja",
    "vehicle_setting_item_high_beam_headlight": "Luz Frontal Alta",
    "vehicle_setting_item_high_beam_headlight_brightness": "Intensidad de Luz Frontal Alta",
    "vehicle_setting_item_auto_headlight": "Luz Frontal Automática",
    "vehicle_setting_item_auto_headlight_brightness_threshold": "Umbral de Luminosidad para Luz Frontal Automática",
    "vehicle_setting_item_auto_low_high_beam": "Automático de Luz Alta y Baja",
    "vehicle_setting_item_auto_low_high_beam_switch_speed_threshold": "Umbral de Velocidad para Luz Frontal Alta y Baja Automática",
    "vehicle_setting_item_light_effect": "Efectos Luminosos",
    "vehicle_setting_item_light_effect_mode": "Modo de Efectos Luminosos",
    "vehicle_setting_item_light_effect_front": "Modo de Efectos de Luces Frontales",
    "vehicle_setting_item_light_effect_rear": "Modo de Efecto de Luces Traseras",
    "vehicle_setting_item_light_diy": "Personalizado",
    "vehicle_setting_item_auto_turn_signal": "Señales de Viraje",
    "vehicle_setting_item_audio_state": "Sonidos",
    "vehicle_setting_item_volume": "Volumen",
    "vehicle_setting_item_audio_package": "Paquete de Sonidos",
    "vehicle_setting_item_standby_time": "Tiempo de Espera",
    "vehicle_setting_item_spin_kill_btn": "Corta-Motor",
    "vehicle_setting_item_sound_wave": "Sonido Presencial",
    "vehicle_setting_item_sound_wave_sensitivity": "Sensibilidad del Sonido Presencial",
    "vehicle_setting_item_estimated_remainder_range": "Estimador de Distancia Remanente",
    "vehicle_setting_item_user_info": "Información del Vehículo",
    "vehicle_setting_item_fan_quiet_mode": "Modo Silencioso",
    "vehicle_setting_item_forced_fan": "Refrigeración Forzada",
    "vehicle_setting_item_transport_mode": "Modo Transporte",
    "vehicle_setting_item_low_battery_safe_mode": "Modo de Seguridad Ante Batería Baja",
    "vehicle_setting_item_auto_screen_off": "Apagado Automático de Pantalla",
    "vehicle_setting_item_speed_unit": "Unidades Métricas/Imperiales",
    "vehicle_setting_item_sn": "Número Serial",
    "vehicle_setting_item_acc_force": "Fuerza de Aceleración",
    "title_vehicle_acc_front_force": "Fuerza de Aceleración Delantera",
    "title_vehicle_acc_rear_force": "Fuerza de Aceleración Trasera",
    "vehicle_setting_item_brake_force": "Intensidad de Frenado",
    "title_vehicle_brake_front_force": "Intensidad de Freno Delantero",
    "title_vehicle_brake_rear_force": "Intensidad de Freno Trasero",
    "vehicle_setting_item_one_pedal_mode": "Modo 'Un Pedal'",
    "vehicle_setting_item_brake_first": "Primero Frenado",
    "vehicle_setting_item_auto_park_time": "Tiempo de estacionamiento automático",
    "vehicle_setting_item_activate_date": "Activado el",
    "vehicle_setting_item_total_mileage": "Kilometraje Total",
    "vehicle_setting_item_hmic_board_version": "Placa HMIC",
    "vehicle_setting_item_bt_board_version": "Placa Bluetooth",
    "vehicle_setting_item_driver_board_version": "Placa de Control",
    "vehicle_setting_item_driver_board_temp": "Temperatura de la Placa de Control",
    "vehicle_setting_item_riding_mode": "Modo de Conducción",
    "vehicle_setting_riding_mode_eco": "Económico",
    "vehicle_setting_riding_mode_eco_tips": "Aceleración suave recomendado para principiantes.",
    "vehicle_setting_riding_mode_normal": "Modo Normal",
    "vehicle_setting_riding_mode_sport": "Modo Deportivo",
    "vehicle_setting_riding_mode_sport_tips": "Respuesta activa y poderosa, recomendado para conductores experimentados",
    "vehicle_setting_riding_mode_extreme": "Modo Extremo",
    "vehicle_setting_riding_pedestrian_mode": "Modo Peatón",
    "vehicle_setting_riding_pedestrian_mode_tips": "Modo en el que es más fácil empujar el eScooter.",
    "vehicle_setting_item_riding_mode_euc_normal": "Normal",
    "vehicle_setting_item_riding_mode_euc_normal_tips": "Mayor seguridad, apropiado para la mayoría de los conductores.",
    "vehicle_setting_item_riding_mode_euc_fancier": "Realzado",
    "vehicle_setting_item_riding_mode_euc_fancier_tips": "Mayor potencia de salida y velocidad máxima.",
    "prompt_cannt_set_sport_mode_when_limit_speed_25kmph_enabled": "No es posible cambiar a Modo Deportivo cuando está activado el limitador conforme la 'Norma de 25km/h'.",
    "prompt_cannt_enable_limit_speed_25kmph_when_sport_mode_enabled": "No se puede activar el 'limitador por Norma de 25km/h' cuando está seleccionado el Modo Deportivo.",
    "vehicle_setting_item_berm_angle_mode": "Modo Peralte",
    "prompt_unlock_factory_safe_speed_limit": "Por su seguridad, el límite de la velocidad máxima puede ser incrementado a 90km/h, sólo luego de haber recorrido al menos 30km. %s",
    "prompt_unlock_factory_safe_speed_limit_not_now": "Por su seguridad, el límite de la velocidad máxima puede ser incrementado a 90km/h, sólo luego de haber recorrido al menos 30km. Aún debe continuar conduciendo por %s.",
    "prompt_unlock_now": "Desbloquear Ahora>>",

    "warning_unlock_v13_factory_speed_limit": "Su seguridad es nuestra mayor prioridad. Para proteger mejor sus derechos personales e intereses, favor leer esta declaración cuidadosamente para asegurar la comprensión de su contenido.\n\n1. Ud comprende y reconoce que está actualmente intentando desbloquear la máxima velocidad del vehículo. Luego de levantarse esta restricción, Ud podrá ajustar el límite de la velocidad máxima hasta los 90km/h.\n2. Ud está consciente y comprende los riesgos asociados con la conducción a ultra alta velocidad y se responsabilizará por cualquier pérdida, o daño o riesgo causado por conducir a alta velocidad.\n3. Ud tiene la obligación de conocer las leyes, normas y reglamentos asociados con la conducción de uniciclos eléctricos en su área y cumplir estrictamente con ello cuando conduzca su V13. No conduzca su V13 en zonas prohibidas por leyes locales.\n4. Favor impedir que su V13 sea conducido por personas que no han leído cuidadosamente las instrucciones o o está familiarizado con las precauciones de seguridad del V13.\n5. Antes de cada viaje, favor revisar que los productos y accesorios están en buenas condiciones; evite utilizar baterías y accesorios no originales; y no desarme, dañe o modifique los productor y accesorios sin previa autorización del fabricante. Ud será responsable de toda pérdida, o daño y riesgo causado por una operación incorrecta.\n\nFavor leer cuidadosamente y decidir si acepta o no esta declaración. La restricción del límite de velocidad máxima no puede ser desbloqueada sin antes confirmar esta declaración. Ud \"concuerda\" será considerada como aceptada esta declaración. Si tiene alguna consulta o duda sobre esta declaración, favor hacer clic en \"Cancelar\"",
    "warning_enable_berm_angle_mode": "Cuando esta función es activada, aumenta el ángulo de inclinación lateral que induce la desconexión preventiva del motor, demorando esta protección. Esto significa que el vehículo podrá inclinarse adelante y atrás sin control debido a pequeños cambios de balance hasta que quede de costado. Esto puede dañarle a Ud y su entorno. Habiendo conocido todos los posibles riesgos, está seguro de activar esta función?",
    "warning_disable_berm_angle_mode": "Para habilitar el cambio, recuerde presionar una vez el botón Corta-Motor.",

    "title_vehicle_balance_angle": "Ángulo de Balance",
    "title_vehicle_calibration": "Calibración del Vehículo",
    "title_vehicle_balance_angle_calibration": "Calibración del Balance",
    "prompt_vehicle_balance_angle_calibration_desc": "Si luego de ajustar el Ángulo de Balance a cero, nota que el vehículo permanece inclinado adelante o atrás, es posible remediarlo con esta calibración. %s",
    "prompt_vehicle_balance_angle_calibration": "Favor presionar y sostener el botón Corta-Motor para poder mantener el vehículo en la posición vertical, perpendicular al suelo, mientras ejecuta la calibración.",
    "title_vehicle_turning_calibration": "Calibración de Viraje",
    "title_vehicle_turning_calibration_desc": "Si al virar los pedales cambian de ángulo o el vehículo se inclina adelante o atrás, esta calibración puede corregirlo. %s",
    "text_view_calibration_guide": "Ver Instructivo>>",
    "title_motor_self_adjustment": "Ajuste Automático del Motor",
    "prompt_motor_self_adjustment_desc": "El motor girará lento por un minuto mientras se ajusta automáticamente. Por su seguridad, asegurarse que el vehículo esté de costado, sin nada topando el neumático y no tocarlo hasta que termine.",
    "prompt_clear_motor_self_adjustment_effect_desc": "Se recomienda %s si no se observa una mejora en la experiencia de condccción.",
    "title_clear_motor_self_adjustment_effect": "Eliminar el ajuste automático de las prestaciones del motor",
    "prompt_motor_self_adjustment_in_progress": "Ajuste Automático en Desarrollo...",
    "prompt_motor_self_adjustment_terminated": "Ajuste Automático Terminado",
    "prompt_motor_self_adjustment_succeed": "Ajuste Automático Completado con Éxito",
    "prompt_motor_self_adjustment_finished": "Ajuste Automático Terminado",
    "prompt_motor_self_adjustment_timeout": "Ajuste Automático Expirado",
    "prompt_confirm_to_clear_motor_self_adjustment_effect": "Confirma eliminar el ajuste automático de las prestaciones del motor?",

    "prompt_motor_self_check_in_progress": "Autoexamen en desarrollo...",
    "prompt_motor_self_check_terminated": "Autoexamen Terminado",
    "prompt_motor_self_check_passed": "Autoexamen Superado",
    "prompt_motor_self_check_not_passed": "Autoexamen NO Superado",
    "prompt_motor_self_check_timeout": "Autoexamen Expirado",
    "prompt_motor_self_check_failed": "Falló el inicio del Autoexamen",

    "title_vehicle_acc_calibration": "Calibración de Aceleración",
    "title_vehicle_brake_calibration": "Calibración de Frenado",
    "title_vehicle_gyro_calibration": "Calibración de Giróscopo",
    "prompt_vehicle_acc_calibration_tips": "Luego de iniciada la calibración, llevar el acelerador de puño al punto máximo y mínimo por un segundo. Asegurar completar la operación de calibración dentro de cinco segundos.",
    "prompt_vehicle_brake_calibration_tips": "Luego de iniciada la calibración, llevar el manillar del freno al punto máximo y mínimo por un segundo. Asegurar completar la operación de calibración dentro de cinco segundos.",
    "prompt_vehicle_gyro_calibration_tips": "Favor enderezar el eScooter para mantener la pisadera paralela al suelo, entonces iniciar la calibración y esperar hasta completar la operación.",
    "prompt_cannt_start_vehicle_acc_calibration_when_zero_start_enabled": "No es posible iniciar la calibración del puño de aceleración cuando el modo 'Impulso Desde Cero' está activado!",

    "prompt_calibration_succeed": "Calibración Exitosa",
    "prompt_calibration_failed": "Calibración Fallida",
    "prompt_calibration_timeout": "Calibración Expirada",

    "title_vehicle_factory_reset": "Restauración de Fábrica",
    "prompt_vehicle_confirm_to_factory_reset": "Confirma hacer una restauración de fábrica?",
    "prompt_vehicle_confirm_to_factory_reset_desc": "Restablecer todos los ajustes y paquetes de sonido a la configuración de fábrica",
    "prompt_vehicle_ezcan_confirm_to_factory_reset_desc": "La restauración de fábrica puede tomar algunos minutos. Favor no salir de la aplicación.",
    "prompt_vehicle_ezcan_factory_reset_succeed": "Restauración de fábrica exitosa. Favor apagar el vehículo, esperar 10 segundos y encender.",
    "prompt_vehicle_factory_reset_succeed": "Restauración de fábrica exitosa!",

    "prompt_vehicle_euc_need_motor_free": "Favor estacionar el EUC en su pie de apoyo o ponerlo de costado",

    "title_vehicle_firmware_update": "Actualización de Firmware",

    /// EBike Assist
    "title_vehicle_assistant_mode": "Nivel de Asistencia",
    "text_vehicle_assistant_mode_none": "Ninguno",
    "prompt_vehicle_assistant_mode_none_desc": "Este modo apaga la asistencia motora y sólo podrá avanzar pedaleando.",
    "text_vehicle_assistant_mode_medium": "Limitado",
    "prompt_vehicle_assistant_mode_medium_desc": "Este modo aporta una asistencia motora limitada, adecuado para pedalear en rutas planas y extender la energía para viajes más largos.",
    "text_vehicle_assistant_mode_max": "Máximo",
    "prompt_vehicle_assistant_mode_max_desc": "Este modo aumenta la asistencia motora, adecuado para viajes en rutas con frecuentes subidas y bajadas. Este modo consumirá la energía de la batería más rápidamente.",

    /// L8 Light Effect
    "text_light_effect_mode_0": "Modo 1",
    "text_light_effect_mode_1": "Modo 2",
    "text_light_effect_mode_2": "Modo 3",
    "text_light_effect_mode_3": "Modo 4",
    "text_light_effect_mode_4": "Modo 5",
    "text_light_effect_mode_5": "Modo 6",
    "text_light_effect_mode_6": "Modo 7",
    "text_light_effect_mode_7": "Modo 8",
    "title_light_effect_color": "Modo 9",

    /// V12 Light Effect
    "text_light_effect_mode_close": "Desactivado",
    "text_light_effect_mode_light_package": "Efecto Luminoso",
    "text_light_effect_mode_light_package_change": "Modificar Efecto Luminoso",
    "text_light_effect_mode_follow_music": "Seguir Música",
    "text_light_effect_mode_follow_speed": "Seguir Velocidad",
    "text_light_effect_mode_follow_speed_1": "Fluido de Agua",
    "text_light_effect_mode_follow_speed_2": "Siempre Encendido",

    /// Diagnosis
    "title_vehicle_diagnosis": "Autoexamen",
    "prompt_vehicle_diagnosis_result": "Resultado del Autoexamen",
    "prompt_vehicle_diagnosis_ok": "No fueron encontrados ni advertencias ni errores conocidos",
    "prompt_vehicle_diagnosis_abnormal": "El vehículo está en una condición anormal",
    "title_vehicle_diagnosis_history": "Historial de Autoexamen",
    "title_view_history": "Ver Historial",
    "title_vehicle_upload_log": "Enviar Registro",
    "prompt_upload_log_tips": "Favor ser paciente, el envío del registro puede tomar algunos minutos",
    "title_upload_euc_log": "Enviar Registro del EUC",
    "title_upload_bms_log": "Enviar Registro de BMS",
    "title_uploading_euc_log": "Enviando Registro del EUC",
    "title_uploading": "Enviando %s",
    "title_upload_euc_and_bms_log": "Enviar Registros de EUC y BMS",
    "title_upload_bms_log_tips": "Si el vehículo no informa ni advertencias, ni errores relacionados con las baterías, no es necesario enviar el Registro de BMS. A menos que sea solicitado directamente por personal de INMOTION.",

    /// Remote Diagnosis
    "title_remote_diagnosis": "Diagnóstico Remoto",
    "prompt_remote_diagnosis_tips": "Favor utilizar esta función bajo la guía de personal de INMOTION.",
    "prompt_remote_diagnosis_enter_failed": "Falló el ingreso al modo Diagnóstico Remoto!",
    "prompt_remote_diagnosis_remote_disconnected": "Dispositivo remoto está desconectado!",
    "prompt_remote_diagnosis_disconnected": "Diagnóstico Remoto desconectado!",
    "prompt_remote_diagnosis_waiting_remote_connection": "El vehículo está en línea! Favor esperar que el dispositivo remoto se conecte.",
    "prompt_remote_diagnosis_confirm_to_cancel": "Actualmente, Ud está esperando que se conecte el dispositivo remoto. Está seguro de querer salir?",
    "prompt_remote_diagnosis_waiting_remote_timeout": "Acceso Fallido - el tiempo de espera por la conexión del dispositivo remoto ha expirado.",
    "prompt_remote_diagnosis_enter_again": "Entrar nuevamente",
    "prompt_remote_diagnosis_in_progress": "El diagnóstico en linea está en desarrollo. Favor asegurar que el teléfono esté cerca del vehículo, la red Internet se mantenga activa y no apague la pantalla del teléfono.",
    "prompt_remote_diagnosis_connect_identifier": "El código de enlace es [%s], clic para copiar a la memoria. Favor enviar este código a INMOTION para comenzar el diagnóstico remoto.",

    "prompt_upload_log_success": "El envío del registro fue exitoso!",
    "prompt_upload_log_failed": "El envío del registro falló!",

    /// Firmware update
    "text_vehicle_current_firmware_version": "Versión instalada: %s",
    "title_vehicle_current_firmware_version": "Versión Instalada",
    "prompt_new_firmware_version_found": "Una versión más reciente del firmware está disponible.",
    "prompt_cannt_interrupt_firmware_updating": "Favor continuar para completar la actualización.",
    "prompt_no_new_firmware_version_found": "No se encontraron versiones más recientes de firmware,",
    "btn_update_firmware": "Actualizar Ahora",
    "title_firmware_update_notes": "Notas",
    "text_firmware_update_notes_1": "· Antes de actualizar, favor confirmar que la batería tenga al menos 20% de energía remanente.",
    "text_firmware_update_notes_2": "· No operar el vehículo durante la actualización.",
    "text_firmware_update_notes_3": "· Si la actualización falla, intente salir de la App y actualizar nuevamente.",
    "prompt_contact_us": "Contacto",
    "prompt_firmware_update_learn_more_notes": "Aprender Más>>",
    "title_new_firmware_version_summary": "Resumen",
    "text_new_firmware_version_learn_more": "Aprender Más>>",
    "prompt_firmware_update_success": "Actualización Exitosa",
    "prompt_firmware_update_failed": "Actualización Fallida!",
    "prompt_last_firmware_update_interrupted": "La última actualización de firmware puede haber sido interrumpida. Para resolverlo, favor continuar para completar la actualización.",
    "prompt_forced_firmware_update_tips": ">Se requiere actualizar el firmware del vehículo a la versión más reciente antes de poder ser utilizado con normalidad.",
    "prompt_firmware_update_le1_manually_process_tips": "Luego que el vehículo se apague, esperar tres segundos y encenderlo manualmente. Luego hacer clic en 'Confirmar' para continuar con la actualización.",
    "prompt_firmware_updating": "Actualizando %s",
    "prompt_firmware_update_waiting_device": "Esperando actualización",

    "title_device_name_unknown": "Desconocido",
    "title_device_name_hmic_board": "Placa HMIC",
    "title_device_name_driver_board": "Placa de Control",
    "title_device_name_bt_board": "Placa Bluetooth",
    "title_device_name_display_board": "Placa de Pantalla",
    "title_device_name_bms_1": "BMS 1",
    "title_device_name_bms_2": "BMS 2",

    /// 驱动板故障
    "title_vehicle_diagnosis_module_driver_board": "Placa de Control",
    "vehicle_error_parse_current_sensor": "Falló el sensor de corriente de Fase. Es probable que deba reemplazar la Placa de Control.",
    "vehicle_error_bus_current_sensor": "Falló el sensor de corriente del Bus. Es probable que deba reemplazar la Placa de Control.",
    "vehicle_error_imu_sensor": "Falló el sensor de la IMU. Es probable que deba reemplazar la Placa de Control.",
    "vehicle_error_mos_temp_sensor": "Falló el sensor de temperatura de los MOS. Es probable que deba reemplazar la Placa de Control.",
    "vehicle_error_bus_voltage_sensor": "Falló el sensor principal de voltaje. Es probable que deba reemplazar la Placa de Control.",
    "vehicle_error_battery_voltage_sensor": "Falló el sensor de voltaje de la batería. Es probable que deba reemplazar la Placa de Control.",
    "vehicle_error_board_high_temp_area_sensor": "Falló el sensor de temperatura de la zona caliente. Es probable que deba reemplazar la Placa de control.",
    "vehicle_error_current_sampling": "Error de dato inicial de monitoreo de corriente. Es probable que deba reemplazar la Placa de Control.",
    "vehicle_error_sensor": "Error del sensor de salida. Es probable que deba reemplazar la Placa de Control.",
    "vehicle_error_rtc": "Error de RTC. Es probable que deba reemplazar la Placa de Control.",
    "vehicle_error_spi_flash": "Error de Almacenaje Externo. Es probable que deba Reemplazar la Placa de Control.",
    "vehicle_error_log": "Error de Sistema de Registro.",
    "vehicle_error_external_flash": "Falló el almacenaje externo. Es probable que deba reemplazar la Placa HMIC.",
    "vehicle_error_euc_driver_board_communication": "Falló la comunicación con la Placa de Control. Es probable que deba reemplazar la Placa HMIC o la Placa de Control.",
    "vehicle_error_scooter_driver_board_communication": "Falló la comunicación con la Placa de Control. Es probable que deba reemplazar la Placa de Pantalla o la Placa de Control.",
    "vehicle_error_scooter_driver_board_communication_unstable": "La comunicación con la Placa de Control es inestable. Es probable que deba reemplazar la Placa de Pantalla o la Placa de Control.",
    "vehicle_error_communication": "Falló la comunicación con la Placa de Control. Favor intente apagar y encender el vehículo.",
    "vehicle_error_voltage": "Error de voltaje.",
    "vehicle_error_driver_board": "Falló la Placa de Control. Es probable que deba reemplazar la Placa de Control.",
    "vehicle_error_driver_board_oscillator": "Error del Oscilador de Cristal.",

    "vehicle_warning_over_current": "Advertencia de sobrecarga. Favor conducir con gentileza.",
    "vehicle_warning_over_temp": "La Placa de Control se ha sobrecalentado. Favor detenerse por un instante.",
    "vehicle_warning_cpu_over_temp": "El procesador central de la Placa de Control está sobrecalentado. Favor detenerse por un instante.",
    "vehicle_warning_imu_over_temp": "La IMU está sobrecalentada. Favor detenerse por un instante.",
    "vehicle_warning_mos_over_temp": "Los MOS están sobrecalentados. Favor detenerse por un instante.",

    /// display board errors and warnings
    "vehicle_error_scooter_imu_sensor": "El sensor IMU falló. Es probable que deba reemplazar la placa de pantalla.",

    /// hmic board errors and warnings
    "title_vehicle_diagnosis_module_hmic_board": "Placa HMIC",
    "vehicle_error_hmic_board_rtc": "El RTC falló. Es probable que deba reemplazar la placa madre.",
    "vehicle_error_hmic_board_flash": "El almacenaje externo falló. Es probable que deba reemplazar la placa madre.",

    /// bt board errors and warnings
    "title_vehicle_diagnosis_module_bt_board": "Placa Bluetooth",
    "vehicle_error_bt_board_communication": "La comunicación Bluetooth falló. Es probable que deba reemplazar la placa madre o la placa Bluetooth.",

    /// motor errors and warnings
    "title_vehicle_diagnosis_module_motor": "Motor",
    "vehicle_error_motor_hall": "El sensor Hall del motor falló. Es probable que deba reemplazar el motor..",
    "vehicle_error_motor_hall_left": "El sensor Hall izquierdo falló. Es probable que deba reemplazar el motor.",
    "vehicle_error_motor_hall_right": "El sensor Hall derecho falló. Es probable que deba reemplazar el motor.",
    "vehicle_error_front_motor_hall": "El sensor Hall del motor delantero ha fallado. Es posible que deba reemplazar el motor.",
    "vehicle_error_rear_motor_hall": "El sensor Hall del motor trasero ha fallado. Es posible que deba reemplazar el motor.",
    "vehicle_error_motor_temp_sensor": "El sensor térmico del motor ha fallado. Es probable que deba reemplazar el motor.",
    "vehicle_error_motor_phase": "Fase de motor faltante. Es probable que deba reemplazar el motor.",
    "vehicle_warning_motor_over_temp": "Advertencia por motor sobrecalentado. Favor detenerse por un instante.",
    "vehicle_warning_motor_spin": "Advertencia, no levante el vehículo encendido, sin presionar el botón Corta-Motor.",
    "vehicle_warning_motor_blocked": "Advertencia de motor frenado. Favor no detenerse en pendientes extremas por mucho tiempo y revise cuerpos extraños que puedan estar trancando el motor.",

    /// battery errors and warnings
    "title_vehicle_diagnosis_module_battery": "Batería",
    "vehicle_error_battery": "La batería ha fallado. Es probable que deba reemplazar la batería.",
    "vehicle_error_battery_temp_sensor": "El sensor térmico de la batería ha fallado. Es probable que deba reemplazar la batería.",
    "vehicle_error_battery_cannt_power_off": "El apagado normal del vehículo ha fallado. Es probable que deba reemplazarla batería.",
    "vehicle_error_battery_cannt_charge": "No ha sido posible cargar con normalidad la batería. Es probable que deba reemplazar el cargador o la batería.",
    "vehicle_error_battery_signal": "Señal de error de batería.",
    "vehicle_warning_low_battery": "Advertencia de nivel bajo de energía. Favor recargar el vehículo tan pronto como sea posible.",
    "vehicle_warning_battery_over_temp": "La batería está sobrecalentada. Favor detenerse por un instante.",
    "vehicle_warning_battery_calibration": "Advertencia de calibración anormal de voltaje de batería. Favor %s.",
    "text_calibrate_battery": "Calibrar el voltaje de la batería",
    "vehicle_warning_some_batteries_not_enabled": "Advertencia: una batería no está operativa. Esto afectará el rendimiento del vehículo. Favor conducir con precaución.",
    "vehicle_warning_danger_charge1_dual_charger": "Advertencia: los voltajes de las baterías izquierda y derecha están diferentes. Recargar el vehículo de forma inadecuada puede ser inseguro. \nLo que debe hacer: \n①Utilice sólo un único cargador original para recargar el vehículo. Temporalmente no conectar dos cargadores simultáneos.\n②Mantenga el vehículo a la vista y supervise el proceso de recarga. %s",
    "vehicle_warning_danger_charge1_single_charger": "Advertencia: los voltajes de las baterías izquierda y derecha están diferentes. Recargar el vehículo de forma inapropiada puede ser inseguro. \nLo que debe hacer: \nMantenga el vehículo a la vista y supervise el proceso de recarga. %s",
    "vehicle_warning_danger_charge2": "Peligro! Detener Recarga! \nError de batería. Favor desconectar el cargador inmediatamente y ubicar le vehículo en un sitio seguro. \nFavor enviar el Registro (Ajustes del Vehículo - Diagnóstico- Enviar Registro) y contacte los servicios de su distribuidor. %s",
    "btn_i_know_danger_charge_risk_and_turn_off_alert": "Apagar esta Advertencia, comprendo el riesgo.",
    "btn_i_know_danger_charge_risk": "Comprendo el Riesgo",
    "vehicle_warning_battery_over_voltage": "Voltaje excesivo en la batería. Es probable que deba reemplazar el cargador o la batería.",
    "vehicle_warning_battery_output_abnormal": "Batería con energía de salida anormal. Favor intente recargar el vehículo o posiblemente deberá reemplazar la batería.",
    "vehicle_warning_too_low_battery": "Advertencia de voltaje demasiado bajo. Favor recargar el vehículo tan pronto como sea posible para evitar daños en las baterías.",

    /// Fan
    "title_vehicle_diagnosis_module_fan": "Ventilador",
    "vehicle_error_fan": "El ventilador ha fallado. Es probable que deba reemplazar el ventilador de refrigeración.",
    "vehicle_warning_fan_low_speed": "Ventilador girando demasiado lento. Esto afecta su capacidad para enfriar. Favor revisar si está trabado.",

    /// vehicle errors and warnings
    "title_vehicle_diagnosis_module_vehicle": "Vehículo",
    "vehicle_error_brake_handle": "Manillar de Freno con Fallo. Favor revisar cuidadosamente si el manillar está o no liberado.",
    "vehicle_error_acc_handle": "Acelerador con Fallo. Favor revisar cuidadosamente si el acelerador está o no liberado.",

    "vehicle_warning_lock_caused_by_safe_issue": "Debido a una posible condición de riesgo, el vehículo ha sido temporalmente bloqueado.",
    "vehicle_warning_over_speed": "Advertencia de Velocidad: favor disminuya la velocidad.",
    "vehicle_warning_fall_down": "Alerta de Caída: favor conduzca con precaución.",
    "vehicle_warning_risk_behavior": "Advertencia por Conducción Peligrosa: favor conducir de forma moderada.",
    "vehicle_warning_software_incompatible": "Advertencia por Firmware incompatible con algunos componentes. Favor actualizar a la versión más reciente.",
    "vehicle_warning_motor_no_load_protection": "Advertencia de motor girando libre. Se recomienda presionar el botón Corta-Motor y asegurarse que el motor esté detenido antes de levantar el vehículo.",
    "vehicle_warning_power_key_long_pressed": "Advertencia, botón de encendido presionado por largo tiempo. Esto puede inducir el apagado forzado. Favor detener la conducción!",
    "vehicle_warning_necessary_self_check_not_passed": "Advertencia: una revisión automática falló o no fue exitosa, %s.",
    "text_execute_self_check": "Ejecute el autoexamen",
    "vehicle_warning_function_limited_by_uncompleted_fw_update": "El funcionamiento del vehículo está limitado y se requiere actualizar el firmware para operar con normalidad.",
    "vehicle_warning_remote_locked": "El vehículo ha sido bloqueado. Favor contactar INMOTION para verificar su identidad y desbloquearlo.",
    "vehicle_warning_hardware_incompatible": "Advertencia por incompatibilidad de algunos componentes físicos. Las placas de control y madre deben ser reemplazadas en conjunto.",
    "vehicle_warning_over_power": "Potencia Excedida",

    /// BMS Error
    "bms_error_voltage_sample": "Error de Medición de Voltaje.",
    "bms_error_charge_current_sample": "Error de medición de corriente de carga.",
    "bms_error_discharge_current_sample": "Error de medición de corriente de descarga.",
    "bms_error_temperature_sensor": "Error de sensor de temperatura.",
    "bms_error_rh_sensor": "Error de sensor de humedad relativa.",
    "bms_error_charge_mosfet": "Error de carga de MOS.",
    "bms_error_discharge_mosfet": "Error de descarga de MOS.",
    "bms_error_afe": "Error de AFE.",
    "bms_error_cell": "Error de celda.",
    "bms_error_mcu": "Error de MCU.",

    /// BMS Warning
    "bms_warning_low_soc": "Advertencia de estado de carga SOC baja.",
    "bms_warning_pack_over_charge": "Advertencia de batería sobrecargada.",
    "bms_warning_pack_over_discharge": "Advertencia de batería con sobredescarga.",
    "bms_warning_cell_over_charge": "Advertencia de celda con sobrecarga.",
    "bms_warning_cell_over_discharge": "Advertencia de celda con sobredescarga.",
    "bms_warning_charge_over_current": "Advertencia de carga con sobrecorriente.",
    "bms_warning_charge_mosfet_over_temperature": "Advertencia de carga de MOS con exceso de temperatura.",
    "bms_warning_charge_cell_over_temperature": "Advertencia de carga de celda con exceso de temperatura.",
    "bms_warning_charge_cell_low_temperature": "Advertencia de carga de celda de batería con temperatura baja.",
    "bms_warning_discharge_over_current": "Advertencia de sobrecorriente de descarga.",
    "bms_warning_discharge_mosfet_over_temperature": "Advertencia de descarga de MOS con exceso de temperatura.",
    "bms_warning_discharge_cell_over_temperature": "Advertencia de descarga de celda de batería con exceso de temperatura.",
    "bms_warning_discharge_cell_low_temperature": "Advertencia de descarga de celda de batería con temperatura baja.",
    "bms_warning_over_humidity": "Advertencia de humedad relativa alta.",

    /// BMS Protection
    "bms_protection_short_circuit": "Protección de cortocircuito.",
    "bms_protection_pack_over_charge": "Protección de sobrecarga de batería.",
    "bms_protection_pack_over_discharge": "Protección de sobredescarga de batería.",
    "bms_protection_cell_over_charge": "Protección de sobrecarga de celda de batería.",
    "bms_protection_cell_over_discharge": "Protección de sobredescarga de celda de batería.",
    "bms_protection_charge_over_current": "Protección de carga por sobrecorriente.",
    "bms_protection_charge_mosfet_over_temperature": "Protección de carga por MOS con sobretemperatura.",
    "bms_protection_charge_cell_over_temperature": "Protección de carga por celda de batería con sobretemperatura.",
    "bms_protection_charge_cell_low_temperature": "Protección de carga por celda de batería con baja temperatura.",
    "bms_protection_discharge_over_current": "Protección de descarga por sobrecorriente.",
    "bms_protection_discharge_mosfet_over_temperature": "Protección de descarga por MOS con sobretemperatura.",
    "bms_protection_discharge_cell_over_temperature": "Protección de descarga por celda con sobretemperatura.",
    "bms_protection_discharge_cell_low_temperature": "Protección de descarga por celda con baja temperatura.",
    "bms_protection_over_humidity": "Protección por exceso de humedad.",
    "bms_protection_associated_charge": "Protección de carga asociada.",
    "bms_protection_associated_discharge": "Protección de descarga asociada.",

    /// light effect
    'title_light_effect_preview': 'Previsualizar Efecto Luminoso',
    'title_complete_light_effect_info': 'Favor completar la información del Efecto Luminoso',
    'prompt_input_light_effect_name': 'Favor ingresar el nombre del Efecto Luminoso',
    'prompt_invalid_light_effect_info': 'Información inválida del Efecto Luminoso',
    'text_light_effect_frame_interval': 'Intervalo de Cuadros',
    'title_light_effect_my_colors': 'Mis Colores',
    'text_light_effect_frame_keyframe': 'Cuadro Clave',
    'text_light_effect_frame_total': 'Total de cuadros',
    'text_light_effect_frame_number': '%s Cuadro',
    'text_light_effect_frame': '%s Cuadro',
    'text_light_effect_frame_mode_normal': 'Balance',
    'text_light_effect_frame_mode_fast': 'Más Rápido',
    'text_light_effect_frame_mode_slow': 'Más Lento',
    'title_light_effect_edit': 'Editar Efecto Luminoso',
    'prompt_light_effect_edit_back_tips': 'Salir no guardará los cambios en los Efectos Luminosos',
    'prompt_light_effect_edit_gradient_mode_1': 'Soltar para fijar el Cuadro Clave, o seguir arrastrando para cancelar',
    'prompt_light_effect_edit_gradient_mode_2': 'En el modo de gradiente de intra-cuadro actual, favor continuar para seleccionar el punto final del gradiente, o %s',
    'prompt_light_effect_edit_gradient_mode_3': 'En el modo de gradiente intra-cuadro actual, Ud está seleccionando el punto final del gradiente. Soltar para salir de este modo',
    'prompt_light_effect_edit_gradient_mode_4': 'En el modo de gradiente intra-cuadro actual, Ud está seleccionando el punto final del gradiente. Ud puede arrastrar aquí para salir del modo',
    'text_light_effect_exit_edit_gradient_mode': 'salir de este modo',
    'prompt_light_effect_edit_already_first_step': "Ya está el primer paso!",
    'prompt_light_effect_edit_already_last_step': "Ya está el último paso!",
    'prompt_light_effect_drag_to_delete': 'Arrastrar aquí para eliminar',
    'prompt_light_effect_release_to_delete': 'Soltar para eliminar',
    "title_vehicle_light_effect_exists": "Efecto Luminoso en el Vehículo",
    "text_light_effect_default_package": "Efecto Luminoso de Fábrica",
    "text_light_effect_unknown_package": "Efecto Luminoso Desconocido",
    "prompt_enable_light_effect_failed": "Falló la activación del Efecto Luminoso",
    'prompt_confirm_to_delete_light_effect': 'Confirma eliminar?',
    'prompt_confirm_to_delete_diy_light_effect': "El Efecto Luminoso personalizado no podrá ser recuperado una vez que sea eliminado. Confirma la eliminar '%s'?",

    /// sound pack
    "title_vehicle_sound_pack": "Paquete de Sonido",
    "title_vehicle_sound_pack_exists": "Paquete de Sonido en el Vehículo",
    "text_default_sound_pack": "Paquete de Sonido de Fábrica",
    "text_unknown_sound_pack": "Paquete de Sonido Desconocido",
    "prompt_input_sound_pack_name": "Favor ingresar un nombre para el Paquete de Sonido",
    "prompt_select_sound_pack_cover": "Favor escoja una cubierta",
    "title_diy_single_sound_pack_item": "Personalizar Sonido Individual",
    "title_diy_sound_pack": "Personalizar Paquete de Sonido",
    'prompt_confirm_to_use_default_sound_pack': 'Confirma recuperar el Paquete de Sonido de fábrica?',
    "prompt_select_from_local_file": "Seleccionar de entre archivos locales",
    "prompt_vehicle_transferring_file": "Favor mantener el vehículo detenido y no operarlo durante la transferencia del archivo.",
    "prompt_enable_sound_pack_success": "Activación exitosa de Paquete de Sonido",
    "prompt_enable_sound_pack_failed": "Activación fallida de Paquete de Sonido.",
    "prompt_vehicle_storage_capacity_not_enough": "Capacidad de almacenamiento insuficiente en el vehículo.",
    "prompt_sound_pack_composing": "Componiendo...",
    "prompt_sound_pack_item_file_is_too_large": "El archivo de sonido es muy grande",
    "title_custom_sound_pack": "Personalización de Paquete de Sonido",
    "title_complete_sound_pack_info": "Completar Información de Paquete de Sonido",
    "btn_compose": "Componer",
    "title_sound_pack_compose": "Componer Paquete de Sonido",
    "prompt_sound_pack_compose_succeed": "Composición Exitosa",
    "prompt_sound_pack_compose_failed": "La composición de Paquete de Sonido ha fallado",
    "title_sound_pack_audition": "Escuchar",
    "title_select_sound_pack_item": "Seleccionar sonido",
    'prompt_confirm_to_delete_sound_pack': 'Confirma eliminar el Paquete de Sonido?',
    'prompt_confirm_to_delete_sound_pack_in_vehicle': "El Paquete de Sonido en el vehículo no podrá ser recuperado si lo elimina. Confirma eliminar '%s'?",
    'prompt_confirm_to_delete_diy_sound_pack': "El Paquete de Sonido personalizado no podrá ser recuperado si lo elimina. Confirma eliminar '%s'?",
    'text_sound_pack_file_local': 'Local',
    'text_sound_pack_file_record': 'Grabación',
    'text_sound_pack_file_library': 'Biblioteca de Sonidos',
    'text_sound_pack_item_duration': 'Duración: ',
    'text_sound_pack_item_size': 'Tamaño: ',
    'prompt_sound_pack_compose_item_cannt_be_empty': "No pueden estar todos los campos vacíos",
    'title_sound_pack_diy_create_from_template': 'Crear desde plantilla',
    'title_sound_pack_diy_create_directly': 'Crear directamente',
    'title_sound_pack_diy_select_template': 'Seleccionar una plantilla',
    "title_sound_pack_audition_on_phone": "Escuchar en el teléfono",
    "title_sound_pack_audition_on_vehicle": "Escuchar en el vehículo",

    ///
    /// Mine
    ///
    'btn_authorized_vehicles': 'Mis Vehículos',
    'btn_vehicle_authorization': 'Autentificación del Propietario',
    'btn_customer_service': 'Servicio al Consumidor',
    'title_find_my_vehicle': 'Encontrar Mi Vehículo',
    'title_unit_metric_imperial': 'Unidades Métricas/Imperiales',
    'text_unit_metric': 'Métricas',
    'text_unit_imperial': 'Imperiales',
    'title_language': 'Idioma',
    'text_follow_system': 'Mismo del sistema',
    'title_select_language': 'Seleccionar Idioma',
    'title_account_security': 'Cuenta y Seguridad',
    'title_clear_cache': 'Borrar Memoria Cache',
    'prompt_clear_cache_tips': 'Confirma borrar memoria cache?',
    'title_app_about': 'Sobre la App',
    'text_app_version': '%s',

    'title_message_center': 'Centro de Mensajes',
    'title_user_info': 'Información Personal',
    'btn_take_a_photo': 'Tomar foto',
    'btn_select_from_album': 'Seleccionar desde álbum',

    'title_scan_qrcode': 'Escanear Código QR',

    /// About
    "user_agreement": "Acuerdo del Usuario",
    "privacy_policy": "Política de Privacidad",
    'inmotion_company': 'INMOTION',

    /// personal info
    'title_avatar': 'Avatar',
    'title_nickname': 'Sobrenombre',
    'title_username': 'Nombre de Usuario',
    'title_signature': 'Clave Personal',
    'title_modify_nickname': 'Modificar sobrenombre',
    'title_modify_username': 'Modificar nombre de usuario',
    'title_modify_signature': 'Modificar Alias Personal',
    'prompt_nickname_limit': '6-20 caracteres',
    'prompt_signature_limit': '0-100 caracteres',

    /// my vehicle
    'title_my_vehicles': 'Mis Vehículos',
    'title_delete_authorized_vehicle': 'Remover Autentificación del Propietario',
    'prompt_delete_authorized_vehicle_tips': 'Remover el vehículo eliminará la autentificación del propietario. Confirma eliminarlo?',
    'title_delete_vice_owner': 'Borrar Copropietario',
    'prompt_delete_vice_owner_tips': 'Confirma borrar el copropietario?',
    'title_vehicle_details': 'Detalles del Vehículo',
    'title_vehicle_info': 'Información del Vehículo',
    'prompt_vehicle_info_updated_at': 'La siguiente información fue actualizada: %s',
    'title_vehicle_model': 'Modelo',
    'title_activated_date': 'Activado el',
    'title_total_mileage': 'Kilometraje total',
    'title_riding_record': 'Registro de Viajes',
    "title_bluetooth_name": "Identificación Bluetooth",
    "text_vehicle_remaining_mileage": "Distancia remanente: %s",
    'title_vehicle_owner_info': 'Información del Propietario',
    'title_vehicle_main_owner': 'Propietario',
    'btn_go_to_authorize_as_owner': 'Ir a Autentificar Propietario',
    'prompt_not_owner_and_go_to_authorize_as_owner': 'Sólo el actual propietario registrado para este vehículo puede hacerlo. Desea autentificarse como propietario ahora?',
    'text_vehicle_info_owner_me_suffix': '(Yo)',
    'title_vehicle_vice_owner': 'Copropietario',
    'title_vehicle_no_owner': 'Ninguno',
    'title_transfer_vehicle_main_owner': 'Transferir Propietario',
    'prompt_transfer_vehicle_main_owner_tips': 'Luego de transferir, el usuario "%s" será autentificado como el Propietario actual de este vehículo y Ud pasará a ser copropietario.\n Desea confirmar esta transferencia?',
    'title_invite_as_vehicle_vice_owner': 'Invitar',
    'prompt_invite_as_vehicle_vice_owner_tips': 'Favor usar la App INMOTION para escanear el código QR para autorizar como Copropietario.',
    'title_vehicle_authorization': 'Autorización del Vehículo',
    'prompt_authorize_current_connected_vehicle_tips': 'El vehículo %s está actualmente conectado. Desea Ud autentificarse ahora como su propietario?',
    'prompt_input_sn': 'Favor ingresar N/S',
    'title_vehicle_authorization_requests': 'Historial de Solicitudes',
    'title_sent_vehicle_authorization_requests': 'Solicitud Enviada',
    'title_received_vehicle_authorization_requests': 'Solicitud Recibida',
    'prompt_vehicle_authorization_apply_to': 'Aplicado para %s',
    'prompt_vehicle_authorization_apply_from': 'Aplicado por %s',
    'prompt_vehicle_authorization_waiting': 'Esperando',
    'text_status_pending': 'Pendiente',
    'text_status_approved': 'Aprobado',
    'text_status_rejected': 'Rechazado',
    'text_status_expired': 'Expirado',

    /// vehicle authorization
    'prompt_vehicle_authorization_apply_success': 'La solicitud ha sido enviada exitosamente.',
    'prompt_vehicle_authorization_success': 'Autentificado exitosamente como Propietario',
    'prompt_vehicle_authorized_as_vice_owner_tips': 'Ya existe un propietario autentificado para este vehículo. Desea autentificarse como copropietario?',
    'prompt_vehicle_authorized_as_vice_owner_success': 'Autentificación exitosa como copropietario',
    'prompt_vehicle_authorization_failed': 'Autentificación fallida',

    /// customer service
    'title_message_board': 'Mensajería',
    'prompt_leave_message_tips': 'Favor dejar un mensaje, le contactaremos a la brevedad.',
    'btn_leave_a_message': 'Dejar Mensaje',
    'prompt_please_leave_a_message': 'Favor deje un mensaje',
    'btn_chat_menu_picture': 'Fotografías',
    'btn_chat_menu_video': 'Videos',
    'prompt_leave_message_success': 'Envío exitoso de mensaje',
    'prompt_leave_message_failed': 'Envío fallido de mensaje',
    'prompt_content_couldnt_be_empty': "El contenido no puede estar vacío.",
    'prompt_customer_service_waiting_for_access': 'Esperando acceder',
    'prompt_customer_service_queue_number': 'Hay %s personas previas en línea',
    'prompt_customer_service_offline': 'Servicio al Consumidor está temporalmente fuera de linea',
    'prompt_customer_service_session_ended': 'La sesión ha terminado',
    'btn_customer_service_evaluate': 'Evaluar',
    'prompt_input_question_to_consult': 'Favor ingresar su consulta',

    "title_official_recommends": "Recomendaciones",

    /// riding record
    "text_riding_record_summary": "En total, %shoras, %s de emisiones de carbono han sido evitadas.",

    ///
    /// errors
    ///
    'prompt_request_failed': 'Solicitud fallida',
    'prompt_request_failed_timeout': 'Solicitud expirada',
    'prompt_request_failed_network': 'Error de red',

    'prompt_unauthenticated_request': 'La sesión de usuario expiró; favor ingrese nuevamente!',
    'prompt_unknown_error': 'Error desconocido',
    'prompt_operate_too_frequently': 'Operación demasiado frecuente; favor tratar nuevamente más tarde.',
    'prompt_file_download_failed': 'Falló la descarga del archivo',
    'prompt_unknown_product_model': 'Modelo desconocido de producto',
};
