const Map<String, String> en_US = {
    ///
    /// Common
    ///
    "prompt_welcome_to_inmotion": "Bonjour, \nBienvenue chez INMOTION",
    "btn_more": "Plus",
    "btn_view_more": "Voir Plus",
    "btn_cancel": "Annuler",
    "btn_exit": "Sortir",
    "btn_confirm": "Confirmer",
    "btn_complete": "Terminer",
    "btn_submit": "Soumettre",
    "btn_i_see": "",
    "btn_skip": "Passer",
    "btn_next_step": "Suivant",
    "btn_save": "Sauvegarder",
    "btn_save_image": "Sauvegarder Image",
    "btn_edit": "Editer",
    "btn_preview": "Prévisualiser",
    "btn_rename": "Renommer",
    "btn_delete": "Supprimer",
    "btn_publish": "Publier",
    "tab_vehicle": "Vehicule",
    "tab_moment": "Moments",
    "tab_discover": "Découvrir",
    "tab_mine": "Moi",
    "prompt_page_error": "Une erreur s'est produite.",
    "btn_share": "Partager",
    "btn_report": "Rapporter",
    "btn_enable": "Activer",
    "btn_enabled": "Activé",
    "btn_retry": "Réessayer",
    "prompt_title_warning": "Attention",
    "prompt_title_tips": "",
    "prompt_title_warm_tips": "Astuces",
    "prompt_confirm_to_cancel": "Vous confirmez l'annulation?",
    "prompt_failed": "Echec",
    "btn_agree": "Accepter",
    'btn_reject': 'Rejeter',
    "btn_need_help": "Besoin d'Aide?",
    "btn_common_problem": "FAQ",
    "page_message_center": "Messagerie",
    "title_sys_message": "Message Système",
    "title_social_message": "Message Social",
    "btn_save_and_share": "Enregistrer et Partager",
    "prompt_saved": "Sauvegardé",
    "prompt_save_failed": "Sauvegarde échouée",
    "prompt_updated": "Mis à jour",
    "prompt_update_failed": "Echec de mise à jour",
    "prompt_data_empty": "Donnée vide.",
    "prompt_loading": "Chargement...",
    "prompt_load_failed": "Echec de chargement",
    "prompt_copied": "Copié",
    "prompt_action_failed": "Echec",
    "prompt_press_again_to_exit": "Appuyer de nouveau pour sortir.",

    "datetime_just_now": "Maintenant",
    "datetime_x_minutes_ago": "il y a %smin",
    "datetime_yesterday_x": "Hier %s",

    "unknown": "Inconnu",

    ///
    /// Account
    ///

    "prompt_auto_register_if_account_not_exists": "Le numéro de téléphone sera utilisé automatiquement pour la création du compte après la vérification",
    "btn_login": "Connexion",
    "btn_register": "S'inscrire",
    "title_register": "S'inscrire",
    "title_cn_phone_quick_login": "Connexion Rapide",
    "prompt_input_phone": "Numéro de Tèl",
    "prompt_input_email": "Adresse E-mail",
    "prompt_input_email_or_username": "Adresse E-mail/Identifiant",
    "prompt_input_verification_code": "Code de vérification",
    "prompt_input_password": "Mot de Passe",
    "prompt_input_a_valid_phone": "Merci de saisir un numéro de téléphone valide!",
    "prompt_input_a_valid_email": "Merci de saisir une adresse E-mail valide!",
    "prompt_input_a_valid_email_or_username": "Merci de saisir une adresse E-mail ou un Identifiant valide!",
    "prompt_input_a_valid_password": "Merci de saisir un mot de passe valide",
    "btn_forgot_password": "Mot de passe oublié?",
    "btn_reset_password": "Réinitialiser Mot de Passe",
    "btn_login_via_password": "Se connecter avec Identifiant/Mot de Passe",
    "btn_login_via_verification_code": "Se connecter avec un code de vérification",
    "btn_request_verification_code": "Obtenir un Code",
    "btn_request_sms_verification_code": "Obtenir un Code",
    "prompt_verification_code_has_sent_to": "Le code de vérification a été envoyé à %s",
    "btn_resend": "Renvoyer",
    "title_user_agreement": "Accord de l'Utilisateur",
    "title_privacy_policy": "Politique de Confidentialité",
    "prompt_register_agreement_tips": "S'inscrire ou se connecter implique votre accord à %s et %s",
    "title_select_country_or_region": "Choisir Pays/Région",
    "btn_modify_phone": "Modifier le numéro de téléphone",
    "btn_modify_email": "Modifier l'adresse E-Mail",
    "btn_bind_phone": "Lier le numéro de Téléphone",
    "btn_modify_password": "Modifier le Mot de Passe",
    "phone_number": "Numéro de Téléphone",
    "email": "E-Mail",
    "btn_register_via": "S'inscrire avec %s",
    "btn_bind_via": "Associer avec %s",
    "btn_reset_password_via": "Réinitialiser avec %s",
    "btn_bind_account": "Associer le Compte",
    "prompt_password_limit_tips": "Merci d'entrer entre 6 et 20 caractères, pas de chiffres",
    "prompt_empty_password": "Mot de passe vide",
    "title_bind_social_account": "",
    "prompt_social_account_auth_failed": "Echec d'autorisation",
    "prompt_bind_social_account_tips": "",
    'state_bound': 'Associé',
    'state_not_bound': 'Non Associé',
    'prompt_unbind_social_account_tips': 'Après la dissociation, vous ne pourrez plus utiliser %s poiur vous connecter à INMOTION, êtes-vous sûr de vouloir dissocier?',
    'btn_logout': 'Déconnexion',
    'prompt_logout_tips': 'Confirmez-vous la déconnexion?',
    "title_operation_verification": "Vérification de Sécurité",
    "prompt_operation_verification_tips": "L'opération nécessite une vérification, merci de vérifier avec une des méthodes suivantes",
    "title_verify_operation_via": "Vérifier avec %s",
    "prompt_operation_verification_expired": "Merci de procéder d'abord à la vérification de sécurité!",
    "text_none": "",

    /// Chinese phone quick verify error
    "prompt_cn_phone_auth_no_sim_card": "Pas de carte SIM détectée!",
    "prompt_cn_phone_auth_unknown_operator": "Opérateur inconnu!",
    "prompt_cn_phone_auth_network_not_enable": "Les données mobiles ne sont pas activées!",
    "prompt_cn_phone_auth_unknown": "Erreur inconnue!",

    ///
    /// Vehicle
    ///
    "btn_search_vehicle": "Recherche du Véhicule",
    "prompt_had_connected_before": "Connecté précédemment",
    "title_vehicle_activation": "Activation",
    "prompt_wait_for_activation_tips_finished": "Merci de lire/regarder les avertissements de sécurité.",
    "prompt_had_read_activation_tips": "J'ai lu attentivement les avertiseements de sécurité ci-dessus et je connais les risques encourus",
    "btn_activate": "Activer maintenant",
    "prompt_activated": "Activé avec succès!",
    "prompt_activate_failed": "Echec de l'activation",
    "prompt_activate_canceled": "Annulé",
    "prompt_authorize_as_owner_after_activation": "L'enregistrement du véhicule est requise pour les fonctionnalités comme le verouillage du véhicule dans l'application. Voulez-vous l'enregistrer en tant que propriétaire maintenant?",
    "prompt_authorize_as_owner_later_after_activation": "Vous pouvez aussi le faire plus tard dans 'Moi - Enregistrement du Propriétaire'",
    "prompt_set_vehicle_password_failed": "Echec de la création du mot de passe",
    "prompt_set_vehicle_password_later_after_activation": "Vous pouvez aussi le faire plus tard dans 'Véhicule - Réglages Véhicule - Mot de Passe'",
    "prompt_bluetooth_disabled": "Le Bluetooth du téléphone n'est pas activé",
    "prompt_location_disabled": "Le service de localisation n'est pas activé",
    "prompt_no_bluetooth_permission": "Pas d'authorisation Bluetooth",
    "prompt_no_location_permission": "Pas d'authorisation de localisation",
    "prompt_no_scan_bluetooth_permission": "Pas d'authorisation de recherche Bluetooth",
    "prompt_no_connect_bluetooth_permission": "Pas d'authorisation de connexion Bluetooth",
    "prompt_no_device_found": "Pas de Véhicule trouvé.",
    "prompt_tap_to_connect": "Cliquez sur le véhicule ci-desoous pour vous connecter",
    "prompt_scanning": "Recherche...",
    "prompt_connecting": "Connexion...",
    "prompt_connection_canceled": "Connexion annulée",
    "prompt_connected": "Connecté",
    "prompt_connection_timeout": "Temps de connexion dépassé",
    "prompt_connection_failed": "Echec de connexion",
    "prompt_unsupported_models": "Modèle non supporté",
    "btn_enable_bluetooth": "Activer le Bluetooth du téléphone",
    "btn_enable_location": "Activer le service de localisation",
    "btn_request_bluetooth_permission": "Demander les permissions Bluetooth",
    "btn_request_location_permission": "Demander les permissions de localisation",
    "btn_scan_again": "Chercher encore",
    "btn_cancel_connection": "Annuler",
    "prompt_why_need_to_enable_location": "Pourquoi dois-je activer le service de localisation?",
    "prompt_why_need_location_permission": "Pourquoi INMOTION a besoin des permissions de localisation?",
    "prompt_why_do_i_couldnt_find_vehicles": "Pourquoi je ne peux pas rechercher mon véhicule?",
    "btn_view_solutions": "Vois les Solutions",
    "prompt_connect_failed_server_ip_service_error": "Erreur temporaire des serveurs, nous allons regler le problème, merci de réessayer plus tard.",
    "prompt_connect_failed_unknown_model": "Vous ne pouvez pas utiliser l'application INMOTION parce que le modèle de ce véhicule est invalide.\nMerci de nous contacter pour plus d'informations.",
    "prompt_connect_failed_unknown_sn": "Vous ne pouvez pas utiliser l'application INMOTION parce que le numéro de série du véhicule est invalide.\nMerci de nous contacter pour plus d'informations.",
    "prompt_connect_failed_vehicle_locked": "Le véhicule est en MODE VERROUILLE. Merci de nous contacter pour plus d'informations.",
    "prompt_connect_failed_vehicle_lost_mode": "Le véhocule est en MODE PERDU. Vous pouvez le désactiver dans 'Moi-Trouve mon véhicule' si vous êtes le propriétaire du véhicule.",

    "text_vehicle_ride_time": "Durée du Parcours",
    "text_vehicle_ride_mileage": "Distance du Parcours",
    "text_vehicle_max_speed": "Vitesse Max.",
    "text_vehicle_ave_speed": "Vitesse Moy.",
    "text_vehicle_total_mileage": "Distance Totale",
    "text_vehicle_dynamic_speed_limit": "Vitesse limite dynamique",
    "text_vehicle_power": "Puissance",
    "text_vehicle_max_power": "Puissance Max.",
    "text_vehicle_mos_temp": "Temp MOS",
    "text_vehicle_consumption": "Consommation",
    "text_vehicle_last_ride_mileage": "Distance du dernier parcours",
    "text_vehicle_last_ride_time": "Durée du dernier parcours",
    "text_vehicle_last_max_speed": "Vitesse Max. du dernier parcours",
    "text_vehicle_speed": "Vitesse",
    "text_vehicle_battery_discharge_current": "Tension de sortie de la batterie",
    "text_vehicle_battery_voltage": "Tension Batterie",
    "text_vehicle_battery_output_power": "Puissance de sortie de la batterie",
    "text_vehicle_motor_output_power": "Puissance de sortie du moteur",
    "text_vehicle__motor_torque": "Couple",
    "text_vehicle_remaining_battery": "Batterie restante",
    "text_vehicle_output_rate": "Tension vectorielle de sortie(%)",
    "text_vehicle_dynamic_current_limit": "Limite dynamique de Surtension",

    "text_vehicle_motor_temp": "Temp Moteur",
    "text_vehicle_battery_temp": "Temp Batterie",
    "text_vehicle_motherboard_high_temp": "Temp Carte Mère",
    "text_vehicle_driver_board_cpu_temp": "Temp CPU Carte Mère",
    "text_vehicle_imu_temp": "Temp IMU",

    "text_gps_speed": "Vitesse GPS",

    "prompt_status_connecting": "Connexion",
    "prompt_status_connected": "Connecté",
    "prompt_status_disconnected": "Non connecté",
    "prompt_vehicle_disconnected": "Le véhicule est déconnecté",
    "prompt_no_connected_vehicles_yet": "Pas encore de véhicule connecté.",
    "prompt_current_connected_vehicle": "Connecté",
    "prompt_last_connected_at": "Dernière connexion: %s",
    "title_switch_vehicle": "Changer de véhicule",
    "btn_disconnect_and_scan": "Déconnecter et Chercher",
    "btn_scan": "Chercher",
    "btn_detailed_data": "Données détaillées",
    "title_about_vehicle": "A Propose du véhicule",
    "title_battery_info": "Informations de la Batterie",
    "title_customer_service": "Service en Ligne",
    "title_faq": "FAQ",

    "title_gps_riding_tracks": "Mes Parcours",
    "title_vehicle_riding_record": "Enregistrement des Parcours",

    "text_vehicle_riding_record_mileage": "Distance Parcourue: %s",
    "text_vehicle_riding_record_max_speed": "Vitesse Max.: %s",

    "title_vehicle_riding_report": "Rapport de Parcours",
    "prompt_invalid_riding_track": "Rapport de parcours invalide.",

    "title_basic_battery_info": "Informations Basiques",
    "text_battery_voltage": "Tension",
    "text_battery_charge_voltage": "Tension de Charge",
    "title_detailed_battery_info": "Informations du pack de Batteries",
    "text_battery_detected_status": "Etat détecté de la Batterie",
    "text_battery_detected": "Détecté",
    "text_battery_not_detected": "Non Détecté",
    "text_battery_enable_status": "Etat d'activation de la Batterie",
    "text_battery_enabled": "Activée",
    "text_battery_disabled": "Désactivée",
    "text_battery_error_status": "Etat d'Erreur de la Batterie",
    "text_battery_ok": "OK",
    "text_battery_error": "Erreur",
    "text_battery_signal_logic_error": "Erreur du signal logique",

    "title_battery_cells_voltage": "Tension des cellules de la Batterie",

    "title_bms_basic_info": "Infos Basiques",
    "text_bms_battery_sn": "SN Batterie",
    "text_bms_manufacture_date": "Date de Fabrication",
    "text_bms_full_charge_cycles": "Cycles de charges complètes",
    "text_bms_software_version": "Version logicielle du BMS",
    "text_bms_hardware_Version": "Version matérielle du BMS",
    "title_bms_data_and_status": "Données et Etat",
    "text_bms_voltage": "Voltage",
    "text_bms_charge_state": "Etat de Charge",
    "text_bms_charge_current": "Tension de Charge",
    "text_bms_discharge_current": "Tnesion de Decharge",
    "text_bms_charge_mos_state": "Charge MOS",
    "text_bms_discharge_mos_state": "Decharge MOS",
    "text_bms_error_status": "Etat d'Erreur",
    "text_bms_warning_status": "Etat d'Avertissement",
    "text_bms_protection_status": "Etat de Protection",
    "text_bms_cell_balancing_status": "Equilibrage des Cellules",
    "text_bms_max_cell_voltage": "Tension Max. des Cellules",
    "text_bms_min_cell_voltage": "Tension Min. des Cellules",
    "text_bms_charge_mos_temp": "Température de Charge MOS",
    "text_bms_discharge_mos_temp": "Température de Décharge MOS",
    "text_bms_cells_temp": "Température des Cellules",
    "text_bms_cells_voltage": "Tension des Cellules",

    /// vehicle settings
    "title_vehicle_settings": "Vehicle Settings",
    "prompt_operation_succeed": "Succeed",
    "prompt_operation_failed": "Failed",
    "title_vehicle_password": "Password",
    "text_vehicle_password_disabled": "Disabled",
    "text_vehicle_password_gesture": "Gesture",
    "text_vehicle_password_slide": "Slide",
    "text_vehicle_password_number": "Number",
    "title_modify_vehicle_password": "Modify Password",
    "title_set_vehicle_password": "Set Password",
    "prompt_vehicle_number_password_tips": "Please input a 4 or 6 digit password",
    "title_vehicle_userinfo": "Vehicle User Info",
    "title_vehicle_userinfo_avatar": "Avatar",
    "title_vehicle_userinfo_name": "Vehicle Name",
    "prompt_vehicle_userinfo_name_tips": "Please input 1–16 letters, numbers and English symbols",
    "title_choose_setting_item": "Select setting items",
    "vehicle_setting_item_limit_speed_25": "Speed Clamp at 25km/h",
    "vehicle_setting_item_limit_speed": "Speed Limit",
    "vehicle_setting_item_drive_mode": "Drive Mode",
    "vehicle_setting_item_drive_mode_normal": "Commuting",
    "vehicle_setting_item_drive_mode_normal_tips": "Soft and smooth acceleration and deceleration",
    "vehicle_setting_item_drive_mode_off_road": "Off-Roading",
    "vehicle_setting_item_drive_mode_off_road_tips": "High level of pedal hardness to handle hard acceleration, hills climbing, and off-road riding",
    "vehicle_setting_item_pedestrian_mode_limit_speed": "Max. Speed(Pedestrian mode)",
    "vehicle_setting_item_pedal_sensitivity": "Pedal Hardness",
    "vehicle_setting_item_spilt_mode": "Spilt MOde",
    "vehicle_setting_item_spilt_mode_speeding": "Speeding",
    "vehicle_setting_item_spilt_mode_breaking": "Braking",
    "vehicle_setting_item_power_assist": "Power Assist",
    "vehicle_setting_item_acc_assist": "Accelerate Assist",
    "vehicle_setting_item_brake_assist": "Brake Assist",
    "vehicle_setting_item_cruise": "Cruise",
    "vehicle_setting_item_ride_assist": "Ride Assist",
    "vehicle_setting_item_zero_start": "Zero-Start",
    "vehicle_setting_item_assist_balance": "Assistant Balance",
    "vehicle_setting_item_load_detect": "Load Detection",
    "vehicle_setting_item_noload_detect": "No-load Detection",
    "vehicle_setting_item_up_hill_assist": "Uphill Assistance",
    "vehicle_setting_item_down_hill_assist": "Downhill Assistance",
    "vehicle_setting_item_overspeed_alarm": "Speed Alarm",
    "vehicle_setting_item_lock": "Lock",
    "vehicle_setting_item_password": "Password",
    "vehicle_setting_item_diagnosis": "Diagnosis",
    "vehicle_setting_item_headlight": "Headlight",
    "vehicle_setting_item_headlight_brightness": "Headlight Brightness",
    "vehicle_setting_item_drl": "DRL",
    "vehicle_setting_item_low_beam_headlight": "Low Beam Headlight",
    "vehicle_setting_item_low_beam_headlight_brightness": "Low Beam Headlight Brightness",
    "vehicle_setting_item_high_beam_headlight": "High Beam Headlight",
    "vehicle_setting_item_high_beam_headlight_brightness": "High Beam Headlight Brightness",
    "vehicle_setting_item_auto_headlight": "Auto Headlight",
    "vehicle_setting_item_auto_headlight_brightness_threshold": "Auto-Headlight switch threshold",
    "vehicle_setting_item_auto_low_high_beam": "Auto Low-High Beam Headlight",
    "vehicle_setting_item_auto_low_high_beam_switch_speed_threshold": "Auto Low-High Beam Headlight switch speed threshold",
    "vehicle_setting_item_light_effect": "Light Effect",
    "vehicle_setting_item_light_effect_mode": "Light Effect Mode",
    "vehicle_setting_item_light_effect_front": "Front Light Effect Mode",
    "vehicle_setting_item_light_effect_rear": "Rear Light Effect Mode",
    "vehicle_setting_item_light_diy": "DIY",
    "vehicle_setting_item_auto_turn_signal": "Turn Signals",
    "vehicle_setting_item_audio_state": "Audio",
    "vehicle_setting_item_volume": "Volume",
    "vehicle_setting_item_audio_package": "Audio Pack",
    "vehicle_setting_item_standby_time": "Standby",
    "vehicle_setting_item_spin_kill_btn": "Spin-Kill",
    "vehicle_setting_item_sound_wave": "Sound Wave",
    "vehicle_setting_item_sound_wave_sensitivity": "Sound Wave Sensitivity",
    "vehicle_setting_item_estimated_remainder_range": "Remainder Range Estimating",
    "vehicle_setting_item_user_info": "Vehicle Information",
    "vehicle_setting_item_fan_quiet_mode": "Cooling Fan Silent Mode",
    "vehicle_setting_item_forced_fan": "Forced Air Cooling",
    "vehicle_setting_item_transport_mode": "Transport Mode",
    "vehicle_setting_item_low_battery_safe_mode": "Low Battery Safe Mode",
    "vehicle_setting_item_auto_screen_off": "Auto Screen Off",
    "vehicle_setting_item_speed_unit": "Metric/Imperial Units",
    "vehicle_setting_item_sn": "SN",
    "vehicle_setting_item_activate_date": "Activated At",
    "vehicle_setting_item_total_mileage": "Total Mileage",
    "vehicle_setting_item_hmic_board_version": "HMIC Board",
    "vehicle_setting_item_bt_board_version": "BT Board",
    "vehicle_setting_item_driver_board_version": "Driver Board",
    "vehicle_setting_item_driver_board_temp": "Driver Board Temp",
    "vehicle_setting_item_riding_mode": "Ride Mode",
    "vehicle_setting_riding_mode_eco": "ECO",
    "vehicle_setting_riding_mode_eco_tips": "Recommendation to beginner, smooth acceleration.",
    "vehicle_setting_riding_mode_normal": "D",
    "vehicle_setting_riding_mode_sport": "S",
    "vehicle_setting_riding_mode_sport_tips": "Recommendation to professional riders, more responsive power",
    "vehicle_setting_riding_pedestrian_mode": "Pedestrian Mode",
    "vehicle_setting_riding_pedestrian_mode_tips": "Easier to push the scooter.",
    "vehicle_setting_item_riding_mode_euc_normal": "Normal",
    "vehicle_setting_item_riding_mode_euc_normal_tips": "More safe, suitable for most users.",
    "vehicle_setting_item_riding_mode_euc_fancier": "Fancier",
    "vehicle_setting_item_riding_mode_euc_fancier_tips": "Higher power output and higher top speed.",
    "prompt_cannt_set_sport_mode_when_limit_speed_25kmph_enabled": "You couldn't switch to 'S' mode when the 'Speed Clamp at 25km/h' is enabled.",
    "prompt_cannt_enable_limit_speed_25kmph_when_sport_mode_enabled": "You couldn't enable the 'Speed Clamp at 25km/h' on 'S' mode.",
    "vehicle_setting_item_berm_angle_mode": "Berm Angle Mode",
    "prompt_unlock_factory_safe_speed_limit": "For your safety, the max. speed limit can only be raised to 90km/h when your total mileage exceed 30km. %s",
    "prompt_unlock_factory_safe_speed_limit_not_now":
    "For your safety, the max. speed limit can only be raised to 90km/h when your total mileage exceed 30km. You still need to continue riding for %s.",
    "prompt_unlock_now": "Unlock Now>>",

    "warning_unlock_v13_factory_speed_limit":
    "Your safety and security is our top priority. To better protect your personal rights and interests, please understand and read this Statement carefully to ensure that you fully understand the content of this Statement.\n\n1. You acknowledge and understand that you are currently attempting to unlock the maximum speed limit of the wheel. After this restriction is lifted, you will be able to adjust the maximum speed limit to 90km/h.\n2. You understand and are aware of the risks associated with ultra-high speed riding and shall be liable for any loss of, or damage and risk caused by the high speed.\n3. You are obligated to be aware of all laws and regulations regarding the riding of electric unicycles in your area, and strictly comply with applicable laws, regulations and policies when riding V13. Do not ride V13 in areas prohibited by local law.\n4. Please do not allow anyone who has not read the instructions carefully or is not familiar with V13 riding safety precautions to ride your vehicle.\n5. Before each ride, please be sure to check whether the products and accessories are in good condition, avoid using non-original batteries and accessories, and do not disassemble, crack or modify the products and accessories without permission. You shall be liable for any loss of, or damage and risk caused by wrong operation.\n\nPlease read carefully and choose to accept or not accept this statement. You cannot unlock the maximum speed limit until you agree to this statement. Your \"Agree\" will be deemed as acceptance of this disclaimer. If you have any questions about this disclaimer, please click \"Cancel\"",
    "warning_enable_berm_angle_mode": "When this mode is enabled, the angle of vehicle rollover protection will become larger, which means the vehicle may swing back and forth and easily be out of control due to small changes on the balance angle when it is positioned sideways. This may harm you or the surroundings. You’ve already known all possible risks, are you sure you want to enable it?",
    "warning_disable_berm_angle_mode": "To activate, press the Spin-Kill button after the mode is on/off. ",

    "title_vehicle_balance_angle": "Balance Angle",
    "title_vehicle_calibration": "Vehicle Calibration",
    "title_vehicle_balance_angle_calibration": "Balance Calibration",
    "prompt_vehicle_balance_angle_calibration_desc": "If the vehicle still tilts back or forward on the ground after you have set the Balancing Angle to zero, then you can try this calibration to get it fixed. %s",
    "prompt_vehicle_balance_angle_calibration": "Please press and hold the Spin-Kill to keep the vertical direction of the vehicle always perpendicular to the horizontal ground",
    "title_vehicle_turning_calibration": "Turning Calibration",
    "title_vehicle_turning_calibration_desc": "This can improve turning experience. %s",
    "text_view_calibration_guide": "View Guidance>>",
    "title_motor_self_adjustment": "Self-adjustment on Motor",
    "prompt_motor_self_adjustment_desc": "The motor will automatically run for 1 minute once started. For your safety, please make sure the EUC is in a tipped state and do not touch the wheels!",
    "prompt_clear_motor_self_adjustment_effect_desc": "It is recommended to %s if there is no improvement on riding experience",
    "title_clear_motor_self_adjustment_effect": "Clear the Self-adjustment performance on motor",
    "prompt_motor_self_adjustment_in_progress": "Self-adjustment is in progress...",
    "prompt_motor_self_adjustment_terminated": "Self-adjustment Terminated",
    "prompt_motor_self_adjustment_succeed": "Self-adjustment completed",
    "prompt_motor_self_adjustment_finished": "Self-adjustment finished",
    "prompt_motor_self_adjustment_timeout": "Self-adjustment timeout",
    "prompt_confirm_to_clear_motor_self_adjustment_effect": "Do you confirm to clear the self-adjustment performance on motor?",

    "prompt_motor_self_check_in_progress": "Self-inspection in progress...",
    "prompt_motor_self_check_terminated": "Self-inspection terminated",
    "prompt_motor_self_check_passed": "Self-inspection passed",
    "prompt_motor_self_check_not_passed": "Self-inspection NOT passed",
    "prompt_motor_self_check_timeout": "Self-inspection timeout",
    "prompt_motor_self_check_failed": "Failed to start Self-inspection",

    "title_vehicle_acc_calibration": "Throttle Calibration",
    "title_vehicle_brake_calibration": "Brake Calibration",
    "title_vehicle_gyro_calibration": "Gyro Calibration",
    "prompt_vehicle_acc_calibration_tips": "After starting the calibration, keep the throttle handle at the maximum value and the minimum value for 1 second. Make sure complete the specified calibration operation within 5 seconds.",
    "prompt_vehicle_brake_calibration_tips": "After starting the calibration, keep the brake handle at the maximum value and the minimum value for 1 second. Make sure complete the specified calibration operation within 5 seconds.",
    "prompt_vehicle_gyro_calibration_tips": "Please straighten the scooter to keep the footrest parallel to the ground, then start the calibration until it completed.",
    "prompt_cannt_start_vehicle_acc_calibration_when_zero_start_enabled": "You couldn't start a throttle handle calibration when 'Zero Start' mode is enabled!",

    "prompt_calibration_succeed": "Calibrate succeed",
    "prompt_calibration_failed": "Calibrate failed",
    "prompt_calibration_timeout": "Calibrate timeout",

    "title_vehicle_factory_reset": "Factory Reset",
    "prompt_vehicle_confirm_to_factory_reset": "Do you confirm to do factory reset?",
    "prompt_vehicle_confirm_to_factory_reset_desc": "Restore all settings and audio pack to factory default",
    "prompt_vehicle_ezcan_confirm_to_factory_reset_desc": "Factory reset may take several minutes, please do not exit App.",
    "prompt_vehicle_ezcan_factory_reset_succeed": "Factory reset successfully, please power-off and wait for 10 seconds then power on.",
    "prompt_vehicle_factory_reset_succeed": "Factory reset successfully!",

    "prompt_vehicle_euc_need_motor_free": "Please prop up the EUC on kickstands or put it on its side",

    "title_vehicle_firmware_update": "Firmware Update",

    /// EBike Assist
    "title_vehicle_assistant_mode": "Assistance Mode",
    "text_vehicle_assistant_mode_none": "None",
    "prompt_vehicle_assistant_mode_none_desc": "This mode will shut down power-assistance, you could only cycle to move forward.",
    "text_vehicle_assistant_mode_medium": "Limited",
    "prompt_vehicle_assistant_mode_medium_desc": "This mode has limited assistance which suits flat road cycling.",
    "text_vehicle_assistant_mode_max": "Max",
    "prompt_vehicle_assistant_mode_max_desc": "This mode will strengthen the power-assistance support, suitable for frequent uphill and downhill riding. This mode will consume the battery faster.",

    /// L8 Light Effect
    "text_light_effect_mode_0": "Mode 1",
    "text_light_effect_mode_1": "Mode 2",
    "text_light_effect_mode_2": "Mode 3",
    "text_light_effect_mode_3": "Mode 4",
    "text_light_effect_mode_4": "Mode 5",
    "text_light_effect_mode_5": "Mode 6",
    "text_light_effect_mode_6": "Mode 7",
    "text_light_effect_mode_7": "Mode 8",
    "title_light_effect_color": "Mode 9",

    /// V12 Light Effect
    "text_light_effect_mode_close": "Disable",
    "text_light_effect_mode_audio_package": "Audio Pack",
    "text_light_effect_mode_audio_package_change": "Modify Audio Pack",
    "text_light_effect_mode_follow_music": "Follow Music",
    "text_light_effect_mode_follow_speed": "Follow Speed",
    "text_light_effect_mode_follow_speed_1": "Water Flow",
    "text_light_effect_mode_follow_speed_2": "Always On",

    /// Diagnosis
    "title_vehicle_diagnosis": "Diagnosis",
    "prompt_vehicle_diagnosis_result": "Diagnose Result",
    "prompt_vehicle_diagnosis_ok": "No known error and warnings found yet",
    "prompt_vehicle_diagnosis_abnormal": "Your vehicle is in an abnormal condition",
    "title_vehicle_diagnosis_history": "Diagnosis History",
    "title_view_history": "View History",
    "title_vehicle_upload_log": "Upload Log",
    "prompt_upload_log_tips": "It may take a few minutes to upload log, please be patient",

    /// Remote Diagnosis
    "title_remote_diagnosis": "Remote Diagnosis",
    "prompt_remote_diagnosis_tips": "Please use this function under the guidance of the INMOTION team.",
    "prompt_remote_diagnosis_enter_failed": "Failed to enter the remote diagnosis!",
    "prompt_remote_diagnosis_remote_disconnected": "Remote device is disconnected!",
    "prompt_remote_diagnosis_disconnected": "Remote diagnosis is disconnected!",
    "prompt_remote_diagnosis_waiting_remote_connection": "You are currently in the online diagnostic mode! Please waiting for remote device access.",
    "prompt_remote_diagnosis_confirm_to_cancel": "Currently you are waiting for the remote device to access, are you sure to exit?",
    "prompt_remote_diagnosis_waiting_remote_timeout": "Access failed, waiting for remote device access is timeout.",
    "prompt_remote_diagnosis_in_progress": "Online diagnosis is in progress. Please make sure your mobile phone is near the vehicle and the network is active. Please do not turn off the screen of the mobile phone.",

    "prompt_upload_log_success": "Log upload successfully!",
    "prompt_upload_log_failed": "Log upload failed!",

    /// Firmware update
    "text_vehicle_current_firmware_version": "Current version: %s",
    "title_vehicle_current_firmware_version": "Current Version",
    "prompt_new_firmware_version_found": "New firmware found",
    "prompt_cannt_interrupt_firmware_updating": "Please continue to complete the updating.",
    "prompt_no_new_firmware_version_found": "No new firmware found",
    "btn_update_firmware": "Update Now",
    "title_firmware_update_notes": "Notice",
    "text_firmware_update_notes_1": "· Before updating, please make sure that the remaining battery is not less than 20%",
    "text_firmware_update_notes_2": "· Do not operate the vehicle during updating",
    "text_firmware_update_notes_3": "· If update failed, try to exit the App and update again",
    "prompt_contact_us": "Contact with us",
    "prompt_firmware_update_learn_more_notes": "Learn More>>",
    "title_new_firmware_version_summary": "Recommend",
    "text_new_firmware_version_learn_more": "Learn More>>",
    "prompt_firmware_update_success": "Update successfully",
    "prompt_firmware_update_failed": "Update Failed!",
    "prompt_last_firmware_update_interrupted": "The last firmware upgrade may have been interrupted, please continue to complete the upgrade to fix it.",
    "prompt_forced_firmware_update_tips": ">You need to update the vehicle firmware to the latest version before it can be used normally",
    "prompt_firmware_update_le1_manually_process_tips": "After the vehicle display is turned off, please wait for 3 seconds and turn on it manually. Then click 'Confirm' to continue update",
    "prompt_firmware_updating": "Updating %s",
    "prompt_firmware_update_waiting_device": "Waiting device update",

    "title_device_name_unknown": "Unknown",
    "title_device_name_hmic_board": "HMIC Board",
    "title_device_name_driver_board": "Driver Board",
    "title_device_name_bt_board": "BT Board",
    "title_device_name_display_board": "Display Board",
    "title_device_name_bms_1": "BMS 1",
    "title_device_name_bms_2": "BMS 2",

    /// 驱动板故障
    "title_vehicle_diagnosis_module_driver_board": "Driver Board",
    "vehicle_error_parse_current_sensor": "The Phase current sensor failed, you may need to replace the driver board.",
    "vehicle_error_bus_current_sensor": "The bus-current-sensor failed, you may need replace the driver board.",
    "vehicle_error_imu_sensor": "The IMU sensor failed, you may need replace the driver board.",
    "vehicle_error_mos_temp_sensor": "The MOS temperature sensor failed, you may need to replace the driver board.",
    "vehicle_error_bus_voltage_sensor": "The main voltage sensor failed, you may need to replace the driver board.",
    "vehicle_error_battery_voltage_sensor": "The battery voltage sensor failed, you may need to replace the driver board.",
    "vehicle_error_board_high_temp_area_sensor": "The high-temp area temperature sensor failed, you may need to replace the driver board.",
    "vehicle_error_current_sampling": "Current sampling initial data error, you may need to replace the driver board.",
    "vehicle_error_sensor": "Sensor output error, you may need to replace the driver board.",
    "vehicle_error_rtc": "RTC Error, you may need to replace the driver board.",
    "vehicle_error_spi_flash": "External storage error, you may need to replace the driver board.",
    "vehicle_error_log": "Log system error.",
    "vehicle_error_external_flash": "The external storage failed, you may need to replace the HMIC board.",
    "vehicle_error_euc_driver_board_communication": "The driver board communication failed, you may need to replace the HMIC board or driver board.",
    "vehicle_error_scooter_driver_board_communication": "The driver board communication failed, you may need to replace the display board or driver board.",
    "vehicle_error_scooter_driver_board_communication_unstable": "The driver board communication is unstable, you may need replace the display board or driver board.",
    "vehicle_error_communication": "The driver board communication failed， please try to re-power on.",
    "vehicle_error_voltage": "Voltage error.",
    "vehicle_error_driver_board": "The driver board failed, you may need to replace the driver board.",
    "vehicle_error_driver_board_oscillator": "Crystal oscillator error.",

    "vehicle_warning_over_current": "Warning by the over-current, please ride gently.",
    "vehicle_warning_over_temp": "The driver board is overheat, please stop riding for a while.",
    "vehicle_warning_cpu_over_temp": "The CPU of driver board is overheat, please stop riding for a while.",
    "vehicle_warning_imu_over_temp": "The IMU is overheat, please stop riding for a while.",
    "vehicle_warning_mos_over_temp": "The MOS is overheat, please stop riding for a while.",

    /// display board errors and warnings
    "vehicle_error_scooter_imu_sensor": "The IMU sensor failed, you may need replace the display board.",

    /// hmic board errors and warnings
    "title_vehicle_diagnosis_module_hmic_board": "HMIC Board",
    "vehicle_error_hmic_board_rtc": "The RTC failed, you may need to replace the main-board.",
    "vehicle_error_hmic_board_flash": "The external storage failed, you may need to replace the main board.",

    /// bt board errors and warnings
    "title_vehicle_diagnosis_module_bt_board": "BT Board",
    "vehicle_error_bt_board_communication": "The bluetooth communication failed, you may need to replace the main-board or bluetooth board.",

    /// motor errors and warnings
    "title_vehicle_diagnosis_module_motor": "Motor",
    "vehicle_error_motor_hall": "The motor hall failed, you may need replace the motor.",
    "vehicle_error_motor_hall_left": "The motor left hall failed, you may need replace the motor.",
    "vehicle_error_motor_hall_right": "The motor right hall failed, you may need replace the motor.",
    "vehicle_error_front_motor_hall": "The front motor hall failed, you may need replace the motor.",
    "vehicle_error_rear_motor_hall": "The rear motor hall failed, you may need replace the motor.",
    "vehicle_error_motor_temp_sensor": "The motor temperature sensor failed, you may need to replace the motor.",
    "vehicle_error_motor_phase": "Motor Phrase-lacking, you may need to replace the motor.",
    "vehicle_warning_motor_over_temp": "Warning by overheat on motor, please stop your riding for a while.",
    "vehicle_warning_motor_spin": "Spinning Warning. Don't lift up the EUC without pressing the Spin-kill button.",
    "vehicle_warning_motor_blocked": "Warning by motor stall, please do not park at a steep slopes for a long time.",

    /// battery errors and warnings
    "title_vehicle_diagnosis_module_battery": "Battery",
    "vehicle_error_battery": "The battery failed, you may need replace the battery.",
    "vehicle_error_battery_temp_sensor": "The battery temperature sensor failed, you may need to replace the battery.",
    "vehicle_error_battery_cannt_power_off": "Failure to power off normally, you may need to replace the battery.",
    "vehicle_error_battery_cannt_charge": "Failure to charge normally, you may need to replace the battery or the charger.",
    "vehicle_error_battery_signal": "Battery signal error.",
    "vehicle_warning_low_battery": "Warning by low battery, please recharge as soon as possible.",
    "vehicle_warning_battery_over_temp": "The battery is overheat, please stop riding for a while.",
    "vehicle_warning_battery_calibration": "Battery voltage calibration abnormal warning. Please %s.",
    "text_calibrate_battery": "calibrate battery voltage",
    "vehicle_warning_some_batteries_not_enabled": "Warning by some batteries not work. It will affect the performance of vehicle. Please ride carefully.",
    "vehicle_warning_danger_charge1_dual_charger": "Warning: The voltages of the left and right battery packs are different, inappropriate charging may cause safety issues. What you should do: ①Only use one original charger to charge up the wheel, two chargers to charge the wheel at the same time is not allowed ②Place the wheel within you sight, don't leave the wheel alone, observe the charging process closely. %s",
    "vehicle_warning_danger_charge1_single_charger": "Warning: The voltages of the left and right battery packs are different, inappropriate charging may cause safety issues. What you should do: Place the wheel within you sight, don't leave the wheel alone, observe the charging process closely. %s",
    "vehicle_warning_danger_charge2": "Danger! Stop Charging! Battery error, please stop charging and remove your charger immediately, put your wheel at a safe place. Please upload the vehicle log (Vehicle Settings - Diagnose- Upload log ), contact your dealer for service. %s",
    "btn_i_know_danger_charge_risk_and_turn_off_alert": "I Know That Risk and Turn Off This Warning Alert",
    "vehicle_warning_battery_over_voltage": "High voltage of battery, you may need to replace the battery or the charger.",
    "vehicle_warning_battery_output_abnormal": "Battery no output power, please try to recharge or you may need to replace the battery.",
    "vehicle_warning_too_low_battery": "Warning by the too-low voltage, please recharge as soon as possible to avoid damaging to battery.",

    /// Fan
    "title_vehicle_diagnosis_module_fan": "Fan",
    "vehicle_error_fan": "The cooling fan failed, you may need to replace the cooling fan.",
    "vehicle_warning_fan_low_speed": "Fan rotating speed is low. It will affect the max brightness level. Please check if the fan is blocked or not.",

    /// vehicle errors and warnings
    "title_vehicle_diagnosis_module_vehicle": "Vehicle",
    "vehicle_error_brake_handle": "Brake handlebar failed, please double check whether the brake handlebar released or not.",
    "vehicle_error_acc_handle": "Throttle failed, please double check whether the throttle handlebar released or not.",

    "vehicle_warning_lock_caused_by_safe_issue": "The vehicle has been temporarily locked due to safety-related hidden danger.",
    "vehicle_warning_over_speed": "Speeding Warning. Please slow down.",
    "vehicle_warning_fall_down": "Falling Alert. Please ride carefully.",
    "vehicle_warning_risk_behavior": "Warning by dangerous driving, please do not drive excessively.",
    "vehicle_warning_software_incompatible": "Warning by the firmware incompatibility on some parts, please upgrade the latest firmware.",
    "vehicle_warning_motor_no_load_protection": "Warning by motor free-load protection, it is recommended to press the Spin-kill button before lifting up, and make sure that the vehicle is stationary.",
    "vehicle_warning_power_key_long_pressed": "Warning by pressing the Power button for long time,Pressing the power button for a long time may trigger a forced power off. Please stop riding!",
    "vehicle_warning_necessary_self_check_not_passed": "A necessary self-inspection item failed or un-passed warning, %s.",
    "text_execute_self_check": "execute the self-inspection",
    "vehicle_warning_function_limited_by_uncompleted_fw_update": "The function of the vehicle is limited, and the firmware needs to be upgraded before it can be used normally.",
    "vehicle_warning_remote_locked": "The vehicle has been locked, please contact us to verify your identity to unlock.",
    "vehicle_warning_hardware_incompatible": "Warning by the hardware incompatibility on some parts, the main board and driver board need to be replaced in a complete set.",
    "vehicle_warning_over_power": "Over power.",

    /// BMS Error
    "bms_error_voltage_sample": "Voltage Sample error.",
    "bms_error_charge_current_sample": "Charge current sample error.",
    "bms_error_discharge_current_sample": "Discharge current sample error.",
    "bms_error_temperature_sensor": "Temperature sensor error.",
    "bms_error_rh_sensor": "Relative humidity sensor error.",
    "bms_error_charge_mosfet": "Charge mos error.",
    "bms_error_discharge_mosfet": "Discharge mos error.",
    "bms_error_afe": "Afe error.",
    "bms_error_cell": "Cell error.",
    "bms_error_mcu": "MCU error.",

    /// BMS Warning
    "bms_warning_low_soc": "Low soc warning.",
    "bms_warning_pack_over_charge": "Battery pack over charge warning.",
    "bms_warning_pack_over_discharge": "Battery pack over discharge warning.",
    "bms_warning_cell_over_charge": "Battery cell over charge warning.",
    "bms_warning_cell_over_discharge": "Battery cell over discharge warning.",
    "bms_warning_charge_over_current": "Charge over current warning.",
    "bms_warning_charge_mosfet_over_temperature": "Charge mos over temperature warning.",
    "bms_warning_charge_cell_over_temperature": "Battery cell charge over temperature warning.",
    "bms_warning_charge_cell_low_temperature": "Battery cell charge low temperature warning.",
    "bms_warning_discharge_over_current": "Discharge over current warning.",
    "bms_warning_discharge_mosfet_over_temperature": "Discharge mos over over temperature warning.",
    "bms_warning_discharge_cell_over_temperature": "Battery cell discharge over temperature warning.",
    "bms_warning_discharge_cell_low_temperature": "Battery cell discharge low temperature warning.",
    "bms_warning_over_humidity": "Over humidity warning.",

    /// BMS Protection
    "bms_protection_short_circuit": "Short circuit protection.",
    "bms_protection_pack_over_charge": "Battery pack over charge protection.",
    "bms_protection_pack_over_discharge": "Battery pack over discharge protection.",
    "bms_protection_cell_over_charge": "Battery cell over charge protection.",
    "bms_protection_cell_over_discharge": "Battery cell over discharge protection.",
    "bms_protection_charge_over_current": "Charge over current protection.",
    "bms_protection_charge_mosfet_over_temperature": "Charge mos over temperature protection.",
    "bms_protection_charge_cell_over_temperature": "Battery cell charge over temperature protection.",
    "bms_protection_charge_cell_low_temperature": "Battery cell charge low temperature protection.",
    "bms_protection_discharge_over_current": "Discharge over current protection.",
    "bms_protection_discharge_mosfet_over_temperature": "Discharge mos over over temperature protection.",
    "bms_protection_discharge_cell_over_temperature": "Battery cell discharge over temperature protection.",
    "bms_protection_discharge_cell_low_temperature": "Battery cell discharge low temperature protection.",
    "bms_protection_over_humidity": "Over humidity temperature protection.",
    "bms_protection_associated_charge": "Associated charge protection.",
    "bms_protection_associated_discharge": "Associated discharge protection.",

    /// light effect
    'title_light_effect_preview': 'Light Effect Preview',
    'title_complete_light_effect_info': 'Please complete Light Effect information',
    'prompt_input_light_effect_name': 'Please input a Light Effect name',
    'prompt_invalid_light_effect_info': 'Invalid Light Effect info',
    'text_light_effect_frame_interval': 'Frame Interval',
    'title_light_effect_my_colors': 'My Colors',
    'text_light_effect_frame_keyframe': 'Key Frame',
    'text_light_effect_frame_total': 'Total frames',
    'text_light_effect_frame_number': '%s Frame',
    'text_light_effect_frame': '%s Frame',
    'text_light_effect_frame_mode_normal': 'Balance',
    'text_light_effect_frame_mode_fast': 'Faster',
    'text_light_effect_frame_mode_slow': 'Slower',
    'title_light_effect_edit': 'Edit Light Effect',
    'prompt_light_effect_edit_back_tips': 'Exiting will not save edited lighting effects',
    'prompt_light_effect_edit_gradient_mode_1': 'Release to set as Key Frame, or keep dragging to cancel',
    'prompt_light_effect_edit_gradient_mode_2': 'Currently in the intra-frame gradient mode, please continue to select the gradient end point, or %s',
    'prompt_light_effect_edit_gradient_mode_3': 'Currently in the intra-frame gradient mode, you are selecting the end point of the gradient, release it to exit this mode',
    'prompt_light_effect_edit_gradient_mode_4': 'Currently in the intra-frame gradient mode, you are selecting the end point of the gradient, you can also slide here to exit the mode',
    'text_light_effect_exit_edit_gradient_mode': 'exit this mode',
    'prompt_light_effect_edit_already_first_step': "It's already the first step!",
    'prompt_light_effect_edit_already_last_step': "It's already the last step!",
    'prompt_light_effect_drag_to_delete': 'Drag here to delete',
    'prompt_light_effect_release_to_delete': 'Release to delete',
    "title_vehicle_light_effect_exists": "Light Effect in Vehicle",
    "text_light_effect_default_package": "Default Light Effect",
    "text_light_effect_unknown_package": "Unknown Light Effect",
    "prompt_enable_light_effect_failed": "Failed to enable Light Effect",
    'prompt_confirm_to_delete_light_effect': 'Do you confirm to delete?',
    'prompt_confirm_to_delete_diy_light_effect': "DIY light effect couldn't be restored once you deleted, do you confirm to delete '%s'?",

    /// sound pack
    "title_vehicle_sound_pack": "Sound Pack",
    "title_vehicle_sound_pack_exists": "Sound Pack in Vehicle",
    "text_default_sound_pack": "Default Sound Pack",
    "text_unknown_sound_pack": "Unknown Sound Pack",
    "prompt_input_sound_pack_name": "Please input a sound pack name",
    "prompt_select_sound_pack_cover": "Please choose a cover",
    "title_diy_single_sound_pack_item": "DIY Single Sound",
    "title_diy_sound_pack": "DIY Sound Pack",
    'prompt_confirm_to_use_default_sound_pack': 'Do you confirm to restore sound pack to factory default?',
    "prompt_select_from_local_file": "Select local filed",
    "prompt_vehicle_transferring_file": "Please keep the vehicle stationary and do not operate the vehicle during file transfer.",
    "prompt_enable_sound_pack_success": "Succeed",
    "prompt_enable_sound_pack_failed": "Failed to enable sound pack.",
    "prompt_vehicle_storage_capacity_not_enough": "Vehicle storage capacity is not enough.",
    "prompt_sound_pack_composing": "Composing...",
    "prompt_sound_pack_item_file_is_too_large": "Sound file is too large",
    "title_custom_sound_pack": "DIY Sound Pack",
    "title_complete_sound_pack_info": "Complete Sound Pack Information",
    "btn_compose": "Compose",
    "title_sound_pack_compose": "Compose Sound Pack",
    "prompt_sound_pack_compose_succeed": "Compose successfully",
    "prompt_sound_pack_compose_failed": "Failed to compose sound pack",
    "title_sound_pack_audition": "Audition",
    "title_select_sound_pack_item": "Select sound",
    'prompt_confirm_to_delete_sound_pack': 'Do you confirm to delete?',
    'prompt_confirm_to_delete_sound_pack_in_vehicle': "Sound pack in vehicle couldn't be restored once you deleted, do you confirm to delete '%s'?",
    'prompt_confirm_to_delete_diy_sound_pack': "DIY sound pack couldn't be restored once you deleted, do you confirm to delete '%s'?",
    'text_sound_pack_file_local': 'Local',
    'text_sound_pack_file_record': 'Record',
    'text_sound_pack_file_library': 'Sound Library',
    'text_sound_pack_item_duration': 'Duration: ',
    'text_sound_pack_item_size': 'Size: ',
    'prompt_sound_pack_compose_item_cannt_be_empty': "All items couldn't be empty",
    'title_sound_pack_diy_create_from_template': 'Create from template',
    'title_sound_pack_diy_create_directly': 'Create directly',
    'title_sound_pack_diy_select_template': 'Select a template',
    "title_sound_pack_audition_on_phone": "Audition on phone",
    "title_sound_pack_audition_on_vehicle": "Audition on vehicle",

    ///
    /// Mine
    ///
    'btn_authorized_vehicles': 'My Vehicles',
    'btn_vehicle_authorization': 'Owner Authorization',
    'btn_customer_service': 'Customer Service',
    'title_find_my_vehicle': 'Find My Vehicle',
    'title_unit_metric_imperial': 'Metric/Imperial Units',
    'text_unit_metric': 'Metric',
    'text_unit_imperial': 'Imperial',
    'title_language': 'Language',
    'text_follow_system': 'Follow system',
    'title_select_language': 'Select Language',
    'title_account_security': 'Account and Security',
    'title_clear_cache': 'Clear Cache',
    'prompt_clear_cache_tips': 'Do you confirm to clear cache?',
    'title_app_about': 'About',
    'text_app_version': '%s',

    'title_message_center': 'Message Center',
    'title_user_info': 'Personal Information',
    'btn_take_a_photo': 'Take a phone',
    'btn_select_from_album': 'Select from album',

    'title_scan_qrcode': 'Scan QR Code',

    /// About
    "user_agreement": "User Agreement",
    "privacy_policy": "Privacy Policy",
    'inmotion_company': 'INMOTION',

    /// personal info
    'title_avatar': 'Avatar',
    'title_nickname': 'Nickname',
    'title_signature': 'Signature',
    'title_modify_nickname': 'Modify nickname',
    'title_modify_signature': 'Modify signature',
    'prompt_nickname_limit': '6-20 characters',
    'prompt_signature_limit': '0-100 characters',

    /// my vehicle
    'title_my_vehicles': 'My Vehicles',
    'title_delete_authorized_vehicle': 'Remove Owner Authorization',
    'prompt_delete_authorized_vehicle_tips': 'Deleting vehicle will remove the owner authorization of the vehicle. Do you confirm to delete it?',
    'title_delete_vice_owner': 'Remove vice owner',
    'prompt_delete_vice_owner_tips': 'Do you confirm to remove the vice owner?',
    'title_vehicle_details': 'Vehicle Information',
    'title_vehicle_info': 'Vehicle Information',
    'prompt_vehicle_info_updated_at': 'Information below were updated at: %s',
    'title_vehicle_model': 'Model',
    'title_activated_date': 'Activated At',
    'title_total_mileage': 'Total Mileage',
    'title_riding_record': 'Riding Record',
    "title_bluetooth_name": "BT Name",
    "text_vehicle_remaining_mileage": "Remaining Mileage: %s",
    'title_vehicle_owner_info': 'Owner Information',
    'title_vehicle_main_owner': 'Main Owner',
    'btn_go_to_authorize_as_owner': 'Go to Authorize',
    'prompt_not_owner_and_go_to_authorize_as_owner': 'Only the owner of current vehicle can do it, do you want to authorize as an owner now?',
    'text_vehicle_info_owner_me_suffix': '(Me)',
    'title_vehicle_vice_owner': 'Vice Owner',
    'title_vehicle_no_owner': 'None',
    'title_transfer_vehicle_main_owner': 'Transfer Main Owner',
    'prompt_transfer_vehicle_main_owner_tips': 'After transferring, the user "%s" will become the main owner of the current vehicle and you will become the vice owner.\n Do you confirm to transfer?',
    'title_invite_as_vehicle_vice_owner': 'Invite',
    'prompt_invite_as_vehicle_vice_owner_tips': 'Please use INMOTION App to scan the QR code to authorize as vice owner.',
    'title_vehicle_authorization': 'Vehicle Authorization',
    'prompt_authorize_current_connected_vehicle_tips': 'The vehicle %s is currently connected, do you want to be authenticated as an owner immediately?',
    'prompt_input_sn': 'Please input SN',
    'title_vehicle_authorization_requests': 'History Request',
    'title_sent_vehicle_authorization_requests': 'Sent',
    'title_received_vehicle_authorization_requests': 'Received',
    'prompt_vehicle_authorization_apply_to': 'Applied to %s',
    'prompt_vehicle_authorization_apply_from': '%s applied to me',
    'prompt_vehicle_authorization_waiting': 'Waiting',
    'text_status_pending': 'Pending',
    'text_status_approved': 'Approved',
    'text_status_rejected': 'Rejected',
    'text_status_expired': 'Expired',

    /// vehicle authorization
    'prompt_vehicle_authorization_apply_success': 'Application has been sent successfully.',
    'prompt_vehicle_authorization_success': 'Successfully authorized as main owner',
    'prompt_vehicle_authorized_as_vice_owner_tips': 'This vehicle already has a main owner, do you want to authorize as vice owner?',
    'prompt_vehicle_authorized_as_vice_owner_success': 'Successfully authorized as vice owner',
    'prompt_vehicle_authorization_failed': 'Authorize failed',

    /// customer service
    'title_message_board': 'Message Board',
    'prompt_leave_message_tips': 'Please leave a message, we will contact you soon.',
    'btn_leave_a_message': 'Leave a Message',
    'prompt_please_leave_a_message': 'Please leave a message',
    'btn_chat_menu_picture': 'Pictures',
    'btn_chat_menu_video': 'Video',
    'prompt_leave_message_success': 'Succeed',
    'prompt_leave_message_failed': 'Leave message failed',
    'prompt_content_couldnt_be_empty': "Content couldn't be empty.",
    'prompt_customer_service_waiting_for_access': 'Waiting access',
    'prompt_customer_service_queue_number': 'There are %s people ahead of you in line',
    'prompt_customer_service_offline': 'Customer service is offline',
    'prompt_customer_service_session_ended': 'Session is ended',
    'btn_customer_service_evaluate': 'Evaluate',
    'prompt_input_question_to_consult': 'Please enter the question you want to consult',

    "title_official_recommends": "Recommend",

    /// riding record
    "text_riding_record_summary": "In total, %shours, %sKg of carbon emissions saved.",

    ///
    /// errors
    ///
    'prompt_request_failed': 'Request failed',
    'prompt_request_failed_timeout': 'Request timeout',
    'prompt_request_failed_network': 'Network error',

    'prompt_unauthenticated_request': 'Login session was expired, please sign in again!',
    'prompt_unknown_error': 'Unknown error',
    'prompt_operate_too_frequently': 'Operation too frequent, please try again later.',
    'prompt_file_download_failed': 'File download failed',
    'prompt_unknown_product_model': 'Unknown product model',
};
