const Map<String, String> fr_FR = {
  ///
  /// Common
  ///
  "prompt_welcome_to_inmotion": "Bonjour, \nBienvenue chez INMOTION",
  "btn_more": "Plus",
  "btn_view_more": "Voir Plus",
  "btn_cancel": "Annuler",
  "btn_exit": "Sortir",
  "btn_confirm": "Confirmer",
  "btn_complete": "Terminer",
  "btn_submit": "Soumettre",
  "btn_i_see": "",
  "btn_skip": "Passer",
  "btn_next_step": "Suivant",
  "btn_save": "Sauvegarder",
  "btn_copy_and_edit": "Copier et éditer",
  "btn_save_image": "Sauvegarder Image",
  "btn_edit": "Editer",
  "btn_preview": "Prévisualiser",
  "btn_rename": "Renommer",
  "btn_copy": "Copy",
  "btn_delete": "Supprimer",
  "btn_publish": "Publier",
  "tab_vehicle": "Vehicule",
  "tab_moment": "Moments",
  "tab_discover": "Découvrir",
  "tab_mine": "Moi",
  "prompt_page_error": "Une erreur s'est produite.",
  "btn_share": "Partager",
  "btn_report": "Rapporter",
  "btn_enable": "Activer",
  "btn_enabled": "Activé",
  "btn_go_to_enable": "Aller pour activer",
  "btn_retry": "Réessayer",
  "prompt_title_warning": "Attention",
  "prompt_title_tips": "",
  "prompt_title_warm_tips": "Astuces",
  "prompt_confirm_to_cancel": "Vous confirmez l'annulation?",
  "prompt_failed": "Echec",
  "btn_agree": "Accepter",
  "btn_reject": "Rejeter",
  'btn_arrow': 'Autoriser',
  "btn_need_help": "Besoin d'Aide?",
  "btn_common_problem": "FAQ",
  "page_message_center": "Messagerie",
  "title_sys_message": "Message Système",
  "title_social_message": "Message Social",
  "btn_save_and_share": "Enregistrer et Partager",
  "prompt_saved": "Sauvegardé",
  "prompt_save_failed": "Sauvegarde échouée",
  "prompt_updated": "Mis à jour",
  "prompt_update_failed": "Echec de mise à jour",
  "prompt_data_empty": "Donnée vide.",
  "prompt_loading": "Chargement...",
  "prompt_load_failed": "Echec de chargement",
  "prompt_copied": "Copié",
  "prompt_action_failed": "Echec",
  "prompt_press_again_to_exit": "Appuyer de nouveau pour sortir.",
  "prompt_description": "Description",

  "datetime_just_now": "Maintenant",
  "datetime_x_minutes_ago": "il y a %smin",
  "datetime_yesterday_x": "Hier %s",

  "unknown": "Inconnu",

  "prompt_location_settings_tips":
      "Veuillez autoriser INMOTION à accéder à l'emplacement dans Paramètres du téléphone-Applications-INMOTION-Autorisations pour rechercher des véhicules.",
  "prompt_bluetooth_settings_tips":
      "Veuillez autoriser INMOTION à accéder aux appareils à proximité dans Paramètres du téléphone-Applications-INMOTION-Autorisations pour utiliser les fonctions de recherche et de connexion de véhicules normalement.",
  "prompt_camera_settings_tips":
      "Veuillez autoriser INMOTION à accéder à l'appareil photo dans Paramètres du téléphone-Applications-INMOTION-Autorisations pour utiliser des fonctions telles que la prise de photos et la numérisation de codes QR.",
  "prompt_microphone_settings_tips":
      "Veuillez autoriser INMOTION à accéder au microphone dans Paramètres du téléphone-Applications-INMOTION-Autorisations pour utiliser des fonctions telles que le bricolage audio.",
  "prompt_storage_settings_tips":
      "Veuillez autoriser INMOTION à accéder aux fichiers et aux médias dans Paramètres du téléphone-Applications-INMOTION-Autorisations, afin que les fonctions telles que le téléchargement d'avatars et l'enregistrement d'images sur les téléphones mobiles puissent être utilisées normalement.",

  "prompt_location_settings_desc": "INMOTION a besoin d'une autorisation de localisation pour utiliser le véhicule de recherche.",
  "prompt_bluetooth_settings_desc": "INMOTION a besoin de l'autorisation d'accéder aux appareils à proximité pour rechercher et connecter des véhicules.",
  "prompt_camera_settings_desc": "INMOTION a besoin de l'autorisation de l'appareil photo pour prendre des photos et scanner les codes QR.",
  "prompt_microphone_settings_desc": "INMOTION a besoin de l'autorisation du microphone DIY audio.",
  "prompt_storage_settings_desc": "INMOTION a besoin de fichiers et d'autorisations multimédias pour télécharger des avatars et enregistrer des images sur le téléphone.",

  ///
  /// Account
  ///

  "prompt_auto_register_if_account_not_exists": "Le numéro de téléphone sera utilisé automatiquement pour la création du compte après la vérification",
  "btn_login": "Connexion",
  "btn_register": "S'inscrire",
  "title_register": "S'inscrire",
  "title_cn_phone_quick_login": "Connexion Rapide",
  "prompt_input_phone": "Numéro de Tèl",
  "prompt_input_email": "Adresse E-mail",
  "prompt_input_email_or_username": "Adresse E-mail/Identifiant",
  "prompt_input_verification_code": "Code de vérification",
  "prompt_input_password": "Mot de Passe",
  "prompt_input_a_valid_phone": "Merci de saisir un numéro de téléphone valide!",
  "prompt_input_a_valid_email": "Merci de saisir une adresse E-mail valide!",
  "prompt_input_a_valid_email_or_username": "Merci de saisir une adresse E-mail ou un Identifiant valide!",
  "prompt_input_a_valid_password": "Merci de saisir un mot de passe valide",
  "btn_forgot_password": "Mot de passe oublié?",
  "btn_reset_password": "Réinitialiser Mot de Passe",
  "btn_login_via_password": "Se connecter avec Identifiant/Mot de Passe",
  "btn_login_via_verification_code": "Se connecter avec un code de vérification",
  "btn_request_verification_code": "Obtenir un Code",
  "btn_request_sms_verification_code": "Obtenir un Code",
  "prompt_verification_code_has_sent_to": "Le code de vérification a été envoyé à %s",
  "btn_resend": "Renvoyer",
  "title_user_agreement": "Accord de l'Utilisateur",
  "title_privacy_policy": "Politique de Confidentialité",
  "title_user_agreement_and_privacy_policy": "INMOTION\nContrat d'utilisation et politique de confidentialité",
  "title_user_agreement_and_privacy_policy_tips":
      "Nous attachons une grande importance à la protection de vos informations personnelles et de votre vie privée. Afin de mieux protéger vos droits, veuillez lire attentivement et accepter les %s et %s pour commencer à utiliser INMOTION APP.",
  "prompt_register_agreement_tips": "S'inscrire ou se connecter implique votre accord à %s et %s",
  "title_select_country_or_region": "Choisir Pays/Région",
  "btn_modify_phone": "Modifier le numéro de téléphone",
  "btn_modify_email": "Modifier l'adresse E-Mail",
  "btn_bind_phone": "Lier le numéro de Téléphone",
  "btn_modify_password": "Modifier le Mot de Passe",
  "phone_number": "Numéro de Téléphone",
  "email": "E-Mail",
  "btn_register_via": "S'inscrire avec %s",
  "btn_bind_via": "Associer avec %s",
  "btn_reset_password_via": "Réinitialiser avec %s",
  "btn_bind_account": "Associer le Compte",
  "prompt_password_limit_tips": "Merci d'entrer entre 6 et 20 caractères, pas de chiffres",
  "prompt_empty_password": "Mot de passe vide",
  "title_bind_social_account": "",
  "prompt_social_account_auth_failed": "Echec d'autorisation",
  "prompt_bind_social_account_tips": "",
  "state_bound": "Associé",
  "state_not_bound": "Non Associé",
  "prompt_unbind_social_account_tips": "Après la dissociation, vous ne pourrez plus utiliser %s poiur vous connecter à INMOTION, êtes-vous sûr de vouloir dissocier?",
  "btn_logout": "Déconnexion",
  "prompt_logout_tips": "Confirmez-vous la déconnexion?",
  "title_operation_verification": "Vérification de Sécurité",
  "prompt_operation_verification_tips": "L'opération nécessite une vérification, merci de vérifier avec une des méthodes suivantes",
  "title_verify_operation_via": "Vérifier avec %s",
  "prompt_operation_verification_expired": "Merci de procéder d'abord à la vérification de sécurité!",
  "text_none": "Aucun",
  "title_account_cancellation": "Annulation de compte",
  "prompt_account_cancellation_details":
      "Le compte INMOTION devient irrécupérable après la fermeture de la clôture. Nous vous recommandons de sauvegarder les informations et les données liées à votre compte. N'oubliez pas : si vous fermez votre compte INMOTION, vous ne pourrez plus utiliser ce compte ou récupérer votre produits vérifiés ou d'autres informations (même si vous vous enregistrez et utilisez à nouveau INMOTION avec le même numéro de téléphone ou compte de messagerie), y compris, mais sans s'y limiter :\n(1) Les produits authentifiés par votre compte INMOTION seront automatiquement dissociés, et les autres utilisateurs peut s'authentifier directement après avoir connecté ces produits ;\n(2) Vous ne pourrez pas récupérer les mises à jour, les likes et les commentaires que vous avez partagés sur votre compte INMOTION ;\n(3) La pièce LE de votre compte INMOTION et le les objets virtuels échangés avec Le coin (tels que les packs d'effets de lumière d'ambiance) ne seront pas récupérés ;\n(4) Veuillez noter que l'annulation de votre compte INMOTION ne signifie pas que les activités du compte et les responsabilités associées avant l'annulation de ce compte seront être exempté ou atténué.",
  "prompt_account_cancellation_apply_success": "La demande a été soumise avec succès et nous traiterons votre demande d'annulation dès que possible.",

  /// Chinese phone quick verify error
  "prompt_cn_phone_auth_no_sim_card": "Pas de carte SIM détectée!",
  "prompt_cn_phone_auth_unknown_operator": "Opérateur inconnu!",
  "prompt_cn_phone_auth_network_not_enable": "Les données mobiles ne sont pas activées!",
  "prompt_cn_phone_auth_unknown": "Erreur inconnue!",

  ///
  /// Vehicle
  ///
  "btn_search_vehicle": "Recherche du Véhicule",
  "prompt_canceled": "Annulé",
  "prompt_had_connected_before": "Connecté précédemment",
  "title_vehicle_activation": "Activation",
  "prompt_wait_for_activation_tips_finished": "Merci de lire/regarder les avertissements de sécurité.",
  "prompt_had_read_activation_tips": "J'ai lu attentivement les avertiseements de sécurité ci-dessus et je connais les risques encourus",
  "btn_activate": "Activer maintenant",
  "prompt_activated": "Activé avec succès!",
  "prompt_activate_failed": "Echec de l'activation",
  "prompt_activate_canceled": "Annulé",
  "prompt_authorize_as_owner_after_activation":
      "L'enregistrement du véhicule est requise pour les fonctionnalités comme le verouillage du véhicule dans l'application. Voulez-vous l'enregistrer en tant que propriétaire maintenant?",
  "prompt_authorize_as_owner_later_after_activation": "Vous pouvez aussi le faire plus tard dans 'Moi - Enregistrement du Propriétaire'",
  "prompt_set_vehicle_password_failed": "Echec de la création du mot de passe",
  "prompt_set_vehicle_password_later_after_activation": "Vous pouvez aussi le faire plus tard dans 'Véhicule - Réglages Véhicule - Mot de Passe'",
  "prompt_bluetooth_disabled": "Le Bluetooth du téléphone n'est pas activé",
  "prompt_location_disabled": "Le service de localisation n'est pas activé",
  "prompt_no_bluetooth_permission": "Pas d'authorisation Bluetooth",
  "prompt_no_location_permission": "Pas d'authorisation de localisation",
  "prompt_no_scan_bluetooth_permission": "Pas d'authorisation de recherche Bluetooth",
  "prompt_no_connect_bluetooth_permission": "Pas d'authorisation de connexion Bluetooth",
  "prompt_no_device_found": "Pas de Véhicule trouvé.",
  "prompt_tap_to_connect": "Cliquez sur le véhicule ci-desoous pour vous connecter",
  "prompt_scanning": "Recherche...",
  "prompt_connecting": "Connexion...",
  "prompt_connection_canceled": "Connexion annulée",
  "prompt_connected": "Connecté",
  "prompt_connection_timeout": "Temps de connexion dépassé",
  "prompt_connection_failed": "Echec de connexion",
  "prompt_unsupported_models": "Modèle non supporté",
  "prompt_Initialization_data_exception": "Exception de données d'initialisation, code d'erreur : %s",
  "btn_enable_bluetooth": "Activer le Bluetooth du téléphone",
  "btn_enable_location": "Activer le service de localisation",
  "btn_request_bluetooth_permission": "Demander les permissions Bluetooth",
  "btn_request_location_permission": "Demander les permissions de localisation",
  "btn_scan_again": "Chercher encore",
  "btn_cancel_connection": "Annuler",
  "prompt_why_need_to_enable_location": "Pourquoi dois-je activer le service de localisation?",
  "prompt_why_need_location_permission": "Pourquoi INMOTION a besoin des permissions de localisation?",
  "prompt_why_do_i_couldnt_find_vehicles": "Pourquoi je ne peux pas rechercher mon véhicule?",
  "btn_view_solutions": "Vois les Solutions",
  "prompt_connect_failed_server_ip_service_error": "Erreur temporaire des serveurs, nous allons regler le problème, merci de réessayer plus tard.",
  "prompt_connect_failed_unknown_model":
      "Vous ne pouvez pas utiliser l'application INMOTION parce que le modèle de ce véhicule est invalide.\nMerci de nous contacter pour plus d'informations.",
  "prompt_connect_failed_unknown_sn":
      "Vous ne pouvez pas utiliser l'application INMOTION parce que le numéro de série du véhicule est invalide.\nMerci de nous contacter pour plus d'informations.",
  "prompt_connect_failed_vehicle_locked": "Le véhicule est en MODE VERROUILLE. Merci de nous contacter pour plus d'informations.",
  "prompt_connect_failed_vehicle_lost_mode": "Le véhocule est en MODE PERDU. Vous pouvez le désactiver dans 'Moi-Trouve mon véhicule' si vous êtes le propriétaire du véhicule.",
  "prompt_connect_failed_area_not_available": "Vous ne pouvez pas utiliser ce véhicule dans la zone actuelle.",

  "text_vehicle_ride_time": "Durée du Parcours",
  "text_vehicle_ride_mileage": "Distance du Parcours",
  "text_vehicle_max_speed": "Vitesse Max.",
  "text_vehicle_ave_speed": "Vitesse Moy.",
  "text_vehicle_total_mileage": "Distance Totale",
  "text_vehicle_manual_odo_mileage": "ODO Manuel",
  "text_vehicle_dynamic_speed_limit": "Vitesse limite dynamique",
  "text_vehicle_max_power": "Puissance Max.",
  "text_vehicle_mos_temp": "Temp MOS",
  "text_vehicle_consumption": "Consommation",
  "text_vehicle_last_ride_mileage": "Distance du dernier parcours",
  "text_vehicle_last_ride_time": "Durée du dernier parcours",
  "text_vehicle_last_max_speed": "Vitesse Max. du dernier parcours",
  "text_vehicle_battery_discharge_current": "Tension de sortie de la batterie",
  "text_vehicle_battery_voltage": "Tension Batterie",
  "text_vehicle_battery_output_power": "Puissance de sortie de la batterie",
  "text_vehicle_motor_output_power": "Puissance de sortie du moteur",
  "text_vehicle__motor_torque": "Couple",
  "text_vehicle_remaining_battery": "Batterie restante",
  "text_vehicle_output_rate": "Tension vectorielle de sortie(%)",
  "text_vehicle_dynamic_current_limit": "Limite dynamique de Surtension",

  "text_dashboard_settings": "Paramètres du tableau de bord",
  "text_dashboard_settings_choose": "Choisir",
  "prompt_long_press_to_edit": "Appui long pour éditer",
  "prompt_double_click_to_reset_manual_odo":
      "Le compteur kilométrique manuel peut être réinitialisé pour accumuler le kilométrage à partir d'un emplacement spécifique ou pour mesurer la distance même entre les trajets. Double-cliquez pour réinitialiser l'ODO manuel.",
  "prompt_confirm_to_reset_manual_odo": "Confirmez-vous la réinitialisation de l'odomètre manuel?",

  "text_vehicle_speed": "Vitesse",
  "text_vehicle_mileage": "Kilométrage",
  "text_vehicle_power": "Puissance",
  "text_vehicle_time": "Heure",
  "text_vehicle_temperature": "Température",
  "text_vehicle_other": "Autre",

  "text_vehicle_motor_temp": "Temp Moteur",
  "text_vehicle_battery_temp": "Temp Batterie",
  "text_vehicle_motherboard_high_temp": "Temp Carte Mère",
  "text_vehicle_driver_board_cpu_temp": "Temp CPU Carte Mère",
  "text_vehicle_imu_temp": "Temp IMU",

  "text_gps_speed": "Vitesse GPS",

  "prompt_status_connecting": "Connexion",
  "prompt_status_connected": "Connecté",
  "prompt_status_disconnected": "Non connecté",
  "prompt_vehicle_disconnected": "Le véhicule est déconnecté",
  "prompt_no_connected_vehicles_yet": "Pas encore de véhicule connecté.",
  "prompt_current_connected_vehicle": "Connecté",
  "prompt_last_connected_at": "Dernière connexion: %s",
  "title_switch_vehicle": "Changer de véhicule",
  "btn_disconnect_and_scan": "Déconnecter et Chercher",
  "btn_scan": "Chercher",
  "btn_detailed_data": "Données détaillées",
  "title_about_vehicle": "A Propose du véhicule",
  "title_battery_info": "Informations de la Batterie",
  "title_customer_service": "Service en Ligne",
  "title_faq": "FAQ",

  "title_gps_riding_tracks": "Mes Parcours",
  "title_vehicle_riding_record": "Enregistrement des Parcours",

  "text_vehicle_riding_record_mileage": "Distance Parcourue: %s",
  "text_vehicle_riding_record_max_speed": "Vitesse Max.: %s",

  "title_vehicle_riding_report": "Rapport de Parcours",
  "prompt_invalid_riding_track": "Rapport de parcours invalide.",

  "title_basic_battery_info": "Informations Basiques",
  "text_battery_voltage": "Tension",
  "text_battery_charge_voltage": "Tension de Charge",
  "title_detailed_battery_info": "Informations du pack de Batteries",
  "text_battery_detected_status": "Etat détecté de la Batterie",
  "text_battery_detected": "Détecté",
  "text_battery_not_detected": "Non Détecté",
  "text_battery_enable_status": "Etat d'activation de la Batterie",
  "text_battery_enabled": "Activée",
  "text_battery_disabled": "Désactivée",
  "text_battery_error_status": "Etat d'Erreur de la Batterie",
  "text_battery_ok": "OK",
  "text_battery_error": "Erreur",
  "text_battery_signal_logic_error": "Erreur du signal logique",

  "title_battery_cells_voltage": "Tension des cellules de la Batterie",

  "title_bms_basic_info": "Infos Basiques",
  "text_bms_battery_sn": "SN Batterie",
  "text_bms_manufacture_date": "Date de Fabrication",
  "text_bms_full_charge_cycles": "Cycles de charges complètes",
  "text_bms_software_version": "Version logicielle du BMS",
  "text_bms_hardware_Version": "Version matérielle du BMS",
  "title_bms_data_and_status": "Données et Etat",
  "text_bms_voltage": "Voltage",
  "text_bms_charge_state": "Etat de Charge",
  "text_bms_charge_current": "Tension de Charge",
  "text_bms_discharge_current": "Tnesion de Decharge",
  "text_bms_charge_mos_state": "Charge MOS",
  "text_bms_discharge_mos_state": "Decharge MOS",
  "text_bms_error_status": "Etat d'Erreur",
  "text_bms_warning_status": "Etat d'Avertissement",
  "text_bms_protection_status": "Etat de Protection",
  "text_bms_cell_balancing_status": "Equilibrage des Cellules",
  "text_bms_max_cell_voltage": "Tension Max. des Cellules",
  "text_bms_min_cell_voltage": "Tension Min. des Cellules",
  "text_bms_charge_mos_temp": "Température de Charge MOS",
  "text_bms_discharge_mos_temp": "Température de Décharge MOS",
  "text_bms_cells_temp": "Température des Cellules",
  "text_bms_cells_voltage": "Tension des Cellules",

  /// vehicle settings
  "title_vehicle_settings": "Réglages du Véhicule",
  "prompt_operation_succeed": "Réussi",
  "prompt_operation_failed": "Echec",
  "title_vehicle_password": "Mot de Passe",
  "text_vehicle_password_disabled": "Désactivé",
  "text_vehicle_password_gesture": "Geste",
  "text_vehicle_password_slide": "Glisser",
  "text_vehicle_password_number": "Numéro",
  "title_modify_vehicle_password": "Changer le Mot de Passe",
  "title_set_vehicle_password": "Définir le Mot de Passe",
  "prompt_vehicle_number_password_tips": "Merci d'indiquer un mot de Passe de 4 ou 6 chiffres",
  "title_vehicle_userinfo": "Informations Utilisateur",
  "title_vehicle_userinfo_avatar": "Avatar",
  "title_vehicle_userinfo_name": "Nom du Véhicule",
  "prompt_vehicle_userinfo_name_tips": "Merci d'indiquer entre 1 et 16 lettres, chiffres et symboles",
  "title_choose_setting_item": "Selection des Réglages",
  "vehicle_setting_item_limit_speed_25": "Limite de Vitesse à 25km/h",
  "vehicle_setting_item_limit_speed": "Limite de Vitesse",
  "vehicle_setting_item_drive_mode": "Mode de Conduite",
  "vehicle_setting_item_drive_mode_normal": "Commuting",
  "vehicle_setting_item_drive_mode_normal_tips": "Accélération et Décélération douce et linéaire",
  "vehicle_setting_item_drive_mode_off_road": "Off-Road",
  "vehicle_setting_item_drive_mode_off_road_tips": "Sensibilité des pédales renforcée pour des accélérations vives, grimper des collines, et rouler en Hors-Pistes",
  "vehicle_setting_item_pedestrian_mode_limit_speed": "Vitesse Max.(Mode Piéton)",
  "vehicle_setting_item_pedal_sensitivity": "Sensibilité des Pédales",
  "vehicle_setting_item_spilt_mode": "Spilt Mode",
  "vehicle_setting_item_spilt_mode_speeding": "Accélération",
  "vehicle_setting_item_spilt_mode_breaking": "Freinage",
  "vehicle_setting_item_power_assist": "Assistance de Puissance",
  "vehicle_setting_item_acc_assist": "Assistance à l'Accélération",
  "vehicle_setting_item_brake_assist": "Assistance au Freinage",
  "vehicle_setting_item_cruise": "Croisière",
  "vehicle_setting_item_ride_assist": "Assistantce à la conduite",
  "vehicle_setting_item_zero_start": "Zero-Start",
  "vehicle_setting_item_assist_balance": "Assistance d'équilibre",
  "vehicle_setting_item_load_detect": "Détection de Charge",
  "vehicle_setting_item_noload_detect": "Détéction de Non-Charge",
  "vehicle_setting_item_up_hill_assist": "Assistance en Côtes",
  "vehicle_setting_item_down_hill_assist": "Assistance en Descente",
  "vehicle_setting_item_overspeed_alarm": "Alarme de Vitesse",
  "vehicle_setting_item_lock": "Vérouillage",
  "vehicle_setting_item_password": "Mot de Passe",
  "vehicle_setting_item_diagnosis": "Diagnostic",
  "vehicle_setting_item_headlight": "Feu avant",
  "vehicle_setting_item_headlight_brightness": "Luminosité du Feu Avant",
  "vehicle_setting_item_drl": "DRL",
  "vehicle_setting_item_low_beam_headlight": "Faisceau Bas du Feu Avant",
  "vehicle_setting_item_low_beam_headlight_brightness": "Luminosité du Faisceau Bas du Feu Avant",
  "vehicle_setting_item_high_beam_headlight": "Faisceau Haut du Feu Avant",
  "vehicle_setting_item_high_beam_headlight_brightness": "Luminosité du Faisceau Haut du Feu Avant",
  "vehicle_setting_item_auto_headlight": "Feu Avant Automatique",
  "vehicle_setting_item_auto_headlight_brightness_threshold": "Seuil de réglage du Feu Avant Automatique",
  "vehicle_setting_item_auto_low_high_beam": "Faisceau Haut/Bas du Feu Avant Automatique",
  "vehicle_setting_item_auto_low_high_beam_switch_speed_threshold": "Seuil de Vitesse du Faisceau Haut/Bas du Feu Avant Automatique",
  "vehicle_setting_item_light_effect": "Effet de Lumière",
  "vehicle_setting_item_light_effect_mode": "Mode d'Effet de Lumière",
  "vehicle_setting_item_light_effect_front": "Mode d'Effet de Lumière Avant",
  "vehicle_setting_item_light_effect_rear": "Mode d'Effet de Lumière Arrière",
  "vehicle_setting_item_light_diy": "DIY",
  "vehicle_setting_item_auto_turn_signal": "Clignotants",
  "vehicle_setting_item_audio_state": "Audio",
  "vehicle_setting_item_volume": "Volume",
  "vehicle_setting_item_audio_package": "Pack Audio",
  "vehicle_setting_item_standby_time": "Standby",
  "vehicle_setting_item_spin_kill_btn": "Bloc-Roue",
  "vehicle_setting_item_sound_wave": "Son de Vague",
  "vehicle_setting_item_sound_wave_sensitivity": "Sensibilité du Son de Vague",
  "vehicle_setting_item_estimated_remainder_range": "Estimation de Distance Restante",
  "vehicle_setting_item_user_info": "Informations du Véhicule",
  "vehicle_setting_item_fan_quiet_mode": "Mode silencieux du Ventilateur",
  "vehicle_setting_item_forced_fan": "Ventilateur Forcé",
  "vehicle_setting_item_transport_mode": "Mode Transport",
  "vehicle_setting_item_low_battery_safe_mode": "Mode Sans-echec Batterie Faible",
  "vehicle_setting_item_auto_screen_off": "Mise en Veuille Automatique de l'Ecran",
  "vehicle_setting_item_speed_unit": "Metric/Imperial",
  "vehicle_setting_item_sn": "SN",
  "vehicle_setting_item_acc_force": "Force acc.",
  "title_vehicle_acc_front_force": "Force acc. avant",
  "title_vehicle_acc_rear_force": "Force d'acc. arrière",
  "vehicle_setting_item_brake_force": "Force de freinage",
  "title_vehicle_brake_front_force": "Force de freinage avant",
  "title_vehicle_brake_rear_force": "Force de freinage arrière",
  "vehicle_setting_item_one_pedal_mode": "Mode à une pédale",
  "vehicle_setting_item_brake_first": "Freiner d'abord",
  "vehicle_setting_item_auto_park_time": "Temps de stationnement automatique",
  "vehicle_setting_item_activate_date": "Activée le",
  "vehicle_setting_item_total_mileage": "Distance Totale",
  "vehicle_setting_item_hmic_board_version": "Carte HMIC",
  "vehicle_setting_item_bt_board_version": "Carte BT",
  "vehicle_setting_item_driver_board_version": "Carte Mère",
  "vehicle_setting_item_driver_board_temp": "Temp Carte Mère",
  "vehicle_setting_item_riding_mode": "Mode de Conduite",
  "vehicle_setting_riding_mode_p": "P",
  "vehicle_setting_riding_mode_eco": "ECO",
  "vehicle_setting_riding_mode_eco_tips": "Recommandé aux débutants, accélération douce.",
  "vehicle_setting_riding_mode_normal": "D",
  "vehicle_setting_riding_mode_sport": "S",
  "vehicle_setting_riding_mode_extreme": "X",
  "vehicle_setting_riding_mode_sport_tips": "Recommandé aux conducteurs expérimentés, plus de puissance et d'accélération",
  "vehicle_setting_riding_pedestrian_mode": "Mode Piéton",
  "vehicle_setting_riding_pedestrian_mode_tips": "Trotinette plus facile à pousser.",
  "vehicle_setting_item_riding_mode_euc_normal": "Normal",
  "vehicle_setting_item_riding_mode_euc_normal_tips": "Plus prudent, convient à la majorité des conducteurs.",
  "vehicle_setting_item_riding_mode_euc_fancier": "Fancy",
  "vehicle_setting_item_riding_mode_euc_fancier_tips": "Plus de Puissance et Vitesse Max. plus élévée.",
  "prompt_cannt_set_sport_mode_when_limit_speed_25kmph_enabled": "Vous ne pouvez pas passer en mode 'S' quand la 'Limite de vitesse à 25km/h' est activée.",
  "prompt_cannt_enable_limit_speed_25kmph_when_sport_mode_enabled": "Vous ne pouvez pas activer la 'Limite de vitesse à 25km/h' en mode 'S'.",
  "vehicle_setting_item_berm_angle_mode": "Berm Angle Mode",
  "prompt_unlock_factory_safe_speed_limit": "Pour votre Sécurite, la limite de vitesse Max. peut être augmentée à 90km/h quand votre distance totale parcourue dépasse 30km. %s",
  "prompt_unlock_factory_safe_speed_limit_not_now":
      "Pour votre Sécurite, la limite de vitesse Max. peut être augmentée à 90km/h quand votre distance totale parcourue dépasse 30km. VOus devez encore rouler pendant %s.",
  "prompt_unlock_now": "Debloquer Maintenant>>",

  "warning_unlock_v13_factory_speed_limit":
      "Votre sûreté et votre sécurité sont notre priorité absolue. Pour mieux protéger vos droits et intérêts personnels, veuillez comprendre et lire attentivement cette déclaration afin de vous assurer que vous comprenez pleinement le contenu de cette déclaration.\n\n1. Vous reconnaissez et comprenez que vous êtes tentez actuellement de déverrouiller la limite de vitesse maximale du volant. Une fois cette restriction levée, vous pourrez ajuster la limite de vitesse maximale à 90 km/h.\n2. Vous comprenez et êtes conscient des risques associés à l'ultra-haute vitesse conduite et sera responsable de toute perte, dommage et risque causé par la vitesse élevée.\n3. Vous êtes tenu de connaître toutes les lois et réglementations concernant la conduite de monocycles électriques dans votre région et de vous conformer strictement aux lois applicables , réglementations et politiques relatives à la conduite du V13. Ne conduisez pas le V13 dans les zones interdites par la législation locale.\n4. Veuillez interdire à toute personne n'ayant pas lu attentivement les instructions ou ne connaissant pas les consignes de sécurité de conduite du V13 de conduire votre véhicule.\n5 . Avant chaque trajet, assurez-vous de vérifier si les produits et accessoires sont en bon état, évitez d'utiliser des batteries et accessoires non originaux, et ne démontez pas, ne fissurez pas ou ne modifiez pas les produits et accessoires sans autorisation. Vous serez responsable de toute perte, ou dommage et risque causé par une mauvaise opération.\n\nVeuillez lire attentivement et choisir d'accepter ou de ne pas accepter cette déclaration. Vous ne pouvez pas déverrouiller la limite de vitesse maximale tant que vous n'acceptez pas cette déclaration. Votre \"Accord\" sera considéré comme une acceptation de cette clause de non-responsabilité. Si vous avez des questions concernant cette clause de non-responsabilité, veuillez cliquer sur \"Annuler\"",
  "warning_enable_berm_angle_mode":
      "Lorsque ce mode est activé, l'angle de protection contre le retournement du véhicule s'agrandit, ce qui signifie que le véhicule peut osciller d'avant en arrière et être facilement hors de contrôle en raison de petits changements d'angle d'équilibre lorsqu'il est positionné latéralement. Cela peut vous blesser ou les environs. Vous connaissez déjà tous les risques possibles, êtes-vous sûr de vouloir l'activer ?",
  "warning_disable_berm_angle_mode": "Pour activer, appuyez sur le bouton Spin-Kill une fois le mode activé/désactivé. ",

  "title_vehicle_balance_angle": "Angle d'équilibre",
  "title_vehicle_calibration": "Calibrage du véhicule",
  "title_vehicle_balance_angle_calibration": "Étalonnage de la balance",
  "prompt_vehicle_balance_angle_calibration_desc":
      "Si le véhicule s'incline toujours vers l'arrière ou vers l'avant sur le sol après avoir réglé l'angle d'équilibrage sur zéro, vous pouvez essayer cet étalonnage pour le réparer. %s",
  "prompt_vehicle_balance_angle_calibration":
      "Veuillez appuyer et maintenir le Spin-Kill pour garder la direction verticale du véhicule toujours perpendiculaire au sol horizontal",
  "title_vehicle_turning_calibration": "Étalonnage des virages",
  "title_vehicle_turning_calibration_desc": "Cela peut améliorer l'expérience de virage. %s",
  "text_view_calibration_guide": "Afficher le guidage>>",
  "title_motor_self_adjustment": "Auto-ajustement sur le moteur",
  "prompt_motor_self_adjustment_desc":
      "Le moteur fonctionnera automatiquement pendant 1 minute une fois démarré. Pour votre sécurité, assurez-vous que l'EUC est dans un état basculé et ne touchez pas les roues !",
  "prompt_clear_motor_self_adjustment_effect_desc": "Il est recommandé de %s s'il n'y a pas d'amélioration de l'expérience de conduite",
  "title_clear_motor_self_adjustment_effect": "Effacer les performances d'auto-ajustement sur le moteur",
  "prompt_motor_self_adjustment_in_progress": "L'auto-ajustement est en cours...",
  "prompt_motor_self_adjustment_terminated": "Auto-ajustement terminé",
  "prompt_motor_self_adjustment_succeed": "Auto-ajustement terminé",
  "prompt_motor_self_adjustment_finished": "Auto-ajustement terminé",
  "prompt_motor_self_adjustment_timeout": "Délai d'auto-ajustement",
  "prompt_confirm_to_clear_motor_self_adjustment_effect": "Confirmez-vous d'effacer les performances d'auto-ajustement sur le moteur ?",

  "prompt_motor_self_check_in_progress": "Auto-inspection en cours...",
  "prompt_motor_self_check_terminated": "Auto-inspection terminée",
  "prompt_motor_self_check_passed": "Auto-inspection réussie",
  "prompt_motor_self_check_not_passed": "Auto-inspection NON réussie",
  "prompt_motor_self_check_timeout": "Délai d'auto-inspection",
  "prompt_motor_self_check_failed": "Échec du démarrage de l'auto-inspection",

  "title_vehicle_acc_calibration": "Étalonnage de l'accélérateur",
  "title_vehicle_brake_calibration": "Calibrage des freins",
  "title_vehicle_gyro_calibration": "Calibrage du gyroscope",
  "prompt_vehicle_acc_calibration_tips":
      "Après avoir démarré l'étalonnage, maintenez la poignée des gaz à la valeur maximale et à la valeur minimale pendant 1 seconde. Assurez-vous de terminer l'opération d'étalonnage spécifiée dans les 5 secondes.",
  "prompt_vehicle_brake_calibration_tips":
      "Après avoir démarré l'étalonnage, maintenez la poignée de frein à la valeur maximale et à la valeur minimale pendant 1 seconde. Assurez-vous de terminer l'opération d'étalonnage spécifiée dans les 5 secondes.",
  "prompt_vehicle_gyro_calibration_tips": "Veuillez redresser le scooter pour garder le repose-pied parallèle au sol, puis démarrez le calibrage jusqu'à ce qu'il soit terminé.",
  "prompt_cannt_start_vehicle_acc_calibration_when_zero_start_enabled": "Vous ne pouvez pas démarrer un étalonnage de la poignée des gaz lorsque le mode 'Zero Start' est activé !",

  "prompt_calibration_succeed": "Calibrage réussi",
  "prompt_calibration_failed": "Le calibrage a échoué",
  "prompt_calibration_timeout": "Temporisation d'étalonnage",

  "title_vehicle_factory_reset": "Réinitialisation d'usine",
  "prompt_vehicle_confirm_to_factory_reset": "Confirmez-vous la réinitialisation d'usine ?",
  "prompt_vehicle_confirm_to_factory_reset_desc": "Restaurer tous les paramètres et le pack audio par défaut",
  "prompt_vehicle_ezcan_confirm_to_factory_reset_desc": "La réinitialisation d'usine peut prendre plusieurs minutes, veuillez ne pas quitter l'application.",
  "prompt_vehicle_ezcan_factory_reset_succeed": "Réinitialisation d'usine réussie, veuillez éteindre et attendre 10 secondes puis rallumer.",
  "prompt_vehicle_factory_reset_succeed": "Réinitialisation d'usine réussie !",

  "prompt_vehicle_euc_need_motor_free": "Veuillez caler l'EUC sur des béquilles ou le mettre sur le côté",

  "title_vehicle_firmware_update": "Mise à jour du micrologiciel",

  /// Assistance vélo électrique
  "title_vehicle_assistant_mode": "Mode d'assistance",
  "text_vehicle_assistant_mode_none": "Aucun",
  "prompt_vehicle_assistant_mode_none_desc": "Ce mode arrêtera l'assistance électrique, vous ne pouvez faire du vélo que pour avancer.",
  "text_vehicle_assistant_mode_medium": "Limité",
  "prompt_vehicle_assistant_mode_medium_desc": "Ce mode a une assistance limitée qui convient au cyclisme sur route plate.",
  "text_vehicle_assistant_mode_max": "Max",
  "prompt_vehicle_assistant_mode_max_desc":
      "Ce mode renforcera le support d'assistance électrique, adapté aux montées et descentes fréquentes. Ce mode consommera la batterie plus rapidement.",

  /// Effet lumineux L8
  "text_light_effect_mode_0": "Mode 1",
  "text_light_effect_mode_1": "Mode 2",
  "text_light_effect_mode_2": "Mode 3",
  "text_light_effect_mode_3": "Mode 4",
  "text_light_effect_mode_4": "Mode 5",
  "text_light_effect_mode_5": "Mode 6",
  "text_light_effect_mode_6": "Mode 7",
  "text_light_effect_mode_7": "Mode 8",
  "title_light_effect_color": "Couleur",

  /// Effet lumineux V12
  "text_light_effect_mode_close": "Désactiver",
  "text_light_effect_mode_light_package": "Pack audio",
  "text_light_effect_mode_light_package_change": "Modifier le pack audio",
  "text_light_effect_mode_follow_music": "Suivre la musique",
  "text_light_effect_mode_follow_speed": "Vitesse de suivi",
  "text_light_effect_mode_follow_speed_1": "Débit d'eau",
  "text_light_effect_mode_follow_speed_2": "Toujours activé",

  /// Diagnostic
  "title_vehicle_diagnosis": "Diagnostic",
  "prompt_vehicle_diagnosis_result": "Résultat du diagnostic",
  "prompt_vehicle_diagnosis_ok": "Aucune erreur connue ni avertissement n'a encore été trouvé",
  "prompt_vehicle_diagnosis_abnormal": "Votre véhicule est dans un état anormal",
  "title_vehicle_diagnosis_history": "Historique de diagnostic",
  "title_view_history": "Afficher l'historique",
  "title_vehicle_upload_log": "Journal de téléchargement",
  "prompt_upload_log_tips": "Le téléchargement du journal peut prendre quelques minutes, veuillez patienter",
  "title_upload_euc_log": "Télécharger le journal EUC",
  "title_upload_bms_log": "Télécharger le journal BMS",
  "title_uploading_euc_log": "Téléchargement du journal EUC",
  "title_uploading": "Téléchargement de %s",
  "title_upload_euc_and_bms_log": "Télécharger le journal EUC et BMS",
  "title_upload_bms_log_tips":
      "Il n'est pas nécessaire de télécharger les journaux BMS si la roue ne signale pas les avertissements/erreurs liés à la batterie, sauf demande spécifique de l'équipe INMOTION.",

  /// Diagnostic à distance
  "title_remote_diagnosis": "Diagnostic à distance",
  "prompt_remote_diagnosis_tips": "Veuillez utiliser cette fonction sous la direction de l'équipe INMOTION.",
  "prompt_remote_diagnosis_enter_failed": "Échec de la saisie du diagnostic à distance !",
  "prompt_remote_diagnosis_remote_disconnected": "L'appareil distant est déconnecté !",
  "prompt_remote_diagnosis_disconnected": "Le diagnostic à distance est déconnecté !",
  "prompt_remote_diagnosis_waiting_remote_connection": "Vous êtes actuellement en mode de diagnostic en ligne ! Veuillez attendre l'accès à l'appareil à distance.",
  "prompt_remote_diagnosis_confirm_to_cancel": "Vous attendez actuellement que l'appareil distant accède, êtes-vous sûr de quitter ?",
  "prompt_remote_diagnosis_waiting_remote_timeout": "L'accès a échoué, l'attente de l'accès à l'appareil distant a expiré.",
  "prompt_remote_diagnosis_in_progress":
      "Le diagnostic en ligne est en cours. Veuillez vous assurer que votre téléphone mobile est à proximité du véhicule et que le réseau est actif. Veuillez ne pas éteindre l'écran du téléphone mobile.",
  "prompt_remote_diagnosis_connect_identifier":
      "Le code de liaison est [%s], cliquez pour copier dans le presse-papiers. Veuillez envoyer ce code à INMOTION pour commencer le diagnostic.",

  "prompt_upload_log_success": "Téléchargement du journal réussi !",
  "prompt_upload_log_failed": "Le téléchargement du journal a échoué !",

  /// Mise à jour du firmware
  "text_vehicle_current_firmware_version": "Version actuelle : %s",
  "title_vehicle_current_firmware_version": "Version actuelle",
  "prompt_new_firmware_version_found": "Nouveau firmware trouvé",
  "prompt_cannt_interrupt_firmware_updating": "Veuillez continuer pour terminer la mise à jour.",
  "prompt_no_new_firmware_version_found": "Aucun nouveau firmware trouvé",
  "btn_update_firmware": "Mettre à jour maintenant",
  "title_firmware_update_notes": "Avis",
  "text_firmware_update_notes_1": "· Avant la mise à jour, assurez-vous que la batterie restante n'est pas inférieure à 20 %",
  "text_firmware_update_notes_2": "· Ne faites pas fonctionner le véhicule pendant la mise à jour",
  "text_firmware_update_notes_3": "· Si la mise à jour a échoué, essayez de quitter l'application et de mettre à jour à nouveau",
  "prompt_contact_us": "Contactez-nous",
  "prompt_firmware_update_learn_more_notes": "En savoir plus>>",
  "title_new_firmware_version_summary": "Recommander",
  "text_new_firmware_version_learn_more": "En savoir plus>>",
  "prompt_firmware_update_success": "Mise à jour réussie",
  "prompt_firmware_update_failed": "La mise à jour a échoué !",
  "prompt_last_firmware_update_interrupted": "La dernière mise à jour du firmware a peut-être été interrompue, veuillez continuer à terminer la mise à jour pour y remédier.",
  "prompt_forced_firmware_update_tips": ">Vous devez mettre à jour le firmware du véhicule vers la dernière version avant de pouvoir l'utiliser normalement",
  "prompt_firmware_update_le1_manually_process_tips":
      "Une fois l'affichage du véhicule éteint, veuillez attendre 3 secondes et rallumez-le manuellement. Cliquez ensuite sur 'Confirmer' pour continuer la mise à jour",
  "prompt_firmware_updating": "Mise à jour de %s",
  "prompt_firmware_update_waiting_device": "Mise à jour de l'appareil en attente",
  "prompt_vehicle_requesting_fw_update": "Le firmware de %s est cassé, veuillez passer à la mise à jour.",
  "prompt_vehicle_requesting_fw_update_manually_canceled": "Le firmware de %s est cassé, veuillez vous reconnecter et suivre les invites pour résoudre le problème du firmware.",

  "title_device_name_unknown": "Inconnu",
  "title_device_name_hmic_board": "Carte HMIC",
  "title_device_name_driver_board": "Carte pilote",
  "title_device_name_bt_board": "Carte BT",
  "title_device_name_display_board": "Tableau d'affichage",
  "title_device_name_bms": "BMS",
  "title_device_name_bms_1": "BMS 1",
  "title_device_name_bms_2": "BMS 2",
  "title_device_name_driver_board_1": "Driver Board(Front)",
  "title_device_name_driver_board_2": "Driver Board(Rear)",

  /// 驱动板故障
  "title_vehicle_diagnosis_module_driver_board": "Carte conducteur",
  "vehicle_error_parse_current_sensor": "Le capteur de courant de phase a échoué, vous devrez peut-être remplacer la carte de commande.",
  "vehicle_error_driver_board_front_current_sensor": "The current sensor of front driver board failed, you may need to replace the board.",
  "vehicle_error_driver_board_rear_current_sensor": "The current sensor of rear driver board failed, you may need to replace the board.",
  "vehicle_error_bus_current_sensor": "Le capteur de courant de bus a échoué, vous devrez peut-être remplacer la carte de pilote.",
  "vehicle_error_imu_sensor": "Le capteur IMU a échoué, vous devrez peut-être remplacer la carte pilote.",
  "vehicle_error_mos_temp_sensor": "Le capteur de température MOS est tombé en panne, vous devrez peut-être remplacer la carte pilote.",
  "vehicle_error_bus_voltage_sensor": "Le capteur de tension principal a échoué, vous devrez peut-être remplacer la carte de commande.",
  "vehicle_error_battery_voltage_sensor": "Le capteur de tension de la batterie est tombé en panne, vous devrez peut-être remplacer la carte pilote.",
  "vehicle_error_board_high_temp_area_sensor": "Le capteur de température de la zone à haute température a échoué, vous devrez peut-être remplacer la carte du conducteur.",
  "vehicle_error_current_sampling": "Erreur de données initiales d'échantillonnage actuel, vous devrez peut-être remplacer la carte pilote.",
  "vehicle_error_sensor": "Erreur de sortie du capteur, vous devrez peut-être remplacer la carte pilote.",
  "vehicle_error_rtc": "Erreur RTC, vous devrez peut-être remplacer la carte pilote.",
  "vehicle_error_spi_flash": "Erreur de stockage externe, vous devrez peut-être remplacer la carte pilote.",
  "vehicle_error_log": "Journaliser l'erreur système.",
  "vehicle_error_external_flash": "Le stockage externe a échoué, vous devrez peut-être remplacer la carte HMIC.",
  "vehicle_error_euc_driver_board_communication": "La communication de la carte conducteur a échoué, vous devrez peut-être remplacer la carte HMIC ou la carte conducteur.",
  "vehicle_error_scooter_driver_board_communication": "La communication de la carte pilote a échoué, vous devrez peut-être remplacer la carte d'affichage ou la carte pilote.",
  "vehicle_error_scooter_driver_board_communication_unstable":
      "La communication de la carte pilote est instable, vous devrez peut-être remplacer la carte d'affichage ou la carte pilote.",
  "vehicle_error_communication": "La communication de la carte du conducteur a échoué ， veuillez essayer de rallumer.",
  "vehicle_error_voltage": "Erreur de tension.",
  "vehicle_error_driver_board": "La carte pilote a échoué, vous devrez peut-être remplacer la carte pilote.",
  "vehicle_error_driver_board_oscillator": "Erreur de l'oscillateur à cristal.",
  "vehicle_error_scooter_front_driver_board_to_display_communication":
  "The front driver board communication failed, you may need to check the cable connections or replace the front driver board.",
  "vehicle_error_scooter_rear_driver_board_to_display_communication":
  "The rear driver board communication failed, you may need to check the cable connections or replace the rear driver board.",
  "vehicle_error_scooter_display_to_driver_board_communication":
  "The display board communication failed, you may need to check the cable connections or replace the display board.",

  "vehicle_warning_over_current": "Attention par surintensité, veuillez rouler doucement.",
  "vehicle_warning_over_temp": "La carte conducteur est en surchauffe, veuillez arrêter de rouler pendant un moment.",
  "vehicle_warning_cpu_over_temp": "Le CPU de la carte pilote est en surchauffe, veuillez arrêter de rouler pendant un moment.",
  "vehicle_warning_front_driver_cpu_over_temp": "The CPU of front driver board is overheat, please stop riding for a while.",
  "vehicle_warning_rear_driver_cpu_over_temp": "The CPU of rear driver board is overheat, please stop riding for a while.",
  "vehicle_warning_imu_over_temp": "L'IMU surchauffe, veuillez arrêter de rouler pendant un moment.",
  "vehicle_warning_mos_over_temp": "Le MOS surchauffe, veuillez arrêter de rouler pendant un moment.",
  "vehicle_warning_front_driver_hardware_over_temp": "Warning by front driver hardware over current, please stop riding for a while.",
  "vehicle_warning_rear_driver_hardware_over_temp": "Warning by rear driver hardware over current, please stop riding for a while.",
  "vehicle_warning_front_mos_over_temp": "Warning by front driver board MOS overheat, please stop riding for a while.",
  "vehicle_warning_rear_mos_over_temp": "Warning by rear driver board MOS overheat, please stop riding for a while.",

  /// affiche les erreurs et les avertissements du tableau
  "vehicle_error_scooter_imu_sensor": "Le capteur IMU a échoué, vous devrez peut-être remplacer la carte d'affichage.",

  /// erreurs et avertissements de la carte hmic
  "title_vehicle_diagnosis_module_hmic_board": "Carte HMIC",
  "vehicle_error_hmic_board_rtc": "Le RTC a échoué, vous devrez peut-être remplacer la carte mère.",
  "vehicle_error_hmic_board_flash": "Le stockage externe a échoué, vous devrez peut-être remplacer la carte principale.",

  /// erreurs et avertissements de la carte bt
  "title_vehicle_diagnosis_module_bt_board": "Carte BT",
  "vehicle_error_bt_board_communication": "La communication Bluetooth a échoué, vous devrez peut-être remplacer la carte mère ou la carte Bluetooth.",

  /// erreurs et avertissements du moteur
  "title_vehicle_diagnosis_module_motor": "Moteur",
  "vehicle_error_motor_hall": "Le hall du moteur est tombé en panne, vous devrez peut-être remplacer le moteur.",
  "vehicle_error_motor_hall_left": "Le moteur du hall gauche est tombé en panne, vous devrez peut-être remplacer le moteur.",
  "vehicle_error_motor_hall_right": "Le moteurle hall droit a échoué, vous devrez peut-être remplacer le moteur.",
  "vehicle_error_front_motor_hall": "La salle du moteur avant est tombée en panne, vous devrez peut-être remplacer le moteur.",
  "vehicle_error_rear_motor_hall": "La salle du moteur arrière est en panne, vous devrez peut-être remplacer le moteur.",
  "vehicle_error_motor_temp_sensor": "Le capteur de température du moteur est tombé en panne, vous devrez peut-être remplacer le moteur.",
  "vehicle_error_motor_phase": "Motor Phrase-manque, vous devrez peut-être remplacer le moteur.",
  "vehicle_warning_motor_over_temp": "Attention par surchauffe du moteur, veuillez arrêter de rouler pendant un moment.",
  "vehicle_warning_front_motor_over_temp": "Warning by overheat on front motor, please stop your riding for a while.",
  "vehicle_warning_rear_motor_over_temp": "Warning by overheat on rear motor, please stop your riding for a while.",
  "vehicle_warning_motor_spin": "Avertissement de rotation. Ne soulevez pas l'EUC sans appuyer sur le bouton Spin-kill.",
  "vehicle_warning_motor_blocked": "Avertissement par décrochage du moteur, veuillez ne pas vous garer sur une pente raide pendant une longue période.",
  "vehicle_warning_front_motor_blocked": "Warning by front motor stall, please do not park at a steep slopes for a long time.",
  "vehicle_warning_rear_motor_blocked": "Warning by rear motor stall, please do not park at a steep slopes for a long time.",

  /// erreurs et avertissements de batterie
  "title_vehicle_diagnosis_module_battery": "Batterie",
  "vehicle_error_battery": "La batterie est tombée en panne, vous devrez peut-être la remplacer.",
  "vehicle_error_battery_temp_sensor": "Le capteur de température de la batterie a échoué, vous devrez peut-être remplacer la batterie.",
  "vehicle_error_battery_cannt_power_off": "Impossible de s'éteindre normalement, vous devrez peut-être remplacer la batterie.",
  "vehicle_error_battery_cannt_charge": "Impossible de charger normalement, vous devrez peut-être remplacer la batterie ou le chargeur.",
  "vehicle_error_battery_signal": "Erreur de signal de batterie.",
  "vehicle_warning_low_battery": "Attention par batterie faible, veuillez recharger dès que possible.",
  "vehicle_warning_battery_over_temp": "La batterie est en surchauffe, veuillez arrêter de rouler pendant un moment.",
  "vehicle_warning_battery_calibration": "Avertissement anormal de l'étalonnage de la tension de la batterie. Veuillez %s.",
  "text_calibrate_battery": "étalonner la tension de la batterie",
  "vehicle_warning_some_batteries_not_enabled":
      "L'avertissement de certaines batteries ne fonctionne pas. Cela affectera les performances du véhicule. Veuillez rouler prudemment.",
  "vehicle_warning_danger_charge1_dual_charger":
      "Attention : les tensions des batteries gauche et droite sont différentes, une charge inappropriée peut entraîner des problèmes de sécurité. Ce que vous devez faire : ①Utilisez uniquement un chargeur d'origine pour charger la roue, deux chargeurs pour charger la roue en même temps n'est pas autorisé ②Placez la roue dans votre champ de vision, ne laissez pas la roue seule, observez attentivement le processus de charge. %s",
  "vehicle_warning_danger_charge1_single_charger":
      "Attention : les tensions des batteries gauche et droite sont différentes, une charge inappropriée peut entraîner des problèmes de sécurité. Ce que vous devez faire : placez la roue dans votre champ de vision, ne la laissez pas seule, observez attentivement le processus de charge. %s ",
  "vehicle_warning_danger_charge2":
      "Danger ! Arrêtez de charger ! Erreur de batterie, veuillez arrêter de charger et retirer votre chargeur immédiatement, placez votre roue dans un endroit sûr. Veuillez télécharger le journal du véhicule (Paramètres du véhicule - Diagnostiquer - Télécharger le journal), contactez votre revendeur pour le service. %s",
  "btn_i_know_danger_charge_risk_and_turn_off_alert": "Je connais ce risque et je désactive cette alerte d'avertissement",
  "vehicle_warning_battery_over_voltage": "Tension élevée de la batterie, vous devrez peut-être remplacer la batterie ou le chargeur.",
  "vehicle_warning_battery_output_abnormal": "Batterie pas de puissance de sortie, veuillez essayer de recharger ou vous devrez peut-être remplacer la batterie.",
  "vehicle_warning_too_low_battery": "Attention par la tension trop basse, veuillez recharger dès que possible pour éviter d'endommager la batterie.",

  /// Ventilateur
  "title_vehicle_diagnosis_module_fan": "Ventilateur",
  "vehicle_error_fan": "Le ventilateur de refroidissement est tombé en panne, vous devrez peut-être remplacer le ventilateur de refroidissement.",
  "vehicle_warning_fan_low_speed":
      "La vitesse de rotation du ventilateur est faible. Cela affectera le niveau de luminosité maximum. Veuillez vérifier si le ventilateur est bloqué ou non.",

  /// erreurs et avertissements du véhicule
  "title_vehicle_diagnosis_module_vehicle": "Véhicule",
  "vehicle_error_brake_handle": "Le guidon de frein a échoué, veuillez vérifier si le guidon de frein s'est relâché ou non.",
  "vehicle_error_acc_handle": "Échec de l'accélérateur, veuillez vérifier si le guidon de l'accélérateur s'est relâché ou non.",

  "vehicle_warning_lock_caused_by_safe_issue": "Le véhicule a été temporairement verrouillé en raison d'un danger caché lié à la sécurité.",
  "vehicle_warning_over_speed": "Avertissement d'excès de vitesse. Veuillez ralentir.",
  "vehicle_warning_fall_down": "Alerte de chute. Veuillez rouler prudemment.",
  "vehicle_warning_risk_behavior": "Attention par conduite dangereuse, merci de ne pas conduire excessivement.",
  "vehicle_warning_software_incompatible": "Attention par l'incompatibilité du firmware sur certaines pièces, veuillez mettre à jour le dernier firmware.",
  "vehicle_warning_motor_no_load_protection":
      "Avertissement par la protection contre la charge libre du moteur, il est recommandé d'appuyer sur le bouton Spin-kill avant de soulever et de s'assurer que le véhicule est à l'arrêt.",
  "vehicle_warning_power_key_long_pressed":
      "Avertissement en appuyant sur le bouton d'alimentation pendant une longue période, appuyer sur le bouton d'alimentation pendant une longue période peut déclencher une mise hors tension forcée. Veuillez arrêter de rouler !",
  "vehicle_warning_necessary_self_check_not_passed": "Unéchec de l'élément d'auto-inspection nécessaire ou avertissement non passé, %s.",
  "text_execute_self_check": "exécuter l'auto-inspection",
  "vehicle_warning_function_limited_by_uncompleted_fw_update": "La fonction du véhicule est limitée et le firmware doit être mis à jour avant de pouvoir être utilisé normalement.",
  "vehicle_warning_remote_locked": "Le véhicule a été verrouillé, veuillez nous contacter pour vérifier votre identité pour le déverrouiller.",
  "vehicle_warning_hardware_incompatible":
      "Attention par l'incompatibilité matérielle sur certaines pièces, la carte mère et la carte pilote doivent être remplacées dans un ensemble complet.",
  "vehicle_warning_over_power": "Surpuissance.",

  /// Erreur BMS
  "bms_error_voltage_sample": "Erreur d'échantillon de tension.",
  "bms_error_charge_current_sample": "Erreur d'échantillon de courant de charge.",
  "bms_error_discharge_current_sample": "Erreur d'échantillon de courant de décharge.",
  "bms_error_temperature_sensor": "Erreur du capteur de température.",
  "bms_error_rh_sensor": "Erreur du capteur d'humidité relative.",
  "bms_error_charge_mosfet": "Erreur de charge mos.",
  "bms_error_discharge_mosfet": "Erreur de décharge mos.",
  "bms_error_afe": "Erreur Afe.",
  "bms_error_cell": "Erreur de cellule.",
  "bms_error_mcu": "Erreur MCU.",

  /// Avertissement BMS
  "bms_warning_low_soc": "Avertissement de faible consommation.",
  "bms_warning_pack_over_charge": "Avertissement de surcharge de la batterie.",
  "bms_warning_pack_over_discharge": "Avertissement de décharge excessive de la batterie.",
  "bms_warning_cell_over_charge": "Avertissement de surcharge de la cellule de la batterie.",
  "bms_warning_cell_over_discharge": "Avertissement de décharge excessive de cellule de batterie.",
  "bms_warning_charge_over_current": "Avertissement de surcharge actuelle.",
  "bms_warning_charge_mosfet_over_temperature": "Avertissement de dépassement de température de Charge mos.",
  "bms_warning_charge_cell_over_temperature": "Avertissement de dépassement de température de la cellule de batterie.",
  "bms_warning_charge_cell_low_temperature": "Avertissement de basse température de charge de cellule de batterie.",
  "bms_warning_discharge_over_current": "Avertissement de décharge excessive.",
  "bms_warning_discharge_mosfet_over_temperature": "Avertissement de dépassement de température de décharge mos.",
  "bms_warning_discharge_cell_over_temperature": "Avertissement de décharge excessive de la cellule de la batterie.",
  "bms_warning_discharge_cell_low_temperature": "Avertissement de basse température de décharge de cellule de batterie.",
  "bms_warning_over_humidity": "Avertissement de surhumidité.",

  /// Protection BMS
  "bms_protection_short_circuit": "Protection contre les courts-circuits.",
  "bms_protection_pack_over_charge": "Protection contre la surcharge de la batterie.",
  "bms_protection_pack_over_discharge": "Protection contre la décharge excessive du bloc-batterie.",
  "bms_protection_cell_over_charge": "Protection contre la surcharge des cellules de la batterie.",
  "bms_protection_cell_over_discharge": "Protection de cellule de batterie contre la décharge.",
  "bms_protection_charge_over_current": "Protection contre les surintensités de charge.",
  "bms_protection_charge_mosfet_over_temperature": "Charge mos protection contre la surchauffe.",
  "bms_protection_charge_cell_over_temperature": "Protection contre la surchauffe de la charge des cellules de la batterie.",
  "bms_protection_charge_cell_low_temperature": "Protection contre les basses températures de charge des cellules de batterie.",
  "bms_protection_discharge_over_current": "Protection contre les surintensités de décharge.",
  "bms_protection_discharge_mosfet_over_temperature": "Discharge mos over over temperature protection.",
  "bms_protection_discharge_cell_over_temperature": "Protection contre la décharge excessive des cellules de la batterie.",
  "bms_protection_discharge_cell_low_temperature": "Protection contre les basses températures de décharge des cellules de la batterie.",
  "bms_protection_over_humidity": "Protection contre la surchauffe de l'humidité.",
  "bms_protection_associated_charge": "Protection de charge associée.",
  "bms_protection_associated_discharge": "Protection contre les décharges associées.",

  /// effet de lumière
  "title_light_effect_preview": "Aperçu de l'effet de lumière",
  "title_complete_light_effect_info": "Veuillez compléter les informations sur l'effet lumineux",
  "prompt_input_light_effect_name": "Veuillez saisir un nom d'effet lumineux",
  'prompt_input_light_effect_name_tips': 'Veuillez saisir 2 à 20 caractères',
  "prompt_invalid_light_effect_info": "Informations sur l'effet de lumière non valides",
  "text_light_effect_frame_interval": "Intervalle de trame",
  "title_light_effect_my_colors": "Mes couleurs",
  "text_light_effect_frame_keyframe": "Image clé",
  "text_light_effect_frame_total": "Nombre total d'images",
  "text_light_effect_frame_number": "%s Frame",
  "text_light_effect_frame": "%s Frame",
  "text_light_effect_frame_mode_normal": "Équilibre",
  "text_light_effect_frame_mode_fast": "Plus rapide",
  "text_light_effect_frame_mode_slow": "Plus lent",
  "title_light_effect_edit": "Modifier l'effet de lumière",
  "prompt_light_effect_edit_back_tips": "Quitter n'enregistrera pas les effets d'éclairage modifiés",
  "prompt_light_effect_edit_gradient_mode_1": "Relâchez pour définir comme image clé ou continuez à faire glisser pour annuler",
  "prompt_light_effect_edit_gradient_mode_2": "Actuellement en mode dégradé intra-image, veuillez continuer à sélectionner le point final du dégradé, ou %s",
  "prompt_light_effect_edit_gradient_mode_3": "Actuellement en mode dégradé intra-image, vous sélectionnez le point final du dégradé, relâchezpour quitter ce mode",
  'prompt_light_effect_edit_gradient_mode_4':
      'Actuellement en mode dégradé intra-image, vous sélectionnez le point final du dégradé, vous pouvez également faire glisser ici pour quitter le mode',
  "text_light_effect_exit_edit_gradient_mode": "quitter ce mode",
  "prompt_light_effect_edit_already_first_step": "C'est déjà la première étape !",
  "prompt_light_effect_edit_already_last_step": "C'est déjà la dernière étape !",
  "prompt_light_effect_drag_to_delete": "Faites glisser ici pour supprimer",
  "prompt_light_effect_release_to_delete": "Libérer pour supprimer",
  "title_vehicle_light_effect_exists": "Effet lumineux dans le véhicule",
  "text_light_effect_default_package": "Effet de lumière par défaut",
  "text_light_effect_unknown_package": "Effet lumineux inconnu",
  "prompt_enable_light_effect_failed": "Échec de l'activation de l'effet de lumière",
  "prompt_confirm_to_delete_light_effect": "Confirmez-vous la suppression ?",
  "prompt_confirm_to_delete_diy_light_effect": "L'effet de lumière DIY n'a pas pu être restauré une fois supprimé, confirmez-vous la suppression de '%s' ?",

  /// pack de sons
  "title_vehicle_sound_pack": "Pack de sons",
  "title_vehicle_sound_pack_exists": "Pack de sons dans le véhicule",
  "text_default_sound_pack": "Pack de sons par défaut",
  "text_unknown_sound_pack": "Pack de sons inconnu",
  "prompt_input_sound_pack_name": "Veuillez saisir un nom de pack de sons",
  "prompt_select_sound_pack_cover": "Veuillez choisir une couverture",
  "title_diy_single_sound_pack_item": "Son unique bricolage",
  "title_diy_sound_pack": "Pack de sons bricolage",
  "prompt_confirm_to_use_default_sound_pack": "Confirmez-vous la restauration du pack de sons par défaut ?",
  "prompt_select_from_local_file": "Sélectionner un fichier local",
  "prompt_vehicle_transferring_file": "Veuillez garder le véhicule à l'arrêt et ne pas utiliser le véhicule pendant le transfert de fichiers.",
  "prompt_enable_sound_pack_success": "Réussi",
  "prompt_enable_sound_pack_failed": "Échec de l'activation du pack de sons.",
  "prompt_vehicle_storage_capacity_not_enough": "La capacité de stockage du véhicule n'est pas suffisante.",
  "prompt_sound_pack_composing": "Composer...",
  "prompt_sound_pack_item_file_is_too_large": "Le fichier son est trop volumineux",
  "title_custom_sound_pack": "Pack de sons bricolage",
  "title_complete_sound_pack_info": "Informations complètes sur le pack de sons",
  "btn_compose": "Composer",
  "title_sound_pack_compose": "Composer un pack de sons",
  "prompt_sound_pack_compose_succeed": "Composer avec succès",
  "prompt_sound_pack_compose_failed": "Échec de la composition du pack de sons",
  "title_sound_pack_audition": "Auditer",
  "title_select_sound_pack_item": "Sélectionner le son",
  "prompt_confirm_to_delete_sound_pack": "Confirmez-vous la suppression ?",
  "prompt_confirm_to_delete_sound_pack_in_vehicle": "Le pack de sons dans le véhicule n'a pas pu être restauré une fois supprimé, confirmez-vous la suppression de '%s' ?",
  "prompt_confirm_to_delete_diy_sound_pack": "Le pack de sons DIY n'a pas pu être restauré une fois supprimé, confirmez-vous la suppression de '%s' ?",
  "text_sound_pack_file_local": "Local",
  "text_sound_pack_file_record": "Enregistrer",
  "text_sound_pack_file_library": "Bibliothèque de sons",
  "text_sound_pack_item_duration": "Durée : ",
  "text_sound_pack_item_size": "Taille : ",
  "prompt_sound_pack_compose_item_cannt_be_empty": "Tous les éléments ne peuvent pas être vides",
  "title_sound_pack_diy_create_from_template": "Créer à partir d'un modèle",
  "title_sound_pack_diy_create_directly": "Créer directement",
  "title_sound_pack_diy_select_template": "Sélectionnez un modèle",
  "title_sound_pack_audition_on_phone": "Audition sur téléphone",
  "title_sound_pack_audition_on_vehicle": "Audition sur véhicule",

  ///
  /// Exploiter
  ///
  "btn_authorized_vehicles": "Mes véhicules",
  "btn_vehicle_authorization": "Autorisation du propriétaire",
  "btn_customer_service": "Service client",
  "title_find_my_vehicle": "Trouver mon véhicule",
  "title_unit_metric_imperial": "Unités métriques/impériales",
  "text_unit_metric": "Métrique",
  "text_unit_imperial": "Impérial",
  "title_language": "Langue",
  "text_follow_system": "Suivre le système",
  "title_select_language": "Sélectionner la langue",
  "title_account_security": "Compte et sécurité",
  "title_clear_cache": "Effacer le cache",
  "prompt_clear_cache_tips": "Confirmez-vous de vider le cache ?",
  "title_app_about": "À propos",
  "text_app_version": "%s",

  "title_message_center": "Centre de messagerie",
  "title_user_info": "Informations personnelles",
  "btn_take_a_photo": "Prendre un téléphone",
  "btn_select_from_album": "Sélectionner dans l'album",

  "title_scan_qrcode": "Scanner le code QR",

  /// À propos
  "user_agreement": "Contrat d'utilisation",
  "privacy_policy": "Politique de confidentialité",
  "inmotion_company": "INMOTION",

  /// Informations personnelles
  "title_avatar": "Avatar",
  "title_nickname": "Pseudo",
  'title_username': "Nom d'utilisateur",
  "title_signature": "Signature",
  "title_modify_nickname": "Modifier le pseudo",
  'title_modify_username': "Modifier le nom d'utilisateur",
  "title_modify_signature": "Modifier la signature",
  "prompt_nickname_limit": "6-20 caractères",
  "prompt_signature_limit": "0-100 caractères",

  /// mon véhicule
  "title_my_vehicles": "Mes véhicules",
  "title_delete_authorized_vehicle": "Supprimer l'autorisation du propriétaire",
  "prompt_delete_authorized_vehicle_tips": "DeLa location du véhicule supprimera l'autorisation du propriétaire du véhicule. Confirmez-vous de le supprimer ?",
  "title_delete_vice_owner": "Supprimer le vice-propriétaire",
  "prompt_delete_vice_owner_tips": "Confirmez-vous la suppression du vice-propriétaire ?",
  "title_vehicle_details": "Informations sur le véhicule",
  "title_vehicle_info": "Informations sur le véhicule",
  "prompt_vehicle_info_updated_at": "Les informations ci-dessous ont été mises à jour à : %s",
  "title_vehicle_model": "Modèle",
  "title_activated_date": "Activé à",
  "title_total_mileage": "Kilométrage total",
  "title_riding_record": "Record d'équitation",
  "title_bluetooth_name": "Nom BT",
  "text_vehicle_remaining_mileage": "Kilométrage restant : %s",
  "title_vehicle_owner_info": "Informations sur le propriétaire",
  "title_vehicle_main_owner": "Propriétaire principal",
  "btn_go_to_authorize_as_owner": "Aller à Autoriser",
  "prompt_not_owner_and_go_to_authorize_as_owner": "Seul le propriétaire du véhicule actuel peut le faire, voulez-vous autoriser en tant que propriétaire maintenant ?",
  "text_vehicle_info_owner_me_suffix": "(Moi)",
  "title_vehicle_vice_owner": "Vice-propriétaire",
  "title_vehicle_no_owner": "Aucun",
  "title_transfer_vehicle_main_owner": "Transférer le propriétaire principal",
  'prompt_transfer_vehicle_main_owner_tips':
      "Après le transfert, l'utilisateur \"%s\" deviendra le propriétaire principal du véhicule actuel et vous deviendrez le vice-propriétaire.\n Confirmez-vous le transfert ?",
  "title_invite_as_vehicle_vice_owner": "Inviter",
  "prompt_invite_as_vehicle_vice_owner_tips": "Veuillez utiliser l'application INMOTION pour scanner le code QR pour autoriser en tant que vice-propriétaire.",
  "title_vehicle_authorization": "Autorisation du véhicule",
  "prompt_authorize_current_connected_vehicle_tips": "Le véhicule %s est actuellement connecté, voulez-vous être authentifié en tant que propriétaire immédiatement ?",
  "prompt_input_sn": "Veuillez saisir le SN",
  "title_vehicle_authorization_requests": "Demande d'historique",
  "title_sent_vehicle_authorization_requests": "Envoyé",
  "title_received_vehicle_authorization_requests": "Reçu",
  "prompt_vehicle_authorization_apply_to": "Appliqué à %s",
  "prompt_vehicle_authorization_apply_from": "%s m'a appliqué",
  "prompt_vehicle_authorization_waiting": "En attente",
  "text_status_pending": "En attente",
  "text_status_approved": "Approuvé",
  "text_status_rejected": "Refusé",
  "text_status_expired": "Expiré",

  /// autorisation de véhicule
  "prompt_vehicle_authorization_apply_success": "La candidature a été envoyée avec succès.",
  "prompt_vehicle_authorization_success": "Autorisé avec succès en tant que propriétaire principal",
  "prompt_vehicle_authorized_as_vice_owner_tips": "Ce véhicule a déjà un propriétaire principal, voulez-vous l'autoriser en tant que vice-propriétaire ?",
  "prompt_vehicle_authorized_as_vice_owner_success": "Autorisé avec succès en tant que vice-propriétaire",
  "prompt_vehicle_authorization_failed": "L'autorisation a échoué",

  /// service Clients
  "title_message_board": "Message Board",
  "prompt_leave_message_tips": "Veuillez laisser un message, nous vous contacterons bientôt.",
  "btn_leave_a_message": "Laisser un message",
  "prompt_please_leave_a_message": "Veuillez laisser un message",
  "btn_chat_menu_picture": "Images",
  "btn_chat_menu_video": "Vidéo",
  "prompt_leave_message_success": "Réussi",
  "prompt_leave_message_failed": "Laisser un message a échoué",
  "prompt_content_couldnt_be_empty": "Le contenu ne peut pas être vide.",
  "prompt_customer_service_waiting_for_access": "Accès en attente",
  "prompt_customer_service_queue_number": "Il y a %s personnes devant vous dans la file",
  "prompt_customer_service_offline": "Le service client est hors ligne",
  "prompt_customer_service_session_ended": "La session est terminée",
  "btn_customer_service_evaluate": "Évaluer",
  "prompt_input_question_to_consult": "Veuillez saisir la question que vous souhaitez consulter",

  "title_official_recommends": "Recommander",

  /// record d'équitation
  "text_riding_record_summary": "Au total, %sheures, %sKg d'émissions de carbone économisées.",

  ///
  /// les erreurs
  ///
  "prompt_request_failed": "La demande a échoué",
  "prompt_request_failed_timeout": "Délai d'expiration de la demande",
  "prompt_request_failed_network": "Erreur réseau",

  "prompt_unauthenticated_request": "La session de connexion a expiré, veuillez vous reconnecter !",
  "prompt_unknown_error": "Erreur inconnue",
  "prompt_operate_too_frequently": "Opération trop fréquente, veuillez réessayer plus tard.",
  "prompt_file_download_failed": "Le téléchargement du fichier a échoué",
  "prompt_unknown_product_model": "Modèle de produit inconnu",
};
