const  Map < String , String > ru_RU = {
    ///
    /// Common
    ///
    "prompt_welcome_to_inmotion" :  "Привет, \n Добро пожаловать в INMOTION" ,
    "btn_more" :  "Еще" ,
    "btn_view_more" :  "Посмотреть больше" ,
    "btn_cancel" :  "Отмена" ,
    "btn_exit" :  "Выход" ,
    "btn_confirm" :  "Подтвердить" ,
    "btn_complete" :  "Готово" ,
    "btn_submit" :  "Отправить" ,
    "btn_i_see" :  "Я вижу" ,
    "btn_skip" :  "Пропустить" ,
    "btn_next_step" :  "Далее" ,
    "btn_save" :  "Сохранить" ,
    "btn_save_image" :  "Сохранить изображение" ,
    "btn_edit" :  "Редактировать" ,
    "btn_preview" :  "Предварительный просмотр" ,
    "btn_rename" :  "Переименовать" ,
    "btn_delete" :  "Удалить" ,
    "btn_publish" :  "Опубликовать" ,
    "tab_vehicle" :  "Колесо" ,
    "tab_moment" :  "Момент" ,
    "tab_discover" :  "Открыть" ,
    "tab_mine" :  "Профиль" ,
    "prompt_page_error" :  "Произошла ошибка." ,
    "btn_share" :  "Поделиться" ,
    "btn_report" :  "Отчет" ,
    "btn_enable" :  "Включить" ,
    "btn_enabled" :  "Включено" ,
    "btn_retry" :  "Повторить" ,
    "prompt_title_warning" :  "Предупреждение" ,
    "prompt_title_tips" :  "Уведомление" ,
    "prompt_title_warm_tips" :  "Советы" ,
    "prompt_confirm_to_cancel" :  "Вы подтверждаете отмену?" ,
    "prompt_failed" :  "Ошибка" ,
    "btn_agree" :  "Принять" ,
    'btn_reject' :  'Отклонить' ,
    "btn_need_help" :  "Помощь" ,
    "btn_common_problem" :  "Часто задаваемые вопросы" ,
    "page_message_center" :  "Центр сообщений" ,
    "title_sys_message" :  "Системное сообщение" ,
    "title_social_message" :  "Социальное сообщение" ,
    "btn_save_and_share" :  "Сохранить и поделиться" ,
    "prompt_saved" :  "Сохранено" ,
    "prompt_save_failed" :  "Не удалось сохранить" ,
    "prompt_updated" :  "Обновлено" ,
    "prompt_update_failed" :  "Обновление не выполнено" ,
    "prompt_data_empty" :  "Данные отсутствуют". ,
    "prompt_loading" :  "Загрузка..." ,
    "prompt_load_failed" :  "Загрузка не удалась" ,
    "prompt_copied" :  "Скопировано" ,
    "prompt_action_failed" :  "Ошибка" ,
    "prompt_press_again_to_exit" :  "Нажмите еще раз, чтобы выйти." ,

    "datetime_just_now" :  "Только что" ,
    "datetime_x_minutes_ago" :  "%smin назад" ,
    "datetime_yesterday_x" :  "Вчера %s" ,

     "unknown": "неизвестно" ,

    ///
    ///  Account
    ///
    "prompt_auto_register_if_account_not_exists" :  "Незарегистрированный номер телефона будет использоваться для автоматического создания учетной записи после проверки" ,
    "btn_login" :  "Войти" ,
    "btn_register" :  "Зарегистрироваться" ,
    "title_register" :  "Регистрация" ,
    "title_cn_phone_quick_login" :  "Быстрая проверка" ,
    "prompt_input_phone" :  "Номер телефона" ,
    "prompt_input_email" :  "Адрес электронной почты" ,
    "prompt_input_email_or_username" :  "Адрес электронной почты/имя учетной записи" ,
    "prompt_input_verification_code" :  "Код подтверждения" ,
    "prompt_input_password" :  "Пароль" ,
    "prompt_input_a_valid_phone" :  "Пожалуйста, введите номер телефона!" ,
    "prompt_input_a_valid_email" :  "Пожалуйста, введите адрес электронной почты!" ,
    "prompt_input_a_valid_email_or_username" :  "Пожалуйста, введите адрес эл.почты или имя учетной записи!" ,
    "prompt_input_a_valid_password" :  "Введите пароль" ,
    "btn_forgot_password" :  "Забыли пароль?" ,
    "btn_reset_password" :  "Сбросить пароль" ,
    "btn_login_via_password" :  "Войти по учетной записи и паролю" ,
    "btn_login_via_verification_code" :  "Войти через проверочный код" ,
    "btn_request_verification_code" :  "Получить код" ,
    "btn_request_sms_verification_code" :  "Получить код" ,
    "prompt_verification_code_has_sent_to" :  "Код подтверждения отправлен %s" ,
    "btn_resend" :  "Отправить повторно" ,
    "title_user_agreement" :  "Пользовательское соглашение" ,
    "title_privacy_policy" :  "Политика конфиденциальности" ,
    "prompt_register_agreement_tips" :  "Регистрация или вход означает, что вы согласились с %s и %s" ,
    "title_select_country_or_region" :  "Выберите страну/регион" ,
    "btn_modify_phone" :  "Изменить номер телефона" ,
    "btn_modify_email" :  "Изменить адрес электронной почты" ,
    "btn_bind_phone" :  "Привязать номер телефона" ,
    "btn_modify_password" :  "Изменить пароль" ,
    "номер_телефона" :  "Номер телефона" ,
    "электронная почта" :  "Электронная почта" ,
    "btn_register_via" :  "Зарегистрироваться через %s" ,
    "btn_bind_via" :  "Привязать через %s" ,
    "btn_reset_password_via" :  "Сброс через %s" ,
    "btn_bind_account" :  "Привязать учетную запись" ,
    "prompt_password_limit_tips" :  "Пожалуйста, введите 6-20 цифр и английских символов, а не чистые числа" ,
    "prompt_empty_password" :  "Пустой пароль" ,
    "title_bind_social_account" :  "Привязка социальной учетной записи" ,
    "prompt_social_account_auth_failed" :  "Авторизация не удалась" ,
    "prompt_bind_social_account_tips" :  "*Вы можете войти в INMOTION с привязанной социальной учетной записью." ,
    'state_bound' :  'Связанный' ,
    «state_not_bound» :  «Не привязано» ,
    'prompt_unbind_social_account_tips' :  'После отмены привязки вы не сможете использовать %s для входа в INMOTION, вы уверены, что хотите отменить?' ,
    'btn_logout' :  'Выход' ,
    'prompt_logout_tips' :  'Вы подтверждаете выход из системы?' ,
    "title_operation_verification" :  "Проверка безопасности" ,
    "prompt_operation_verification_tips" :  "Текущая операция требует проверки, проверьте ее одним из следующих способов" ,
    "title_verify_operation_via" :  "Подтвердить через %s" ,
    "prompt_operation_verification_expired" :  "Сначала выполните проверку безопасности!" ,
    "text_none" :  "无" ,

    /// Chinese phone quick verify error
    "prompt_cn_phone_auth_no_sim_card" :  "SIM-карта не обнаружена!" ,
    "prompt_cn_phone_auth_unknown_operator" :  "Неизвестный оператор!" ,
    "prompt_cn_phone_auth_network_not_enable" :  "Мобильные данные не включены!" ,
    "prompt_cn_phone_auth_unknown" :  "Неизвестная ошибка!" ,

    ///
    /// Vehicle
    ///
    "btn_search_vehicle" :  "Поиск колеса" ,
    "prompt_had_connected_before" :  "Подключено до" ,
    "title_vehicle_activation" :  "Активация" ,
    "prompt_wait_for_activation_tips_finished" :  "Пожалуйста, прочтите/посмотрите напоминания о безопасности." ,
    "prompt_had_read_activation_tips" :  "Я внимательно прочитал приведенные выше напоминания о безопасности и знаю о возможных рисках" ,
    "btn_activate" :  "Активировать сейчас" ,
    "prompt_activated" :  "Активировано успешно!" ,
    "prompt_activate_failed" :  "Не удалось активировать" ,
    "prompt_activate_canceled" :  "Отменено" ,
    "prompt_authorize_as_owner_after_activation" :  "Аутентификация колеса требуется для таких операций, как блокировка. Вы хотите подтвердить что вы владельц?" ,
    "prompt_authorize_as_owner_later_after_activation" :  "Вы также можете сделать это позже в разделе Профиль - авторизация владельца" ,
    "prompt_set_vehicle_password_failed" :  "Не удалось установить пароль" ,
    "prompt_set_vehicle_password_later_after_activation" :  "Вы также можете сделать это позже в разделе - Настройки колеса - Пароль"" ,
    "prompt_bluetooth_disabled" :  "Bluetooth на телефоне не включен" ,
    "prompt_location_disabled" :  "GPS не включен" ,
    "prompt_no_bluetooth_permission" :  "Нет разрешения Bluetooth" ,
    "prompt_no_location_permission" :  "Нет разрешения на GPS" ,
    "prompt_no_scan_bluetooth_permission" :  "Нет разрешения на сканирование Bluetooth" ,
    "prompt_no_connect_bluetooth_permission" :  "Нет разрешения на подключение Bluetooth" ,
    "prompt_no_device_found" :  "Устройства не найдены." ,
    "prompt_tap_to_connect" :  "Нажмите на устройство ниже, чтобы подключиться" ,
    "prompt_scanning" :  "Поиск..." ,
    "prompt_connecting" :  "Подключение..." ,
    "prompt_connection_canceled" :  "Соединение отменено" ,
    "prompt_connected" :  "Подключено" ,
    "prompt_connection_timeout" :  "Время ожидания соединения" ,
    "prompt_connection_failed" :  "Не удалось подключиться" ,
    "prompt_unsupported_models" :  "Неподдерживаемая модель" ,
    "btn_enable_bluetooth" :  "Открыть Bluetooth" ,
    "btn_enable_location" :  "Включить GPS" ,
    "btn_request_bluetooth_permission" :  "Запросить разрешение Bluetooth" ,
    "btn_request_location_permission" :  "Запрос разрешения на GPS" ,
    "btn_scan_again" :  "Повторить поиск" ,
    "btn_cancel_connection" :  "Отмена" ,
    "prompt_why_need_to_enable_location" :  "Зачем мне включать службу определения местоположения?" ,
    "prompt_why_need_location_permission" :  "Зачем INMOTION требуется разрешение на определение местоположения?" ,
    "prompt_why_do_i_couldnt_find_vehicles" :  "Почему я не могу найти устройство?" ,
    "btn_view_solutions" :  "Варианты решений" ,
    "prompt_connect_failed_server_ip_service_error" :  "Временная ошибка сервера, мы скоро это исправим, повторите попытку позже." ,
    "prompt_connect_failed_unknown_model" :  "Вы не можете использовать приложение INMOTION, потому что модель текущего устройства недействительна. \n Пожалуйста, свяжитесь с нами для получения дополнительной информации." ,
    "prompt_connect_failed_unknown_sn" :  "Вы не можете использовать приложение INMOTION, потому что серийный номер текущего автомобиля недействителен. \n Пожалуйста, свяжитесь с нами для получения дополнительной информации." ,
    "prompt_connect_failed_vehicle_locked" :  "Устройство находится в РЕЖИМЕ ПОТЕРИ. Пожалуйста, свяжитесь с нами для получения дополнительной информации." ,
    "prompt_connect_failed_vehicle_lost_mode" :  "Устройство находится в РЕЖИМЕ ПОТЕРИ. Вы можете отключить его в разделе "Найти мое устройство", если вы являетесь его владельцем." ,

    "text_vehicle_ride_time" :  "Время в пути" ,
    "text_vehicle_ride_mileage" :  "Пробег в пути" ,
    "text_vehicle_max_speed" :  "Макс.скорость" ,
    "text_vehicle_ave_speed" :  "Средняя скорость" ,
    "text_vehicle_total_mileage" :  "Общий пробег" ,
    "text_vehicle_dynamic_speed_limit" :  "Ограничение скорости" ,
    "text_vehicle_power" :  "Мощность" ,
    "text_vehicle_max_power" :  "Макс.мощность" ,
    "text_vehicle_mos_temp" :  "Температура MOS" ,
    "text_vehicle_consumption" :  "Расход" ,
    "text_vehicle_last_ride_mileage" :  "Последний пробег" ,
    "text_vehicle_last_ride_time" :  "Время последней поездки" ,
    "text_vehicle_last_max_speed" :  "Последняя макс.скорость" ,
    "text_vehicle_speed" :  "Скорость" ,
    "text_vehicle_battery_discharge_current" :  "Ток разряда аккумулятора" ,
    "text_vehicle_battery_voltage" :  "Напряжение" ,
    "text_vehicle_battery_output_power" :  "Мощность разряда аккумулятора" ,
    "text_vehicle_motor_output_power" :  "Выходная мощность двигателя" ,
    "text_vehicle__motor_torque" :  "Крутящий момент" ,
    "text_vehicle_remaining_battery" :  "Остаток батареи" ,
    "text_vehicle_output_rate" :  "Выходное напряжение (%)" ,
    "text_vehicle_dynamic_current_limit" :  "Ограничение перегрузки по току" ,

    "text_vehicle_motor_temp" :  "Температура двигателя" ,
    "text_vehicle_battery_temp" :  "Температура батареи" ,
    "text_vehicle_motherboard_high_temp" :  "Температура платы драйвера" ,
    "text_vehicle_driver_board_cpu_temp" :  "Температура процессора" ,
    "text_vehicle_imu_temp" :  "Температура IMU" ,

    "text_gps_speed" :  "Скорость по GPS" ,

    "prompt_status_connecting" :  "Подключение" ,
    "prompt_status_connected" :  "Подключено" ,
    "prompt_status_disconnected" :  "Не подключено" ,
    "prompt_vehicle_disconnected" :  "Устройство отключено" ,
    "prompt_no_connected_vehicles_yet" :  "Подключенных пока нет." ,
    "prompt_current_connected_vehicle" :  "Подключено" ,
    "prompt_last_connected_at" :  "Последнее подключение: %s" ,
    "title_switch_vehicle" :  "Сменить устройство" ,
    "btn_disconnect_and_scan" :  "Отключение и поиск" ,
    "btn_scan" :  "Поиск" ,
    "btn_detailed_data" :  "Подробные данные" ,
    "title_about_vehicle" :  "Об устройстве" ,
    "title_battery_info" :  "Информация о батарее" ,
    "title_customer_service" :  "Онлайн-сервис" ,
    "title_faq" :  "Часто задаваемые вопросы" ,

    "title_gps_riding_tracks" :  "Мои поездки" ,
    "title_vehicle_riding_record" :  "Рекорд по езде" ,

    "text_vehicle_riding_record_mileage" :  "Пробег: %s" ,
    "text_vehicle_riding_record_max_speed" :  "Макс. скорость: %s" ,

    "title_vehicle_riding_report" :  "Отчет о поездке" ,
    "prompt_invalid_riding_track" :  "Недопустимая дорожка для езды". ,

    "title_basic_battery_info" :  "Основная информация" ,
    "text_battery_voltage" :  "Напряжение" ,
    "text_battery_charge_voltage" :  "Напряжение заряда" ,
    "title_detailed_battery_info" :  "Информация о батарее" ,
    "text_battery_detected_status" :  "Обнаружения батареи" ,
    "text_battery_detected" :  "Подключено" ,
    "text_battery_not_detected" :  "Не подключено" ,
    "text_battery_enable_status" :  "Статус работы батареи" ,
    "text_battery_enabled" :  "Включено" ,
    "text_battery_disabled" :  "Отключено" ,
    "text_battery_error_status" :  "Состояние ошибки батареи" ,
    "text_battery_ok" :  "Норм" ,
    "text_battery_error" :  "Ошибка" ,
    "text_battery_signal_logic_error" :  "Ошибка логического сигнала" ,

    "title_battery_cells_voltage" :  "Напряжение элементов батареи" ,

    "title_bms_basic_info" :  "Основная информация" ,
    "text_bms_battery_sn" :  "Серийный номер батареи" ,
    "text_bms_manufacture_date" :  "Дата изготовления" ,
    "text_bms_full_charge_cycles" :  "Полные циклы зарядки" ,
    "text_bms_software_version" :  "Версия программного обеспечения BMS" ,
    "text_bms_hardware_Version" :  "Версия оборудования BMS" ,
    "title_bms_data_and_status" :  "Данные и статус" ,
    "text_bms_voltage" :  "Напряжение" ,
    "text_bms_charge_state" :  "Состояние зарядки" ,
    "text_bms_charge_current" :  "Ток заряда" ,
    "text_bms_discharge_current" :  "Ток разряда" ,
    "text_bms_charge_mos_state" :  "Зарядить MOS" ,
    "text_bms_discharge_mos_state" :  "Разрядить MOS" ,
    "text_bms_error_status" :  "Статус ошибки" ,
    "text_bms_warning_status" :  "Статус предупреждения" ,
    "text_bms_protection_status" :  "Статус защиты" ,
    "text_bms_cell_balancing_status" :  "Балансировка ячеек" ,
    "text_bms_max_cell_voltage" :  "Макс.напряжение ячейки" ,
    "text_bms_min_cell_voltage" :  "Мин. напряжение ячейки" ,
    "text_bms_charge_mos_temp" :  "Температура заряда MOS" ,
    "text_bms_discharge_mos_temp" :  "Разрядить температуру MOS" ,
    "text_bms_cells_temp" :  "Температура ячеек" ,
    "text_bms_cells_voltage" :  "Напряжение ячеек" ,

    /// vehicle settings
    "title_vehicle_settings" :  "Настройка устройства" ,
    "prompt_operation_succeed" :  "Успешно" ,
    "prompt_operation_failed" :  "Ошибка" ,
    "title_vehicle_password" :  "Пароль" ,
    "text_vehicle_password_disabled" :  "Отключено" ,
    "text_vehicle_password_gesture" :  "Жест" ,
    "text_vehicle_password_slide" :  "Слайд" ,
    "text_vehicle_password_number" :  "Номер" ,
    "title_modify_vehicle_password" :  "Изменить пароль" ,
    "title_set_vehicle_password" :  "Установить пароль" ,
    "prompt_vehicle_number_password_tips" :  "Пожалуйста, введите пароль из 4 или 6 цифр" ,
    "title_vehicle_userinfo" :  "Информация о пользователе устройства" ,
    "title_vehicle_userinfo_avatar" :  "Аватар"устройства" ,
    "prompt_vehicle_userinfo_name_tips" :  "Введите от 1 до 16 букв, цифр и английских символов" ,
    "title_choose_setting_item" :  "Выберите элементы настройки" ,
    "vehicle_setting_item_limit_speed_25" :  "Зафиксировать скорость на 25 км/ч" ,
    "vehicle_setting_item_limit_speed" :  "Ограничение скорости" ,
    "vehicle_setting_item_drive_mode" :  "Режим вождения" ,
    "vehicle_setting_item_drive_mode_normal" :  "Нормальный" ,
    "vehicle_setting_item_drive_mode_normal_tips" :  "Мягкое и плавное ускорение и торможение" ,
    "vehicle_setting_item_drive_mode_off_road" :  "Спортивный" ,
    "vehicle_setting_item_drive_mode_off_road_tips" :  "Высокий уровень жесткости педалей для резкого ускорения, подъема в гору и езды по бездорожью" ,
    "vehicle_setting_item_pedestrian_mode_limit_speed" :  "Макс. скорость (пешеходный режим)" ,
    "vehicle_setting_item_pedal_sensitivity" :  "Жесткость педали" ,
    "vehicle_setting_item_spilt_mode" :  "Режим помощи" ,
    "vehicle_setting_item_spilt_mode_speeding" :  "Ускорение" ,
    "vehicle_setting_item_spilt_mode_breaking" :  "Торможение" ,
    "vehicle_setting_item_power_assist" :  "Помощь при усилии" ,
    "vehicle_setting_item_acc_assist" :  "Помощь при ускорении" ,
    "vehicle_setting_item_brake_assist" :  "Помощь при торможении" ,
    "vehicle_setting_item_cruise" :  "Круиз" ,
    "vehicle_setting_item_ride_assist" :  "Помощник при вождении" ,
    "vehicle_setting_item_zero_start" :  "Нулевой старт" ,
    "vehicle_setting_item_assist_balance" :  "Ассистент балансировки" ,
    "vehicle_setting_item_load_detect" :  "Обнаружение нагрузки" ,
    "vehicle_setting_item_noload_detect" :  "Обнаружение отсутствия нагрузки" ,
    "vehicle_setting_item_up_hill_assist" :  "Помощь на подъеме" ,
    "vehicle_setting_item_down_hill_assist" :  "Помощь на спуске" ,
    "vehicle_setting_item_overspeed_alarm" :  "Сигнализация по скорости" ,
    "vehicle_setting_item_lock" :  "Замок" ,
    "vehicle_setting_item_password" :  "Пароль" ,
    "vehicle_setting_item_diagnosis" :  "Диагностика" ,
    "vehicle_setting_item_headlight" :  "Свет" ,
    "vehicle_setting_item_headlight_brightness" :  "Яркость света" ,
    "vehicle_setting_item_drl" :  "Ходовые огни" ,
    "vehicle_setting_item_low_beam_headlight" :  "Ближний свет фар" ,
    "vehicle_setting_item_low_beam_headlight_brightness" :  "Яркость света ближнего света" ,
    "vehicle_setting_item_high_beam_headlight" :  "Свет дальнего света" ,
    "vehicle_setting_item_high_beam_headlight_brightness" :  "Яркость дальнего света" ,
    "vehicle_setting_item_auto_headlight" :  "Автом. свет" ,
    "vehicle_setting_item_auto_headlight_brightness_threshold" :  "Порог автоматического включения" ,
    "vehicle_setting_item_auto_low_high_beam" :  "Автоматический свет ближнего и дальнего света" ,
    "vehicle_setting_item_auto_low_high_beam_switch_speed_threshold" :  "Порог скорости автоматического переключения света ближнего на дальний" ,
    "vehicle_setting_item_light_effect" :  "Световой эффект" ,
    "vehicle_setting_item_light_effect_mode" :  "Режим светового эффекта" ,
    "vehicle_setting_item_light_effect_front" :  "Режим эффекта переднего света" ,
    "vehicle_setting_item_light_effect_rear" :  "Режим эффекта заднего света" ,
    "vehicle_setting_item_light_diy" :  "сделай сам" ,
    "vehicle_setting_item_auto_turn_signal" :  "Поворотники" ,
    "vehicle_setting_item_audio_state" :  "Аудио" ,
    "vehicle_setting_item_volume" :  "Громкость" ,
    "vehicle_setting_item_audio_package" :  "Аудиопакет" ,
    "vehicle_setting_item_standby_time" :  "В режиме ожидания" ,
    "vehicle_setting_item_spin_kill_btn" :  "Вращение" ,
    "vehicle_setting_item_sound_wave" :  "Звуковая волна" ,
    "vehicle_setting_item_sound_wave_sensitivity" :  "Чувствительность звуковой волны" ,
    "vehicle_setting_item_estimated_remainder_range" :  "Запас хода" ,
    "vehicle_setting_item_user_info" :  "Информация об устройстве" ,
    "vehicle_setting_item_fan_quiet_mode" :  "Тихий режим вентилятора" ,
    "vehicle_setting_item_forced_fan" :  "Принудительное воздушное охлаждение" ,
    "vehicle_setting_item_transport_mode" :  "Транспортный режим" ,
    "vehicle_setting_item_low_battery_safe_mode" :  "Безопасный режим при низком заряде батареи" ,
    "vehicle_setting_item_auto_screen_off" :  "Автоотключение экрана" ,
    "vehicle_setting_item_speed_unit" :  "Метрические/британские единицы" ,
    "vehicle_setting_item_sn" :  "SN" ,
    "vehicle_setting_item_activate_date" :  "Активировано в" ,
    "vehicle_setting_item_total_mileage" :  "Общий пробег" ,
    "vehicle_setting_item_hmic_board_version" :  "Плата контроллера" ,
    "vehicle_setting_item_bt_board_version" :  "BT плата" ,
    "vehicle_setting_item_driver_board_version" :  "Панель драйвера" ,
    "vehicle_setting_item_driver_board_temp" :  "Температура платы драйвера" ,
    "vehicle_setting_item_riding_mode" :  "Режим езды" ,
    "vehicle_setting_riding_mode_eco" :  "ECO" ,
    "vehicle_setting_riding_mode_eco_tips" :  "Рекомендация новичку, плавное ускорение." ,
    "vehicle_setting_riding_mode_normal" :  "D" ,
    "vehicle_setting_riding_mode_sport" :  "S" ,
    "vehicle_setting_riding_mode_sport_tips" :  "Рекомендация профессиональным гонщикам, более отзывчивая мощность" ,
    "vehicle_setting_riding_pedestrian_mode" :  "Плавный режим" ,
    "vehicle_setting_riding_pedestrian_mode_tips" :  "Легче толкать". ,
    "vehicle_setting_item_riding_mode_euc_normal" :  "Нормальный" ,
    "vehicle_setting_item_riding_mode_euc_normal_tips" :  "Более безопасный, подходит для большинства пользователей." ,
    "vehicle_setting_item_riding_mode_euc_fancier" :  "Скоростной" ,
    "vehicle_setting_item_riding_mode_euc_fancier_tips" :  "Более высокая выходная мощность и более высокая максимальная скорость". ,
    "prompt_cannt_set_sport_mode_when_limit_speed_25kmph_enabled" :  "Вы не можете переключиться в режим 'S', когда включено ограничение скорости на 25 км/ч." ,
    "prompt_cannt_enable_limit_speed_25kmph_when_sport_mode_enabled" :  "Вы не можете включить «Ограничение скорости на 25 км/ч» в режиме «S». ,
    "vehicle_setting_item_berm_angle_mode" :  "Режим угла" ,
    "prompt_unlock_factory_safe_speed_limit" :  "Для вашей безопасности ограничение максимальной скорости может быть увеличено до 90 км/ч только тогда, когда ваш общий пробег превышает 30 км. %s" ,
    «prompt_unlock_factory_safe_speed_limit_not_now» :
    «Для вашей безопасности ограничение максимальной скорости может быть увеличено до 90 км/ч только тогда, когда ваш общий пробег превысит 30 км. Вам все равно нужно продолжать движение в течение %s». ,
    "prompt_unlock_now" :  "Разблокировать сейчас>>" ,

    "warning_unlock_v13_factory_speed_limit" :
    Не ездите на V13 в местах, запрещенных местным законодательством.\n4. Пожалуйста, не позволяйте никому, кто не прочитал инструкцию внимательно или не знаком с мерами предосторожности при езде на V13, управлять вашим устройством.\n5. Перед каждой поездкой обязательно проверяйте, находятся ли продукты и аксессуары в хорошем состоянии, избегайте использования неоригинальных аккумуляторов и аксессуаров, а также не разбирайте, не взламывайте и не модифицируйте продукты и аксессуары без разрешения. Вы несете ответственность за любые потери, ущерб и риски, вызванные неправильной операцией.\n\nПожалуйста, внимательно прочитайте и решите принять или не принять это заявление. Вы не можете разблокировать ограничение максимальной скорости, пока не согласитесь с этим утверждением. Ваше \"Согласие\" будет считаться принятием данного отказа от ответственности. Если у вас есть какие-либо вопросы об этом отказе от ответственности, нажмите \"Отмена\"", Пожалуйста, не позволяйте никому, кто не прочитал инструкцию внимательно или не знаком с мерами предосторожности при езде на V13, управлять вашим устройством.\n5. Перед каждой поездкой обязательно проверяйте, находятся ли продукты и аксессуары в хорошем состоянии, избегайте использования неоригинальных аккумуляторов и аксессуаров, а также не разбирайте, не взламывайте и не модифицируйте продукты и аксессуары без разрешения. Вы несете ответственность за любые потери, ущерб и риски, вызванные неправильной операцией.\n\nПожалуйста, внимательно прочитайте и решите принять или не принять это заявление. Вы не можете разблокировать ограничение максимальной скорости, пока не согласитесь с этим утверждением. Ваше \"Согласие\" будет считаться принятием данного отказа от ответственности. Если у вас есть какие-либо вопросы об этом отказе от ответственности, нажмите \"Отмена\"", Пожалуйста, не позволяйте никому, кто не прочитал инструкцию внимательно или не знаком с мерами предосторожности при езде на V13, управлять вашим устройством.\n5. Перед каждой поездкой обязательно проверяйте, находятся ли продукты и аксессуары в хорошем состоянии, избегайте использования неоригинальных аккумуляторов и аксессуаров, а также не разбирайте, не взламывайте и не модифицируйте продукты и аксессуары без разрешения. Вы несете ответственность за любые потери, ущерб и риски, вызванные неправильной операцией.\n\nПожалуйста, внимательно прочитайте и решите принять или не принять это заявление. Вы не можете разблокировать ограничение максимальной скорости, пока не согласитесь с этим утверждением. Ваше \"Согласие\" будет считаться принятием данного отказа от ответственности. Если у вас есть какие-либо вопросы об этом отказе от ответственности, нажмите \"Отмена\"",
    "warning_enable_berm_angle_mode" :  "Когда этот режим включен, угол защиты от опрокидывания транспортного средства становится больше, что означает, что транспортное средство может раскачиваться вперед и назад и легко выходить из-под контроля из-за небольших изменений угла балансировки, когда оно расположено боком. Это может нанести вред вам или окружающей среде. Вы уже знаете обо всех возможных рисках, вы уверены, что хотите включить это?" ,
    "warning_disable_berm_angle_mode" :  "Для активации нажмите кнопку блокировки колеса после включения/выключения режима. " ,

    "title_vehicle_balance_angle" :  "Угол балансировки" ,
    "title_vehicle_dication" :  "Калибровка устройства" ,
    "title_vehicle_balance_angle_dication" :  "Калибровка" ,
    "prompt_vehicle_balance_angle_dication_desc" :  "Если транспортное средство все еще наклоняется назад или вперед на земле после того, как вы установили угол балансировки на ноль, вы можете попробовать эту калибровку, чтобы исправить. %s" ,
    "prompt_vehicle_balance_angle_dication" :  "Пожалуйста, нажмите и удерживайте кнопку балансировки, чтобы вертикальное направление устройства было перпендикулярно горизонтальной поверхности" ,
    "title_vehicle_turning_caulibation" :  "Калибровка наклона" ,
    "title_vehicle_turning_dication_desc" :  "Это может улучшить опыт наклона. %s" ,
    "text_view_dication_guide" :  "Просмотреть руководство>>" ,
    "title_motor_self_adjustment" :  "Саморегулировка двигателя" ,
    "prompt_motor_self_adjustment_desc" :  "Мотор будет автоматически работать в течение 1 минуты после запуска. Для вашей безопасности убедитесь, что EUC находится в опрокинутом состоянии, и не касайтесь колеса!" ,
    "prompt_clear_motor_self_adjustment_effect_desc" :  "Рекомендуется %s, если нет улучшения опыта вождения" ,
    "title_clear_motor_self_adjustment_effect" :  "Очистить самонастройки двигателя" ,
    "prompt_motor_self_adjustment_in_progress" :  "Выполняется регулировка..." ,
    "prompt_motor_self_adjustment_terminated" :  "Регулировка прекращена" ,
    "prompt_motor_self_adjustment_succeed" :  "Регулировка завершена" ,
    "prompt_motor_self_adjustment_finished" :  "Ррегулировка завершена" ,
    "prompt_motor_self_adjustment_timeout" :  "Тайм-аут настройки" ,
    "prompt_confirm_to_clear_motor_self_adjustment_effect" :  "Вы подтверждаете сброс настройки двигателя?" ,

    "prompt_motor_self_check_in_progress" :  "Выполняется проверка..." ,
    "prompt_motor_self_check_terminated" :  "Проверка прекращена" ,
    "prompt_motor_self_check_passed" :  "Проверка пройдена" ,
    "prompt_motor_self_check_not_passed" :  "Проверка НЕ ​​пройдена" ,
    "prompt_motor_self_check_timeout" :  "Тайм-аут проверки" ,
    "prompt_motor_self_check_failed" :  "Не удалось запустить проверку" ,

    "title_vehicle_acc_dication" :  "Калибровка дроссельной заслонки" ,
    "title_vehicle_brake_dication" :  "Калибровка тормозов" ,
    "title_vehicle_gyro_dication" :  "Калибровка гироскопа" ,
    "prompt_vehicle_acc_dication_tips" :  "После начала калибровки удерживайте ручку газа в максимальном и минимальном положении в течение 1 секунды. Убедитесь, что указанная операция калибровки завершена в течение 5 секунд." ,
    "prompt_vehicle_brake_dication_tips" :  "После начала калибровки удерживайте ручку тормоза в максимальном и минимальном положении в течение 1 секунды. Убедитесь, что указанная операция калибровки завершена в течение 5 секунд." ,
    "prompt_vehicle_gyro_dication_tips" :  "Пожалуйста, выпрямите самокат, чтобы подставка для ног оставалась параллельной земле, затем начните калибровку, пока она не завершится." ,
    "prompt_cannt_start_vehicle_acc_dication_when_zero_start_enabled" :  "Вы не могли начать калибровку рукоятки газа, когда включен режим "Нулевой старт"!" ,

    "prompt_dication_succeed" :  "Калибровка прошла успешно" ,
    "prompt_caulibation_failed" :  "Калибровка не удалась" ,
    "prompt_dication_timeout" :  "Тайм-аут калибровки" ,

    "title_vehicle_factory_reset" :  "Сброс к заводским настройкам" ,
    "prompt_vehicle_confirm_to_factory_reset" :  "Вы подтверждаете сброс до заводских настроек?" ,
    "prompt_vehicle_confirm_to_factory_reset_desc" :  "Восстановить все настройки и звуковой пакет до заводских" ,
    "prompt_vehicle_ezcan_confirm_to_factory_reset_desc" :  "Сброс настроек может занять несколько минут, пожалуйста, не выходите из приложения." ,
    "prompt_vehicle_ezcan_factory_reset_succeed" :  "Заводские настройки успешно сброшены, пожалуйста, выключите питание и подождите 10 секунд, затем включите питание." ,
    "prompt_vehicle_factory_reset_succeed" :  "Сброс до заводских настроек выполнен успешно!" ,

    "prompt_vehicle_euc_need_motor_free" :  "Пожалуйста, поддержите EUC на подставках или положите его на бок" ,

    "title_vehicle_firmware_update" :  "Обновление прошивки" ,

    /// EBike Assist
    "title_vehicle_assistant_mode" :  "Режим помощи" ,
    "text_vehicle_assistant_mode_none" :  "Нет" ,
    "prompt_vehicle_assistant_mode_none_desc" :  "Этот режим отключит вспомогательное питание, вы можете двигаться только вперед." ,
    "text_vehicle_assistant_mode_medium" :  "Ограничено" ,
    "prompt_vehicle_assistant_mode_medium_desc" :  "Этот режим имеет ограниченную помощь, которая подходит для езды по ровной дороге." ,
    "text_vehicle_assistant_mode_max" :  "Макс" ,
    "prompt_vehicle_assistant_mode_max_desc" :  "Этот режим усилит поддержку энергоснабжения, подходящую для частых подъемов и спусков. Этот режим быстрее расходует заряд батареи." ,

    /// L8 Light Effect
    "text_light_effect_mode_0" :  "Режим 1" ,
    "text_light_effect_mode_1" :  "Режим 2" ,
    "text_light_effect_mode_2" :  "Режим 3" ,
    "text_light_effect_mode_3" :  "Режим 4" ,
    "text_light_effect_mode_4" :  "Режим 5" ,
    "text_light_effect_mode_5" :  "Режим 6" ,
    "text_light_effect_mode_6" :  "Режим 7" ,
    "text_light_effect_mode_7" :  "Режим 8" ,
    "title_light_effect_color" :  "Режим 9" ,

    /// V12 Light Effect
    "text_light_effect_mode_close" :  "отключить" ,
    "text_light_effect_mode_audio_package" :  "Тип" ,
    "text_light_effect_mode_audio_package_change" :  "Изменить Тип" ,
    "text_light_effect_mode_follow_music" :  "по музыке" ,
    "text_light_effect_mode_follow_speed" :  "по скорости" ,
    "text_light_effect_mode_follow_speed_1" :  "переливание" ,
    "text_light_effect_mode_follow_speed_2" :  "всегда включено" ,

    ///  Diagnosis
    "title_vehicle_diagnosis" :  "Диагностика" ,
    "prompt_vehicle_diagnosis_result" :  "Результат диагностики" ,
    "prompt_vehicle_diagnosis_ok" :  "Известных ошибок и предупреждений не обнаружено" ,
    "prompt_vehicle_diagnosis_abnormal" :  "Ваше устройство находится в ненормальном состоянии" ,
    "title_vehicle_diagnosis_history" :  "История диагностики" ,
    "title_view_history" :  "Просмотр истории" ,
    "title_vehicle_upload_log" :  "Журнал загрузки" ,
    "prompt_upload_log_tips" :  "Загрузка журнала может занять несколько минут, ожидайте" ,

    /// Remote Diagnosis
    "title_remote_diagnosis" :  "Удаленная диагностика" ,
    "prompt_remote_diagnosis_tips" :  "Используйте эту функцию под руководством команды INMOTION." ,
    "prompt_remote_diagnosis_enter_failed" :  "Не удалось войти в удаленную диагностику!" ,
    "prompt_remote_diagnosis_remote_disconnected" :  "Устройство отключено!" ,
    "prompt_remote_diagnosis_disconnected" :  "Удаленная диагностика отключена!" ,
    "prompt_remote_diagnosis_waiting_remote_connection" :  "В настоящее время вы находитесь в режиме онлайн-диагностики! Ожидайте доступа к устройству." ,
    "prompt_remote_diagnosis_confirm_to_cancel" :  "В настоящее время вы ожидаете доступа к устройству, вы уверены, что желаете выйди" ,
    "prompt_remote_diagnosis_waiting_remote_timeout" :  "Ошибка доступа, время ожидания доступа к устройству истекло." ,
    "prompt_remote_diagnosis_in_progress" :  "Выполняется онлайн-диагностика. Пожалуйста, убедитесь, что ваш мобильный телефон находится рядом с устройством, сеть активна. Пожалуйста, не выключайте экран смартфона." ,

    "prompt_upload_log_success" :  "Загрузка журнала прошла успешно!" ,
    "prompt_upload_log_failed" :  "Ошибка загрузки журнала!" ,

    /// Firmware update
    "text_vehicle_current_firmware_version" :  "Текущая версия: %s" ,
    "title_vehicle_current_firmware_version" :  "Текущая версия" ,
    "prompt_new_firmware_version_found" :  "Найдена новая прошивка" ,
    "prompt_cannt_interrupt_firmware_updating" :  "Пожалуйста, продолжите обновление." ,
    "prompt_no_new_firmware_version_found" :  "Новая прошивка не найдена" ,
    "btn_update_firmware" :  "Обновить сейчас" ,
    "title_firmware_update_notes" :  "Уведомление" ,
    "text_firmware_update_notes_1" :  "· Перед обновлением убедитесь, что оставшийся заряд батареи не менее 20%" ,
    "text_firmware_update_notes_2" :  "· Не управляйте устройством во время обновления" ,
    "text_firmware_update_notes_3" :  "· Если обновление не удалось, попробуйте выйти из приложения и выполнить обновление снова" ,
    "prompt_contact_us" :  "Свяжитесь с нами" ,
    "prompt_firmware_update_learn_more_notes" :  "Подробнее>>" ,
    "title_new_firmware_version_summary" :  "Рекомендации" ,
    "text_new_firmware_version_learn_more" :  "Подробнее>>" ,
    "prompt_firmware_update_success" :  "Обновление произведено успешно" ,
    "prompt_firmware_update_failed" :  "Ошибка обновления!" ,
    "prompt_last_firmware_update_interrupted" :  "Последнее обновление прошивки могло быть прервано, пожалуйста, продолжайте обновление, чтобы исправить это." ,
    "prompt_forced_firmware_update_tips" :  ">Вам необходимо обновить прошивку устройства до последней версии, прежде чем ее можно будет использовать" ,
    "prompt_firmware_update_le1_manually_process_tips" :  "После отключения дисплея устройства подождите 3 секунды и включите его вручную. Затем нажмите "Подтвердить", чтобы продолжить обновление" ,
    "prompt_firmware_updating" :  "Обновление %s" ,
    "prompt_firmware_update_waiting_device" :  "Ожидание обновления устройства" ,

    "title_device_name_unknown" :  "Неизвестно" ,
    "title_device_name_hmic_board" :  "HMIC" ,
    "title_device_name_driver_board" :  "драйвер" ,
    "title_device_name_bt_board" :  "BT" ,
    "title_device_name_display_board" :  "Дисплей" ,
    "title_device_name_bms_1" :  "BMS 1" ,
    "title_device_name_bms_2" :  "BMS 2" ,

    /// 驱动板故障
    "title_vehicle_diagnosis_module_driver_board" :  "Панель драйвера" ,
    "vehicle_error_parse_current_sensor" :  "Сбой датчика фазного тока, возможно, вам потребуется заменить плату драйвера." ,
    "vehicle_error_bus_current_sensor" :  "Сбой датчика тока в шине, возможно, вам потребуется заменить плату драйвера." ,
    "vehicle_error_imu_sensor" :  "Сбой датчика IMU, возможно, вам нужно заменить плату драйвера." ,
    "vehicle_error_mos_temp_sensor" :  "Сбой датчика температуры MOS, возможно, вам потребуется заменить плату драйвера." ,
    "vehicle_error_bus_voltage_sensor" :  "Сбой основного датчика напряжения, возможно, вам потребуется заменить плату драйвера." ,
    "vehicle_error_battery_voltage_sensor" :  "Сбой датчика напряжения аккумулятора, возможно, вам потребуется заменить плату драйвера." ,
    "vehicle_error_board_high_temp_area_sensor" :  "Сбой датчика температуры высокотемпературной зоны, возможно, вам придется заменить плату драйвера." ,
    "vehicle_error_current_sampling" :  "Ошибка исходных данных текущей выборки, возможно, вам потребуется заменить плату драйвера." ,
    "vehicle_error_sensor" :  "Ошибка вывода датчика, возможно, вам потребуется заменить плату драйвера." ,
    "vehicle_error_rtc" :  "Ошибка RTC, возможно, вам потребуется заменить плату драйвера." ,
    "vehicle_error_spi_flash" :  "Ошибка внешнего хранилища, возможно, вам потребуется заменить плату драйвера." ,
    "vehicle_error_log" :  "Системная ошибка журнала." ,
    "vehicle_error_external_flash" :  "Сбой внешнего хранилища, возможно, вам потребуется заменить плату HMIC." ,
    "vehicle_error_euc_driver_board_communication" :  "Сбой связи платы драйвера, возможно, вам потребуется заменить плату HMIC." ,
    "vehicle_error_scooter_driver_board_communication" :  "Сбой связи с платой драйвера, возможно, вам потребуется заменить плату дисплея или плату драйвера." ,
    "vehicle_error_scooter_driver_board_communication_unstable" :  "Связь с платой драйвера нестабильна, возможно, вам необходимо заменить плату дисплея или плату драйвера. проверьте соединения." ,
    "vehicle_error_communication" :  "Сбой связи с платой драйвера, попробуйте снова включить питание и проверьте соединения." ,
    "vehicle_error_voltage" :  "Ошибка напряжения". ,
    "vehicle_error_driver_board" :  "Плата драйвера вышла из строя, вам может потребоваться ее заменить." ,
    "vehicle_error_driver_board_oscillator" :  "Ошибка кварцевого генератора на плате драйвера." ,

    "vehicle_warning_over_current" :  "Предупреждение о перегрузке по току, пожалуйста, езжайте осторожно." ,
    "vehicle_warning_over_temp" :  "Плата контроллера перегрелась, пожалуйста, остановитесь на время." ,
    "vehicle_warning_cpu_over_temp" :  "Процессор платы контроллера перегрелся, пожалуйста, остановитесь на время." ,
    "vehicle_warning_imu_over_temp" :  "IMU перегрелся, пожалуйста, остановитесь на время." ,
    "vehicle_warning_mos_over_temp" :  "MOS перегрелся, пожалуйста, прекратите езду на некоторое время." ,

    /// display board errors and warnings
    "vehicle_error_scooter_imu_sensor" :  "Сбой датчика IMU, возможно, вам нужно заменить плату дисплея." ,

    /// hmic board errors and warnings
    "title_vehicle_diagnosis_module_hmic_board" :  "Плата HMIC" ,
    "vehicle_error_hmic_board_rtc" :  "Сбой RTC, возможно, вам потребуется заменить материнскую плату." ,
    "vehicle_error_hmic_board_flash" :  "Сбой внешнего хранилища, возможно, вам потребуется заменить основную плату." ,

    /// ошибки и предупреждения платы bt
    "title_vehicle_diagnosis_module_bt_board" :  "BT Board" ,
    "vehicle_error_bt_board_communication" :  "Сбой связи Bluetooth, возможно, вам потребуется заменить основную плату или плату Bluetooth." ,

    /// bt board errors and warnings
    "title_vehicle_diagnosis_module_motor" :  "Мотор" ,
    "vehicle_error_motor_hall" :  "Моторный вал вышел из строя, возможно, вам нужно заменить мотор." ,
    "vehicle_error_motor_hall_left" :  "Мотор левый вышел из строя, возможно, вам нужно заменить мотор." ,
    "vehicle_error_motor_hall_right" :  "Мотор правый вышел из строя, возможно, вам нужно заменить двигатель." ,
    "vehicle_error_front_motor_hall" :  "Вышел из строя передний моторный отсек, возможно, вам нужно заменить мотор." ,
    "vehicle_error_rear_motor_hall" :  "Вышел из строя задний моторный отсек, возможно, вам нужно заменить мотор." ,
    "vehicle_error_motor_temp_sensor" :  "Неисправен датчик температуры двигателя, возможно, вам придется заменить двигатель/датчик." ,
    "vehicle_error_motor_phase" :  "Отсутствует фаза двигателя, возможно, вам придется заменить двигатель." ,
    "vehicle_warning_motor_over_temp" :  "Предупреждение о перегреве двигателя, пожалуйста, остановитесь на время." ,
    "vehicle_warning_motor_spin" :  "Предупреждение о вращении. Не поднимайте EUC, не нажав кнопку остановки вращения." ,
    "vehicle_warning_motor_blocked" :  "Предупреждение о остановке двигателя, пожалуйста, не напрягайте мотор на крутых склонах в течение длительного времени." ,

    ///  battery errors and warnings
    "title_vehicle_diagnosis_module_battery" :  "Батаремя" ,
    "vehicle_error_battery" :  "Аккумулятор вышел из строя, возможно, вам нужно заменить его." ,
    "vehicle_error_battery_temp_sensor" :  "Сбой датчика температуры аккумулятора, возможно, вам потребуется заменить аккумулятор/датчик." ,
    "vehicle_error_battery_cannt_power_off" :  "Не удается нормально выключить питание, возможно, вам потребуется заменить аккумулятор." ,
    "vehicle_error_battery_cannt_charge" :  "Не удалось нормально зарядить, возможно, вам потребуется заменить аккумулятор или зарядное устройство." ,
    "vehicle_error_battery_signal" :  "Ошибка сигнала от батареи." ,
    "vehicle_warning_low_battery" :  "Предупреждение о низком заряде батареи. Подзарядите ее как можно скорее." ,
    "vehicle_warning_battery_over_temp" :  "Аккумулятор перегрелся, пожалуйста, остановитесь на некоторое время." ,
    "vehicle_warning_battery_caulibation" :  "Предупреждение о ненормальной калибровке напряжения батареи. Пожалуйста, %s." ,
    "text_clerate_battery" :  "откалибровать напряжение батареи" ,
    "vehicle_warning_some_batteries_not_enabled" :  "Предупреждение от некоторых аккумуляторов не работает. Это повлияет на производительность устройства. Пожалуйста, ездите осторожно." ,
    "vehicle_warning_danger_charge1_dual_charger" :  "Предупреждение: напряжение левого и правого аккумуляторных блоков отличается, неправильная зарядка может привести к проблемам с безопасностью. Что вам следует делать: ① Используйте только одно оригинальное зарядное устройство для зарядки колеса, два зарядных устройства для зарядки колеса на одно и то же время не допускается ②Поместите колесо в поле зрения, не оставляйте колесо в покое, внимательно наблюдайте за процессом зарядки. %s" , ,
    "vehicle_warning_danger_charge1_single_charger" :  "Предупреждение: напряжение левого и правого аккумуляторов разное, неправильная зарядка может привести к проблемам с безопасностью. Что делать: поместите устройство в поле зрения, не оставляйте руль в покое, наблюдайте за процессом зарядки близко. %s" ,
    "vehicle_warning_danger_charge2" :  "Опасность! - Загрузить журнал), обратитесь к дилеру для обслуживания .%s" ,
    "btn_i_know_danger_charge_risk_and_turn_off_alert" :  "Я знаю об этом риске и отключу это предупреждение" ,
    "vehicle_warning_battery_over_voltage" :  "Высокое напряжение батареи, возможно, вам потребуется заменить батарею или зарядное устройство." ,
    "vehicle_warning_battery_output_abnormal" :  "Аккумулятор критически разряжен, попробуйте перезарядить его, иначе вам может понадобиться заменить аккумулятор." ,
    "vehicle_warning_too_low_battery" :  "Предупреждение о слишком низком напряжении, перезарядите аккумулятор как можно скорее, чтобы не повредить его." ,

    /// Fan
    "title_vehicle_diagnosis_module_fan" :  "Вентилятор" ,
    "vehicle_error_fan" :  "Вентилятор охлаждения неисправен, возможно, вам придется его заменить." ,
    "vehicle_warning_fan_low_speed" :  "Скорость вращения вентилятора низкая. Это повлияет на максимальный уровень яркости фары. Пожалуйста, проверьте, не заблокирован ли он/исправен." ,

    ///  vehicle errors and warnings
    "title_vehicle_diagnosis_module_vehicle" :  "Устройство" ,
    "vehicle_error_brake_handle" :  "Сбой руля тормоза, пожалуйста, дважды проверьте, отпущен ли руль тормоза." ,
    "vehicle_error_acc_handle" :  "Дроссельная заслонка нзаблокирована, пожалуйста, дважды проверьте, отпущен ли руль дроссельной заслонки или нет." ,

    "vehicle_warning_lock_caused_by_safe_issue" :  "Устройство временно заблокировано из-за скрытой опасности, связанной с безопасностью." ,
    "vehicle_warning_over_speed" :  "Предупреждение о превышении скорости. Пожалуйста, притормозите." ,
    "vehicle_warning_fall_down" :  "Предупреждение о падении. Пожалуйста, езжайте осторожно." ,
    "vehicle_warning_risk_behavior" :  "Предупреждение об опасном вождении, пожалуйста, прекратите." ,
    "vehicle_warning_software_incompatible" :  "Предупреждение о несовместимости прошивки, обновите прошивку устройства до последней версии." ,
    "vehicle_warning_motor_no_load_protection" :  "Предупреждение защиты двигателя от холостого хода, перед подъемом рекомендуется нажать кнопку блокировки и убедиться, что устройство неподвижно." ,
    "vehicle_warning_power_key_long_pressed" :  "Предупреждение при длительном нажатии кнопки питания. Длительное нажатие кнопки питания может привести к принудительному отключению питания. Пожалуйста, прекратите ехать!" ,
    "vehicle_warning_necessary_self_check_not_passed" :  "Необходимый элемент проверки не пройден или не пройден, %s." ,
    "text_execute_self_check" :  "выполнить проверку" ,
    "vehicle_warning_function_limited_by_uncompleted_fw_update" :  "Функции устройства ограничены, и для его нормального использования необходимо обновить прошивку." ,
    "vehicle_warning_remote_locked" :  "Устройство заблокировано, пожалуйста, свяжитесь с нами, чтобы подтвердить личность и разблокировать." ,
    "vehicle_warning_hardware_incompatible" :  "Предупреждение по аппаратной несовместимости, контроллер,плата драйвера должны быть заменены в полном комплекте." ,
    "vehicle_warning_over_power" :  "Чрезмерная выходная мощность". ,

    /// Ошибка BMS
    "bms_error_voltage_sample" :  "Ошибка выборки напряжения." ,
    "bms_error_charge_current_sample" :  "Ошибка текущего образца заряда." ,
    "bms_error_discharge_current_sample" :  "Ошибка сброса текущего образца." ,
    "bms_error_temperature_sensor" :  "Ошибка датчика температуры." ,
    "bms_error_rh_sensor" :  "Ошибка датчика относительной влажности." ,
    "bms_error_charge_mosfet" :  "Ошибка зарядки mos." ,
    "bms_error_discharge_mosfet" :  "Ошибка разряда mos." ,
    "bms_error_afe" :  "Ошибка Afe." ,
    "bms_error_cell" :  "Ошибка ячейки". ,
    «bms_error_mcu» :  «Ошибка MCU». ,

    /// BMS Warning
    "bms_warning_low_soc" :  "Предупреждение о низком уровне заряда." ,
    "bms_warning_pack_over_charge" :  "Предупреждение о перезарядке аккумуляторной батареи." ,
    "bms_warning_pack_over_discharge" :  "Предупреждение о переразрядке аккумуляторной батареи." ,
    "bms_warning_cell_over_charge" :  "Предупреждение о перезарядке аккумуляторной батареи." ,
    "bms_warning_cell_over_discharge" :  "Предупреждение о переразрядке аккумуляторной батареи." ,
    "bms_warning_charge_over_current" :  "Предупреждение о превышении текущего заряда." ,
    "bms_warning_charge_mosfet_over_temperature" :  "Предупреждение о перегреве зарядного устройства." ,
    "bms_warning_charge_cell_over_temperature" :  "Предупреждение о превышении температуры заряда батареи." ,
    "bms_warning_charge_cell_low_temperature" :  "Предупреждение о низкой температуре заряда аккумуляторной батареи." ,
    "bms_warning_discharge_over_current" :  "Предупреждение о превышении тока разряда." ,
    "bms_warning_discharge_mosfet_over_temperature" :  "Предупреждение о перегреве разряда mosfet". ,
    "bms_warning_discharge_cell_over_temperature" :  "Предупреждение о перегреве разряда аккумуляторной батареи." ,
    "bms_warning_discharge_cell_low_temperature" :  "Предупреждение о низкой температуре разряда аккумуляторной батареи." ,
    "bms_warning_over_humidity" :  "Предупреждение о повышенной влажности." ,

    /// BMS Protection
    "bms_protection_short_circuit" :  "Защита от короткого замыкания". ,
    "bms_protection_pack_over_charge" :  "Защита аккумулятора от перезарядки." ,
    "bms_protection_pack_over_discharge" :  "Защита аккумуляторной батареи от разрядки." ,
    "bms_protection_cell_over_charge" :  "Защита аккумуляторной батареи от перезарядки." ,
    "bms_protection_cell_over_discharge" :  "Защита аккумуляторной батареи от разрядки." ,
    "bms_protection_charge_over_current" :  "Защита от перегрузки по току." ,
    "bms_protection_charge_mosfet_over_temperature" :  "Зарядить мосфет для защиты от перегрева." ,
    "bms_protection_charge_cell_over_temperature" :  "Защита аккумулятора от перегрева." ,
    "bms_protection_charge_cell_low_temperature" :  "Защита аккумулятора от низкой температуры." ,
    "bms_protection_discharge_over_current" :  "Защита от перегрузки по току." ,
    "bms_protection_discharge_mosfet_over_temperature" :  "Разрядить mosfet для защиты от перегрева." ,
    "bms_protection_discharge_cell_over_temperature" :  "Защита от перегрева при разрядке аккумуляторной батареи." ,
    "bms_protection_discharge_cell_low_temperature" :  "Защита от низкой температуры разряда аккумуляторной батареи." ,
    "bms_protection_over_humidity" :  "Защита от перегрева." ,
    "bms_protection_associated_charge" :  "Защита связанного заряда". ,
    "bms_protection_associated_discharge" :  "Защита от связанного разряда". ,

    /// light effect
    'title_light_effect_preview' :  'Предварительный просмотр светового эффекта' ,
    'title_complete_light_effect_info' :  'Пожалуйста, заполните информацию о световом эффекте' ,
    'prompt_input_light_effect_name' :  'Пожалуйста, введите название' ,
    'prompt_invalid_light_effect_info' :  'Неверная информация' ,
    'text_light_effect_frame_interval' :  'Интервал кадра' ,
    'title_light_effect_my_colors' :  'Мои цвета' ,
    'text_light_effect_frame_keyframe' :  'Ключевой кадр' ,
    'text_light_effect_frame_total' :  'Всего кадров' ,
    'text_light_effect_frame_number' :  '%s кадр' ,
    'text_light_effect_frame' :  '%s Кадр' ,
    'text_light_effect_frame_mode_normal' :  'нормально' ,
    'text_light_effect_frame_mode_fast' :  'быстро' ,
    'text_light_effect_frame_mode_slow' :  'медленно' ,
    'title_light_effect_edit' :  'Редактировать' ,
    'prompt_light_effect_edit_back_tips' :  'Выход не сохранит отредактированные световые эффекты' ,
    'prompt_light_effect_edit_gradient_mode_1' :  'Отпустите, чтобы установить ключевой кадр, или продолжайте перетаскивать, чтобы отменить' ,
    'prompt_light_effect_edit_gradient_mode_2' :  'В настоящее время в режиме внутрикадрового градиента, пожалуйста, продолжайте выбирать конечную точку градиента или %s' ,
    'prompt_light_effect_edit_gradient_mode_3' :  'В настоящее время в режиме внутрикадрового градиента вы выбираете конечную точку градиента, отпустите ее, чтобы выйти из этого режима' ,
    'prompt_light_effect_edit_gradient_mode_4' :  'В настоящее время в режиме внутрикадрового градиента вы выбираете конечную точку градиента, вы также можете провести здесь, чтобы выйти из режима' ,
    'text_light_effect_exit_edit_gradient_mode' :  'выйти из этого режима' ,
    'prompt_light_effect_edit_already_first_step' :  "Это уже первый шаг!" ,
    'prompt_light_effect_edit_already_last_step' :  "Это уже последний шаг!" ,
    'prompt_light_effect_drag_to_delete' :  'Перетащите сюда, чтобы удалить' ,
    'prompt_light_effect_release_to_delete' :  'Отпустите, чтобы удалить' ,
    "title_vehicle_light_effect_exists" :  "Световой эффект в устройство" ,
    "text_light_effect_default_package" :  "Световой эффект по умолчанию" ,
    "text_light_effect_unknown_package" :  "Неизвестный световой эффект" ,
    "prompt_enable_light_effect_failed" :  "Не удалось включить световой эффект" ,
    'prompt_confirm_to_delete_light_effect' :  'Вы подтверждаете удаление?' ,
    'prompt_confirm_to_delete_diy_light_effect' :  "Световой эффект "Сделай сам" не может быть восстановлен после удаления. Вы подтверждаете удаление "%s"?" ,

    /// sound pack
    "title_vehicle_sound_pack" :  "Звуковой пакет" ,
    "title_vehicle_sound_pack_exists" :  "Звуковой пакет в устройстве" ,
    "text_default_sound_pack" :  "по умолчанию" ,
    "text_unknown_sound_pack" :  "неизвестный звуковой пакет" ,
    "prompt_input_sound_pack_name" :  "Пожалуйста, введите название звукового пакета" ,
    "prompt_select_sound_pack_cover" :  "Выберите обложку" ,
    "title_diy_single_sound_pack_item" :  "Сделай сам, один звук" ,
    "title_diy_sound_pack" :  "Сделай сам звуковой пакет" ,
    'prompt_confirm_to_use_default_sound_pack' :  'Подтверждаете ли вы восстановление заводских настроек звукового пакета по умолчанию?' ,
    "prompt_select_from_local_file" :  "Выберите локальный файл" ,
    "prompt_vehicle_transferring_file" :  "Пожалуйста, держите транспортное средство неподвижным и не управляйте транспортным средством во время передачи файла." ,
    "prompt_enable_sound_pack_success" :  "Установлено!" ,
    "prompt_enable_sound_pack_failed" :  "Не удалось установить" ,
    "prompt_vehicle_storage_capacity_not_enough" :  "Недостаточно места" ,
    "prompt_sound_pack_composing" :  "Компиляция..." ,
    "prompt_sound_pack_item_file_is_too_large" :  "файл слишком велик" ,
    "title_custom_sound_pack" :  "Сделай сам" ,
    "title_complete_sound_pack_info" :  "Информация о звуковом пакете" ,
    "btn_compose" :  "Компилировать" ,
    "title_sound_pack_compose" :  "Компилировать звуковой пакет" ,
    "prompt_sound_pack_compose_succeed" :  "Завершено!" ,
    "prompt_sound_pack_compose_failed" :  "Не удалось создать" ,
    "title_sound_pack_audition" :  "Прослушивание" ,
    "title_select_sound_pack_item" :  "Выбрать звук" ,
    'prompt_confirm_to_delete_sound_pack' :  'Вы подтверждаете удаление?' ,
    'prompt_confirm_to_delete_sound_pack_in_vehicle' :  "Звуковой пакет в устройстве не может быть восстановлен после удаления. Вы подтверждаете удаление "%s"?" ,
    'prompt_confirm_to_delete_diy_sound_pack' :  "Не удалось восстановить звуковой пакет "Сделай сам" после удаления. Вы подтверждаете удаление "%s"?" ,
    'text_sound_pack_file_local' :  'Локальный' ,
    'text_sound_pack_file_record' :  'Запись' ,
    'text_sound_pack_file_library' :  'Звуковая библиотека' ,
    'text_sound_pack_item_duration' :  'Продолжительность: ' ,
    'text_sound_pack_item_size' :  'Размер: ' ,
    'prompt_sound_pack_compose_item_cannt_be_empty' :  "Все элементы не могут быть пустыми" ,
    'title_sound_pack_diy_create_from_template' :  'Создать из шаблона' ,
    'title_sound_pack_diy_create_directly' :  'Создать напрямую' ,
    'title_sound_pack_diy_select_template' :  'Выберите шаблон' ,
    "title_sound_pack_audition_on_phone" :  "Прослушать" ,
    "title_sound_pack_audition_on_vehicle" :  "Прослушивание на устройстве" ,

    ///
    /// Mine
    ///
    'btn_authorized_vehicles' :  'Мои устройства' ,
    'btn_vehicle_authorization' :  'Авторизация владельца' ,
    'btn_customer_service' :  'Обслуживание клиентов' ,
    'title_find_my_vehicle' :  "Найти мое устройство" ,
    'title_unit_metric_imperial' :  'Метрические/имперские единицы' ,
    'text_unit_metric' :  'Метрика' ,
    'text_unit_imperial' :  'Империал' ,
    'title_language' :  'Язык' ,
    'text_follow_system' :  'системный' ,
    'title_select_language' :  'Выберите язык' ,
    'title_account_security' :  "Учетная запись" ,
    'title_clear_cache' :  'Очистить кеш' ,
    'prompt_clear_cache_tips' :  'Вы подтверждаете очистку кеша?' ,
    'title_app_about' :  'О приложении' ,
    'text_app_version' :  '%s' ,

    'title_message_center' :  'Центр сообщений' ,
    'title_user_info' :  "Личная информация" ,
    'btn_take_a_photo' :  'Возьми телефон' ,
    'btn_select_from_album' :  'Выбрать из альбома' ,

    'title_scan_qrcode' :  'Сканировать QR-код' ,

    /// About
    "user_agreement" :  "Пользовательское соглашение" ,
    "privacy_policy" :  "Политика конфиденциальности" ,
    'inmotion_company' :  'INMOTION' ,

    ///  personal info
    'title_avatar' :  'Аватар' ,
    'title_nickname' :  'Псевдоним' ,
    'title_signature' :  'Подпись' ,
    'title_modify_nickname' :  'Изменить никнейм' ,
    'title_modify_signature' :  'Изменить подпись' ,
    'prompt_nickname_limit' :  '6-20 символов' ,
    'prompt_signature_limit' :  '0-100 символов' ,

    /// my vehicle
    'title_my_vehicles' :  'Мои устройства' ,
    'title_delete_authorized_vehicle' :  'Удалить авторизацию владельца' ,
    'prompt_delete_authorized_vehicle_tips' :  'Удаление устройства приведет к удалению авторизации его владельца. Вы подтверждаете?» ,
    'title_delete_vice_owner' :  'Удалить вице-владельца' ,
    'prompt_delete_vice_owner_tips' :  'Вы подтверждаете удаление вице-владельца?' ,
    'title_vehicle_details' :  'Информация об устройстве' ,
    'title_vehicle_info' :  'Информация об устройстве' ,
    'prompt_vehicle_info_updated_at' :  'Информация ниже была обновлена ​​в: %s' ,
    'title_vehicle_model' :  'Модель' ,
    'title_activated_date' :  'Активировано' ,
    'title_total_mileage' :  'Общий пробег' ,
    'title_riding_record' :  'Рекорд по езде' ,
    "title_bluetooth_name" :  "Имя BT" ,
    "text_vehicle_remaining_mileage" :  "Оставшийся пробег: %s" ,
    'title_vehicle_owner_info' :  'Информация о владельце' ,
    'title_vehicle_main_owner' :  'Основной владелец' ,
    'btn_go_to_authorize_as_owner' :  'Перейти к авторизации' ,
    'prompt_not_owner_and_go_to_authorize_as_owner' :  'Это может сделать только владелец текущего устройства, вы хотите авторизоваться как владелец сейчас?' ,
    'text_vehicle_info_owner_me_suffix' :  '(Я)' ,
    'title_vehicle_vice_owner' :  'Вице-владелец' ,
    'title_vehicle_no_owner' :  'Нет' ,
    'title_transfer_vehicle_main_owner' :  'Передать основного владельца' ,
    'prompt_transfer_vehicle_main_owner_tips' :  'После передачи пользователь "%s" станет основным владельцем текущего устройства, а вы станете вице-владелец. \n Вы подтверждаете перевод?' ,
    'title_invite_as_vehicle_vice_owner' :  'Пригласить' ,
    'prompt_invite_as_vehicle_vice_owner_tips' :  'Пожалуйста, используйте приложение INMOTION для сканирования QR-кода, чтобы авторизоваться в качестве вице-владельца.' ,
    'title_vehicle_authorization' :  'Авторизация устройства' ,
    'prompt_authorize_current_connected_vehicle_tips' :  'Устройство %s в настоящее время подключено, вы хотите аутентифицироваться как владелец?' ,
    'prompt_input_sn' :  'Пожалуйста, введите серийный номер' ,
    'title_vehicle_authorization_requests' :  'Запрос истории' ,
    'title_sent_vehicle_authorization_requests' :  'Отправлено' ,
    'title_received_vehicle_authorization_requests' :  'Получено' ,
    'prompt_vehicle_authorization_apply_to' :  'Применено к %s' ,
    'prompt_vehicle_authorization_apply_from' :  'Ко мне подали заявку %s' ,
    'prompt_vehicle_authorization_waiting' :  'Ожидание' ,
    'text_status_pending' :  'В ожидании' ,
    'text_status_approved' :  'Одобрено' ,
    'text_status_rejected' :  'Отклонено' ,
    'text_status_expired' :  'Просрочено' ,

    /// vehicle authorization
    'prompt_vehicle_authorization_apply_success' :  'Заявка отправлена.' ,
    'prompt_vehicle_authorization_success' :  'Успешно авторизован как основной владелец' ,
    'prompt_vehicle_authorized_as_vice_owner_tips' :  'У этого транспортного средства уже есть основной владелец, вы хотите авторизоваться в качестве вице-владельца?' ,
    'prompt_vehicle_authorized_as_vice_owner_success' :  'Успешно авторизован как вице-владелец' ,
    'prompt_vehicle_authorization_failed' :  'Авторизация не удалась' ,

    /// customer service
    'title_message_board' :  'Сообщения' ,
    'prompt_leave_message_tips' :  'Пожалуйста, оставьте сообщение, мы свяжемся с вами в ближайшее время.' ,
    'btn_leave_a_message' :  'Оставить сообщение' ,
    'prompt_please_leave_a_message' :  'Пожалуйста, оставьте сообщение' ,
    'btn_chat_menu_picture' :  'Картинка' ,
    'btn_chat_menu_video' :  'Видео' ,
    'prompt_leave_message_success' :  'Успешно' ,
    'prompt_leave_message_failed' :  'Отправить сообщение не удалось' ,
    'prompt_content_couldnt_be_empty' :  "Содержимое не может быть пустым." ,
    'prompt_customer_service_waiting_for_access' :  'Ожидание доступа' ,
    'prompt_customer_service_queue_number' :  'Вы в очереди. Перед вами %s человек' ,
    'prompt_customer_service_offline' :  'Служба поддержки отключена' ,
    'prompt_customer_service_session_ended' :  'Сессия завершена' ,
    'btn_customer_service_evaluate' :  'Оценить' ,
    'prompt_input_question_to_consult' :  'Пожалуйста, введите вопрос, который вы хотите задать' ,

    "title_official_recommends" :  "Рекомендации" ,

    /// riding record
    "text_riding_record_summary" :  "В целом, %sчасов, %sКг. выбросов углекислого газа сохранено." ,

    ///
    /// errors
    ///
    'prompt_request_failed' :  'Запрос не выполнен' ,
    'prompt_request_failed_timeout' :  'Тайм-аут запроса' ,
    'prompt_request_failed_network' :  'Ошибка сети' ,

    'prompt_unauthenticated_request' :  'Сеанс входа в систему истек, пожалуйста, войдите снова!' ,
    'prompt_unknown_error' :  'Неизвестная ошибка' ,
    'prompt_operate_too_frequently' :  'Операция выполняется слишком часто, повторите попытку позже.' ,
    'prompt_file_download_failed' :  'Ошибка загрузки файла' ,
    'prompt_unknown_product_model' :  'Неизвестная модель' ,
};
