const Map<String, String> ru_RU = {
    ///
    /// Common
    ///
    "prompt_welcome_to_inmotion": "Привет, \nДобро пожаловать в INMOTION",
    "btn_more": "Подробнее",
    "btn_view_more": "Просмотреть больше",
    "btn_cancel": "Отмена",
    "btn_exit": "Выход",
    "btn_confirm": "Подтверждать",
    "btn_complete": "Закончить",
    "btn_submit": "Предоставить",
    "btn_i_see": "Понятно",
    "btn_skip": "Пропустить",
    "btn_next_step": "Далее",
    "btn_save": "Сохранить",
    "btn_save_image": "Сохранить изображение",
    "btn_edit": "Редактировать",
    "btn_preview": "Предварительный просмотр",
    "btn_rename": "Переименовать",
    "btn_delete": "Удалить",
    "btn_publish": "Опубликовать",
    "tab_vehicle": "ТС",
    "tab_moment": "Моменты",
    "tab_discover": "Мир",
    "tab_mine": "Я",
    "prompt_page_error": "Произошла ошибка.",
    "btn_share": "Делиться",
    "btn_report": "Отчет",
    "btn_enable": "Включить",
    "btn_enabled": "Включено",
    "btn_retry": "Повторить",
    "prompt_title_warning": "Предупреждение",
    "prompt_title_tips": "Уведомление",
    "prompt_title_warm_tips": "Полезные советы",
    "prompt_confirm_to_cancel": "Вы подтверждаете отмену?",
    "prompt_failed": "Сбой",
    "btn_agree": "Подтверждаю",
    'btn_reject': 'Отклонить',
    "btn_need_help": "Нужна помощь?",
    "btn_common_problem": "FAQ",
    "page_message_center": "Центр сообщений",
    "title_sys_message": "Системное сообщение",
    "title_social_message": "Социальное сообщение",
    "btn_save_and_share": "Сохранить и поделиться",
    "prompt_saved": "Сохранено",
    "prompt_save_failed": "Не удалось сохранить",
    "prompt_updated": "Обновлено",
    "prompt_update_failed": "Не удалось обновить",
    "prompt_data_empty": "Пустые данные.",
    "prompt_loading": "Загружается...",
    "prompt_load_failed": "Загрузка не удалась",
    "prompt_copied": "Скопировано",
    "prompt_action_failed": "Неуспешно",
    "prompt_press_again_to_exit": "Нажмите еще раз, чтобы выйти.",

    "datetime_just_now": "Прямо сейчас",
    "datetime_x_minutes_ago": "%sмин назад",
    "datetime_yesterday_x": "Вчера %s",

    "unknown": "Неизвестный",

    ///
    /// Account
    ///

    "prompt_auto_register_if_account_not_exists": "Незарегистрированный номер телефона будет использоваться для автоматического создания учетной записи после проверки",
    "btn_login": "Авторизоваться",
    "btn_register": "Зарегистрироваться",
    "title_register": "Зарегистрироваться",
    "title_cn_phone_quick_login": "Быстрая проверка",
    "prompt_input_phone": "Номер телефона",
    "prompt_input_email": "Адрес электронной почты",
    "prompt_input_email_or_username": "Адрес электронной почты/имя учетной записи",
    "prompt_input_verification_code": "Проверочный код",
    "prompt_input_password": "Пароль",
    "prompt_input_a_valid_phone": "Пожалуйста, введите действительный номер телефона!",
    "prompt_input_a_valid_email": "Пожалуйста, введите действительный адрес электронной почты!",
    "prompt_input_a_valid_email_or_username": "Пожалуйста, введите действительный адрес электронной почты или имя учетной записи!",
    "prompt_input_a_valid_password": "Пожалуйста, введите правильный пароль",
    "btn_forgot_password": "Забыли пароль?",
    "btn_reset_password": "Сброс пароля",
    "btn_login_via_password": "Войти через учетную запись и пароль",
    "btn_login_via_verification_code": "Войти через проверочный код",
    "btn_request_verification_code": "Получить код",
    "btn_request_sms_verification_code": "Получить код",
    "prompt_verification_code_has_sent_to": "Код подтверждения отправлен %s",
    "btn_resend": "Отправить повторно",
    "title_user_agreement": "Пользовательское Соглашение",
    "title_privacy_policy": "Политика конфиденциальности",
    "prompt_register_agreement_tips": "Регистрация или вход означает, что вы согласились с %s и %s",
    "title_select_country_or_region": "Выберите страну/регион",
    "btn_modify_phone": "Изменить номер телефона",
    "btn_modify_email": "Изменить электронную почту",
    "btn_bind_phone": "Привязать номер телефона",
    "btn_modify_password": "Изменить пароль",
    "phone_number": "Номер телефона",
    "email": "Электронная почта",
    "btn_register_via": "Зарегистрироваться через %s",
    "btn_bind_via": "Привязать через %s",
    "btn_reset_password_via": "Сброс через %s",
    "btn_bind_account": "Привязать аккаунт",
    "prompt_password_limit_tips": "Пожалуйста, введите 6-20 цифр и английских символов, а не только цифры",
    "prompt_empty_password": "Пустой пароль",
    "title_bind_social_account": "Привязка социальной учетной записи",
    "prompt_social_account_auth_failed": "Авторизация не удалась",
    "prompt_bind_social_account_tips": "*Вы можете войти в INMOTION с привязанной социальной учетной записью.",
    'state_bound': 'Привязан',
    'state_not_bound': 'Не привязан',
    'prompt_unbind_social_account_tips': 'После отмены привязки вы не сможете использовать %s для входа в INMOTION, вы уверены, что хотите отменить привязку?',
    'btn_logout': 'Выйти',
    'prompt_logout_tips': 'Вы подтверждаете выход из системы?',
    "title_operation_verification": "Проверка безопасности",
    "prompt_operation_verification_tips": "Текущая операция требует проверки, пожалуйста, подтвердите ее любым из следующих способов",
    "title_verify_operation_via": "Подтвердить через %s",
    "prompt_operation_verification_expired": "Сначала выполните проверку безопасности!",
    "text_none": "无",

    /// Chinese phone quick verify error
    "prompt_cn_phone_auth_no_sim_card": "SIM-карта не обнаружена!",
    "prompt_cn_phone_auth_unknown_operator": "Неизвестный оператор!",
    "prompt_cn_phone_auth_network_not_enable": "Мобильные данные не включены!",
    "prompt_cn_phone_auth_unknown": "Неизвестная ошибка!",

    ///
    /// Vehicle
    ///
    "btn_search_vehicle": "Поиск ТС",
    "prompt_had_connected_before": "Подключено раньше",
    "title_vehicle_activation": "Активация",
    "prompt_wait_for_activation_tips_finished": "Пожалуйста, прочтите/посмотрите напоминания о безопасности.",
    "prompt_had_read_activation_tips": "Я внимательно прочитал вышеуказанные напоминания о безопасности и знаю о возможных рисках",
    "btn_activate": "Активировать сейчас",
    "prompt_activated": "Активирован успешно!",
    "prompt_activate_failed": "Активировать не удалось",
    "prompt_activate_canceled": "Отменено",
    "prompt_authorize_as_owner_after_activation": "Аутентификация ТС требуется для таких операций, как блокировка ТС в приложении. Вы хотите стать владельцем сейчас?",
    "prompt_authorize_as_owner_later_after_activation": "Вы также можете сделать это позже в Я - авторизация владельца",
    "prompt_set_vehicle_password_failed": "Не удалось установить пароль",
    "prompt_set_vehicle_password_later_after_activation": "Вы также можете сделать это позже в ТС - Настройки ТС - Пароль",
    "prompt_bluetooth_disabled": "Bluetooth не включен",
    "prompt_location_disabled": "Служба определения местоположения не включена",
    "prompt_no_bluetooth_permission": "Нет разрешения Bluetooth",
    "prompt_no_location_permission": "Нет разрешения на местоположение",
    "prompt_no_scan_bluetooth_permission": "Нет разрешения на сканирование Bluetooth",
    "prompt_no_connect_bluetooth_permission": "Нет разрешения на подключение Bluetooth",
    "prompt_no_device_found": "ТС не найдены.",
    "prompt_tap_to_connect": "Нажмите на ТС ниже, чтобы подключиться",
    "prompt_scanning": "Поиск...",
    "prompt_connecting": "Подключение...",
    "prompt_connection_canceled": "Соединение отменено",
    "prompt_connected": "Подключен",
    "prompt_connection_timeout": "Время соединения вышло",
    "prompt_connection_failed": "Сбой соединения",
    "prompt_unsupported_models": "Неподдерживаемая модель продукта",
    "btn_enable_bluetooth": "Откройте телефон Bluetooth",
    "btn_enable_location": "Включить службу определения местоположения",
    "btn_request_bluetooth_permission": "Требуются разрешения к Bluetooth",
    "btn_request_location_permission": "Требуются разрешения на определение местоположения",
    "btn_scan_again": "Повторный поиск",
    "btn_cancel_connection": "Отмена",
    "prompt_why_need_to_enable_location": "Зачем мне включать службу определения местоположения?",
    "prompt_why_need_location_permission": "Зачем INMOTION требуется разрешение на определение местоположения?",
    "prompt_why_do_i_couldnt_find_vehicles": "Почему я не могу найти свое ТС?",
    "btn_view_solutions": "Просмотреть решения",
    "prompt_connect_failed_server_ip_service_error": "Временная ошибка сервера. Мы исправим ее в ближайшее время, повторите попытку позже.",
    "prompt_connect_failed_unknown_model": "Вы не можете использовать приложение INMOTION, потому что модель текущего ТС недействительна.\nПожалуйста, свяжитесь с нами для получения дополнительной информации.",
    "prompt_connect_failed_unknown_sn": "Вы не можете использовать приложение INMOTION, потому что серийный номер текущего ТС недействителен.\nПожалуйста, свяжитесь с нами для получения дополнительной информации.",
    "prompt_connect_failed_vehicle_locked": "ТС находится в РЕЖИМЕ ПОТЕРИ. Пожалуйста, свяжитесь с нами для получения дополнительной информации.",
    "prompt_connect_failed_vehicle_lost_mode": "ТС находится в РЕЖИМЕ ПОТЕРИ. Вы можете отключить его в разделе Я-найти мое ТС, если вы являетесь владельцем ТС.",

    "text_vehicle_ride_time": "Время в пути",
    "text_vehicle_ride_mileage": "Пробег поездки",
    "text_vehicle_max_speed": "Макс. скорость",
    "text_vehicle_ave_speed": "Ср. скорость",
    "text_vehicle_total_mileage": "Общий пробег",
    "text_vehicle_dynamic_speed_limit": "Динамическое ограничение скорости",
    "text_vehicle_power": "Мощьность",
    "text_vehicle_max_power": "Макс. мощность",
    "text_vehicle_mos_temp": "Температура MOS",
    "text_vehicle_consumption": "Потребление",
    "text_vehicle_last_ride_mileage": "Последний пробег",
    "text_vehicle_last_ride_time": "Время последней поездки",
    "text_vehicle_last_max_speed": "Последняя макс. скорость",
    "text_vehicle_speed": "Скорость",
    "text_vehicle_battery_discharge_current": "Ток разряда батареи",
    "text_vehicle_battery_voltage": "Напряжение батареи",
    "text_vehicle_battery_output_power": "Мощность разряда батареи",
    "text_vehicle_motor_output_power": "Выходная мощность двигателя",
    "text_vehicle__motor_torque": "Крутящий момент",
    "text_vehicle_remaining_battery": "Оставшийся заряд",
    "text_vehicle_output_rate": "Выходное векторное напряжение (%)",
    "text_vehicle_dynamic_current_limit": "Динамический предел перегрузки по току",

    "text_vehicle_motor_temp": "Температура двигателя",
    "text_vehicle_battery_temp": "Температура батареи",
    "text_vehicle_motherboard_high_temp": "Температура контроллера",
    "text_vehicle_driver_board_cpu_temp": "Температура CPU контроллера",
    "text_vehicle_imu_temp": "Температура IMU",

    "text_gps_speed": "Скорость GPS",

    "prompt_status_connecting": "Подключение",
    "prompt_status_connected": "Подключено",
    "prompt_status_disconnected": "Не подключено",
    "prompt_vehicle_disconnected": "Транспорт отключен",
    "prompt_no_connected_vehicles_yet": "Подключенных устройств пока нет.",
    "prompt_current_connected_vehicle": "Подключено",
    "prompt_last_connected_at": "Последнее подключениe: %s"
    "title_switch_vehicle": "Смена транспорта",
    "btn_disconnect_and_scan": "Отключить и искать",
    "btn_scan": "Поиск",
    "btn_detailed_data": "Подробные данные",
    "title_about_vehicle": "Об устройстве",
    "title_battery_info": "Информация о батарее",
    "title_customer_service": "Интернет поддержка",
    "title_faq": "FAQ",

    "title_gps_riding_tracks": "Мои поездки",
    "title_vehicle_riding_record": "Записи поездок",

    "text_vehicle_riding_record_mileage": "Пробег поездки : %s"
    "text_vehicle_riding_record_max_speed": "Макс. Скорость: %s"

    "title_vehicle_riding_report": "Отчет о поездке",
    "prompt_invalid_riding_track": "Недопустимый маршрут поездки",

    "title_basic_battery_info": "Основная информация",
    "text_battery_voltage": "Напряжение",
    "text_battery_charge_voltage": "Напряжение заряда",
    "title_detailed_battery_info": "Информация о батарейном блоке",
    "text_battery_detected_status": "Статус обнаружения батареи",
    "text_battery_detected": "Обнаружено",
    "text_battery_not_detected": "Не обнаружено",
    "text_battery_enable_status": "Статус батареи",
    "text_battery_enabled": "Включен",
    "text_battery_disabled": "Отключен",
    "text_battery_error_status": "Состояние ошибки батареи",
    "text_battery_ok": "Ошибок нет",
    "text_battery_error": "Ошибка",
    "text_battery_signal_logic_error": "Ошибка логического сигнала",

    "title_battery_cells_voltage": "Напряжение аккумуляторных элементов",

    "title_bms_basic_info": "Базовая информация",
    "text_bms_battery_sn": "Батарея SN",
    "text_bms_manufacture_date": "Дата изготовления",
    "text_bms_full_charge_cycles": "Циклы полной зарядки",
    "text_bms_software_version": "Версия ПО BMS",
    "text_bms_hardware_Version": "Аппаратная версия BMS",
    "title_bms_data_and_status": "Данные и статус",
    "text_bms_voltage": "Напряжение",
    "text_bms_charge_state": "Состояние заряда",
    "text_bms_charge_current": "Ток заряда",
    "text_bms_discharge_current": "Ток разряда",
    "text_bms_charge_mos_state": "Зарядка MOS",
    "text_bms_discharge_mos_state": "Разряд MOS",
    "text_bms_error_status": "Статус ошибки",
    "text_bms_warning_status": "Статус предупреждения",
    "text_bms_protection_status": "Статус защиты",
    "text_bms_cell_balancing_status": "Балансировка ячеек",
    "text_bms_max_cell_voltage": "Макс. напряжение ячейки",
    "text_bms_min_cell_voltage": "Мин. напряжение ячейки",
    "text_bms_charge_mos_temp": "Температура заряда MOS",
    "text_bms_discharge_mos_temp": "Температура разряда MOS",
    "text_bms_cells_temp": "Температура ячеек",
    "text_bms_cells_voltage": "Напряжение ячеек",

    /// vehicle settings
    "title_vehicle_settings": "Настройки устройства",
    "prompt_operation_succeed": "Применено",
    "prompt_operation_failed": "Не удалось применить",
    "title_vehicle_password": "Пароль",
    "text_vehicle_password_disabled": "Отключен",
    "text_vehicle_password_gesture": "Жест",
    "text_vehicle_password_slide": "Слайд",
    "text_vehicle_password_number": "Пин-код",
    "title_modify_vehicle_password": "Изменить пароль",
    "title_set_vehicle_password": "Установка пароля",
    "prompt_vehicle_number_password_tips": "Пожалуйста, введите пароль из 4 или 6 цифр",
    "title_vehicle_userinfo": "Информация о пользователе устройства",
    "title_vehicle_userinfo_avatar": "Аватар",
    "title_vehicle_userinfo_name": "Название ТС",
    "prompt_vehicle_userinfo_name_tips": "Пожалуйста, введите от 1 до 16 букв, цифр и английских символов",
    "title_choose_setting_item": "Выберите элементы настройки",
    "vehicle_setting_item_limit_speed_25": "Ограничение скорости на 25 км/ч",
    "vehicle_setting_item_limit_speed": "Ограничение скорости",
    "vehicle_setting_item_drive_mode": "Режим вождения",
    "vehicle_setting_item_drive_mode_normal": "Комфорт",
    "vehicle_setting_item_drive_mode_normal_tips": "Мягкое и плавное ускорение и замедление",
    "vehicle_setting_item_drive_mode_off_road": "Бездорожье",
    "vehicle_setting_item_drive_mode_off_road_tips": "Высокий уровень жесткости педалей для резкого ускорения, подъема на холмы и езды по бездорожью",
    "vehicle_setting_item_pedestrian_mode_limit_speed": "Макс. Скорость (пешеходный режим)",
    "vehicle_setting_item_pedal_sensitivity": "Жесткость педали",
    "vehicle_setting_item_spilt_mode": "Регулируемый режим",
    "vehicle_setting_item_spilt_mode_speeding": "Ускорение",
    "vehicle_setting_item_spilt_mode_breaking": "Торможение",
    "vehicle_setting_item_power_assist": "Усилитель мощности",
    "vehicle_setting_item_acc_assist": "Помощь в ускорении",
    "vehicle_setting_item_brake_assist": "Помощь в торможении",
    "vehicle_setting_item_cruise": "Круиз",
    "vehicle_setting_item_ride_assist": "Помощь при езде",
    "vehicle_setting_item_zero_start": "Нулевой старт",
    "vehicle_setting_item_assist_balance": "Помощник выравнивания",
    "vehicle_setting_item_load_detect": "Обнаружение нагрузки",
    "vehicle_setting_item_noload_detect": "Обнаружение холостого хода",
    "vehicle_setting_item_up_hill_assist": "Помощь на подъеме",
    "vehicle_setting_item_down_hill_assist": "Помощь на спуске",
    "vehicle_setting_item_overspeed_alarm": "Сигнализация скорости",
    "vehicle_setting_item_lock": "Блокировка",
    "vehicle_setting_item_password": "Пароль",
    "vehicle_setting_item_diagnosis": "Диагностика",
    "vehicle_setting_item_headlight": "Фара",
    "vehicle_setting_item_headlight_brightness": "Яркость фар",
    "vehicle_setting_item_drl": "DRL",
    "vehicle_setting_item_low_beam_headlight": "Фары ближнего света",
    "vehicle_setting_item_low_beam_headlight_brightness": "Яркость фар ближнего света",
    "vehicle_setting_item_high_beam_headlight": "Фара дальнего света",
    "vehicle_setting_item_high_beam_headlight_brightness": "Яркость фар дальнего света",
    "vehicle_setting_item_auto_headlight": "Автофара",
    "vehicle_setting_item_auto_headlight_brightness_threshold": "Порог автоматического включения фар",
    "vehicle_setting_item_auto_low_high_beam": "Автоматический ближний и дальний свет фар",
    "vehicle_setting_item_auto_low_high_beam_switch_speed_threshold": "Порог скорости переключения автоматического ближнего и дальнего света фар",
    "vehicle_setting_item_light_effect": "Световой эффект",
    "vehicle_setting_item_light_effect_mode": "Режим светового эффекта",
    "vehicle_setting_item_light_effect_front": "Режим эффекта переднего света",
    "vehicle_setting_item_light_effect_rear": "Режим эффекта заднего света",
    "vehicle_setting_item_light_diy": "DIY",
    "vehicle_setting_item_auto_turn_signal": "Поворотники",
    "vehicle_setting_item_audio_state": "Аудио",
    "vehicle_setting_item_volume": "Громкость",
    "vehicle_setting_item_audio_package": "Аудиопакет",
    "vehicle_setting_item_standby_time": "Режим ожидания",
    "vehicle_setting_item_spin_kill_btn": "Spin-Kill",
    "vehicle_setting_item_sound_wave": "Звуковая волна",
    "vehicle_setting_item_sound_wave_sensitivity": "Чувствительность звуковой волны",
    "vehicle_setting_item_estimated_remainder_range": "Оценка остатка пробега",
    "vehicle_setting_item_user_info": "Информация об устройстве",
    "vehicle_setting_item_fan_quiet_mode": "Тихий режим вентилятора охлаждения",
    "vehicle_setting_item_forced_fan": "Принудительное воздушное охлаждение",
    "vehicle_setting_item_transport_mode": "Транспортный режим",
    "vehicle_setting_item_low_battery_safe_mode": "Безопасный режим низкого заряда батареи",
    "vehicle_setting_item_auto_screen_off": "Автоотключение экрана",
    "vehicle_setting_item_speed_unit": "Метрические/имперские единицы",
    "vehicle_setting_item_sn": "SN",
    "vehicle_setting_item_activate_date": "Дата активации",
    "vehicle_setting_item_total_mileage": "Общий пробег",
    "vehicle_setting_item_hmic_board_version": "Плата HMIC",
    "vehicle_setting_item_bt_board_version": "Плата BT",
    "vehicle_setting_item_driver_board_version": "Контроллер",
    "vehicle_setting_item_driver_board_temp": "Температура контроллера",
    "vehicle_setting_item_riding_mode": "Режим езды",
    "vehicle_setting_riding_mode_eco": "ЭКО",
    "vehicle_setting_riding_mode_eco_tips": "Рекомендовано новичку, плавный разгон.",
    "vehicle_setting_riding_mode_normal": "D",
    "vehicle_setting_riding_mode_sport": "S",
    "vehicle_setting_riding_mode_sport_tips": "Рекомендовано профессиональным гонщикам, более отзывчивая мощность",
    "vehicle_setting_riding_pedestrian_mode": "Режим пешехода",
    "vehicle_setting_riding_pedestrian_mode_tips": "Легче толкать устройство.",
    "vehicle_setting_item_riding_mode_euc_normal": "Нормальный",
    "vehicle_setting_item_riding_mode_euc_normal_tips": "Более безопасно, подходит для большинства пользователей.",
    "vehicle_setting_item_riding_mode_euc_fancier": "Продвинутый",
    "vehicle_setting_item_riding_mode_euc_fancier_tips": "Более высокая выходная мощность и более высокая максимальная скорость",
    "prompt_cannt_set_sport_mode_when_limit_speed_25kmph_enabled": "Нельзя переключиться в режим 'S' когда включено 'Ограничение скорости на 25 км/ч'",
    "prompt_cannt_enable_limit_speed_25kmph_when_sport_mode_enabled": "Нельзя включить фиксацию скорости на скорости 25 км/ч в режиме S.",
    "vehicle_setting_item_berm_angle_mode": "Режим угла наклона бермы",
    "prompt_unlock_factory_safe_speed_limit": "В целях вашей безопасности ограничение максимальной скорости может быть увеличено только до 90 км/ч, когда ваш общий пробег превышает 30 км. %s",
    "prompt_unlock_factory_safe_speed_limit_not_now":
    "В целях вашей безопасности ограничение максимальной скорости может быть увеличено до 90 км/ч только в том случае, если ваш общий пробег превышает 30 км. Вам все еще нужно продолжать кататься в течение %s".,
	"prompt_unlock_now": "Разблокировать>>",

    "warning_unlock_v13_factory_speed_limit":
    "Ваша безопасность - наш главный приоритет. Чтобы лучше защитить ваши личные права и интересы, пожалуйста, поймите и внимательно прочитайте это Заявление, чтобы убедиться, что вы полностью понимаете содержание этого заявления.\n\n1. Вы признаете и понимаете, что в данный момент пытаетесь разблокировать ограничение максимальной скорости колеса. После снятия этого ограничения вы сможете установить ограничение максимальной скорости до 90 км/ч.\n2. Вы понимаете и осведомлены о рисках, связанных с ездой на сверхвысокой скорости, и несете ответственность за любые потери или повреждения и риски, вызванные высокой скоростью.\n3. Вы обязаны быть осведомлены обо всех законах и подзаконных актах, касающихся езды на маоноколеах в вашем регионе, и строго соблюдать применимые законы, нормативные акты и политику при езде на V13. Не ездите на V13 в местах, запрещенных местным законодательством.\n4. Пожалуйста, не допускайте к управлению вашим моноциклом никого, кто не прочитал внимательно инструкции или не знаком с мерами предосторожности при езде V13.\n5. Перед каждой поездкой, пожалуйста, обязательно проверяйте, находятся ли продукты и аксессуары в хорошем состоянии, избегайте использования неоригинальных батареек и аксессуаров и не разбирайте, не взламывайте и не модифицируйте продукты и аксессуары без разрешения. Вы несете ответственность за любую потерю или повреждение и риск, вызванные неправильной эксплуатацией.\n\N Пожалуйста, внимательно прочитайте и выберите, принимать или не принимать это заявление. Вы не сможете разблокировать ограничение максимальной скорости, пока не согласитесь с этим заявлением. Ваше "Согласен"будет рассматриваться как принятие данного заявления об отказе от ответственности. Если у вас есть какие-либо вопросы по поводу этого заявления об отказе от ответственности, пожалуйста, нажмите "Отменить"",
    "warning_enable_berm_angle_mode": "Когда этот режим включен, угол защиты от опрокидывания транспортного средства становится больше, что означает, что транспортное средство может раскачиваться вперед и назад и легко терять управление из-за небольших изменений угла балансировки, когда оно расположено боком. Это может нанести вред вам или окружающим. Вы уже знаете обо всех возможных рисках, вы уверены, что хотите включить это?",
    "warning_disable_berm_angle_mode": "Для активации нажмите кнопку Spin-Kill после включения/выключения режима. ",

    "title_vehicle_balance_angle": "Угол баланса",
    "title_vehicle_calibration": "Калибровка моноколеса",
    "title_vehicle_balance_angle_calibration": "Калибровка баланса",
    "prompt_vehicle_balance_angle_calibration_desc": "Если моноколесо все еще наклоняется назад или вперед на земле после того, как вы установили угол балансировки равным нулю, то вы можете попробовать эту калибровку, чтобы исправить это. %s",
    "prompt_vehicle_balance_angle_calibration": "Пожалуйста, нажмите и удерживайте кнопку Spin-Kill, чтобы вертикальное направление моноколеса всегда было перпендикулярно горизонтальной поверхности земли",
    "title_vehicle_turning_calibration": "Калибровка поворота",
    "title_vehicle_turning_calibration_desc": "Это может улучшить опыт поворота. %s",
    "text_view_calibration_guide": "Посмотреть руководство>>",
    "title_motor_self_adjustment": "Самонастройка двигателя",
    "prompt_motor_self_adjustment_desc": "После запуска двигатель автоматически будет работать в течение 1 минуты. В целях вашей безопасности, пожалуйста, убедитесь, что ТС находится в опрокинутом состоянии, и не прикасайтесь к колесам!",
    "prompt_clear_motor_self_adjustment_effect_desc": "Рекомендуется %s, если ощущения от езды не улучшились",
    "title_clear_motor_self_adjustment_effect": "Очистить показатели самонастройки двигателя",
    "prompt_motor_self_adjustment_in_progress": "Выполняется самонастройка...",
    "prompt_motor_self_adjustment_terminated": "Самонастройка прекращена",
    "prompt_motor_self_adjustment_succeed": "Самонастройка выполнена",
    "prompt_motor_self_adjustment_finished": "Самонастройка завершена",
    "prompt_motor_self_adjustment_timeout": "Тайм-аут самонастройки",
    "prompt_confirm_to_clear_motor_self_adjustment_effect": "Подтверждаете ли вы очистку показателей самонастройки двигателя?",

    "prompt_motor_self_check_in_progress": "Проводится самообследование...",
    "prompt_motor_self_check_terminated": "Самообследование прекращено",
    "prompt_motor_self_check_passed": "Самообследование пройдено",
    "prompt_motor_self_check_not_passed": "Самообследование НЕ пройдено",
    "prompt_motor_self_check_timeout": "Тайм-аут самообследования",
    "prompt_motor_self_check_failed": "Не удалось запустить самообследование",

    "title_vehicle_acc_calibration": "Калибровка дроссельной заслонки",
    "title_vehicle_brake_calibration": "Калибровка тормозов",
    "title_vehicle_gyro_calibration": "Калибровка гироскопа",
    "prompt_vehicle_acc_calibration_tips": "После начала калибровки удерживайте ручку газа на максимальном и минимальном значениях в течение 1 секунды. Убедитесь, что указанная операция калибровки выполнена в течение 5 секунд.",
    "prompt_vehicle_brake_calibration_tips": "После начала калибровки удерживайте ручку тормоза на максимальном и минимальном значениях в течение 1 секунды. Убедитесь, что указанная операция калибровки выполнена в течение 5 секунд.",
    "prompt_vehicle_gyro_calibration_tips": "Пожалуйста, выпрямите скутер, чтобы подножка была параллельна земле, затем запустите калибровку до ее завершения",
    "prompt_cannt_start_vehicle_acc_calibration_when_zero_start_enabled": "Вы не могли начать калибровку ручки дроссельной заслонки, когда включен режим Zero Start!",

    "prompt_calibration_succeed": "Калибровка удалась",
    "prompt_calibration_failed": "Калибровка не удалась",
    "prompt_calibration_timeout": "Тайм-аут калибровки",

    "title_vehicle_factory_reset": "Сброс к заводским настройкам",
    "prompt_vehicle_confirm_to_factory_reset": "Вы подтверждаете сброс к заводским настройкам?",
    "prompt_vehicle_confirm_to_factory_reset_desc": "Восстановите все настройки и аудиопакет к заводским настройкам по умолчанию",
    "prompt_vehicle_ezcan_confirm_to_factory_reset_desc": "Сброс к заводским настройкам может занять несколько минут, пожалуйста, не выходите из приложения.",
    "prompt_vehicle_ezcan_factory_reset_succeed": "Сброс к заводским настройкам выполнен успешно, пожалуйста, выключите питание и подождите 10 секунд, затем включите.",
    "prompt_vehicle_factory_reset_succeed": "Сброс к заводским настройкам выполнен успешно!",

    "prompt_vehicle_euc_need_motor_free": "Пожалуйста, поставьте EUC на подставки для ног или положите его на бок",

    "title_vehicle_firmware_update": "Обновление встроенного ПО",

    /// EBike Assist
    "title_vehicle_assistant_mode": "Режим помощи",
    "text_vehicle_assistant_mode_none": "Нет",
    "prompt_vehicle_assistant_mode_none_desc": "В этом режиме отключается система помощи при движении, вы можете двигаться вперед только на велосипеде",
    "text_vehicle_assistant_mode_medium": "Ограничено",
    "prompt_vehicle_assistant_mode_medium_desc": "Этот режим имеет ограниченную помощь, что подходит для езды по ровной дороге",
    "text_vehicle_assistant_mode_max": "Максимум",
    "prompt_vehicle_assistant_mode_max_desc": "Этот режим усиливает поддержку мощности, подходит для частых подъемов и спусков.. Этот режим будет быстрее расходовать заряд батареи",

    /// L8 Light Effect
    "text_light_effect_mode_0": "Режим 1",
    "text_light_effect_mode_1": "Режим 2",
    "text_light_effect_mode_2": "Режим 3",
    "text_light_effect_mode_3": "Режим 4",
    "text_light_effect_mode_4": "Режим 5",
    "text_light_effect_mode_5": "Режим 6",
    "text_light_effect_mode_6": "Режим 7",
    "text_light_effect_mode_7": "Режим 8",
    "title_light_effect_color": "Режим 9",

    /// V12 Light Effect
    "text_light_effect_mode_close": "Отключить",
    "text_light_effect_mode_audio_package": "Персональный",
    "text_light_effect_mode_audio_package_change": "Изменить световой эффекта",
    "text_light_effect_mode_follow_music": "Следить за музыкой",
    "text_light_effect_mode_follow_speed": "Следить за скоростью",
    "text_light_effect_mode_follow_speed_1": "Водный поток",
    "text_light_effect_mode_follow_speed_2": "Всегда включен",

    /// Diagnosis
    "title_vehicle_diagnosis": "Диагностика",
    "prompt_vehicle_diagnosis_result": "Результат диагностики",
    "prompt_vehicle_diagnosis_ok": "Известных ошибок и предупреждений не обнаружено",
    "prompt_vehicle_diagnosis_abnormal": "Ваше ТС находится в ненормальном состоянии",
    "title_vehicle_diagnosis_history": "История диагностики",
    "title_view_history": "Просмотр истории",
    "title_vehicle_upload_log": "Журнал загрузки",
    "prompt_upload_log_tips": "Загрузка журнала может занять несколько минут, пожалуйста, будьте терпеливы",

    /// Remote Diagnosis
    "title_remote_diagnosis": "Дистанционная диагностика",
    "prompt_remote_diagnosis_tips": "Пожалуйста, используйте эту функцию под руководством команды INMOTION",
    "prompt_remote_diagnosis_enter_failed": "Не удалось войти в удаленную диагностику!",
    "prompt_remote_diagnosis_remote_disconnected": "Удаленное устройство отключено!",
    "prompt_remote_diagnosis_disconnected": "Удаленная диагностика отключена!",
    "prompt_remote_diagnosis_waiting_remote_connection": "В настоящее время вы находитесь в режиме онлайн-диагностики! Пожалуйста, ожидайте удаленного доступа к устройству.",
    "prompt_remote_diagnosis_confirm_to_cancel": "В настоящее время вы ожидаете доступа к удаленному устройству, вы уверены, что хотите выйти?",
    "prompt_remote_diagnosis_waiting_remote_timeout": "Доступ не удался, ожидание доступа к удаленному устройству закончилось",
    "prompt_remote_diagnosis_in_progress": "Проводится онлайн-диагностика. Убедитесь, что ваш мобильный телефон находится рядом с ТС и сеть активна. Пожалуйста, не выключайте экран мобильного телефона",

    "prompt_upload_log_success": "Журнал загружен успешно!",
    "prompt_upload_log_failed": "Загрузка журнала не удалась!",

    /// Firmware update
    "text_vehicle_current_firmware_version": "Текущая версия: %s"
    "title_vehicle_current_firmware_version": "Текущая версия",
    "prompt_new_firmware_version_found": "Найдена новая прошивка",
    "prompt_cannt_interrupt_firmware_updating": "Пожалуйста, продолжите обновление",
    "prompt_no_new_firmware_version_found": "Новая прошивка не найдена",
    "btn_update_firmware": "Обновить сейчас",
    "title_firmware_update_notes": "Уведомление",
    "text_firmware_update_notes_1": "· Перед обновлением убедитесь, что оставшийся заряд батареи не менее 20%",
    "text_firmware_update_notes_2": "· Не управляйте ТС во время обновления",
    "text_firmware_update_notes_3": "· Если обновление не удалось, попробуйте выйти из приложения и снова выполнить обновление",
    "prompt_contact_us": "Свяжитесь с нами",
    "prompt_firmware_update_learn_more_notes": "Подробнее>>",
    "title_new_firmware_version_summary": "Рекомендации",
    "text_new_firmware_version_learn_more": "Подробнее>>",
    "prompt_firmware_update_success": "Обновление успешно",
    "prompt_firmware_update_failed": "Не удалось обновить!",
    "prompt_last_firmware_update_interrupted": "Последнее обновление прошивки могло быть прервано, пожалуйста, продолжите завершение обновления, чтобы исправить ситуацию.",
    "prompt_forced_firmware_update_tips": "> Вам необходимо обновить прошивку ТС до последней версии, прежде чем его можно будет использовать в обычном режиме",
    "prompt_firmware_update_le1_manually_process_tips": "После того, как дисплей ТС выключится, подождите 3 секунды и включите его вручную. Затем нажмите 'Подтвердить', чтобы продолжить обновление",
    "prompt_firmware_updating": "Обновление %s",
    "prompt_firmware_update_waiting_device": "Ожидание обновления устройства",

    "title_device_name_unknown": "Неизвестный",
    "title_device_name_hmic_board": "Плата HMIC",
    "title_device_name_driver_board": "Контроллер",
    "title_device_name_bt_board": "Плата BT",
    "title_device_name_display_board": "Табло",
    "title_device_name_bms_1": "BMS	1",
    "title_device_name_bms_2": "BMS 2",

    /// Driver board failure
    "title_vehicle_diagnosis_module_driver_board": "Контроллер",
    "vehicle_error_parse_current_sensor": "Датчик фазного тока неисправен, возможно, потребуется заменить контроллер.",
    "vehicle_error_bus_current_sensor": "Неисправен датчик тока шины, возможно, вам потребуется заменить контроллер.",
    "vehicle_error_imu_sensor": "Сбой датчика IMU, возможно, вам потребуется заменить контроллер.",
    "vehicle_error_mos_temp_sensor": "Сбой датчика температуры MOS, возможно, вам потребуется заменить контроллер.",
    "vehicle_error_bus_voltage_sensor": "Вышел из строя датчик основного напряжения, возможно, потребуется заменить контроллер.",
    "vehicle_error_battery_voltage_sensor": "Датчик напряжения аккумулятора неисправен, возможно, вам потребуется заменить контроллер.",
    "vehicle_error_board_high_temp_area_sensor": "Сбой датчика температуры высокотемпературной зоны, возможно, вам потребуется заменить контроллер.",
    "vehicle_error_current_sampling": "Ошибка исходных данных текущей выборки, возможно, вам потребуется заменить контроллер.",
    "vehicle_error_sensor": "Ошибка выхода датчика, возможно, вам потребуется заменить контроллер.",
    "vehicle_error_rtc": "Ошибка RTC, возможно, вам потребуется заменить контроллер.",
    "vehicle_error_spi_flash": "Ошибка внешнего хранилища, возможно, вам потребуется заменить контроллер.",
    "vehicle_error_log": "Системная ошибка журнала.",
    "vehicle_error_external_flash": "Внешний накопитель неисправен, возможно, вам потребуется заменить плату HMIC.",
    "vehicle_error_euc_driver_board_communication": "Сбой связи контроллера, возможно, вам потребуется заменить плату HMIC или контроллер.",
    "vehicle_error_scooter_driver_board_communication": "Сбой связи контроллера, возможно, вам потребуется заменить плату дисплея или контроллер.",
    "vehicle_error_scooter_driver_board_communication_unstable": "Связь контроллера нестабильна, возможно, вам потребуется заменить плату дисплея или контроллер.",
    "vehicle_error_communication": "Сбой связи с контроллером, попробуйте снова включить питание.",
    "vehicle_error_voltage": "Ошибка напряжения.",
    "vehicle_error_driver_board": "Контроллер вышл из строя, возможно, вам потребуется заменить контроллер.",
    "vehicle_error_driver_board_oscillator": "Ошибка кварцевого генератора.",

    "vehicle_warning_over_current": "Предупреждение о перегрузке по току, пожалуйста, езжайте осторожно.",
    "vehicle_warning_over_temp": "Контроллер перегрелся, пожалуйста, прекратите движение на некоторое время.",
    "vehicle_warning_cpu_over_temp": "Процессор контроллера перегрелся, пожалуйста, прекратите движение на некоторое время.",
    "vehicle_warning_imu_over_temp": "IMU перегрелся, пожалуйста, остановитесь на некоторое время.",
    "vehicle_warning_mos_over_temp": "MOS перегрелся, пожалуйста, прекратите езду на некоторое время.",

    /// display board errors and warnings
    "vehicle_error_scooter_imu_sensor": "Сбой датчика IMU, возможно, вам потребуется заменить плату дисплея.",

    /// hmic board errors and warnings
    "title_vehicle_diagnosis_module_hmic_board": "Плата HMIC",
    "vehicle_error_hmic_board_rtc": "Сбой RTC, возможно, вам потребуется заменить материнскую плату.",
    "vehicle_error_hmic_board_flash": "Внешний накопитель неисправен, возможно, вам потребуется заменить основную плату.",

    /// bt board errors and warnings
    "title_vehicle_diagnosis_module_bt_board": "Плата BT",
    "vehicle_error_bt_board_communication": "Сбой соединения Bluetooth, возможно, вам потребуется заменить основную плату или плату Bluetooth.",

    /// motor errors and warnings
    "title_vehicle_diagnosis_module_motor": "Мотор",
    "vehicle_error_motor_hall": "Моторный зал неисправен, возможно, вам потребуется заменить двигатель.",
    "vehicle_error_motor_hall_left": "Мотор левого зала вышел из строя, возможно, вам нужно заменить мотор.",
    "vehicle_error_motor_hall_right": "Правый двигатель вышел из строя, возможно, вам нужно заменить двигатель.",
    "vehicle_error_front_motor_hall": "Вышел из строя передний моторный отсек, возможно, вам потребуется заменить мотор.",
    "vehicle_error_rear_motor_hall": "Вышел из строя задний моторный отсек, возможно, вам потребуется заменить мотор.",
    "vehicle_error_motor_temp_sensor": "Неисправен датчик температуры двигателя, возможно, потребуется заменить двигатель.",
    "vehicle_error_motor_phase": "Отсутствует фраза двигателя, возможно, вам потребуется заменить двигатель.",
    "vehicle_warning_motor_over_temp": "Предупреждение о перегреве двигателя, пожалуйста, остановитесь на некоторое время.",
    "vehicle_warning_motor_spin": "Предупреждение о вращении. Не поднимайте EUC, не нажав кнопку остановки вращения.",
    "vehicle_warning_motor_blocked": "Предупреждение о остановке двигателя, пожалуйста, не паркуйтесь на крутых склонах в течение длительного времени.",

    /// battery errors and warnings
    "title_vehicle_diagnosis_module_battery": "Батарея",
    "vehicle_error_battery": "Аккумулятор неисправен, возможно, вам нужно заменить аккумулятор.",
    "vehicle_error_battery_temp_sensor": "Неисправен датчик температуры аккумулятора, возможно, потребуется заменить аккумулятор.",
    "vehicle_error_battery_cannt_power_off": "Не удалось нормально выключить питание, возможно, вам потребуется заменить аккумулятор.",
    "vehicle_error_battery_cannt_charge": "Не удается нормально зарядить, возможно, вам потребуется заменить аккумулятор или зарядное устройство.",
    "vehicle_error_battery_signal": "Ошибка сигнала батареи.",
    "vehicle_warning_low_battery": "Предупреждение о низком заряде батареи. Пожалуйста, подзарядите ее как можно скорее.",
    "vehicle_warning_battery_over_temp": "Аккумулятор перегрелся, пожалуйста, остановитесь на некоторое время.",
    "vehicle_warning_battery_calibration": "Предупреждение о ненормальной калибровке напряжения батареи. Пожалуйста, %s.",
    "text_calibrate_battery": "откалибровать напряжение батареи",
    "vehicle_warning_some_batteries_not_enabled": "Предупреждение от некоторых батарей, которые не работают. Это повлияет на эксплуатационные характеристики транспортного средства. Пожалуйста, езжайте осторожно.",
    "vehicle_warning_danger_charge1_dual_charger": "Предупреждение: Напряжения левого и правого аккумуляторных блоков различны, неправильная зарядка может вызвать проблемы с безопасностью. Что вам следует делать: ① Используйте только одно оригинальное зарядное устройство для зарядки колеса, два зарядных устройства для зарядки колеса одновременно не допускаются ② Поместите колесо в пределах видимости, не оставляйте колесо в покое, внимательно наблюдайте за процессом зарядки. %s"
    "vehicle_warning_danger_charge1_single_charger": "Предупреждение: Напряжения левого и правого аккумуляторных блоков различны, неправильная зарядка может вызвать проблемы с безопасностью. Что вам следует сделать: Поместите колесо в пределах видимости, не оставляйте колесо в покое, внимательно наблюдайте за процессом зарядки. %s"
    "vehicle_warning_danger_charge2": "Опасность! Прекратите заряжать ТС! Ошибка батареи, пожалуйста, немедленно прекратите зарядку и извлеките зарядное устройство, положите колесо в безопасное место. Пожалуйста, загрузите журнал автомобиля (Настройки ТС - Диагностика- Загрузить журнал), обратитесь к своему дилеру за обслуживанием. %s",
    "btn_i_know_danger_charge_risk_and_turn_off_alert": "Я знаю об этом риске и отключу это предупреждение",
    "vehicle_warning_battery_over_voltage": "Высокое напряжение аккумулятора, возможно, потребуется заменить аккумулятор или зарядное устройство.",
    "vehicle_warning_battery_output_abnormal": "Батарея не имеет выходной мощности, попробуйте перезарядить ее, или вам может потребоваться заменить батарею.",
    "vehicle_warning_too_low_battery": "Предупреждение о слишком низком напряжении, перезарядите аккумулятор как можно скорее, чтобы не повредить аккумулятор.",

    /// Fan
    "title_vehicle_diagnosis_module_fan": "Вентилятор",
    "vehicle_error_fan": "Вентилятор охлаждения неисправен, возможно, вам потребуется заменить вентилятор охлаждения.",
    "vehicle_warning_fan_low_speed": "Скорость вращения вентилятора низкая. Это повлияет на максимальный уровень яркости. Пожалуйста, проверьте, не заблокирован ли вентилятор.",

    /// vehicle errors and warnings
    "title_vehicle_diagnosis_module_vehicle": "Транспортное средство",
    "vehicle_error_brake_handle": "Неисправность тормозного руля, пожалуйста, проверьте, разблокирован ли тормозной руль или нет.",
    "vehicle_error_acc_handle": "Неисправность дроссельной заслонки, пожалуйста, проверьте, освободилась ли ручка дроссельной заслонки или нет.",

    "vehicle_warning_lock_caused_by_safe_issue": "Транспортное средство было временно заблокировано из-за скрытой опасности, связанной с безопасностью.",
    "vehicle_warning_over_speed": "Предупреждение о превышении скорости. Пожалуйста, помедленнее.",
    "vehicle_warning_fall_down": "Предупреждение о падении. Пожалуйста, ездите осторожно.",
    "vehicle_warning_risk_behavior": "Предупреждение по опасному вождению, пожалуйста, не водите чрезмерно.",
    "vehicle_warning_software_incompatible": "Предупреждение о несовместимости прошивки на некоторых частях, пожалуйста, обновите последнюю версию прошивки.",
    "vehicle_warning_motor_no_load_protection": "Предупреждение защиты двигателя от холостого хода, перед подъемом рекомендуется нажать кнопку Spin-kill и убедиться, что транспортное средство неподвижно.",
    "vehicle_warning_power_key_long_pressed": "Предупреждение при длительном нажатии кнопки питания, длительное нажатие кнопки питания может вызвать принудительное отключение питания. Пожалуйста, прекратите ездить!",
    "vehicle_warning_necessary_self_check_not_passed": "Необходимый элемент самопроверки не прошел или не прошел предупреждение, %s.",
    "text_execute_self_check": "выполнить самопроверку",
    "vehicle_warning_function_limited_by_uncompleted_fw_update": "Функции транспортного средства ограничены, и необходимо обновить прошивку, прежде чем его можно будет использовать в обычном режиме.",
    "vehicle_warning_remote_locked": "ТС было заблокировано, пожалуйста, свяжитесь с нами, чтобы подтвердить вашу личность, чтобы разблокировать.",
    "vehicle_warning_hardware_incompatible": "Предупреждение о аппаратной несовместимости некоторых деталей, основная плата и контроллер должны быть заменены в полном комплекте.",
    "vehicle_warning_over_power": "Превышение макс. мощности.",

    /// BMS Error
    "bms_error_voltage_sample": "Ошибка выборки напряжения.",
    "bms_error_charge_current_sample": "Ошибка выборки тока заряда.",
    "bms_error_discharge_current_sample": "Ошибка выборки тока разряда.",
    "bms_error_temperature_sensor": "Ошибка датчика температуры.",
    "bms_error_rh_sensor": "Ошибка датчика относительной влажности.",
    "bms_error_charge_mosfet": "Ошибка заряда MOS.",
    "bms_error_discharge_mosfet": "Ошибка сброса MOS.",
    "bms_error_afe": "Ошибка Afe.",
    "bms_error_cell": "Ошибка ячейки.",
    "bms_error_mcu": "Ошибка MCU.",

    /// BMS Warning
    "bms_warning_low_soc": "Предупреждение о низком уровне soc.",
    "bms_warning_pack_over_charge": "Предупреждение о чрезмерном заряде аккумуляторной батареи.",
    "bms_warning_pack_over_discharge": "Предупреждение о чрезмерном разряде аккумуляторной батареи.",
    "bms_warning_cell_over_charge": "Предупреждение о чрезмерном заряде ячейки АКБ.",
    "bms_warning_cell_over_discharge": "Предупреждение о чрезмерном разряде ячейки АКБ",
    "bms_warning_charge_over_current": "Предупреждение о превышении текущего заряда АКБ.",
    "bms_warning_charge_mosfet_over_temperature": "Предупреждение о перегреве зарядки mos.",
    "bms_warning_charge_cell_over_temperature": "Предупреждение о превышении температуры заряда аккумуляторной батареи.",
    "bms_warning_charge_cell_low_temperature": "Предупреждение о низкой температуре заряда аккумуляторной батареи.",
    "bms_warning_discharge_over_current": "Предупреждение о превышении тока разряда.",
    "bms_warning_discharge_mosfet_over_temperature": "Предупреждение о превышении температуры разряда mos.",
    "bms_warning_discharge_cell_over_temperature": "Предупреждение о превышении температуры разряда ячейки АКБ.",
    "bms_warning_discharge_cell_low_temperature": "Предупреждение о низкой температуре разряда ячеек АКБ.",
    "bms_warning_over_humidity": "Предупреждение о повышенной влажности.",

    /// BMS Protection
    "bms_protection_short_circuit": "Защита от короткого замыкания.",
    "bms_protection_pack_over_charge": "Защита аккумуляторной батареи от перезарядки.",
    "bms_protection_pack_over_discharge": "Защита аккумуляторной батареи от чрезмерного разряда.",
    "bms_protection_cell_over_charge": "Защита ячейки АКБ от перезаряда.",
    "bms_protection_cell_over_discharge": "Защита ячейки АКБ от чрезмерного разряда.",
    "bms_protection_charge_over_current": "Защита от перегрузки по току.",
    "bms_protection_charge_mosfet_over_temperature": "Защита от перегрева зарядного устройства mos.",
    "bms_protection_charge_cell_over_temperature": "Защита от перегрева заряда ячейки АКБ.",
    "bms_protection_charge_cell_low_temperature": "Защита от заряда ячейки АКБ при низкой температуре.",
    "bms_protection_discharge_over_current": "Защита от перегрузки по току при разрядке.",
    "bms_protection_discharge_mosfet_over_temperature": "Защита от перегрева при разряде MOS.",
    "bms_protection_discharge_cell_over_temperature": "Защита от разряда ячейки АКБ при превышении температуры.",
    "bms_protection_discharge_cell_low_temperature": "Защита от разряда ячейки АКБ при низкой температуре.",
    "bms_protection_over_humidity": "Защита от превышения температуры влажности",
    "bms_protection_associated_charge": "Защита от связанного заряда.",
    "bms_protection_associated_discharge": "Защита от сопутствующих разрядов.",

    /// light effect
    'title_light_effect_preview': 'Предварительный просмотр светового эффекта',
    'title_complete_light_effect_info': 'Пожалуйста, заполните информацию о световом эффекте',
    'prompt_input_light_effect_name': 'Пожалуйста, введите название светового эффекта',
    'prompt_invalid_light_effect_info': 'Недопустимая информация о световом эффекте',
    'text_light_effect_frame_interval': 'Интервал между кадрами',
    'title_light_effect_my_colors': 'Мои цвета',
    'text_light_effect_frame_keyframe': 'Ключевой кадр',
    'text_light_effect_frame_total': 'Всего кадров',
    'text_light_effect_frame_number': '%s кадр',
    'text_light_effect_frame': '%s кадр',
    'text_light_effect_frame_mode_normal': 'Баланс',
    'text_light_effect_frame_mode_fast': 'Быстрее',
    'text_light_effect_frame_mode_slow': 'Медленнее',
    'title_light_effect_edit': 'Редактировать световой эффект',
    'prompt_light_effect_edit_back_tips': 'Выход не сохранит отредактированные световые эффекты',
    'prompt_light_effect_edit_gradient_mode_1': 'Отпустите, чтобы установить ключевой кадр, или продолжайте перетаскивать, чтобы отменить',
    'prompt_light_effect_edit_gradient_mode_2': 'В настоящее время в режиме внутрикадрового градиента, пожалуйста, продолжайте выбирать конечную точку градиента или %s',
    'prompt_light_effect_edit_gradient_mode_3': 'В данный момент в режиме внутрикадрового градиента вы выбираете конечную точку градиента, отпустите ее, чтобы выйти из этого режима',
    'prompt_light_effect_edit_gradient_mode_4': 'В настоящее время в режиме внутрикадрового градиента вы выбираете конечную точку градиента, вы также можете сдвинуть здесь, чтобы выйти из режима',
    'text_light_effect_exit_edit_gradient_mode': 'выйти из этого режима',
    'prompt_light_effect_edit_already_first_step': "Это уже первый шаг!",
    'prompt_light_effect_edit_already_last_step': "Это уже последний шаг!",
    'prompt_light_effect_drag_to_delete': 'Перетащите сюда, чтобы удалить',
    'prompt_light_effect_release_to_delete': 'Отпустить, чтобы удалить',
    "title_vehicle_light_effect_exists": "Световой эффект в транспортном средстве",
    "text_light_effect_default_package": "Световой эффект по умолчанию",
    "text_light_effect_unknown_package": "Неизвестный световой эффект",
    "prompt_enable_light_effect_failed": "Не удалось включить световой эффект",
    'prompt_confirm_to_delete_light_effect': 'Вы подтверждаете удаление?',
    'prompt_confirm_to_delete_diy_light_effect': "Световой эффект DIY не получиться восстановить после удаления, подтверждаете ли вы удаление %s?",

    /// sound pack
    "title_vehicle_sound_pack": "Звуковой пакет",
    "title_vehicle_sound_pack_exists": "Звуковой пакет в транспортном средстве",
    "text_default_sound_pack": "Звуковой пакет по умолчанию",
    "text_unknown_sound_pack": "Неизвестный звуковой пакет",
    "prompt_input_sound_pack_name": "Пожалуйста, введите название звукового пакета",
    "prompt_select_sound_pack_cover": "Пожалуйста, выберите обложку",
    "title_diy_single_sound_pack_item": "DIY звук",
    "title_diy_sound_pack": "DIY звуковой пакет",
    'prompt_confirm_to_use_default_sound_pack': 'Подтверждаете ли вы восстановление заводских настроек звукового пакета по умолчанию?',
    "prompt_select_from_local_file": "Выбрать локальный файл",
    "prompt_vehicle_transferring_file": "Пожалуйста, держите транспортное средство неподвижным и не управляйте транспортным средством во время передачи файла.",
    "prompt_enable_sound_pack_success": "Успешно",
    "prompt_enable_sound_pack_failed": "Не удалось включить звуковой пакет.",
    "prompt_vehicle_storage_capacity_not_enough": "Недостаточно места для хранения на транспортном средстве.",
    "prompt_sound_pack_composing": "Составление...",
    "prompt_sound_pack_item_file_is_too_large": "Звуковой файл слишком большой",
    "title_custom_sound_pack": "DIY звуковой пакет",
    "title_complete_sound_pack_info": "Полная информация о звуковом пакете",
    "btn_compose": "Составь",
    "title_sound_pack_compose": "Составить звуковой пакет",
    "prompt_sound_pack_compose_succeed": "Сочини успешно",
    "prompt_sound_pack_compose_failed": "Не удалось составить звуковой пакет",
    "title_sound_pack_audition": "Прослушивание",
    "title_select_sound_pack_item": "Выбрать звук",
    'prompt_confirm_to_delete_sound_pack': 'Вы подтверждаете удаление?',
    'prompt_confirm_to_delete_sound_pack_in_vehicle': "Звуковой пакет в транспортном средстве не может быть восстановлен после удаления. Вы подтверждаете удаление '%s'?",
    'prompt_confirm_to_delete_diy_sound_pack': "Звуковой пакет DIY не может быть восстановлен после удаления, подтверждаете ли вы удаление  '%s'?",
    'text_sound_pack_file_local': 'Локальный',
    'text_sound_pack_file_record': 'Локальный',
    'text_sound_pack_file_library': 'Звуковая библиотека',
    'text_sound_pack_item_duration': 'Продолжительность'
    'text_sound_pack_item_size': 'Размер'
    'prompt_sound_pack_compose_item_cannt_be_empty': "Все элементы не могут быть пустыми",
    'title_sound_pack_diy_create_from_template': 'Создать из шаблона',
    'title_sound_pack_diy_create_directly': 'Создать напрямую',
    'title_sound_pack_diy_select_template': 'Выберите шаблон',
    "title_sound_pack_audition_on_phone": "Прослушивание по телефону",
    "title_sound_pack_audition_on_vehicle": "Прослушивание на транспортном средстве",

    ///
    /// Mine
    ///
    'btn_authorized_vehicles': 'Мои ТС',
    'btn_vehicle_authorization': 'Авторизация владельца',
    'btn_customer_service': 'Служба поддержки клиентов',
    'title_find_my_vehicle': 'Найди мое ТС',
    'title_unit_metric_imperial': 'Метрические/имперские единицы',
    'text_unit_metric': 'Метрика',
    'text_unit_imperial': 'Империал',
    'title_language': 'Язык',
    'text_follow_system': 'Такой же как в системе',
    'title_select_language': 'Выбрать язык',
    'title_account_security': 'Учетная запись и безопасность',
    'title_clear_cache': 'Очистить кэш',
    'prompt_clear_cache_tips': 'Вы подтверждаете очистку кеша?',
    'title_app_about': 'О компании',
    'text_app_version': '%s',

    'title_message_center': 'Центр сообщений',
    'title_user_info': 'Личная информация',
    'btn_take_a_photo': 'Сделать фото',
    'btn_select_from_album': 'Выбрать из альбома',

    'title_scan_qrcode': 'Сканировать QR-код',

    /// About
    "user_agreement": "Пользовательское Соглашение",
    "privacy_policy": "Политика конфиденциальности",
    'inmotion_company': 'INMOTION',

    /// personal info
    'title_avatar': 'Аватар',
    'title_nickname': 'Псевдоним',
    'title_signature': 'Подпись',
    'title_modify_nickname': 'Изменить псевдоним',
    'title_modify_signature': 'Изменить подпись',
    'prompt_nickname_limit': '6-20 символов',
    'prompt_signature_limit': '0-100 символов',

    /// my vehicle
    'title_my_vehicles': 'Мое ТС',
    'title_delete_authorized_vehicle': 'Удалить авторизацию владельца',
    'prompt_delete_authorized_vehicle_tips': 'Удаление транспортного средства приведет к удалению авторизации владельца транспортного средства. Вы подтверждаете удаление?',
    'title_delete_vice_owner': 'Удалить вице-владельца',
    'prompt_delete_vice_owner_tips': 'Вы подтверждаете удаление вице-владельца?',
    'title_vehicle_details': 'Информация о ТС',
    'title_vehicle_info': 'Информация о ТС',
    'prompt_vehicle_info_updated_at': 'Информация ниже была обновлена : %s'
    'title_vehicle_model': 'Модель',
    'title_activated_date': 'Дата активации',
    'title_total_mileage': 'Общий пробег',
    'title_riding_record': 'Записи поездок',
    "title_bluetooth_name": "Имя BT",
    "text_vehicle_remaining_mileage": "Остаточный пробег: %s",
    'title_vehicle_owner_info': 'Информация о владельце',
    'title_vehicle_main_owner': 'Основной владелец',
    'btn_go_to_authorize_as_owner': 'Перейти к авторизации',
    'prompt_not_owner_and_go_to_authorize_as_owner': 'Это может сделать только владелец текущего транспортного средства, вы хотите авторизоваться как владелец сейчас?',
    'text_vehicle_info_owner_me_suffix': '(Я)',
    'title_vehicle_vice_owner': 'Вице-владелец',
    'title_vehicle_no_owner': 'Никто',
    'title_transfer_vehicle_main_owner': 'Передача основного владельца',
    'prompt_transfer_vehicle_main_owner_tips': 'После передачи пользователь "%s" станет основным владельцем текущего ТС, а вы станете заместителем владельца.\n Вы подтверждаете передачу?',
    'title_invite_as_vehicle_vice_owner': 'Пригласить',
    'prompt_invite_as_vehicle_vice_owner_tips': 'Пожалуйста, используйте приложение INMOTION для сканирования QR-кода, чтобы авторизоваться в качестве вице-владельца.',
    'title_vehicle_authorization': 'Авторизация ТС',
    'prompt_authorize_current_connected_vehicle_tips': 'Транспортное средство %s в настоящее время подключено, вы хотите немедленно пройти аутентификацию в качестве владельца?',
    'prompt_input_sn': 'Пожалуйста, введите SN',
    'title_vehicle_authorization_requests': 'Запрос истории',
    'title_sent_vehicle_authorization_requests': 'Отправил',
    'title_received_vehicle_authorization_requests': 'Полученный',
    'prompt_vehicle_authorization_apply_to': 'Применяется к %s',
    'prompt_vehicle_authorization_apply_from': '%s обратился ко мне',
    'prompt_vehicle_authorization_waiting': 'Ожидающий',
    'text_status_pending': 'В ожидании',
    'text_status_approved': 'Одобрен',
    'text_status_rejected': 'Отклонен',
    'text_status_expired': 'Истек',

    /// vehicle authorization
    'prompt_vehicle_authorization_apply_success': 'Заявка успешно отправлена.',
    'prompt_vehicle_authorization_success': 'Успешно авторизован в качестве основного владельца',
    'prompt_vehicle_authorized_as_vice_owner_tips': 'У этого транспортного средства уже есть основной владелец, вы хотите авторизоваться в качестве заместителя владельца?',
    'prompt_vehicle_authorized_as_vice_owner_success': 'Успешно авторизован в качестве вице-владельца',
    'prompt_vehicle_authorization_failed': 'Авторизация не удалась',

    /// customer service
    'title_message_board': 'Доска объявлений',
    'prompt_leave_message_tips': 'Пожалуйста, оставьте сообщение, мы свяжемся с вами в ближайшее время.',
    'btn_leave_a_message': 'Оставить сообщение',
    'prompt_please_leave_a_message': 'Пожалуйста, оставьте сообщение',
    'btn_chat_menu_picture': 'Картинки',
    'btn_chat_menu_video': 'Видео',
    'prompt_leave_message_success': 'Успешно',
    'prompt_leave_message_failed': 'Оставить сообщение не удалось',
    'prompt_content_couldnt_be_empty': "Содержимое не может быть пустым.",
    'prompt_customer_service_waiting_for_access': 'Ожидание доступа',
    'prompt_customer_service_queue_number': 'В очереди перед вами %s человек',
    'prompt_customer_service_offline': 'Служба поддержки не работает',
    'prompt_customer_service_session_ended': 'Сеанс завершен',
    'btn_customer_service_evaluate': 'Оценивать',
    'prompt_input_question_to_consult': 'Пожалуйста, введите вопрос, который вы хотите проконсультироваться',

    "title_official_recommends": "Рекомендации",

    /// riding record
    "text_riding_record_summary": "Всего сэкономлено %shours, %sKg выбросов углерода.",

    ///
    /// errors
    ///
    'prompt_request_failed': 'Запрос не выполнен',
    'prompt_request_failed_timeout': 'Тайм-аут запроса',
    'prompt_request_failed_network': 'Ошибка сети',

    'prompt_unauthenticated_request': 'Сеанс входа в систему истек, пожалуйста, войдите снова!',
    'prompt_unknown_error': 'Неизвестная ошибка',
    'prompt_operate_too_frequently': 'Операция слишком частая, повторите попытку позже.',
    'prompt_file_download_failed': 'Не удалось загрузить файл',
    'prompt_unknown_product_model': 'Неизвестная модель продукта',
};
