const Map<String, String> uk_UA = {
  ///
  /// Common
  ///
  "title_inmotion": "INMOTION",
  "prompt_welcome_to_inmotion": "Привіт!\nВітаємо в INMOTION!",
  "btn_more": "Більше",
  "btn_view_more": "Переглянути більше",
  "btn_cancel": "Відміна",
  "btn_exit": "Вихід",
  "btn_confirm": "Підтвердити",
  "btn_complete": "Завершити",
  "btn_submit": "Прийняти",
  "btn_i_see": "Зрозуміло",
  "btn_skip": "Пропустити",
  "btn_next_step": "Далі",
  "btn_save": "Зберегти",
  "btn_save_image": "Зберегти зображення",
  "btn_edit": "Редагувати",
  "btn_copy_and_edit": "Скопіювати та редагувати",
  "btn_preview": "Попередній перегляд",
  "btn_rename": "Перейменувати",
  "btn_copy": "Скопіювати",
  "btn_delete": "Видалити",
  "btn_publish": "Опублікувати",
  "tab_vehicle": "Транспортний засіб",
  "tab_moment": "Моменти",
  "tab_discover": "Досліджуй",
  "tab_mine": "Я",
  "prompt_page_error": "Виникла помилка.",
  "btn_share": "Поділитися",
  "btn_report": "Звіт",
  "btn_enable": "Застосувати", //
  "btn_enabled": "Застосовано",
  "btn_go_to_enable": "Перейти до активації", //
  "btn_retry": "Повторити спробу",
  "prompt_title_warning": "УВАГА",
  "prompt_title_tips": "Нагадування",
  "prompt_title_warm_tips": "Примітка",
  "prompt_confirm_to_cancel": "Ви підтверджуєте відміну?",
  "prompt_failed": "Не вдалося",
  "btn_agree": "Підтвердити",
  'btn_reject': 'Відхилити',
  'btn_arrow': 'Дозволити', //
  "btn_need_help": "Потрібна допомога?",
  "btn_common_problem": "FAQ", //
  "page_message_center": "Центр повідомлень",
  "title_sys_message": "Сповіщення",
  "title_social_message": "Соціальне повідомлення", //??
  "btn_save_and_share": "Зберегти та поділитися",
  "prompt_saved": "Збережено",
  "prompt_save_failed": "Не вдалося зберегти",
  "prompt_updated": "Оновлено",
  "prompt_update_failed": "Оновлення не вдалося",
  "prompt_data_empty": "Порожньо.",
  "prompt_loading": "Завантаження...",
  "prompt_load_failed": "Завантаження не вдалося",
  "prompt_copied": "Скопійовано",
  "prompt_action_failed": "Не вдалося",
  "prompt_press_again_to_exit": "Повторіть для виходу.",
  "prompt_description": "Опис", //

  "datetime_just_now": "Щойно",
  "datetime_x_minutes_ago": "%s хв тому",
  "datetime_yesterday_x": "Вчора %s",

  "unknown": "Невідомо",

  "prompt_location_settings_tips":
      'Будь ласка, дозвольте INMOTION отримати доступ до місцезнаходження в налаштуваннях телефону - Додатки - INMOTION - Дозволи, щоб шукати транспортні засоби.',
  "prompt_bluetooth_settings_tips":
      "Будь ласка, дозвольте INMOTION отримати доступ до пристроїв поблизу в налаштуваннях телефону - Додатки - INMOTION - Дозволи, щоб використовувати функції пошуку та з'єднання з транспортними засобами коректно.",
  "prompt_camera_settings_tips":
      'Будь ласка, дозвольте INMOTION отримати доступ до камери в налаштуваннях телефону - Додатки - INMOTION - Дозволи, щоб використовувати функції, такі як зйомка фотографій та сканування QR-кодів.',
  "prompt_microphone_settings_tips":
      'Будь ласка, дозвольте INMOTION отримати доступ до мікрофону в налаштуваннях телефону - Додатки - INMOTION - Дозволи, щоб використовувати функції, такі як створення аудіо.',
  "prompt_storage_settings_tips":
      'Будь ласка, дозвольте INMOTION отримати доступ до файлів та медіа в налаштуваннях телефону - Додатки - INMOTION - Дозволи, щоб використовувати функції, такі як завантаження аватарів та збереження зображень на мобільному телефоні коректно.',

  "prompt_location_settings_desc": 'Для пошуку транспортних засобів INMOTION потребує дозвіл на доступ до місцезнаходження.',
  "prompt_bluetooth_settings_desc": 'Для пошуку та підключення транспортних засобів INMOTION потрібен дозвіл на доступ до пристроїв поблизу.',
  "prompt_camera_settings_desc": 'Для зйомки фотографій та сканування QR-кодів INMOTION потребує дозвіл на доступ до камери.',
  "prompt_microphone_settings_desc": 'Для використання функції створення аудіо INMOTION потребує дозвіл на доступ до мікрофону.',
  "prompt_storage_settings_desc": 'Для завантаження аватарів та збереження зображень на телефоні INMOTION потребує дозволу на доступ до файлів та медіа.',

  ///
  /// Account
  ///

  "prompt_auto_register_if_account_not_exists": "Якщо номер телефону ще не зареєстровано, його буде використано для автоматичного створення облікового запису після перевірки",
  "btn_login": "Увійти",
  "btn_register": "Зареєструватися",
  "title_register": "Реєстрація",
  "title_cn_phone_quick_login": "Швидка перевірка",
  "prompt_input_phone": "Номер телефону",
  "prompt_input_email": "Email-адреса",
  "prompt_input_email_or_username": "Email-адреса / Ім'я облікового запису",
  "prompt_input_verification_code": "Код підтвердження",
  "prompt_input_password": "Пароль",
  "prompt_input_a_valid_phone": "Будь ласка, введіть дійсний номер телефону!",
  "prompt_input_a_valid_email": "Будь ласка, введіть дійсну адресу електронної пошти!",
  "prompt_input_a_valid_email_or_username": "Будь ласка, введіть дійсну адресу електронної пошти або назву облікового запису!",
  "prompt_input_a_valid_password": "Будь ласка, введіть дійсний пароль",
  "btn_forgot_password": "Забули пароль?",
  "btn_reset_password": "Скинути пароль",
  "btn_login_via_password": "Вхід через обліковий запис і пароль",
  "btn_login_via_verification_code": "Увійти за допомогою коду підтвердження",
  "btn_request_verification_code": "Отримати код",
  "btn_request_sms_verification_code": "Отримати код",
  "prompt_verification_code_has_sent_to": "Код підтвердження надіслано на номер %s",
  "btn_resend": " Надіслати повторно",
  "title_user_agreement": "Угодою користувача", //
  "title_privacy_policy": "Політикою конфіденційності", //
  "title_user_agreement_and_privacy_policy": "INMOTION\nУгода користувача та Політика конфіденційності",
  "title_user_agreement_and_privacy_policy_tips":
      "Ми надаємо велике значення захисту Вашої особистої інформації та конфіденційності. Щоб краще захистити свої права, будь ласка, уважно прочитайте та прийміть %s і %s, щоб почати використовувати додаток INMOTION.",
  "prompt_register_agreement_tips": "Реєстрація або вхід означає, що Ви погодилися з \n%s та %s",
  "title_select_country_or_region": "Виберіть країну/регіон",
  "btn_modify_phone": "Змінити номер телефону",
  "btn_modify_email": "Змінити електронну адресу",
  "btn_bind_phone": "Прив'язати номер телефону",
  "btn_modify_password": "Змінити пароль",
  "phone_number": "номеру телефону", //
  "email": "еmail-адреси", //
  "btn_register_via": "Зареєструватися за допомогою %s",
  "btn_bind_via": "Прив’язати за допомогою %s",
  "btn_reset_password_via": "Скинути за допомогою %s",
  "btn_bind_account": "Прив’язати обліковий запис",
  "prompt_password_limit_tips": "Будь ласка, введіть 6-20 чисел та англійські символи, а не одні числа",
  "prompt_empty_password": "Порожній пароль",
  "title_bind_social_account": "Прив'язка облікового запису соцмережі",
  "prompt_social_account_auth_failed": "Помилка авторизації",
  "prompt_bind_social_account_tips": "*Ви можете увійти в INMOTION за допомогою прив’язаного облікового запису в соціальній мережі.",
  'state_bound': "Прив'язано",
  'state_not_bound': "Не прив'язано",
  'prompt_unbind_social_account_tips': "Після скасування прив’язки Ви не зможете використовувати %s для входу в INMOTION? Ви впевнені, що скасували прив’язку?",
  'btn_logout': 'Вийти',
  'prompt_logout_tips': 'Ви підтверджуєте вихід із системи?',
  "title_operation_verification": "Перевірка безпеки",
  "prompt_operation_verification_tips": "Поточна операція потребує перевірки. Перевірте будь-яким із наведених нижче методів",
  "title_verify_operation_via": "Підтвердити через %s",
  "prompt_operation_verification_expired": "Спочатку виконайте перевірку безпеки!",
  "text_none": "(порожньо)",
  "title_account_cancellation": "Видалення облікового запису",
  "prompt_account_cancellation_details":
      "Після закриття облікового запису INMOTION його відновлення неможливе. Ми рекомендуємо вам резервувати інформацію та дані, пов'язані з вашим обліковим записом. Будь ласка, пам'ятайте: якщо Ви закриєте свій обліковий запис INMOTION, Ви більше не зможете використовувати цей обліковий запис або відновити відповідні продукти чи іншу інформацію (навіть якщо зареєструєтеся та використаєте INMOTION знову з тим же номером телефону або адресою електронної пошти), зокрема, але не виключно:\n(1) Продукти, затверджені вашим обліковим записом INMOTION, автоматично зв'язуються з іншими користувачами після підключення цих продуктів;\n(2) Ви не зможете відновити оновлення, лайки та коментарі, які Ви поділилися в своєму обліковому записі INMOTION;\n(3) LE-монети на вашому обліковому записі INMOTION та віртуальні предмети, які обмінюються за LE-монети (наприклад, пакети ефектів атмосферного світла), не будуть відновлені;\n(4) Будь ласка, зверніть увагу, що скасування вашого облікового запису INMOTION не означає, що діяльність облікового запису та пов'язані з ним відповідальності до скасування цього облікового запису будуть звільнені або зменшені.",
  "prompt_account_cancellation_apply_success": "Заявка успішно подана, і ми якнайшвидше обробимо ваш запит на видалення.",

  /// Chinese phone quick verify error
  "prompt_cn_phone_auth_no_sim_card": "SIM-картка не знайдена!",
  "prompt_cn_phone_auth_unknown_operator": "Невідомий оператор!",
  "prompt_cn_phone_auth_network_not_enable": "Мобільні дані вимкнені!",
  "prompt_cn_phone_auth_unknown": "Невідома помилка!",

  ///
  /// Vehicle
  ///
  "btn_search_vehicle": "Знайти транспортний засіб",
  "prompt_canceled": "Скасовано",
  "prompt_had_connected_before": "Підключалось раніше",
  "title_vehicle_activation": "Активація",
  "prompt_wait_for_activation_tips_finished": "Прочитайте/перегляньте нагадування про безпеку.",
  "prompt_had_read_activation_tips": "Я уважно прочитав наведені вище нагадування про безпеку та знаю можливі ризики",
  "btn_activate": "Активувати зараз",
  "prompt_activated": "Активовано успішно!",
  "prompt_activate_failed": "Помилка активації",
  "prompt_activate_canceled": "Відмінено",
  "prompt_authorize_as_owner_after_activation":
      "Автентифікація транспортного засобу потрібна для таких операцій як блокування транспортного засобу в додатку. Хочете підтвердити власника зараз?",
  "prompt_authorize_as_owner_later_after_activation": "Ви також можете зробити це пізніше в розділі «Я – Авторизація власника».",
  "prompt_set_vehicle_password_failed": "Не вдалося встановити пароль",
  "prompt_set_vehicle_password_later_after_activation": "Ви також можете зробити це пізніше в «Транспортний засіб – Налаштування – Пароль».",
  "prompt_bluetooth_disabled": "Bluetooth на телефоні не ввімкнено",
  "prompt_location_disabled": "Службу локації не ввімкнено",
  "prompt_no_bluetooth_permission": "Немає дозволу Bluetooth",
  "prompt_no_location_permission": "Немає дозволу на місцезнаходження",
  "prompt_no_scan_bluetooth_permission": "Немає дозволу на сканування Bluetooth",
  "prompt_no_connect_bluetooth_permission": "Немає дозволу на з’єднання Bluetooth",
  "prompt_no_device_found": "Транспортних засобів не знайдено.",
  "prompt_tap_to_connect": "Торкніться транспортного засобу нижче щоб підключитися",
  "prompt_scanning": "Пошук...",
  "prompt_connecting": "Підключення...",
  "prompt_connection_canceled": "Підключення скасовано",
  "prompt_connected": "Підключено",
  "prompt_connection_timeout": "Час очікування підключення вичерпано",
  "prompt_connection_failed": "Помилка підключення",
  "prompt_unsupported_models": "Непідтримувана модель продукту",
  "prompt_Initialization_data_exception": "Проблема із ініціалізацією даних, код помилки: %s",
  "btn_enable_bluetooth": "Відкрити налаштування Bluetooth",
  "btn_enable_location": "Увімкнути службу визначення місцезнаходження",
  "btn_request_bluetooth_permission": "Запит на дозвіл Bluetooth",
  "btn_request_location_permission": "Запитати дозвіл на місцезнаходження",
  "btn_scan_again": "Шукати знову",
  "btn_cancel_connection": "Скасувати",
  "prompt_why_need_to_enable_location": "Навіщо мені вмикати службу локації?",
  "prompt_why_need_location_permission": "Чому INMOTION потрібен дозвіл на місцезнаходження?",
  "prompt_why_do_i_couldnt_find_vehicles": "Чому я не зміг знайти свій транспортний засіб?",
  "btn_view_solutions": "Переглянути можливі рішення",
  "prompt_connect_failed_server_ip_service_error": "Тимчасова помилка сервера. Невдовзі ми її виправимо. Повторіть спробу пізніше.",
  "prompt_connect_failed_unknown_model":
      "Ви не можете використовувати додаток INMOTION, оскільки модель поточного транспортного засобу недійсна.\nБудь ласка, зв'яжіться з нами для отримання додаткової інформації.",
  "prompt_connect_failed_unknown_sn":
      "Ви не можете використовувати додаток INMOTION, оскільки серійний номер поточного транспортного засобу недійсний.\nБудь ласка, зв'яжіться з нами для отримання додаткової інформації.",
  "prompt_connect_failed_vehicle_locked": "Транспортний засіб знаходиться у ВТРАЧЕНОМУ РЕЖИМІ. Будь ласка, зв'яжіться з нами для отримання додаткової інформації.",
  "prompt_connect_failed_vehicle_lost_mode":
      'Транспортний засіб знаходиться у ВТРАЧЕНОМУ РЕЖИМІ. Ви можете вимкнути його в "Я - Знайти мій транспортний засіб", якщо Ви є власником транспортного засобу.',
  "prompt_connect_failed_area_not_available": "Ви не можете використовувати цю транспортний засіб в поточному регіоні.",
  "text_vehicle_ride_time": "Тривалість поїздки",
  "text_vehicle_power_on_time": "Тривалість роботи", //
  "text_vehicle_ride_mileage": "Відстань поїздки",
  "text_vehicle_max_speed": "Макс. швидкість",
  "text_vehicle_ave_speed": "Сер. швидкість",
  "text_vehicle_last_ave_speed": "Остання сер. шв-сть",
  "text_vehicle_total_mileage": "Загальний пробіг",
  "text_vehicle_manual_odo_mileage": "Ручний одометр",
  "text_vehicle_dynamic_speed_limit": "Обмеження швидкості",
  "text_vehicle_realtime_power": "Потужність",
  "text_vehicle_max_power": "Макс. потужність",
  "text_vehicle_ave_power": "Сер. потужність",
  "text_vehicle_mos_temp": "Температура MOS",
  "text_vehicle_current": "Струм",
  "text_vehicle_voltage": "Напруга",
  "text_vehicle_consumption": "Енергоспоживання",
  "text_vehicle_recovery": "Регенерація",
  "text_vehicle_last_ride_mileage": "Останній пробіг",
  "text_vehicle_last_ride_time": "Тривалість останньої поїздки",
  "text_vehicle_last_max_speed": "Остання макс. швидкість",
  "text_vehicle_realtime_speed": "Швидкість",
  "text_vehicle_battery_discharge_current": "Струм розрядки батареї",
  "text_vehicle_battery_voltage": "Напруга батареї",
  "text_vehicle_battery_output_power": "Потужність розрядки батареї",
  "text_vehicle_motor_output_power": "Вихідна потужність мотору",
  "text_vehicle_motor_torque": "Крутний момент",
  "text_vehicle_remaining_battery": "Залишок батареї",
  "text_vehicle_output_rate": "Вихідний вектор напруги(%)",
  "text_vehicle_dynamic_current_limit": "Динамічний ліміт перевантаження по струму",

  "prompt_long_press_to_edit": "Утримуйте для редагування",
  "prompt_double_click_to_reset_manual_odo": "Торкніться двічі щоб скинути одометр",
  "prompt_confirm_to_reset_manual_odo": "Ви підтверджуєте скидання значення одометру?",

  "text_vehicle_speed": "Швидкість",
  "text_vehicle_mileage": "Пробіг",
  "text_vehicle_power": "Потужність",
  "text_vehicle_time": "Тривалість",
  "text_vehicle_temperature": "Температура",
  "text_vehicle_other": "Інше",

  "text_vehicle_motor_temp": "Температура мотору",
  "text_vehicle_front_motor_temp": "Темп. переднього мотору",
  "text_vehicle_rear_motor_temp": "Темп. заднього мотору",
  "text_vehicle_battery_temp": "Температура батареї",
  "text_vehicle_motherboard_high_temp": "Температура плати",
  "text_vehicle_driver_board_cpu_temp": "Температура CPU",
  "text_vehicle_imu_temp": "Температура IMU",

  "text_gps_speed": "Швидкість по GPS",

  "prompt_status_connecting": "Підключення",
  "prompt_status_connected": "Підключено",
  "prompt_status_disconnected": "Не підключено",
  "prompt_vehicle_disconnected": "Транспортний засіб відключено",
  "prompt_no_connected_vehicles_yet": "Ще немає підключених транспортних засобів.",
  "prompt_current_connected_vehicle": "Підключено",
  "prompt_last_connected_at": "Останнє підключення: %s",
  "title_switch_vehicle": "Перемикання між ТЗ",
  "btn_disconnect_and_scan": "Відключення та пошук",
  "btn_scan": "Пошук",
  "btn_detailed_data": "Детально",
  "title_about_vehicle": "Про транспортний засіб",
  "title_battery_info": "Інформація про акумулятор",
  "title_customer_service": "Онлайн-сервіс",
  "title_faq": "FAQ",

  "title_gps_riding_tracks": "Мої маршрути",
  "title_vehicle_riding_record": "Записи поїздок",

  "text_vehicle_riding_record_mileage": "Відстань поїздки: %s",
  "text_vehicle_riding_record_max_speed": "Макс. швидкість: %s",

  "title_vehicle_riding_report": "Звіт про поїздку",
  "prompt_invalid_riding_track": "Недійсний запис поїздки.",

  "title_basic_battery_info": "Базова інформація",
  "text_battery_voltage": "Напруга",
  "text_battery_charge_voltage": "Напруга зарядки",
  "title_detailed_battery_info": "Інформація про акумулятор",
  "text_battery_detected_status": "Статус наявності батареї",
  "text_battery_detected": "Наявна",
  "text_battery_not_detected": "Не виявлено",
  "text_battery_enable_status": "Статус активності батареї",
  "text_battery_enabled": "Активна",
  "text_battery_disabled": "Неактивна",
  "text_battery_error_status": "Статус справності батареї",
  "text_battery_ok": "OK",
  "text_battery_error": "Помилка",
  "text_battery_signal_logic_error": "Помилка логічного сигналу",

  "title_battery_cells_voltage": "Напруга елементів батареї",

  "title_bms_basic_info": "Основна інформація",
  "text_bms_battery_sn": "Серійний номер батареї",
  "text_bms_manufacture_date": "Дата виготовлення",
  "text_bms_full_charge_cycles": "Повні цикли зарядки",
  "text_bms_software_version": "Версія програмного забезпечення BMS",
  "text_bms_hardware_Version": "Апаратна версія BMS",
  "title_bms_data_and_status": "Дані та статус",
  "text_bms_voltage": "Напруга",
  "text_bms_charge_state": "Стан заряду",
  "text_bms_charge_current": "Струм заряду",
  "text_bms_discharge_current": "Струм розряду",
  "text_bms_charge_mos_state": "MOS зарядки",
  "text_bms_discharge_mos_state": "MOS розрядки",
  "text_bms_error_status": "Статус помилок",
  "text_bms_warning_status": "Статус попереджень",
  "text_bms_protection_status": "Статус захисту",
  "text_bms_cell_balancing_status": "Балансування комірок",
  "text_bms_max_cell_voltage": "Макс. напруга комірки",
  "text_bms_min_cell_voltage": "Мін. напруга комірки",
  "text_bms_charge_mos_temp": "Температу MOS зарядки",
  "text_bms_discharge_mos_temp": "Температу MOS розрядки",
  "text_bms_cells_temp": "Температура комірок",
  "text_bms_cells_voltage": "Напруга комірок",

  /// vehicle settings
  "title_vehicle_settings": "Налаштування транспортного засобу",
  "prompt_operation_succeed": "Успішно",
  "prompt_operation_failed": "Не вдалося",
  "title_vehicle_password": "Пароль",
  "text_vehicle_password_disabled": "Вимкнено",
  "text_vehicle_password_gesture": "Графічний",
  "text_vehicle_password_slide": "Свайп",
  "text_vehicle_password_number": "Цифровий",
  "title_modify_vehicle_password": "Змінити пароль",
  "title_set_vehicle_password": "Встановити пароль",
  "prompt_vehicle_number_password_tips": "Будь ласка, введіть 4- або 6-значний пароль",
  "title_vehicle_userinfo": "Інформація про користувача ТЗ",
  "title_vehicle_userinfo_avatar": "Аватар",
  "title_vehicle_userinfo_name": "Назва ТЗ",
  "prompt_vehicle_userinfo_name_tips": "Будь ласка, введіть 1–16 літер, цифр і англійських символів",
  "title_choose_setting_item": "Виберіть елементи налаштування",
  "vehicle_setting_item_limit_speed_25": "Фіксатор швидкості 25 км/год",
  "vehicle_setting_item_limit_speed": "Обмеження швидкості",
  "vehicle_setting_item_drive_mode": "Режим їзди",
  "vehicle_setting_item_drive_mode_normal": "Повсякденний",
  "vehicle_setting_item_drive_mode_normal_tips": "М'який і плавний розгін та уповільнення. Зручніше на довгих дистанціях.",
  "vehicle_setting_item_drive_mode_off_road": "Екстремальний",
  "vehicle_setting_item_drive_mode_off_road_tips": "Високий рівень жорсткості педалей для різкого прискорення, підйому на пагорби та їзди по бездоріжжю.",
  "vehicle_setting_item_pedestrian_mode_limit_speed": "Макс. швидкість (Пішохідний режим)",
  "vehicle_setting_item_pedal_sensitivity": "Жорсткість педалей",
  "vehicle_setting_item_spilt_mode": "Регульований режим", //
  "vehicle_setting_item_spilt_mode_speeding": "Розгін",
  "vehicle_setting_item_spilt_mode_breaking": "Гальмування",
  "vehicle_setting_item_electronic_brake_force": "Сила гальмування",
  "vehicle_setting_item_power_assist": "Помічник потужності",
  "vehicle_setting_item_acc_assist": "Помічник прискорення",
  "vehicle_setting_item_brake_assist": "Помічник гальмування",
  "vehicle_setting_item_cruise": "Круїз",
  "vehicle_setting_item_ride_assist": "Помічник поїздки",
  "vehicle_setting_item_zero_start": "Нульовий старт", //?
  "vehicle_setting_item_assist_balance": "Помічник балансу",
  "vehicle_setting_item_load_detect": "Виявлення навантаження",
  "vehicle_setting_item_noload_detect": "Виявлення холостого ходу",
  "vehicle_setting_item_up_hill_assist": "Допомога при підйомі",
  "vehicle_setting_item_down_hill_assist": "Допомога при спуску",
  "vehicle_setting_item_overspeed_alarm": "Попередження про швидкість",
  "vehicle_setting_item_lock": "Блокування",
  "vehicle_setting_item_password": "Пароль",
  "vehicle_setting_item_diagnosis": "Діагностика",
  "vehicle_setting_item_headlight": "Фара",
  "vehicle_setting_item_headlight_brightness": "Яскравість фари",
  "vehicle_setting_item_drl": "Денні ходові вогні",
  "vehicle_setting_item_low_beam_headlight": "Фара ближнього світла",
  "vehicle_setting_item_low_beam_headlight_brightness": "Яскравість фари ближнього світла",
  "vehicle_setting_item_high_beam_headlight": "Фара дальнього світла",
  "vehicle_setting_item_high_beam_headlight_brightness": "Яскравість фари дальнього світла",
  "vehicle_setting_item_auto_headlight": "Автоувімкнення фари",
  "vehicle_setting_item_auto_headlight_brightness_threshold": "Поріг автоматичного перемикання фар",
  "vehicle_setting_item_auto_low_high_beam": "Автоматичне ближнє і дальнє світло фар",
  "vehicle_setting_item_auto_low_high_beam_switch_speed_threshold": "Автоматичний поріг швидкості перемикання ближнього та дальнього світла",
  "vehicle_setting_item_light_effect": "Світловий ефекти",
  "vehicle_setting_item_light_effect_mode": "Режим світлових ефектів",
  "vehicle_setting_item_light_effect_front": "Режим переднього світлового ефекту",
  "vehicle_setting_item_light_effect_rear": "Режим ефекту заднього світла",
  "vehicle_setting_item_light_diy": "Створити", //
  "vehicle_setting_item_auto_turn_signal": "Поворотники",
  "vehicle_setting_item_audio_state": "Звук",
  "vehicle_setting_item_volume": "Гучність",
  "vehicle_setting_item_audio_package": "Аудіопакет",
  "vehicle_setting_item_standby_time": "Режим очікування",
  "vehicle_setting_item_spin_kill_btn": "Кнопка вимкнення мотору",
  "vehicle_setting_item_sound_wave": "Sound Wave",
  "vehicle_setting_item_sound_wave_sensitivity": "Чутливість Sound Wave",
  "vehicle_setting_item_estimated_remainder_range": "Оцінка залишкового пробігу",
  "vehicle_setting_item_user_info": "Інформація про транспортний засіб",
  "vehicle_setting_item_fan_quiet_mode": "Безшумний режим вентилятора",
  "vehicle_setting_item_forced_fan": "Примусове охолодження",
  "vehicle_setting_item_transport_mode": "Транспортувальний режим",
  "vehicle_setting_item_low_battery_safe_mode": "Безпечний режим низького заряду батареї",
  "vehicle_setting_item_auto_screen_off": "Автоматичне вимкнення екрана",
  "vehicle_setting_item_speed_unit": "Метричні/британські одиниці",
  "vehicle_setting_item_sn": "Серійний номер",
  "vehicle_setting_item_acc_force": "Сила прискор.",
  "title_vehicle_acc_front_force": "Сила прискор. спереду",
  "title_vehicle_acc_rear_force": "Сила прискор. ззаду",
  "vehicle_setting_item_brake_force": "Сила гальм.",
  "title_vehicle_brake_front_force": "Сила гальм. спереду",
  "title_vehicle_brake_rear_force": "Сила гальм. ззаду",
  "vehicle_setting_item_one_pedal_mode": "Однопедальний режим",
  "vehicle_setting_item_brake_first": "Brake First", //
  "vehicle_setting_item_auto_park_time": "Auto Park Time", //
  "vehicle_setting_item_activate_date": "Дата активації",
  "vehicle_setting_item_total_mileage": "Загальний пробіг",
  "vehicle_setting_item_hmic_board_version": "HMIC плата",
  "vehicle_setting_item_bt_board_version": "Bluetooth-модуль",
  "vehicle_setting_item_driver_board_version": "Плата драйвера",
  "vehicle_setting_item_driver_board_temp": "Температура плати драйвера",
  "vehicle_setting_item_riding_mode": "Режим їзди",
  "vehicle_setting_riding_mode_p": "P",
  "vehicle_setting_riding_mode_eco": "ECO",
  "vehicle_setting_riding_mode_eco_tips": "Рекомендація новачкам, плавний розгін.",
  "vehicle_setting_riding_mode_normal": "D (звичайний)",
  "vehicle_setting_riding_mode_sport": "S (спорт)",
  "vehicle_setting_riding_mode_sport_tips": "Рекомендується професійним райдерам, більша чутливість",
  "vehicle_setting_riding_mode_extreme": "X (екстрим)",
  "vehicle_setting_riding_pedestrian_mode": "Пішохідний режим",
  "vehicle_setting_riding_pedestrian_mode_tips": "Легше штовхати самокат.",
  "vehicle_setting_item_riding_mode_euc_normal": "Звичайний",
  "vehicle_setting_item_riding_mode_euc_normal_tips": "Більш безпечний, підходить для більшості користувачів.",
  "vehicle_setting_item_riding_mode_euc_fancier": "Любитель",
  "vehicle_setting_item_riding_mode_euc_fancier_tips": "Вища вихідна потужність і вища максимальна швидкість.",
  "prompt_cannt_set_sport_mode_when_limit_speed_25kmph_enabled": "Ви не можете переключитися в режим «S», коли ввімкнено «Фіксатор швидкості на 25 км/год»..",
  "prompt_cannt_enable_limit_speed_25kmph_when_sport_mode_enabled": "Ви не можете ввімкнути «Фіксатор швидкості на 25 км/год» у режимі «S».",
  "vehicle_setting_item_berm_angle_mode": "Режим кута Берма",
  "prompt_unlock_factory_safe_speed_limit": "Для вашої безпеки макс. обмеження швидкості можна збільшити лише до 90 км/год, якщо ваш загальний пробіг перевищує 30 км. %s",
  "prompt_unlock_factory_safe_speed_limit_not_now":
      "Для вашої безпеки макс. обмеження швидкості можна збільшити лише до 90 км/год, якщо ваш загальний пробіг перевищує 30 км. Вам ще потрібно продовжувати їхати %s.",
  "prompt_unlock_now": "Розблокувати зараз>>",

  "warning_unlock_v13_factory_speed_limit":
      "Ваша безпека є нашим головним пріоритетом. Щоб краще захистити свої особисті права та інтереси уважно прочитайте цю Заяву, щоб переконатися, що Ви повністю розумієте її зміст.\n\n1. Ви підтверджуєте та усвідомлюєте, що  намагаєтеся розблокувати максимальну швидкість колеса. Після зняття цього обмеження Ви зможете встановити максимальну швидкість до 90 км/год.\n2. Ви розумієте та усвідомлюєте ризики, пов’язані з їздою на надвисокій швидкості і несете відповідальність за будь-які втрати та пошкодження, спричинені високою швидкістю.\n3. Ви зобов’язані знати про всі закони та правила щодо їзди на моноколесах у вашому регіоні та суворо дотримуватись чинних законів, постанов і правил під час їзди на V13. Не їздіть на V13 у місцях заборонених місцевим законодавством.\n4. Будь ласка, не дозволяйте нікому, хто не прочитав уважно інструкції або не знайомий із заходами безпеки під час їзди на V13 їздити на ньому.\n5. Перед кожною поїздкою обов’язково перевіряйте, чи пристрій та аксесуари знаходяться в справному стані, уникайте використання неоригінальних акумуляторів і аксесуарів, а також не розбирайте, не ламайте та не модифікуйте пристрій та аксесуари без дозволу. Ви несете відповідальність за будь-які втрати, пошкодження та ризики, спричинені неправильною експлуатацією.\n\nБудь ласка, уважно прочитайте та оберіть, чи приймати цю заяву. Ви не можете розблокувати обмеження максимальної швидкості, доки не погодитеся з цією заявою. Ваше «Погоджуюсь» вважатиметься прийняттям цієї відмови від відповідальності. Якщо у вас виникли сумніви щодо цієї відмови від відповідальності, натисніть «Скасувати»",
  "warning_enable_berm_angle_mode":
      "Коли цей режим увімкнено, кут захисту транспортного засобу від перекидання стане більшим, що означає, що транспортний засіб може хитатися вперед-назад і легко вийти з-під контролю через невеликі зміни кута балансу, коли він нахилений убік. Це може завдати шкоди вам або оточенню. Ви вже знаєте про всі можливі ризики, Ви впевнені, що хочете це ввімкнути?",
  "warning_disable_berm_angle_mode": "Щоб активувати, натисніть кнопку вимкнення мотору після ввімкнення/вимкнення режиму. ",

  "title_vehicle_balance_angle": "Кут нахилу",
  "title_vehicle_calibration": "Калібрування",
  "title_vehicle_balance_angle_calibration": "Калібрування кута нахилу",
  "prompt_vehicle_balance_angle_calibration_desc":
      "Якщо транспортний засіб все ще нахиляється назад або вперед на землі після того, як Ви встановили кут балансування на нуль, Ви можете спробувати це калібрування, щоб виправити це. %s",
  "prompt_vehicle_balance_angle_calibration":
      "Будь ласка, натисніть і утримуйте кнопку вимкнення мотору щоб вертикальний напрямок транспортного засобу завжди був перпендикулярним до горизонтальної поверхні землі",
  "title_vehicle_turning_calibration": "Калібрування поворотів",
  "title_vehicle_turning_calibration_desc": "Це може покращити зручність при поворотах. %s",
  "text_view_calibration_guide": "Переглянути вказівки>>",
  "title_motor_self_adjustment": "Саморегулювання мотору",
  "prompt_motor_self_adjustment_desc":
      "Після запуску двигун автоматично працюватиме протягом 1 хвилини. Для вашої безпеки переконайтеся, що моноколесо знаходиться в нахиленому стані та не торкайтеся колеса!",
  "prompt_clear_motor_self_adjustment_effect_desc": "Рекомендується %s, якщо досвід їзди не покращився", //
  "title_clear_motor_self_adjustment_effect": "Скинути дані саморегулювання мотору",
  "prompt_motor_self_adjustment_in_progress": "Триває саморегулювання...",
  "prompt_motor_self_adjustment_terminated": "Саморегулювання припинено",
  "prompt_motor_self_adjustment_succeed": "Саморегулювання виконано",
  "prompt_motor_self_adjustment_finished": "Саморегулювання закінчено",
  "prompt_motor_self_adjustment_timeout": "Вийшов час очікування саморегулювання",
  "prompt_confirm_to_clear_motor_self_adjustment_effect": "Чи підтверджуєте Ви очищення даних саморегулювання двигуна?",

  "prompt_motor_self_check_in_progress": "Триває самоперевірка...",
  "prompt_motor_self_check_terminated": "Самоперевірку припинено",
  "prompt_motor_self_check_passed": "Самоперевірку пройдено",
  "prompt_motor_self_check_not_passed": "Самоперевірку НЕ пройдено",
  "prompt_motor_self_check_timeout": "Вийшов час очікування самоперевірки",
  "prompt_motor_self_check_failed": "Не вдалося запустити самоперевірку",

  "title_vehicle_acc_calibration": "Калібрування дросельної заслінки",
  "title_vehicle_brake_calibration": "Калібрування гальм",
  "title_vehicle_gyro_calibration": "Калібрування гіроскопа",
  "prompt_vehicle_acc_calibration_tips":
      "Після початку калібрування утримуйте ручку газу на максимальному та мінімальному значенні протягом 1 секунди. Переконайтеся, що зазначену операцію калібрування виконали протягом 5 секунд.",
  "prompt_vehicle_brake_calibration_tips":
      "Після початку калібрування утримуйте ручку гальма на максимальному та мінімальному значенні протягом 1 секунди. Переконайтеся, що зазначену операцію калібрування виконали протягом 5 секунд.",
  "prompt_vehicle_gyro_calibration_tips": "Будь ласка, випряміть скутер, щоб підніжка була паралельна землі, а потім почніть калібрування, доки воно не завершиться.",
  "prompt_cannt_start_vehicle_acc_calibration_when_zero_start_enabled": "Ви не можете розпочати калібрування ручки дросельної заслінки, коли ввімкнено режим «Zero Start»!",

  "prompt_calibration_succeed": "Калібрування успішне",
  "prompt_calibration_failed": "Помилка калібрування",
  "prompt_calibration_timeout": "Вийшов час очікування калібрування",

  "title_vehicle_factory_reset": "Заводські налаштування",
  "prompt_vehicle_confirm_to_factory_reset": "Ви підтверджуєте скидання до заводських налаштувань?",
  "prompt_vehicle_confirm_to_factory_reset_desc": "Відновіть усі налаштування та аудіопакет до заводських налаштувань",
  "prompt_vehicle_ezcan_confirm_to_factory_reset_desc": "Скидання до заводських налаштувань може зайняти кілька хвилин, не виходьте з програми.",
  "prompt_vehicle_ezcan_factory_reset_succeed": "Скидання до заводських налаштувань виконано. Вимкніть і зачекайте 10 секунд, а потім увімкніть.",
  "prompt_vehicle_factory_reset_succeed": "Скидання до заводських налаштувань виконано!",

  "prompt_vehicle_euc_need_motor_free": "Зіпріть моноколесо на підніжку або покладіть його на бік",

  "title_vehicle_firmware_update": "Оновлення ПЗ",

  /// EBike Assist
  "title_vehicle_assistant_mode": "Асистент-режим",
  "text_vehicle_assistant_mode_none": "Вимк.",
  "prompt_vehicle_assistant_mode_none_desc": "У цьому режимі вимикається допомога живлення, Ви можете лише за допомогою педалей рухатися вперед.",
  "text_vehicle_assistant_mode_medium": "Обмежений",
  "prompt_vehicle_assistant_mode_medium_desc": "Цей режим має обмежену допомогу, яка підходить для їзди на рівних дорогах.",
  "text_vehicle_assistant_mode_max": "Макс.",
  "prompt_vehicle_assistant_mode_max_desc":
      "Цей режим посилить підтримку силового підсилення, що підходить для частої їзди вгору та спуску. Цей режим швидше розряджатиме акумулятор.",

  /// L8 Light Effect
  "text_light_effect_mode_0": "Режим 1",
  "text_light_effect_mode_1": "Режим 2",
  "text_light_effect_mode_2": "Режим 3",
  "text_light_effect_mode_3": "Режим 4",
  "text_light_effect_mode_4": "Режим 5",
  "text_light_effect_mode_5": "Режим 6",
  "text_light_effect_mode_6": "Режим 7",
  "text_light_effect_mode_7": "Режим 8",
  "title_light_effect_color": "Колір світлового ефекту", //

  /// V12 Light Effect
  "text_light_effect_mode_close": "Вимкнено",
  "text_light_effect_mode_light_package": "Персональний",
  "text_light_effect_mode_light_package_change": "Змінити світловий ефект",
  "text_light_effect_mode_follow_music": "Прив'язаний до музики",
  "text_light_effect_mode_follow_speed": "Прив'язаний до швидкості",
  "text_light_effect_mode_follow_speed_1": "Водний потік",
  "text_light_effect_mode_follow_speed_2": "Завжди увімкнено",

  /// Diagnosis
  "title_vehicle_diagnosis": "Діагностика",
  "prompt_vehicle_diagnosis_result": "Результат діагностики",
  "prompt_vehicle_diagnosis_ok": "Відомих помилок і попереджень не знайдено",
  "prompt_vehicle_diagnosis_abnormal": "Ваш транспортний засіб в несправному стані",
  "title_vehicle_diagnosis_history": "Історія діагностики",
  "title_view_history": "Переглянути історію",
  "title_vehicle_upload_log": "Вивантаження логу",
  "prompt_upload_log_tips": "Вивантаження логу може зайняти кілька хвилин, наберіться терпіння",
  "title_upload_euc_log": "Вивантажити лог моноколеса",
  "title_upload_bms_log": "Вивантажити лог BMS",
  "title_uploading_euc_log": "Вивантаження логу моноколеса",
  "title_uploading": "Вивантаження %s",
  "title_upload_euc_and_bms_log": "Вивантажити лог моноколеса та BMS",
  "title_upload_bms_log_tips":
      "Немає необхідності вивантажувати логи BMS, якщо колесо не повідомляє про помилки або проблеми, пов'язані з батареєю, якщо не було запиту на це команди INMOTION.",

  /// Remote Diagnosis
  "title_remote_diagnosis": "Дистанційна діагностика",
  "prompt_remote_diagnosis_tips": "Будь ласка, використовуйте цю функцію під керівництвом команди INMOTION.",
  "prompt_remote_diagnosis_enter_failed": "Не вдалося увійти в дистанційну діагностику!",
  "prompt_remote_diagnosis_remote_disconnected": "Віддалений пристрій відключено!",
  "prompt_remote_diagnosis_disconnected": "Дистанційна діагностика відключена!",
  "prompt_remote_diagnosis_waiting_remote_connection": "Зараз Ви перебуваєте в режимі онлайн-діагностики! Очікуйте віддалений доступ до пристрою.",
  "prompt_remote_diagnosis_confirm_to_cancel": "Наразі Ви очікуєте доступу віддаленого пристрою. Ви впевнені, що хочете вийти??",
  "prompt_remote_diagnosis_waiting_remote_timeout": "Помилка доступу, час очікування доступу до віддаленого пристрою минув.",
  "prompt_remote_diagnosis_enter_again": "Увійти знову",
  "prompt_remote_diagnosis_in_progress":
      "Триває онлайн-діагностика. Будь ласка, переконайтеся, що ваш мобільний телефон знаходиться поблизу транспортного засобу і мережа активна. Будь ласка, не вимикайте екран мобільного телефону.",
  "prompt_remote_diagnosis_connect_identifier": "Код прив'язки - [%s], натисніть, щоб скопіювати в буфер обміну. Будь ласка, надішліть цей код в INMOTION щоб почати діагностику.",

  "prompt_upload_log_success": "Лог успішно вивантажено!",
  "prompt_upload_log_failed": "Помилка вивантаження логу!",

  /// Firmware update
  "text_vehicle_current_firmware_version": "Поточна версія: %s",
  "title_vehicle_current_firmware_version": "Поточна версія",
  "prompt_new_firmware_version_found": "Знайдено нове програмне забезпечення",
  "prompt_cannt_interrupt_firmware_updating": "Продовжуйте завершувати оновлення.", //для завершення
  "prompt_no_new_firmware_version_found": "Нового програмного забезпечення не знайдено",
  "btn_update_firmware": "Оновити зараз",
  "title_firmware_update_notes": "Примітка",
  "text_firmware_update_notes_1": "· Перед оновленням переконайтеся, що заряд батареї не менше ніж 20%",
  "text_firmware_update_notes_2": "· Не користуйтесь транспортним засобом під час оновлення",
  "text_firmware_update_notes_3": "· Якщо оновлення не вдалося, спробуйте вийти з програми та оновити знову",
  "prompt_contact_us": "Зв'яжіться з нами",
  "prompt_firmware_update_learn_more_notes": "Дізнатись більше>>",
  "title_new_firmware_version_summary": "Рекомендовано", //?
  "text_new_firmware_version_learn_more": "Дізнатись більше>>",
  "prompt_firmware_update_success": "Оновлено виконано успішно",
  "prompt_firmware_update_failed": "Не вдалося оновити!",
  "prompt_last_firmware_update_interrupted": "Можливо, останнє оновлення програмного забезпечення було перервано. Продовжуйте завершувати оновлення, щоб виправити це.",
  "prompt_forced_firmware_update_tips":
      ">Вам потрібно оновити програмне забезпечення транспортного засобу до останньої версії, перш ніж ним можна буде користуватися в звичайному режимі",
  "prompt_firmware_update_le1_manually_process_tips":
      "Після вимкнення дисплея транспортного засобу зачекайте 3 секунди та ввімкніть його вручну. Потім натисніть «Підтвердити», щоб продовжити оновлення",
  "prompt_firmware_updating": "Оновлення %s",
  "prompt_firmware_update_waiting_device": "Очікування оновлення пристрою",

  "prompt_vehicle_requesting_fw_update": "Прошивка %s пошкоджена, будь ласка, оновіть її.",
  "prompt_vehicle_requesting_fw_update_manually_canceled": "Прошивка %s пошкоджена, будь ласка, перепідключіться та слідуйте вказівкам, щоб виправити проблему з прошивкою.",

  "title_device_name_unknown": "Невідомо",
  "title_device_name_hmic_board": "HMIC-плата",
  "title_device_name_driver_board": "Плата драйвера",
  "title_device_name_bt_board": "Bluetooth-плата",
  "title_device_name_display_board": "Плата дисплея",
  "title_device_name_bms": "BMS",
  "title_device_name_bms_1": "BMS 1",
  "title_device_name_bms_2": "BMS 2",
  "title_device_name_driver_board_1": "Плата драйвера(Передня)",
  "title_device_name_driver_board_2": "Плата драйвера(Задня)",

  /// 驱动板故障
  "title_vehicle_diagnosis_module_driver_board": "Плата драйвера",
  "vehicle_error_parse_current_sensor": "Датчик фазного струму вийшов з ладу, можливо, потрібно буде замінити плату драйвера.",
  "vehicle_error_bus_current_sensor": "Вийшов з ладу датчик струму шини, можливо, потрібно замінити плату драйвера.",
  "vehicle_error_imu_sensor": "Датчик IMU вийшов з ладу, можливо, потрібно замінити плату драйвера.",
  "vehicle_error_mos_temp_sensor": "Датчик температури MOS вийшов з ладу, можливо, потрібно замінити плату драйвера.",
  "vehicle_error_bus_voltage_sensor": "Основний датчик напруги вийшов з ладу, можливо, потрібно замінити плату драйвера.",
  "vehicle_error_battery_voltage_sensor": "Вийшов з ладу датчик напруги акумулятора, можливо, потрібно замінити плату драйвера.",
  "vehicle_error_board_high_temp_area_sensor": "Вийшов з ладу датчик температури високотемпературної зони, можливо, вам доведеться замінити плату драйвера.",
  "vehicle_error_current_sampling": "Помилка початкових даних поточної вибірки, можливо, вам знадобиться замінити плату драйвера.",
  "vehicle_error_sensor": "Помилка виходу датчика, можливо, потрібно буде замінити плату драйвера.",
  "vehicle_error_rtc": "Помилка RTC, можливо, потрібно буде замінити плату драйвера.",
  "vehicle_error_spi_flash": "Помилка зовнішнього накопичувача, можливо, потрібно буде замінити плату драйвера.",
  "vehicle_error_log": "Системна помилка журналу.",
  "vehicle_error_external_flash": "Помилка зовнішнього накопичувача, можливо, вам доведеться замінити плату HMIC.",
  "vehicle_error_euc_driver_board_communication": "Помилка зв’язку плати драйвера, можливо, потрібно буде замінити плату HMIC або плату драйвера.",
  "vehicle_error_scooter_driver_board_communication": "Помилка зв’язку плати драйвера, можливо, потрібно буде замінити плату HMIC або плату драйвера.",
  "vehicle_error_scooter_driver_board_communication_unstable": "Зв’язок плати драйвера нестабільний, можливо, вам знадобиться замінити плату дисплея або плату драйвера.",
  "vehicle_error_communication": "Помилка зв’язку між платою драйвера, спробуйте повторно увімкнути.",
  "vehicle_error_voltage": "Помилка напруги.",
  "vehicle_error_driver_board": "Плата драйвера вийшла з ладу, можливо, потрібно буде замінити плату драйвера.",
  "vehicle_error_driver_board_oscillator": "Помилка кварцевого генератора.",

  "vehicle_warning_over_current": "Попередження про перевищення струму, їдьте обережно.",
  "vehicle_warning_over_temp": "Плата драйвера перегрілася, будь ласка, припиніть їзду на деякий час.",
  "vehicle_warning_cpu_over_temp": "Процесор плати драйвера перегрівається, припиніть їзду на деякий час.",
  "vehicle_warning_imu_over_temp": "IMU перегрівається, припиніть їзду на деякий час.",
  "vehicle_warning_mos_over_temp": "MOS перегрівається, припиніть на деякий час їзду.",

  /// display board errors and warnings
  "vehicle_error_scooter_imu_sensor": "Датчик IMU вийшов з ладу, можливо, вам знадобиться замінити плату дисплея.",

  /// hmic board errors and warnings
  "title_vehicle_diagnosis_module_hmic_board": "HMIC плата",
  "vehicle_error_hmic_board_rtc": "RTC вийшов з ладу, можливо, потрібно буде замінити головну плату.",
  "vehicle_error_hmic_board_flash": "Помилка зовнішнього накопичувача, можливо, доведеться замінити головну плату.",

  /// bt board errors and warnings
  "title_vehicle_diagnosis_module_bt_board": "Bluetooth-модуть",
  "vehicle_error_bt_board_communication": "Помилка зв’язку Bluetooth, можливо, потрібно буде замінити головну плату або плату Bluetooth.",

  /// motor errors and warnings
  "title_vehicle_diagnosis_module_motor": "Мотор",
  "vehicle_error_motor_hall": "Датчик холу мотору вийшов з ладу, можливо, потрібно замінити мотор.",
  "vehicle_error_motor_hall_left": "Лівий датчик холу мотору вийшов з ладу, можливо, потрібно замінити мотор.",
  "vehicle_error_motor_hall_right": "Правий датчик холу мотору вийшов з ладу, можливо, потрібно замінити мотор.",
  "vehicle_error_front_motor_hall": "Передній датчик холу мотору вийшов з ладу, можливо, потрібно замінити мотор.",
  "vehicle_error_rear_motor_hall": "Задній датчик холу мотору вийшов з ладу, можливо, потрібно замінити мотор.",
  "vehicle_error_motor_temp_sensor": "Вийшов з ладу датчик температури мотору, можливо, доведеться замінити мотор.",
  "vehicle_error_motor_phase": "Відсутня фраза двигуна, можливо, вам доведеться замінити двигун.",
  "vehicle_warning_motor_over_temp": "Попередження через перегрів двигуна, припиніть на деякий час їзду.",
  "vehicle_warning_motor_spin": "Попередження про розкручування. Не піднімайте EUC, не натиснувши кнопку вимкнення мотору.",
  "vehicle_warning_motor_blocked": "Попередження про зупинку двигуна, будь ласка, не паркуйтеся на крутих схилах на тривалий час.",

  /// battery errors and warnings
  "title_vehicle_diagnosis_module_battery": "Акумулятор",
  "vehicle_error_battery": "Акумулятор вийшов з ладу, можливо, потрібно замінити акумулятор.",
  "vehicle_error_battery_temp_sensor": "Вийшов з ладу датчик температури батареї, можливо, потрібно замінити батарею.",
  "vehicle_error_battery_cannt_power_off": "Якщо живлення не вимикається належним чином, можливо, доведеться замінити акумулятор.",
  "vehicle_error_battery_cannt_charge": "Якщо не вдається зарядити нормально, можливо, доведеться замінити акумулятор або зарядний пристрій.",
  "vehicle_error_battery_signal": "Помилка сигналу акумулятора.",
  "vehicle_warning_low_battery": "Попередження про низький рівень заряду батареї, зарядіть її якомога швидше.",
  "vehicle_warning_battery_over_temp": "Акумулятор перегрівається, припиніть їзду на деякий час.",
  "vehicle_warning_battery_calibration": "Ненормальне попередження калібрування напруги батареї. Будь ласка %s.",
  "text_calibrate_battery": "відкалібруйте напругу акумулятора",
  "vehicle_warning_some_batteries_not_enabled": "Попередження про те, що деякі батареї не працюють. Це вплине на продуктивність транспортного засобу. Будь ласка, їдьте обережно.",
  "vehicle_warning_danger_charge1_dual_charger":
      "Попередження: напруга лівої та правої батарейних блоків відрізняється, неправильне заряджання може спричинити проблеми з безпекою. Що Ви повинні робити: ①Використовуйте лише один оригінальний зарядний пристрій для заряджання колеса, використання двох зарядних пристроїв для одночасного заряджання колеса заборонено ②Розмістіть колесо в полі зору, не залишайте колесо на самоті, уважно спостерігайте за процесом заряджання. %s",
  "vehicle_warning_danger_charge1_single_charger":
      "Попередження: напруга лівої та правої батарейних блоків відрізняється, неправильне заряджання може спричинити проблеми з безпекою. Що Ви повинні зробити: помістіть колесо в поле зору, не залишайте колесо одне, уважно стежте за процесом заряджання. %s",
  "vehicle_warning_danger_charge2":
      "Небезпека! Припиніть зарядку! Помилка батареї, будь ласка, припиніть зарядку та негайно вийміть зарядний пристрій, покладіть колесо в безпечне місце. Будь ласка, завантажте журнал транспортного засобу (Налаштування - Діагностика - Завантажити журнал), зверніться до свого дилера для обслуговування. %s",
  "btn_i_know_danger_charge_risk_and_turn_off_alert": "Я знаю про ризик, вимкніть це попередження",
  "btn_i_know_danger_charge_risk": "I Know That Risk",
  "vehicle_warning_battery_over_voltage": "Висока напруга акумулятора, можливо, потрібно буде замінити акумулятор або зарядний пристрій.",
  "vehicle_warning_battery_output_abnormal": "Акумулятор не має вихідної потужності, будь ласка, спробуйте перезарядити або вам може знадобитися замінити акумулятор.",
  "vehicle_warning_too_low_battery": "Попередження про занадто низьку напругу, будь ласка, зарядіть якомога швидше, щоб уникнути пошкодження батареї.",

  /// Fan
  "title_vehicle_diagnosis_module_fan": "Вентилятор",
  "vehicle_error_fan": "Вентилятор охолодження вийшов з ладу, можливо, потрібно замінити вентилятор охолодження.",
  "vehicle_warning_fan_low_speed": "Низька швидкість обертання вентилятора. Це вплине на максимальний рівень яскравості. Будь ласка, перевірте, чи вентилятор заблокований чи ні.",

  /// vehicle errors and warnings
  "title_vehicle_diagnosis_module_vehicle": "Транспортний засіб",
  "vehicle_error_brake_handle": "Збій ручки гальма, перевірте, чи відпущено ручку гальма.",
  "vehicle_error_acc_handle": "Збій дросельної заслінки, перевірте ще раз, чи відпущено кермо дросельної заслінки.", //може це газ чи що

  "vehicle_warning_lock_caused_by_safe_issue": "Транспортний засіб було тимчасово заблоковано за для безпеки через приховану небезпеку.",
  "vehicle_warning_over_speed": "Попередження про перевищення швидкості. Будь ласка, повільніше.",
  "vehicle_warning_fall_down": "Попередження про падіння. Будь ласка, їдьте обережно.",
  "vehicle_warning_risk_behavior": "Попередження про небезпечне водіння, будь ласка, не користуйтесь транспортним засобом надмірно.",
  "vehicle_warning_software_incompatible": "Попередження через несумісність мікропрограми деяких частин, будь ласка, оновіть останню версію мікропрограми.",
  "vehicle_warning_motor_no_load_protection":
      "Попередження захисту двигуна від вільного навантаження, рекомендується натиснути кнопку Spin-kill перед підйомом і переконатися, що транспортний засіб нерухомий.",
  "vehicle_warning_power_key_long_pressed":
      "Попередження про тривале натискання кнопки живлення. Тривале натискання кнопки живлення може призвести до примусового вимкнення живлення. Будь ласка, припиніть їздити!",
  "vehicle_warning_necessary_self_check_not_passed": "Необхідний елемент самоперевірки не вдався або не пройшов попередження, %s.",
  "text_execute_self_check": "здійсніть самоперевірку",
  "vehicle_warning_function_limited_by_uncompleted_fw_update": "Функції транспортного засобу обмежені, перед його використанням потрібно оновити програмне забезпечення.",
  "vehicle_warning_remote_locked": "Транспортний засіб заблоковано, зв’яжіться з нами, щоб підтвердити вашу особу та розблокувати.",
  "vehicle_warning_hardware_incompatible": "Попередження через апаратну несумісність деяких частин, основну плату та драйверну плату потрібно замінити в повному комплекті.",
  "vehicle_warning_over_power": "Перевантаження.",

  /// BMS Error
  "bms_error_voltage_sample": "Помилка вибірки напруги.",
  "bms_error_charge_current_sample": "Помилка вибірки струму заряду.",
  "bms_error_discharge_current_sample": "Помилка вибірки струму розряду.",
  "bms_error_temperature_sensor": "Помилка датчика температури.",
  "bms_error_rh_sensor": "Помилка датчика відносної вологості.",
  "bms_error_charge_mosfet": "Помилка MOS заряду.",
  "bms_error_discharge_mosfet": "Помилка MOS розряду.",
  "bms_error_afe": "Помилка Afe.",
  "bms_error_cell": "Помилка комірки.",
  "bms_error_mcu": "Помилка MCU.",

  /// BMS Warning
  "bms_warning_low_soc": "Попередження про низький рівень soc.",
  "bms_warning_pack_over_charge": "Попередження про перезаряд акумулятора.",
  "bms_warning_pack_over_discharge": "Попередження про перерозряд акумуляторної батареї.",
  "bms_warning_cell_over_charge": "Попередження про перезаряд акумулятора.",
  "bms_warning_cell_over_discharge": "Попередження про перерозрядку батареї.",
  "bms_warning_charge_over_current": "Попередження про перевищення заряду.",
  "bms_warning_charge_mosfet_over_temperature": "Попередження про перегрівання mos заряду.",
  "bms_warning_charge_cell_over_temperature": "Попередження про перегрівання акумулятора.",
  "bms_warning_charge_cell_low_temperature": "Попередження про перегрівання акумулятора.",
  "bms_warning_discharge_over_current": "Попередження про перевищення струму.",
  "bms_warning_discharge_mosfet_over_temperature": "Попередження про перегрівання розряду.", //
  "bms_warning_discharge_cell_over_temperature": "Попередження про перегрівання елемента батареї.", //
  "bms_warning_discharge_cell_low_temperature": "Попередження про низьку температуру розряду батареї.",
  "bms_warning_over_humidity": "Попередження про надмірну вологість.",

  /// BMS Protection
  "bms_protection_short_circuit": "Захист від короткого замикання.",
  "bms_protection_pack_over_charge": "Захист акумуляторної батареї від перезаряду.",
  "bms_protection_pack_over_discharge": "Захист акумуляторної батареї від перерозряду.",
  "bms_protection_cell_over_charge": "Захист акумуляторної батареї від перезаряду.",
  "bms_protection_cell_over_discharge": "Захист від перерозряду акумуляторної батареї.",
  "bms_protection_charge_over_current": "Захист від перевищення струму.",
  "bms_protection_charge_mosfet_over_temperature": "Захист зарядки від перегріву.",
  "bms_protection_charge_cell_over_temperature": "Захист акумуляторної батареї від перегріву.",
  "bms_protection_charge_cell_low_temperature": "Захист акумулятора від низької температури.",
  "bms_protection_discharge_over_current": "Захист від перевищення струму.",
  "bms_protection_discharge_mosfet_over_temperature": "Захист від перевищення струму.", //
  "bms_protection_discharge_cell_over_temperature": "Захист від перегріву від розряду батареї.",
  "bms_protection_discharge_cell_low_temperature": "Захист від низької температури від розряду елемента батареї.",
  "bms_protection_over_humidity": "Захист від перепадів температури вологості.",
  "bms_protection_associated_charge": "Пов'язаний захист від заряду.", //
  "bms_protection_associated_discharge": "Пов'язаний захист від розряду.", //

  /// light effect
  'title_light_effect_preview': 'Попередній перегляд світлового ефекту',
  'title_complete_light_effect_info': 'Заповніть інформацію про світловий ефект',
  'prompt_input_light_effect_name': 'Введіть назву світлового ефекту',
  'prompt_input_light_effect_name_tips': 'Будь ласка, введіть 2-20 символів',
  'prompt_invalid_light_effect_info': 'Недійсна інформація про світловий ефект',
  'text_light_effect_frame_interval': 'Інтервал кадрів',
  'title_light_effect_my_colors': 'Мої кольори',
  'text_light_effect_frame_keyframe': 'Ключовий кадр',
  'text_light_effect_frame_total': 'Всього кадрів',
  'text_light_effect_frame_number': '%s кадр',
  'text_light_effect_frame': '%s кадр',
  'text_light_effect_frame_mode_normal': 'Баланс',
  'text_light_effect_frame_mode_fast': 'Швидше',
  'text_light_effect_frame_mode_slow': 'Повільніше',
  'title_light_effect_edit': 'Редагування світлового ефекту',
  'prompt_light_effect_edit_back_tips': 'Вихід не збереже відредаговані світлові ефекти',
  'prompt_light_effect_edit_gradient_mode_1': 'Відпустіть, щоб встановити ключовим кадром, або продовжуйте перетягувати, щоб скасувати',
  'prompt_light_effect_edit_gradient_mode_2': 'Зараз у режимі внутрішньокадрового градієнта, продовжуйте вибирати кінцеву точку градієнта або %s',
  'prompt_light_effect_edit_gradient_mode_3': 'Зараз у режимі внутрішньокадрового градієнта Ви вибираєте кінцеву точку градієнта. Відпустіть її, щоб вийти з цього режиму',
  'prompt_light_effect_edit_gradient_mode_4':
      'Наразі в режимі внутрішньокадрового градієнта Ви вибираєте кінцеву точку градієнта, Ви також можете пересунути тут, щоб вийти з режиму',
  'text_light_effect_exit_edit_gradient_mode': 'Вийти з цього режиму',
  'prompt_light_effect_edit_already_first_step': "Це вже перший крок!",
  'prompt_light_effect_edit_already_last_step': "Це вже останній крок!",
  'prompt_light_effect_drag_to_delete': 'Перетягніть сюди, щоб видалити',
  'prompt_light_effect_release_to_delete': 'Відпустіть, щоб видалити',
  "title_vehicle_light_effect_exists": "Світлові ефекти, завантажені на ТЗ",
  "text_light_effect_default_package": "Світловий ефект за замовчуванням",
  "text_light_effect_unknown_package": "Невідомий світловий ефект",
  "prompt_enable_light_effect_failed": "Не вдалося застосувати світловий ефект",
  'prompt_confirm_to_delete_light_effect': 'Ви підтверджуєте видалення?',
  'prompt_confirm_to_delete_diy_light_effect': 'Створений світловий ефект не вдасться відновити після видалення. Ви підтверджуєте видалення "%s"?',

  /// sound pack
  "title_vehicle_sound_pack": "Звуковий пакет",
  "title_vehicle_sound_pack_exists": "Звуковий пакет, завантажений на ТЗ",
  "text_default_sound_pack": "Стандартний звуковий пакет",
  "text_unknown_sound_pack": "Невідомий звуковий пакет",
  "prompt_input_sound_pack_name": "Введіть назву звукового пакета",
  "prompt_select_sound_pack_cover": "Виберіть обкладинку",
  "title_diy_single_sound_pack_item": "Створити один звук",
  "title_diy_sound_pack": "Створити звуковий пакет",
  'prompt_confirm_to_use_default_sound_pack': 'Ви підтверджуєте відновлення звукового пакета до заводських налаштувань?',
  "prompt_select_from_local_file": "Виберіть локальний файл",
  "prompt_vehicle_transferring_file": "Будь ласка, тримайте транспортний засіб нерухомо та не керуйте ним під час передачі файлів.",
  "prompt_enable_sound_pack_success": "Успішно",
  "prompt_enable_sound_pack_failed": "Не вдалося ввімкнути звуковий пакет.",
  "prompt_vehicle_storage_capacity_not_enough": "Недостатньо пам'яті на трансопртному засобі для зберігання.",
  "prompt_sound_pack_composing": "Компонування...",
  "prompt_sound_pack_item_file_is_too_large": "Звуковий файл завеликий",
  "title_custom_sound_pack": "Створити звуковий пакет",
  "title_complete_sound_pack_info": "Повна інформація про звуковий пакет",
  "btn_compose": "Скомпонувати",
  "title_sound_pack_compose": "Скомпонувати звуковий пакет",
  "prompt_sound_pack_compose_succeed": "Компонування успішне",
  "prompt_sound_pack_compose_failed": "Не вдалося скомпонувати звуковий пакет",
  "title_sound_pack_audition": "Прослуховування",
  "title_select_sound_pack_item": "Виберіть звук",
  'prompt_confirm_to_delete_sound_pack': 'Ви підтверджуєте видалення?',
  'prompt_confirm_to_delete_sound_pack_in_vehicle': "Не можна відновити звуковий пакет у транспортному засобі після видалення. Підтверджуєте видалення? '%s'?",
  'prompt_confirm_to_delete_diy_sound_pack': 'Створений звуковий пакет не вдасться відновити після видалення, Ви підтверджуєте видалення "%s"?',
  'text_sound_pack_file_local': 'Локально',
  'text_sound_pack_file_record': 'Запис',
  'text_sound_pack_file_library': 'Бібліотека звуків',
  'text_sound_pack_item_duration': 'Тривалість: ',
  'text_sound_pack_item_size': 'Розмір: ',
  'prompt_sound_pack_compose_item_cannt_be_empty': "Усі елементи не можуть бути порожніми",
  'title_sound_pack_diy_create_from_template': 'Створити з шаблону',
  'title_sound_pack_diy_create_directly': 'Створити безпосередньо',
  'title_sound_pack_diy_select_template': 'Виберіть шаблон',
  "title_sound_pack_audition_on_phone": "Прослухати на телефоні",
  "title_sound_pack_audition_on_vehicle": "Прослухати на ТЗ",

  ///
  /// Mine
  ///
  'btn_authorized_vehicles': 'Мої ТЗ',
  'btn_vehicle_authorization': 'Авторизація власника',
  'btn_customer_service': 'Служба підтримки',
  'title_find_my_vehicle': 'Знайти мій транспортний засіб',
  'title_unit_metric_imperial': 'Метричні/британські одиниці',
  'text_unit_metric': 'Метричні',
  'text_unit_imperial': 'Британські',
  'title_language': 'Мова',
  'text_follow_system': 'Як в системі',
  'title_select_language': 'Оберіть мову',
  'title_account_security': 'Обліковий запис і безпека',
  'title_clear_cache': 'Очистити кеш',
  'prompt_clear_cache_tips': 'Ви підтверджуєте очищення кешу?',
  'title_app_about': 'Про додаток',
  'text_app_version': '%s',

  'title_message_center': 'Центр повідомлень',
  'title_user_info': 'Персональна інформація',
  'btn_take_a_photo': 'Зробити фото',
  'btn_select_from_album': 'Вибрати з альбому',

  'title_scan_qrcode': 'Відскануйте QR-код',

  /// About
  "user_agreement": "Угода користувача",
  "privacy_policy": "Політика конфіденційності",
  'inmotion_company': 'INMOTION',

  /// personal info
  'title_avatar': 'Аватар',
  'title_nickname': 'Псевдонім',
  'title_username': "Ім'я користувача",
  'title_signature': 'Підпис',
  'title_modify_nickname': 'Змінити псевдонім',
  'title_modify_username': "Змінити ім'я користувача",
  'title_modify_signature': 'Змінити підпис',
  'prompt_nickname_limit': '6-20 символів',
  'prompt_signature_limit': '0-100 символів',

  /// my vehicle
  'title_my_vehicles': 'Мої транспортні засоби',
  'title_delete_authorized_vehicle': 'Видалити авторизацію власника',
  'prompt_delete_authorized_vehicle_tips': 'Видалення транспортного засобу скасує авторизацію власника транспортного засобу. Ви підтверджуєте його видалення?',
  'title_delete_vice_owner': 'Видалити віце-власника',
  'prompt_delete_vice_owner_tips': 'Ви підтверджуєте видалення віце-власника?',
  'title_vehicle_details': 'Інформація про ТЗ',
  'title_vehicle_info': 'Транспортний засіб',
  'prompt_vehicle_info_updated_at': 'Інформація була оновлена: %s',
  'title_vehicle_model': 'Модель',
  'title_activated_date': 'Активовано',
  'title_total_mileage': 'Загальний пробіг',
  'title_riding_record': 'Рекорд поїздки',
  "title_bluetooth_name": "Bluetooth-ім'я",
  "text_vehicle_remaining_mileage": "Залишилось пробігу: %s",
  'title_vehicle_owner_info': 'Власник',
  'title_vehicle_main_owner': 'Основний власник',
  'btn_go_to_authorize_as_owner': 'Перейдіть до авторизації',
  'prompt_not_owner_and_go_to_authorize_as_owner': 'Лише власник поточного транспортного засобу може це зробити. Хочете авторизуватися як власник зараз?',
  'text_vehicle_info_owner_me_suffix': ' (Я)',
  'title_vehicle_vice_owner': 'Співвласник',
  'title_vehicle_no_owner': 'Немає',
  'title_transfer_vehicle_main_owner': 'Передача основного власника',
  'prompt_transfer_vehicle_main_owner_tips':
      'Після передачі користувач «%s» стане основним власником поточного транспортного засобу, а Ви станете співвласником.\n Ви підтверджуєте передачу?',
  'title_invite_as_vehicle_vice_owner': 'Запросити',
  'prompt_invite_as_vehicle_vice_owner_tips': 'Скористайтеся додатком INMOTION, щоб відсканувати QR-код та авторизуватися як співвласник.',
  'title_vehicle_authorization': 'Авторизація ТЗ',
  'prompt_authorize_current_connected_vehicle_tips': 'Транспортний засіб %s наразі підключено, чи хочете Ви одразу автентифікуватися як власник?',
  'prompt_input_sn': 'Будь ласка, \nвведіть серійний номер',
  'title_vehicle_authorization_requests': 'Запит історії',
  'title_sent_vehicle_authorization_requests': 'Надіслано',
  'title_received_vehicle_authorization_requests': 'Отримано',
  'prompt_vehicle_authorization_apply_to': 'Застосовано до %s',
  'prompt_vehicle_authorization_apply_from': '%s застосовано до мене',
  'prompt_vehicle_authorization_waiting': 'Очікування',
  'text_status_pending': 'Очікує',
  'text_status_approved': 'Одобрено',
  'text_status_rejected': 'Відхилено',
  'text_status_expired': 'Закінчився',

  /// vehicle authorization
  'prompt_vehicle_authorization_apply_success': 'Заявка успішно надіслана.',
  'prompt_vehicle_authorization_success': 'Успішно авторизовано як основного власника',
  'prompt_vehicle_authorized_as_vice_owner_tips': 'У цього транспортного засобу вже є основний власник, чи хочете Ви авторизуватися як ще один власник??',
  'prompt_vehicle_authorized_as_vice_owner_success': 'Успішно авторизовано як ще один власник',
  'prompt_vehicle_authorization_failed': 'Помилка авторизації',

  /// customer service
  'title_message_board': 'Дошка оголошень',
  'prompt_leave_message_tips': "Будь ласка, залиште повідомлення і ми зв'яжемося з Вами найближчим часом.",
  'btn_leave_a_message': 'Залишити повідомлення',
  'prompt_please_leave_a_message': 'Будь ласка, залиште повідомлення',
  'btn_chat_menu_picture': 'Зображення',
  'btn_chat_menu_video': 'Відео',
  'prompt_leave_message_success': 'Успішно',
  'prompt_leave_message_failed': 'Не вдалося залишити повідомлення',
  'prompt_content_couldnt_be_empty': "Вміст не може бути порожнім.",
  'prompt_customer_service_waiting_for_access': 'Очікування доступу',
  'prompt_customer_service_queue_number': 'Людей у черзі попереду Вас: %s',
  'prompt_customer_service_offline': 'Обслуговування клієнтів офлайн',
  'prompt_customer_service_session_ended': 'Сеанс закінчено',
  'btn_customer_service_evaluate': 'Оцініть',
  'prompt_input_question_to_consult': 'Будь ласка, введіть питання, з яким Ви хочете отримати консультацію',

  "title_official_recommends": "Рекомендації", //

  /// riding record
  "text_riding_record_summary": "Загалом %sгодин, %sКг збережених викидів вуглецю.",

  ///
  /// errors
  ///
  'prompt_request_failed': 'Запит невдався',
  'prompt_request_failed_timeout': 'Час очікування запиту минув',
  'prompt_request_failed_network': 'Помилка мережі',

  'prompt_unauthenticated_request': 'Сеанс входу закінчився, увійдіть знову!',
  'prompt_unknown_error': 'Невідома помилка',
  'prompt_operate_too_frequently': 'Операції надто часті, спробуйте пізніше.',
  'prompt_file_download_failed': 'Помилка завантаження файлу',
  'prompt_unknown_product_model': 'Невідома модель продукту',
};
