const Map<String, String> zh_HK = {
  ///
  /// Common
  ///
  "prompt_welcome_to_inmotion": "你好，\n歡迎來到樂行天下",
  "btn_more": "更多",
  "btn_view_more": "查看更多",
  "btn_cancel": "取消",
  "btn_exit": "退出",
  "btn_confirm": "確認",
  "btn_complete": "完成",
  "btn_submit": "提交",
  "btn_i_see": "我知道了",
  "btn_skip": "跳過",
  "btn_next_step": "下一步",
  "btn_save": "保存",
  "btn_save_image": "保存圖片",
  "btn_edit": "編輯",
  "btn_preview": "預覽",
  "btn_rename": "重命名",
  "btn_delete": "刪除",
  "btn_publish": "發布",
  "tab_vehicle": "車輛",
  "tab_moment": "動態",
  "tab_discover": "發現",
  "tab_mine": "我的",
  "prompt_page_error": "出錯了",
  "btn_share": "分享",
  "btn_report": "舉報",
  "btn_enable": "啟用",
  "btn_enabled": "已啟用",
  "btn_retry": "重試",
  "prompt_title_warning": "警告",
  "prompt_title_tips": "提示",
  "prompt_title_warm_tips": "溫馨提示",
  "prompt_confirm_to_cancel": "確認要取消嗎？",
  "prompt_failed": "失敗",
  "btn_agree": "同意",
  'btn_reject': '拒絕',
  "btn_need_help": "需要幫助？",
  "btn_common_problem": "常見問題",
  "page_message_center": "消息中心",
  "title_sys_message": "系統消息",
  "title_social_message": "互動消息",
  "btn_save_and_share": "保存並分享",
  "prompt_saved": "保存成功",
  "prompt_save_failed": "保存失敗",
  "prompt_updated": "修改成功",
  "prompt_update_failed": "修改失敗",
  "prompt_data_empty": "數據為空",
  "prompt_loading": "正在加載...",
  "prompt_load_failed": "加載失敗",
  "prompt_copied": "複製成功",
  "prompt_action_failed": "操作失敗",
  "prompt_press_again_to_exit": "再按一次退出",

  "datetime_just_now": "剛剛",
  "datetime_x_minutes_ago": "%s分鐘前",
  "datetime_yesterday_x": "昨天 %s",

  "unknown": "未知",

  ///
  /// Account
  ///

  "prompt_auto_register_if_account_not_exists": "未註冊的手機號驗證後自動創建賬戶",
  "btn_login": "登錄",
  "btn_register": "註冊賬號",
  "title_register": "註冊",
  "title_cn_phone_quick_login": "一鍵登錄",
  "prompt_input_phone": "請輸入手機號",
  "prompt_input_email": "請輸入郵箱賬號",
  "prompt_input_email_or_username": "請輸入郵箱賬號/用戶名",
  "prompt_input_verification_code": "請輸入驗證碼",
  "prompt_input_password": "請輸入密碼",
  "prompt_input_a_valid_phone": "請輸入正確的手機號碼！",
  "prompt_input_a_valid_email": "請輸入正確的郵箱賬號！",
  "prompt_input_a_valid_email_or_username": "請輸入正確的郵箱/用戶名！",
  "prompt_input_a_valid_password": "請輸入正確的密碼！",
  "btn_forgot_password": "忘記密碼",
  "btn_reset_password": "重置密碼",
  "btn_login_via_password": "賬號密碼登錄",
  "btn_login_via_verification_code": "驗證碼登錄",
  "btn_request_verification_code": "獲取驗證碼",
  "btn_request_sms_verification_code": "獲取短信驗證碼",
  "prompt_verification_code_has_sent_to": "驗證碼已發送至%s",
  "btn_resend": "重新獲取",
  "title_user_agreement": "《用戶協議》",
  "title_privacy_policy": "《隱私政策》",
  "prompt_register_agreement_tips": "註冊或登錄即表示您已同意%s和%s",
  "title_select_country_or_region": "選擇國家和地區",
  "btn_modify_phone": "修改手機號",
  "btn_modify_email": "修改郵箱",
  "btn_bind_phone": "綁定手機號",
  "btn_modify_password": "修改密碼",
  "phone_number": "手機號",
  "email": "郵箱",
  "btn_register_via": "使用%s註冊",
  "btn_bind_via": "使用%s綁定",
  "btn_reset_password_via": "使用%s找回",
  "btn_bind_account": "綁定賬號",
  "prompt_password_limit_tips": "請輸入6-20個數字及英文字符，不可以是純數字",
  "prompt_empty_password": "密碼不能為空",
  "title_bind_social_account": "第三方賬號綁定",
  "prompt_social_account_auth_failed": "授權失敗",
  "prompt_bind_social_account_tips": "*綁定第三方賬號後，你可以通過以上賬號登錄樂行",
  'state_bound': '已綁定',
  'state_not_bound': '未綁定',
  'prompt_unbind_social_account_tips': '解除綁定後，你將無法使用%s登錄樂行，確定解綁嗎？ ',
  'btn_logout': '退出登錄',
  'prompt_logout_tips': '確定要退出登錄嗎？ ',
  "title_operation_verification": "操作驗證",
  "prompt_operation_verification_tips": "當前操作需要驗證，請通過以下任意方式驗證",
  "title_verify_operation_via": "通過%s驗證",
  "prompt_operation_verification_expired": "請先進行安全驗證",
  "text_none": "無",

  /// 阿里雲錯誤碼
  "prompt_cn_phone_auth_no_sim_card": "未檢測到sim卡",
  "prompt_cn_phone_auth_unknown_operator": "無法判斷運營商",
  "prompt_cn_phone_auth_network_not_enable": "移動數據網絡未開啟",
  "prompt_cn_phone_auth_unknown": "未知異常",

  ///
  /// Vehicle
  ///
  "btn_search_vehicle": "搜索車輛",
  "prompt_had_connected_before": "以前連接過",
  "title_vehicle_activation": "激活",
  "prompt_wait_for_activation_tips_finished": "請先閱讀觀看安全提醒視頻",
  "prompt_had_read_activation_tips": "我已認真閱讀以上安全提醒並已知可能存在的風險",
  "btn_activate": "立即激活",
  "prompt_activated": "激活成功!",
  "prompt_activate_failed": "激活失敗",
  "prompt_activate_canceled": "激活已取消",
  "prompt_authorize_as_owner_after_activation": "APP內鎖車等操作需要車主認證，是否立即認證成為車主？",
  "prompt_authorize_as_owner_later_after_activation": "您也可以在“我的-車主認證”中進行車主認證",
  "prompt_set_vehicle_password_failed": "設置密碼失敗",
  "prompt_set_vehicle_password_later_after_activation": "您也可以在“車輛-設置-車輛密碼”中設置車輛密碼",
  "prompt_bluetooth_disabled": "手機藍牙未啟用",
  "prompt_location_disabled": "手機位置服務未啟用",
  "prompt_no_bluetooth_permission": "藍牙服務未開啟",
  "prompt_no_location_permission": "未授予位置信息權限",
  "prompt_no_scan_bluetooth_permission": "未授予藍牙掃描權限",
  "prompt_no_connect_bluetooth_permission": "未授予藍牙連接權限",
  "prompt_no_device_found": "暫未搜索到設備",
  "prompt_tap_to_connect": "輕觸以下設備發起連接",
  "prompt_scanning": "正在搜索...",
  "prompt_connecting": "正在連接...",
  "prompt_connection_canceled": "連接已取消",
  "prompt_connected": "連接成功",
  "prompt_connection_timeout": "連接超時",
  "prompt_connection_failed": "連接失敗",
  "prompt_unsupported_models": "不支持的車型",
  "btn_enable_bluetooth": "打開手機藍牙",
  "btn_enable_location": "打開手機位置服務",
  "btn_request_bluetooth_permission": "申請藍牙權限",
  "btn_request_location_permission": "申請位置信息權限",
  "btn_scan_again": "重新搜索",
  "btn_cancel_connection": "取消連接",
  "prompt_why_need_to_enable_location": "為什麼需要開啟位置服務？",
  "prompt_why_need_location_permission": "為什麼需要位置信息權限？",
  "prompt_why_do_i_couldnt_find_vehicles": "為什麼搜索不到我的設備？",
  "btn_view_solutions": "查看解決方案",
  "prompt_connect_failed_server_ip_service_error": "服務器異常，我們會盡快修復此問題，請稍候重試。",
  "prompt_connect_failed_unknown_model": "未能正確識別當前車輛型號，暫無法使用APP功能。\n詳情請諮詢樂行天下官方客服。",
  "prompt_connect_failed_unknown_sn": "當前車輛SN異常，暫無法使用APP功能。\n詳情請諮詢樂行天下官方客服。",
  "prompt_connect_failed_vehicle_locked": "當前車輛處於丟失模式，如果您為該車車主，請聯繫樂行天下官方客服解除。",
  "prompt_connect_failed_vehicle_lost_mode": "當前車輛處於丟失模式，如果您為該車車主，請前往APP內解除丟失模式。",

  "text_vehicle_ride_time": "騎行時長",
  "text_vehicle_ride_mileage": "本次里程",
  "text_vehicle_max_speed": "最高速度",
  "text_vehicle_ave_speed": "平均速度",
  "text_vehicle_total_mileage": "總里程",
  "text_vehicle_dynamic_speed_limit": "動態限速",
  "text_vehicle_power": "實時功率",
  "text_vehicle_max_power": "最大功率",
  "text_vehicle_mos_temp": "MOS溫度",
  "text_vehicle_consumption": "能耗",
  "text_vehicle_last_ride_mileage": "上次里程",
  "text_vehicle_last_ride_time": "上次騎行時長",
  "text_vehicle_last_max_speed": "上次最高速度",
  "text_vehicle_speed": "實時速度",
  "text_vehicle_battery_discharge_current": "電池輸出電流",
  "text_vehicle_battery_voltage": "電池電壓",
  "text_vehicle_battery_output_power": "電池輸出功率",
  "text_vehicle_motor_output_power": "電機輸出功率",
  "text_vehicle__motor_torque": "電機扭矩",
  "text_vehicle_remaining_battery": "剩餘電量",
  "text_vehicle_output_rate": "輸出矢量電壓百分比",
  "text_vehicle_dynamic_current_limit": "實時過流閾值",

  "text_vehicle_motor_temp": "電機溫度",
  "text_vehicle_battery_temp": "電池溫度",
  "text_vehicle_motherboard_high_temp": "主板高溫區溫度",
  "text_vehicle_driver_board_cpu_temp": "驅動板CPU溫度",
  "text_vehicle_imu_temp": "IMU溫度",

  "text_gps_speed": "GPS速度",

  "prompt_status_connecting": "連接中",
  "prompt_status_connected": "已連接",
  "prompt_status_disconnected": "未連接",
  "prompt_vehicle_disconnected": "設備未連接",
  "prompt_no_connected_vehicles_yet": "車輛列表為空",
  "prompt_current_connected_vehicle": "當前連接",
  "prompt_last_connected_at": "上次連接：%s",
  "title_switch_vehicle": "切換車輛",
  "btn_disconnect_and_scan": "斷開並蒐索",
  "btn_scan": "搜索",
  "btn_detailed_data": "詳細數據",
  "title_about_vehicle": "關於車輛",
  "title_battery_info": "電池信息",
  "title_customer_service": "在線客服",
  "title_faq": "常見問題",

  "title_gps_riding_tracks": "我的軌跡",
  "title_vehicle_riding_record": "騎行記錄",

  "text_vehicle_riding_record_mileage": "本次里程：%s",
  "text_vehicle_riding_record_max_speed": "最高速度：%s",

  "title_vehicle_riding_report": "騎行報告",
  "prompt_invalid_riding_track": "本次行程無效",

  "title_basic_battery_info": "基本信息",
  "text_battery_voltage": "電壓",
  "text_battery_charge_voltage": "充電電壓",
  "title_detailed_battery_info": "電池組詳細信息",
  "text_battery_detected_status": "是否有效",
  "text_battery_detected": "有效",
  "text_battery_not_detected": "無效",
  "text_battery_enable_status": "是否開啟",
  "text_battery_enabled": "開啟",
  "text_battery_disabled": "未開啟",
  "text_battery_error_status": "是否故障",
  "text_battery_ok": "正常",
  "text_battery_error": "故障",
  "text_battery_signal_logic_error": "信號邏輯異常",

  "title_battery_cells_voltage": "電池電芯電壓",

  "title_bms_basic_info": "Basic Info",
  "text_bms_battery_sn": "Battery SN",
  "text_bms_manufacture_date": "Manufacture Date",
  "text_bms_full_charge_cycles": "Full Charge Cycles",
  "text_bms_software_version": "BMS Software Version",
  "text_bms_hardware_Version": "BMS Hardware Version",
  "title_bms_data_and_status": "Data & Status",
  "text_bms_voltage": "Voltage",
  "text_bms_charge_state": "Charge State",
  "text_bms_charge_current": "Charge Current",
  "text_bms_discharge_current": "Discharge Current",
  "text_bms_charge_mos_state": "Charge MOS",
  "text_bms_discharge_mos_state": "Discharge MOS",
  "text_bms_error_status": "Error Status",
  "text_bms_warning_status": "Warning Status",
  "text_bms_protection_status": "Protection Status",
  "text_bms_cell_balancing_status": "Cell Balancing",
  "text_bms_max_cell_voltage": "Max. Cell Voltage",
  "text_bms_min_cell_voltage": "Min. Cell Voltage",
  "text_bms_charge_mos_temp": "Charge MOS Temp",
  "text_bms_discharge_mos_temp": "Discharge MOS Temp",
  "text_bms_cells_temp": "Cells Temperature",
  "text_bms_cells_voltage": "Cells Voltage",

  /// 設置
  "title_vehicle_settings": "車輛設置",
  "prompt_operation_succeed": "操作成功",
  "prompt_operation_failed": "操作失敗",
  "title_vehicle_password": "車輛密碼",
  "text_vehicle_password_disabled": "關閉",
  "text_vehicle_password_gesture": "手勢密碼",
  "text_vehicle_password_slide": "滑動解鎖",
  "text_vehicle_password_number": "數字密碼",
  "title_modify_vehicle_password": "修改密碼",
  "title_set_vehicle_password": "設置密碼",
  "prompt_vehicle_number_password_tips": "請輸入4位或6位數字密碼",
  "title_vehicle_userinfo": "車輛用戶信息",
  "title_vehicle_userinfo_avatar": "頭像",
  "title_vehicle_userinfo_name": "車輛名稱",
  "prompt_vehicle_userinfo_name_tips": "請輸入1–16位字母、數字和英文符號",
  "title_choose_setting_item": "選擇設置項",
  "vehicle_setting_item_limit_speed_25": "將最大速度限定在25km/h",
  "vehicle_setting_item_limit_speed": "限速",
  "vehicle_setting_item_drive_mode": "驅動模式",
  "vehicle_setting_item_drive_mode_normal": "舒適模式",
  "vehicle_setting_item_drive_mode_normal_tips": "踏板反應柔和，加減速輕鬆",
  "vehicle_setting_item_drive_mode_off_road": "越野模式",
  "vehicle_setting_item_drive_mode_off_road_tips": "踏板有很強的剛度，越野和爬坡時有更出色的表現",
  "vehicle_setting_item_pedestrian_mode_limit_speed": "最大速度（行人模式）",
  "vehicle_setting_item_pedal_sensitivity": "踏板靈敏度",
  "vehicle_setting_item_spilt_mode": "分離式體感",
  "vehicle_setting_item_spilt_mode_speeding": "加速",
  "vehicle_setting_item_spilt_mode_breaking": "剎車",
  "vehicle_setting_item_power_assist": "動力輔助",
  "vehicle_setting_item_acc_assist": "加速輔助",
  "vehicle_setting_item_brake_assist": "減速輔助",
  "vehicle_setting_item_cruise": "定速巡航",
  "vehicle_setting_item_ride_assist": "騎行輔助",
  "vehicle_setting_item_zero_start": "零速啟動",
  "vehicle_setting_item_assist_balance": "輔助平衡",
  "vehicle_setting_item_load_detect": "負載檢測",
  "vehicle_setting_item_noload_detect": "空載檢測",
  "vehicle_setting_item_up_hill_assist": "上坡輔助",
  "vehicle_setting_item_down_hill_assist": "下坡輔助",
  "vehicle_setting_item_overspeed_alarm": "超速報警",
  "vehicle_setting_item_lock": "鎖定",
  "vehicle_setting_item_password": "密碼",
  "vehicle_setting_item_diagnosis": "故障檢測",
  "vehicle_setting_item_headlight": "照明燈",
  "vehicle_setting_item_headlight_brightness": "照明燈亮度",
  "vehicle_setting_item_drl": "日行燈",
  "vehicle_setting_item_low_beam_headlight": "近光燈",
  "vehicle_setting_item_low_beam_headlight_brightness": "近光燈亮度",
  "vehicle_setting_item_high_beam_headlight": "遠光燈",
  "vehicle_setting_item_high_beam_headlight_brightness": "遠光燈亮度",
  "vehicle_setting_item_auto_headlight": "自動照明燈",
  "vehicle_setting_item_auto_headlight_brightness_threshold": "自動照明燈光照強度開關閾值",
  "vehicle_setting_item_auto_low_high_beam": "自動遠近光燈",
  "vehicle_setting_item_auto_low_high_beam_switch_speed_threshold": "自動遠近光燈切換速度閾值",
  "vehicle_setting_item_light_effect": "氛圍燈",
  "vehicle_setting_item_light_effect_mode": "氛圍燈模式",
  "vehicle_setting_item_light_effect_front": "前氛圍燈",
  "vehicle_setting_item_light_effect_rear": "後氛圍燈",
  "vehicle_setting_item_light_diy": "DIY",
  "vehicle_setting_item_auto_turn_signal": "自動轉向燈",
  "vehicle_setting_item_audio_state": "語音開關",
  "vehicle_setting_item_volume": "音量",
  "vehicle_setting_item_audio_package": "語音包",
  "vehicle_setting_item_standby_time": "待機時長",
  "vehicle_setting_item_spin_kill_btn": "防飛轉按鍵",
  "vehicle_setting_item_sound_wave": "主動聲浪",
  "vehicle_setting_item_sound_wave_sensitivity": "主動聲浪靈敏度",
  "vehicle_setting_item_estimated_remainder_range": "續航智能估算",
  "vehicle_setting_item_user_info": "車輛用戶信息",
  "vehicle_setting_item_fan_quiet_mode": "風扇靜音模式",
  "vehicle_setting_item_forced_fan": "強制風冷",
  "vehicle_setting_item_transport_mode": "運輸模式",
  "vehicle_setting_item_low_battery_safe_mode": "低電安全模式",
  "vehicle_setting_item_auto_screen_off": "自動息屏",
  "vehicle_setting_item_speed_unit": "公英制",
  "vehicle_setting_item_sn": "SN",
  "vehicle_setting_item_activate_date": "激活日期",
  "vehicle_setting_item_total_mileage": "總里程",
  "vehicle_setting_item_hmic_board_version": "人機板",
  "vehicle_setting_item_bt_board_version": "藍牙板",
  "vehicle_setting_item_driver_board_version": "驅動板",
  "vehicle_setting_item_driver_board_temp": "主板溫度",
  "vehicle_setting_item_riding_mode": "騎行模式",
  "vehicle_setting_riding_mode_eco": "ECO 經濟模式",
  "vehicle_setting_riding_mode_eco_tips": "平穩加速，適合初學者",
  "vehicle_setting_riding_mode_normal": "D 正常模式",
  "vehicle_setting_riding_mode_sport": "S 運動模式",
  "vehicle_setting_riding_mode_sport_tips": "運動強勁，適合高級騎行者",
  "vehicle_setting_riding_pedestrian_mode": "行人模式",
  "vehicle_setting_riding_pedestrian_mode_tips": "使推車更輕鬆",
  "vehicle_setting_item_riding_mode_euc_normal": "普通",
  "vehicle_setting_item_riding_mode_euc_normal_tips": "普通模式具有更高的安全係數適合大部分用戶使用。",
  "vehicle_setting_item_riding_mode_euc_fancier": "發燒者",
  "vehicle_setting_item_riding_mode_euc_fancier_tips": "發燒者模式具有更大的功率輸出使您可以騎行至更高速度。",
  "prompt_cannt_set_sport_mode_when_limit_speed_25kmph_enabled": "當開啟“將最大速度限定在25km/h”時，無法啟用“S 運動模式“",
  "prompt_cannt_enable_limit_speed_25kmph_when_sport_mode_enabled": "當啟用了“S 運動模式”時，無法開啟“將最大速度限定在25km/h”",
  "vehicle_setting_item_berm_angle_mode": "賽道傾角模式",
  "prompt_unlock_factory_safe_speed_limit": "出於安全考慮，車輛總里程超過30km後才可以將最大限速調整至90km/h。%s",
  "prompt_unlock_factory_safe_speed_limit_not_now": "出於安全考慮，車輛總里程超過30km後才可以將最大限速調整至90km/h。當前還需騎行%s",
  "prompt_unlock_now": "立即解除>>",

  "warning_unlock_v13_factory_speed_limit":
  "我們非常重視您的騎行安全，為了更好的保障您的人身權益，請了解並認真閱讀本聲明，確保您充分理解本聲明內容。\n\n1. 您理解並知悉您當前正在試圖解鎖車輛最大限速，此限制解除後，您將可以調整最大限速至90km/h。2. 您理解並知悉超高速騎行可能存在的風險，並承諾自行承擔所有風險。 \n3. 您有義務知悉您所在地區關於騎行電動獨輪車的全部法律法規，並在騎行V13時，嚴格遵守所適用的法律法規和政策規定。請勿在當地法律禁止的地區騎行V13。 \n4. 請您不要允許未認真閱讀使用說明或不熟悉V13騎行安全注意事項等內容的人騎行您的車輛。 \n5. 在每次騎行前，請務必檢查產品及配件是否完好，避免使用非原裝電池、配件，禁止擅自拆解、破解和改裝本產品及配件，由此可能造成的後果和損失將由您自行承擔。 \n\n請您審慎閱讀並選擇接受或不接受本聲明。在您同意本聲明後，才能解鎖車輛最大限速。您的“同意”行為將視為對本免責聲明的接受。若您對本免責聲明存在任何疑問，請點擊“取消”。 ",
  "warning_enable_berm_angle_mode": "開啟後，觸發車輛傾倒保護的傾角將會更大，這意味著在你嘗試手動側傾放置車輛的過程中，可能會由於前後平衡角度的微小變化導致車輛極不易受控制。此舉可能會對你或周邊環境造成危害，你已知曉其中的風險，並仍決定開啟嗎？\n開啟或關閉後，按下一次防飛轉按鍵後生效。",
  "warning_disable_berm_angle_mode": "開啟或關閉後，按下一次防飛轉按鍵後生效。",

  "title_vehicle_balance_angle": "平衡角度",
  "title_vehicle_calibration": "車輛校正",
  "title_vehicle_balance_angle_calibration": "平衡角度校正",
  "prompt_vehicle_balance_angle_calibration_desc": "當平衡角度調為0°後，車輛在水平地面仍前傾或後傾，可通過平衡角度校正改善此現象。%s",
  "prompt_vehicle_balance_angle_calibration": "請按住提手，保持車輛豎直方向始終垂直於水平地面",
  "title_vehicle_turning_calibration": "轉彎前傾校正",
  "title_vehicle_turning_calibration_desc": "此操作可改善車輛轉彎時的前傾現象。%s",
  "text_view_calibration_guide": "查看校正指南>>",
  "title_motor_self_adjustment": "電機自適應",
  "prompt_motor_self_adjustment_desc": "啟動後電機將自動運轉約1分鐘，為了您的安全，請確保車輛在傾到狀態，切勿碰觸車輪！",
  "prompt_clear_motor_self_adjustment_effect_desc": "如果進行自適應後騎行效果沒有改善，建議%s",
  "title_clear_motor_self_adjustment_effect": "清除電機自適應效果",
  "prompt_motor_self_adjustment_in_progress": "正在進行電機自適應...",
  "prompt_motor_self_adjustment_terminated": "車輛已終止自適應",
  "prompt_motor_self_adjustment_succeed": "電機自適應成功",
  "prompt_motor_self_adjustment_finished": "電機自適應完成",
  "prompt_motor_self_adjustment_timeout": "電機自適應超時",
  "prompt_confirm_to_clear_motor_self_adjustment_effect": "確認要清除電機自適應效果嗎？",

  "prompt_motor_self_check_in_progress": "正在自檢...",
  "prompt_motor_self_check_terminated": "車輛已終止自檢",
  "prompt_motor_self_check_passed": "自檢通過",
  "prompt_motor_self_check_not_passed": "自檢不通過",
  "prompt_motor_self_check_timeout": "自檢超時",
  "prompt_motor_self_check_failed": "自檢失敗",

  "title_vehicle_acc_calibration": "油門校正",
  "title_vehicle_brake_calibration": "把手校正",
  "title_vehicle_gyro_calibration": "姿態傳感器校正",
  "prompt_vehicle_acc_calibration_tips": "開始校正後，分別讓油門把手保持在最大值和最小值各1s，請在5s內完成指定的校正操作。",
  "prompt_vehicle_brake_calibration_tips": "開始校正後，分別讓剎車把手保持在最大值和最小值各1s，請在5s內完成指定的校正操作。",
  "prompt_vehicle_gyro_calibration_tips": "請扶正車身，保持車輛踏板與地面平行，然後開始校正並等待校正完成。",
  "prompt_cannt_start_vehicle_acc_calibration_when_zero_start_enabled": "零速啟動模式下無法校準油門把手！",

  "prompt_calibration_succeed": "校準成功",
  "prompt_calibration_failed": "校準失敗",
  "prompt_calibration_timeout": "校準超時",

  "title_vehicle_factory_reset": "恢復出廠設置",
  "prompt_vehicle_confirm_to_factory_reset": "確定恢復出廠設置嗎？",
  "prompt_vehicle_confirm_to_factory_reset_desc": "將所有設置以及語音還原到出廠默認狀態",
  "prompt_vehicle_ezcan_confirm_to_factory_reset_desc": "恢復出廠設置可能會需要一分鐘左右，請勿關閉App",
  "prompt_vehicle_ezcan_factory_reset_succeed": "恢復成功，請關機等待10秒後重新開機",
  "prompt_vehicle_factory_reset_succeed": "恢復出廠設置成功！",

  "prompt_vehicle_euc_need_motor_free": "請將車輛用腳撐撐起或側傾放倒",

  "title_vehicle_firmware_update": "固件更新",

  /// 助力模式
  "title_vehicle_assistant_mode": "助力模式",
  "text_vehicle_assistant_mode_none": "無助力",
  "prompt_vehicle_assistant_mode_none_desc": "此檔位會關閉踩踏騎行助力，由用戶通過踩踏產生騎行驅動力",
  "text_vehicle_assistant_mode_medium": "輕助力",
  "prompt_vehicle_assistant_mode_medium_desc": "此檔位有輕微踩踏助力，適合平路休閒騎力s",
  "text_vehicle_assistant_mode_max": "強助力",
  "prompt_vehicle_assistant_mode_max_desc": "此檔位會強化踩踏助力，適合頻繁上下坡騎行，此模式會輕微增加耗電速度。",

  /// L8 氛圍燈
  "text_light_effect_mode_0": "單色呼吸",
  "text_light_effect_mode_1": "單色水波紋",
  "text_light_effect_mode_2": "單色流星",
  "text_light_effect_mode_3": "單色雙向流水",
  "text_light_effect_mode_4": "單色漸變呼吸",
  "text_light_effect_mode_5": "單色漸變流水",
  "text_light_effect_mode_6": "多彩呼吸",
  "text_light_effect_mode_7": "多彩流水",
  "title_light_effect_color": "氛圍燈顏色",

  /// v12 氛圍燈
  "text_light_effect_mode_close": "關閉",
  "text_light_effect_mode_audio_package": "燈效包",
  "text_light_effect_mode_audio_package_change": "修改燈效包",
  "text_light_effect_mode_follow_music": "跟隨音樂",
  "text_light_effect_mode_follow_speed": "跟隨速度",
  "text_light_effect_mode_follow_speed_1": "流水",
  "text_light_effect_mode_follow_speed_2": "常亮",

  /// 故障檢測
  "title_vehicle_diagnosis": "故障檢測",
  "prompt_vehicle_diagnosis_result": "檢測結果",
  "prompt_vehicle_diagnosis_ok": "暫未發現已知故障和警告",
  "prompt_vehicle_diagnosis_abnormal": "車輛狀況異常",
  "title_vehicle_diagnosis_history": "歷史檢測記錄",
  "title_view_history": "查看歷史記錄",
  "title_vehicle_upload_log": "上傳日誌",
  "prompt_upload_log_tips": "上傳日誌可能需要幾分鐘時間，請耐心等待",

  /// 遠程診斷
  "title_remote_diagnosis": "遠程診斷",
  "prompt_remote_diagnosis_tips": "請在樂行團隊的指導下進行此操作",
  "prompt_remote_diagnosis_enter_failed": "進入在線診斷模式失敗！",
  "prompt_remote_diagnosis_remote_disconnected": "遠程設備已斷開",
  "prompt_remote_diagnosis_disconnected": "連接已斷開",
  "prompt_remote_diagnosis_waiting_remote_connection": "您當前已進入在線診斷模式！正在等待遠程設備接入",
  "prompt_remote_diagnosis_confirm_to_cancel": "當前正在等待遠程設備接入，確定退出嗎？",
  "prompt_remote_diagnosis_waiting_remote_timeout": "進入失敗，等待遠程設備接入超時",
  "prompt_remote_diagnosis_in_progress": "正在進行在線診斷，請手機確保處於車輛附近且網絡暢通，不要關閉手機屏幕",

  "prompt_upload_log_success": "日誌上傳成功",
  "prompt_upload_log_failed": "日誌上傳失敗",

  /// 固件更新
  "text_vehicle_current_firmware_version": "當前版本：%s",
  "title_vehicle_current_firmware_version": "當前版本",
  "prompt_new_firmware_version_found": "發現新版本",
  "prompt_cannt_interrupt_firmware_updating": "請繼續完成升級以正常使用",
  "prompt_no_new_firmware_version_found": "暫無新版本",
  "btn_update_firmware": "立即更新",
  "title_firmware_update_notes": "注意事項",
  "text_firmware_update_notes_1": "·更新前請確保車輛剩餘電量不少於20%",
  "text_firmware_update_notes_2": "·更新過程中請勿操作車輛，以免導致更新失敗",
  "text_firmware_update_notes_3": "·若更新失敗，嘗試退出App後重新更新",
  "prompt_contact_us": "與我們聯繫",
  "prompt_firmware_update_learn_more_notes": "了解更多注意事項>>",
  "title_new_firmware_version_summary": "本次推薦",
  "text_new_firmware_version_learn_more": "了解更多>>",
  "prompt_firmware_update_success": "更新成功！",
  "prompt_firmware_update_failed": "更新失敗！",
  "prompt_last_firmware_update_interrupted": "上次固件升級可能被中斷，車輛已無法正常使用，請繼續完成升級",
  "prompt_forced_firmware_update_tips": "您需要將車輛固件更新至最新版本才可以正常使用",
  "prompt_firmware_update_le1_manually_process_tips": "等待車輛顯示屏熄滅後，請重新開機，完成以上操作後，點擊“確認”進行下一步",
  "prompt_firmware_updating": "正在升級",
  "prompt_firmware_update_waiting_device": "等待設備升級",

  "title_device_name_unknown": "未知",
  "title_device_name_hmic_board": "人機板",
  "title_device_name_driver_board": "驅動板",
  "title_device_name_bt_board": "藍牙板",
  "title_device_name_display_board": "儀表板",
  "title_device_name_bms_1": "BMS 1",
  "title_device_name_bms_2": "BMS 2",

  /// 驅動板故障
  "title_vehicle_diagnosis_module_driver_board": "驅動板",
  "vehicle_error_parse_current_sensor": "相電流傳感器故障，您可能需要更換驅動板。",
  "vehicle_error_bus_current_sensor": "總電流傳感器故障，您可能需要更換驅動板。",
  "vehicle_error_imu_sensor": "IMU傳感器故障，您可能需要更換驅動板。",
  "vehicle_error_mos_temp_sensor": "MOS溫控故障，您可能需要更換驅動板。",
  "vehicle_error_bus_voltage_sensor": "總電壓傳感器故障，您可能需要更換驅動板.",
  "vehicle_error_battery_voltage_sensor": "電池電壓傳感器故障，您可能需要更換驅動板。",
  "vehicle_error_board_high_temp_area_sensor": "高溫區溫控故障，您可能需要更換驅動板。",
  "vehicle_error_current_sampling": "驅動板採樣異常，您可能需要更換驅動板",
  "vehicle_error_sensor": "傳感器芯片故障，您可能需要更換驅動板。",
  "vehicle_error_rtc": "RTC異常，您可能需要更換驅動板。",
  "vehicle_error_spi_flash": "傳感器板存儲芯片異常。",
  "vehicle_error_log": "日誌系統異常，請檢修。",
  "vehicle_error_external_flash": "外部存儲器故障。",
  "vehicle_error_euc_driver_board_communication": "驅動器通訊故障，您可能需要更換人機板或驅動板。",
  "vehicle_error_scooter_driver_board_communication": "驅動器通訊故障，您可能需要更換顯示板或驅動板。",
  "vehicle_error_scooter_driver_board_communication_unstable": "驅動器與顯示板通信不穩定，您可能需要更換顯示板或驅動板。",
  "vehicle_error_communication": "通訊異常，請嘗試關機重啟或送修。",
  "vehicle_error_voltage": "電壓錯誤",
  "vehicle_error_driver_board": "控制器錯誤",
  "vehicle_error_driver_board_oscillator": "晶振不起振",

  "vehicle_warning_over_current": "過流警告，請溫柔騎行。", //車輛
  "vehicle_warning_over_temp": "驅動器溫度過高警告，請靜置休息片刻。",
  "vehicle_warning_cpu_over_temp": "CPU溫度過高警告，請靜置休息片刻。",
  "vehicle_warning_imu_over_temp": "IMU溫度過高警告，請靜置休息片刻。",
  "vehicle_warning_mos_over_temp": "MOS溫度過高警告，請靜置休息片刻。",

  /// 顯示板故障（L9）
  "vehicle_error_scooter_imu_sensor": "IMU傳感器故障，您可能需要更換顯示板。",

  /// 人機板故障
  "title_vehicle_diagnosis_module_hmic_board": "人機板",
  "vehicle_error_hmic_board_rtc": "RTC故障，您可能需要更換人機板。",
  "vehicle_error_hmic_board_flash": "外部存儲器故障，您可能需要更換人機板。",

  /// 藍牙板故障
  "title_vehicle_diagnosis_module_bt_board": "藍牙板",
  "vehicle_error_bt_board_communication": "藍牙板通訊故障，您可能需要更換藍牙板或人機板。",

  /// 電機故障
  "title_vehicle_diagnosis_module_motor": "電機",
  "vehicle_error_motor_hall": "電機霍爾故障，您可能需要更換電機。",
  "vehicle_error_motor_hall_left": "電機左霍爾故障，您可能需要更換電機。",
  "vehicle_error_motor_hall_right": "電機右霍爾故障，您可能需要更換電機。",
  "vehicle_error_front_motor_hall": "前電機霍爾故障，您可能需要更換電機。",
  "vehicle_error_rear_motor_hall": "後電機霍爾故障，您可能需要更換電機。",
  "vehicle_error_motor_temp_sensor": "電機溫控故障，您可能需要更換電機。",
  "vehicle_error_motor_phase": "電機缺相錯誤，您可能需要更換電機。",
  "vehicle_warning_motor_over_temp": "電機溫度過高警告，請靜置休息片刻。",
  "vehicle_warning_motor_spin": "飛轉警告，請勿在車輛非靜止狀態下提起車輛。",
  "vehicle_warning_motor_blocked": "電機堵轉警告，請勿在陡坡上駐停過久。",

  /// 電池故障
  "title_vehicle_diagnosis_module_battery": "電池",
  "vehicle_error_battery": "電池故障，您可能需要更換電池。",
  "vehicle_error_battery_temp_sensor": "電池溫控故障，您可能需要更換電池。",
  "vehicle_error_battery_cannt_power_off": "無法正常斷電故障，您可能需要更換電池。",
  "vehicle_error_battery_cannt_charge": "無法充電故障，您可能需要更換電池或充電器。",
  "vehicle_error_battery_signal": "電池信號異常，請檢修",
  "vehicle_warning_low_battery": "低電警告，請盡快充電。",
  "vehicle_warning_battery_over_temp": "電池溫度過高警告，請靜置休息片刻。",
  "vehicle_warning_battery_calibration": "電池電壓校準異常警告，請重新%s。",
  "text_calibrate_battery": "校準電池電壓",
  "vehicle_warning_some_batteries_not_enabled": "有部分電池未工作警告，這會影響車輛的性能，請謹慎使用!",
  "vehicle_warning_danger_charge1_dual_charger": "警告：左右電池組電壓不一致，不當的充電方式可能造成不良後果。\n\n正確的做法：\n①只使用單充電器充電，禁止雙充電器充電\n②充電時將車輛放置於視線範圍內，及時觀察充電進展。%s",
  "vehicle_warning_danger_charge1_single_charger": "警告：左右電池組電壓不一致，不當的充電方式可能造成不良後果。 \n\n正確的做法：\n充電時將車輛放置於視線範圍內，及時觀察充電進展。 %s",
  "vehicle_warning_danger_charge2": "危險，停止充電！\n\n電池故障，請立即拔掉充電器，停止充電，將車輛放置於安全的位置。\n請上傳車輛日誌(車輛設置-診斷-上傳日誌), 聯繫您的代理商進行售後服務。%s",
  "btn_i_know_danger_charge_risk_and_turn_off_alert": "我已知曉風險並關閉警報聲",
  "vehicle_warning_battery_over_voltage": "電池電壓過高，請更換充電器或送修。",
  "vehicle_warning_battery_output_abnormal": "電池輸出異常，請嘗試充電恢復或送修。",
  "vehicle_warning_too_low_battery": "電壓極低警告，請盡快充電，以免損壞您的電池。",

  /// 風扇故障
  "title_vehicle_diagnosis_module_fan": "風扇",
  "vehicle_error_fan": "散熱風扇故障，您可能需要更換散熱風扇。",
  "vehicle_warning_fan_low_speed": "散熱風扇轉速過低警告，這會影響照明燈最大亮度，請檢查風扇是否有異物堵塞",

  /// 車輛異常故障
  "title_vehicle_diagnosis_module_vehicle": "車輛",
  "vehicle_error_brake_handle": "剎車把手故障，請檢查剎車把手是否釋放。",
  "vehicle_error_acc_handle": "油門把手故障，請檢查油門把手是否釋放。",

  "vehicle_warning_lock_caused_by_safe_issue": "由於存在安全相關的隱患，車輛已被臨時鎖定",
  "vehicle_warning_over_speed": "超速騎行警告，請放慢騎行速度。",
  "vehicle_warning_fall_down": "傾倒警告，請小心騎行。",
  "vehicle_warning_risk_behavior": "危險騎行動作警告，請勿過激騎行。",
  "vehicle_warning_software_incompatible": "各組件軟件不兼容警告，請升級最新固件。",
  "vehicle_warning_motor_no_load_protection": "電機空載保護警告，建議開啟提手按鍵，提起前確保車輛靜止。",
  "vehicle_warning_power_key_long_pressed": "電源按鍵被長時間按下警告，電源按鍵被長時間按下可能觸發強制斷電，請停止騎行！",
  "vehicle_warning_necessary_self_check_not_passed": "存在必要的自檢項未進行或未通過警告，%s。",
  "text_execute_self_check": "進行自檢",
  "vehicle_warning_function_limited_by_uncompleted_fw_update": "您的車輛功能受限，需要升級固件後才能正常使用",
  "vehicle_warning_remote_locked": "您的車輛已被鎖定，請聯繫樂行售後核實身份以解鎖",
  "vehicle_warning_hardware_incompatible": "硬件不匹配警告，人機板和驅動板需整套更換禁止拆分重組",
  "vehicle_warning_over_power": "超過輸出能力限制",

  /// BMS故障
  "bms_error_voltage_sample": "電壓採樣故障",
  "bms_error_charge_current_sample": "充電採樣故障",
  "bms_error_discharge_current_sample": "放電採樣故障",
  "bms_error_temperature_sensor": "溫度傳感器故障",
  "bms_error_rh_sensor": "濕度傳感器故障",
  "bms_error_charge_mosfet": "充電MOS故障",
  "bms_error_discharge_mosfet": "放電MOS故障",
  "bms_error_afe": "Afe故障",
  "bms_error_cell": "電芯故障",
  "bms_error_mcu": "MCU故障",

  /// BMS警告
  "bms_warning_low_soc": "低電量警告",
  "bms_warning_pack_over_charge": "電池包過充警告",
  "bms_warning_pack_over_discharge": "電池包過放警告",
  "bms_warning_cell_over_charge": "電芯過充警告",
  "bms_warning_cell_over_discharge": "電芯過放警告",
  "bms_warning_charge_over_current": "充電過流警告",
  "bms_warning_charge_mosfet_over_temperature": "充電MOS過溫警告",
  "bms_warning_charge_cell_over_temperature": "電芯充電過溫警告",
  "bms_warning_charge_cell_low_temperature": "電芯充電溫度過低警告",
  "bms_warning_discharge_over_current": "放電過流警告",
  "bms_warning_discharge_mosfet_over_temperature": "放電MOS過溫警告",
  "bms_warning_discharge_cell_over_temperature": "電芯放電過溫警告",
  "bms_warning_discharge_cell_low_temperature": "電芯放電溫度過低警告",
  "bms_warning_over_humidity": "相對濕度過高警告",

  /// BMS保護
  "bms_protection_short_circuit": "短路保護",
  "bms_protection_pack_over_charge": "電池包過充保護",
  "bms_protection_pack_over_discharge": "電池包過放保護",
  "bms_protection_cell_over_charge": "電芯過充保護",
  "bms_protection_cell_over_discharge": "電芯過放保護",
  "bms_protection_charge_over_current": "充電過流保護",
  "bms_protection_charge_mosfet_over_temperature": "充電MOS過溫保護",
  "bms_protection_charge_cell_over_temperature": "電芯充電過溫保護",
  "bms_protection_charge_cell_low_temperature": "電芯充電溫度過低保護",
  "bms_protection_discharge_over_current": "放電過流保護",
  "bms_protection_discharge_mosfet_over_temperature": "放電MOS過溫保護",
  "bms_protection_discharge_cell_over_temperature": "電芯放電過溫保護",
  "bms_protection_discharge_cell_low_temperature": "電芯放電溫度過低保護",
  "bms_protection_over_humidity": "相對濕度過高保護",
  "bms_protection_associated_charge": "關聯充電保護",
  "bms_protection_associated_discharge": "關聯放電保護",

  /// 燈效
  'title_light_effect_preview': '燈效預覽',
  'title_complete_light_effect_info': '完善燈效信息',
  'prompt_input_light_effect_name': '請輸入燈效名稱',
  'prompt_invalid_light_effect_info': '無效的燈效信息',
  'text_light_effect_frame_interval': '幀間隔',
  'title_light_effect_my_colors': '我的顏色',
  'text_light_effect_frame_keyframe': '關鍵幀',
  'text_light_effect_frame_total': '總幀數',
  'text_light_effect_frame_number': '第%s幀',
  'text_light_effect_frame': '%s幀',
  'text_light_effect_frame_mode_normal': '均勻',
  'text_light_effect_frame_mode_fast': '漸快',
  'text_light_effect_frame_mode_slow': '漸慢',
  'title_light_effect_edit': '燈效編輯',
  'prompt_light_effect_edit_back_tips': '退出將無法保存編輯的燈光效果',
  'prompt_light_effect_edit_gradient_mode_1': '鬆開設為漸變起始點，繼續滑動取消鬆開設為漸變起始點，繼續滑動取消',
  'prompt_light_effect_edit_gradient_mode_2': '當前處於幀內漸變模式，請繼續選擇漸變結束點或%s',
  'prompt_light_effect_edit_gradient_mode_3': '當前處於幀內漸變模式，您正在選擇漸變結束點，鬆開後即可退出該模式',
  'prompt_light_effect_edit_gradient_mode_4': '當前處於幀內漸變模式，您正在選擇漸變結束點，也可以滑動到此處退出該模式',
  'text_light_effect_exit_edit_gradient_mode': '取消該模式',
  'prompt_light_effect_edit_already_first_step': '已經是第一步',
  'prompt_light_effect_edit_already_last_step': '已經是最後一步',
  'prompt_light_effect_drag_to_delete': '拖動到此處刪除',
  'prompt_light_effect_release_to_delete': '鬆手即可刪除',
  "title_vehicle_light_effect_exists": "車內燈效",
  "text_light_effect_default_package": "默認燈效",
  "text_light_effect_unknown_package": "未知燈效",
  "prompt_enable_light_effect_failed": "燈效包啟用失敗",
  'prompt_confirm_to_delete_light_effect': '確認刪除？ ',
  'prompt_confirm_to_delete_diy_light_effect': 'DIY燈效刪除後不可恢復，確認刪除【%s】嗎',

  /// 音效包
  "title_vehicle_sound_pack": "音效包",
  "title_vehicle_sound_pack_exists": "車內音效",
  "text_default_sound_pack": "默認音效",
  "text_unknown_sound_pack": "未知音效",
  "prompt_input_sound_pack_name": "請輸入音效包名稱",
  "prompt_select_sound_pack_cover": "請設置音效包封面圖片",
  "title_diy_single_sound_pack_item": "DIY單條音效",
  "title_diy_sound_pack": "DIY音效包",
  'prompt_confirm_to_use_default_sound_pack': '確認恢復成默認音效嗎？ ',
  "prompt_select_from_local_file": "選擇本地文件",
  "prompt_vehicle_transferring_file": "文件傳輸過程中請保持車輛靜止且不要操作車輛",
  "prompt_enable_sound_pack_success": "音效包啟用成功",
  "prompt_enable_sound_pack_failed": "音效包啟用失敗",
  "prompt_vehicle_storage_capacity_not_enough": "剩餘空間不足",
  "prompt_sound_pack_composing": "正在合成...",
  "prompt_sound_pack_item_file_is_too_large": "音效文件過大",
  "title_custom_sound_pack": "自定義音效",
  "title_complete_sound_pack_info": "完善音效包信息",
  "btn_compose": "合成",
  "title_sound_pack_compose": "音效包合成",
  "prompt_sound_pack_compose_succeed": "合成音效包成功",
  "prompt_sound_pack_compose_failed": "合成音效包失敗",
  "title_sound_pack_audition": "試聽",
  "title_select_sound_pack_item": "選擇音效",
  'prompt_confirm_to_delete_sound_pack': '確認刪除？ ',
  'prompt_confirm_to_delete_sound_pack_in_vehicle': '車內音效刪除後不可恢復，確認刪除【%s】嗎',
  'prompt_confirm_to_delete_diy_sound_pack': 'DIY音效刪除後不可恢復，確認刪除【%s】嗎',
  'text_sound_pack_file_local': '本地',
  'text_sound_pack_file_record': '錄音',
  'text_sound_pack_file_library': '音效庫',
  'text_sound_pack_item_duration': '時長：',
  'text_sound_pack_item_size': '大小：',
  'prompt_sound_pack_compose_item_cannt_be_empty': '所有文件不能為空',
  'title_sound_pack_diy_create_from_template': '從模版中創建',
  'title_sound_pack_diy_create_directly': '直接創建',
  'title_sound_pack_diy_select_template': '選擇模版',
  "title_sound_pack_audition_on_phone": "在手機上試聽",
  "title_sound_pack_audition_on_vehicle": "在車內試聽",

  ///
  /// Mine
  ///
  'btn_authorized_vehicles': '我的車輛',
  'btn_vehicle_authorization': '車主認證',
  'btn_customer_service': '客戶服務',
  'title_find_my_vehicle': '查找車輛',
  'title_unit_metric_imperial': '公英制',
  'text_unit_metric': '公制',
  'text_unit_imperial': '英制',
  'title_language': '語言',
  'text_follow_system': '跟隨系統',
  'title_select_language': '選擇語言',
  'title_account_security': '賬號與安全',
  'title_clear_cache': '清除緩存',
  'prompt_clear_cache_tips': '是否清除緩存？ ',
  'title_app_about': '關於',
  'text_app_version': '版本 %s',

  'title_message_center': '消息中心',
  'title_user_info': '個人信息',
  'btn_take_a_photo': '拍照',
  'btn_select_from_album': '從相冊中選擇',

  'title_scan_qrcode': '掃描二維碼',

  /// 關於
  "user_agreement": "用戶協議",
  "privacy_policy": "隱私政策",
  'inmotion_company': '深圳樂行天下科技有限公司',

  /// 個人信息
  'title_avatar': '頭像',
  'title_nickname': '暱稱',
  'title_signature': '簽名',
  'title_modify_nickname': '修改暱稱',
  'title_modify_signature': '修改簽名',
  'prompt_nickname_limit': '6-20個字符',
  'prompt_signature_limit': '0-100個字符',

  /// 我的車輛
  'title_my_vehicles': '我的車輛',
  'title_delete_authorized_vehicle': '解除車主認證',
  'prompt_delete_authorized_vehicle_tips': '刪除車輛將解除車主身份，確認要刪除車輛嗎？ ',
  'title_delete_vice_owner': '解除副車主',
  'prompt_delete_vice_owner_tips': '確認要解除副車主嗎？ ',
  'title_vehicle_details': '車輛詳情',
  'title_vehicle_info': '車輛信息',
  'prompt_vehicle_info_updated_at': '以下信息更新於：%s',
  'title_vehicle_model': '型號',
  'title_activated_date': '激活日期',
  'title_total_mileage': '總里程',
  'title_riding_record': '騎行記錄',
  "title_bluetooth_name": "藍牙名稱",
  "text_vehicle_remaining_mileage": "剩餘里程：%s",
  'title_vehicle_owner_info': '車主信息',
  'title_vehicle_main_owner': '主車主',
  'btn_go_to_authorize_as_owner': '前往認證',
  'prompt_not_owner_and_go_to_authorize_as_owner': '僅車主才可進行此操作，是否立即前往認證成為車主？ ',
  'text_vehicle_info_owner_me_suffix': '（我）',
  'title_vehicle_vice_owner': '副車主',
  'title_vehicle_no_owner': '無',
  'title_transfer_vehicle_main_owner': '轉移主車主',
  'prompt_transfer_vehicle_main_owner_tips': '轉移後，你將成為副車主，用戶「%s」將成為當前車輛的主車主，確定轉移嗎？ ',
  'title_invite_as_vehicle_vice_owner': '邀請副車主',
  'prompt_invite_as_vehicle_vice_owner_tips': '請讓對方使用樂行App進入車主認證，掃描該二維碼，成為副車主',
  'title_vehicle_authorization': '車主認證',
  'prompt_authorize_current_connected_vehicle_tips': '當前已連接車輛%s，是否立即認證為車主？ ',
  'prompt_input_sn': '請輸入SN',
  'title_vehicle_authorization_requests': '歷史綁定申請',
  'title_sent_vehicle_authorization_requests': '發出申請',
  'title_received_vehicle_authorization_requests': '向我申請',
  'prompt_vehicle_authorization_apply_to': '向 %s 申請',
  'prompt_vehicle_authorization_apply_from': '%s 向我申請',
  'prompt_vehicle_authorization_waiting': '等待中',
  'text_status_pending': '待處理',
  'text_status_approved': '已同意',
  'text_status_rejected': '已拒絕',
  'text_status_expired': '已失效',

  /// 車主認證
  'prompt_vehicle_authorization_apply_success': '已成功發出申請',
  'prompt_vehicle_authorization_success': '已成功認證為車主',
  'prompt_vehicle_authorized_as_vice_owner_tips': '該車輛主用戶已存在，是否認證為副車主？ ',
  'prompt_vehicle_authorized_as_vice_owner_success': '已成功認證為副車主',
  'prompt_vehicle_authorization_failed': '認證失敗',

  /// 在線客服
  'title_message_board': '留言板',
  'prompt_leave_message_tips': '請留言，我們將盡快聯繫您',
  'btn_leave_a_message': '留言',
  'prompt_please_leave_a_message': '請留言',
  'btn_chat_menu_picture': '圖片',
  'btn_chat_menu_video': '視頻',
  'prompt_leave_message_success': '留言成功',
  'prompt_leave_message_failed': '留言失敗',
  'prompt_content_couldnt_be_empty': '內容不能為空',
  'prompt_customer_service_waiting_for_access': '等待接入',
  'prompt_customer_service_queue_number': '排隊人數：%s',
  'prompt_customer_service_offline': '客服離線',
  'prompt_customer_service_session_ended': '會話已結束',
  'btn_customer_service_evaluate': '評價',
  'prompt_input_question_to_consult': '請輸入想諮詢的問題',

  "title_official_recommends": "官方推薦",

  /// 騎行記錄
  "text_riding_record_summary": "共%s小時，節約碳排放%s",

  ///
  /// 錯誤碼提示
  ///
  'prompt_request_failed': '請求失敗',
  'prompt_request_failed_timeout': '請求超時',
  'prompt_request_failed_network': '網絡錯誤',

  'prompt_unauthenticated_request': '登錄狀態失效，請重新登錄！ ',
  'prompt_unknown_error': '未知錯誤',
  'prompt_operate_too_frequently': '操作頻繁，請稍後再試',
  'prompt_file_download_failed': '文件異常',
  'prompt_unknown_product_model': '未知產品型號',
};
